### ISSUE TITLE
haddock after new-repl

### ISSUE THREAD

**Issue by llelf** [haskell/cabal#5178] opened 2018-03-02 16:31 UTC
Recently cabal started to basically do a haddock build after new-repl.
Is it intentional (or my setup is broken)?  It's *definitely* surprising.

This is what I mean:
```
$ cat cabal.project
packages: .

package foo
  documentation: True

$ cabal new-repl lib:foo                        --  new-repl

⟨…⟩

Ok, six modules loaded.
Collecting type info for 6 module(s) ... 	--  ghci repl
→ :quit 					--  exit from ghci
Leaving GHCi.
Preprocessing library ⟨…⟩			--  starting haddock build!!!
Running Haddock on library ⟨…⟩
⟨…⟩

```

**Comment by 23Skidoo** [comment] 2018-03-02 16:54
Likely because `repl` and `build` share the same code path. Agreed that `repl` shouldn't do this. Is this with `2.2` or only with `master`?

**Comment by alexbiehl** [comment] 2018-03-02 17:22
This might be the result of the recent https://github.com/haskell/cabal/commit/c094940abc4266c8d013853b66271540cb2dc7f0. Maybe we should disable haddock'ing for repl builds.

**Comment by llelf** [comment] 2018-03-06 09:24
@23Skidoo master. But I tried  2.2, the same result.

@alexbiehl new-test too likely. It shouldn't fail because of haddock error, … or  is it? Not sure.

**Comment by quasicomputational** [comment] 2018-07-09 16:37
I verified that I can reproduce this with 2.2, and that I can't reproduce now on master. Presumably #5226 has fixed it, so closing.

**Closed by quasicomputational** 2018-07-09 16:37 UTC
Labels: cabal-install: nix-local-build, type: bug
