### ISSUE TITLE
Flag --test-keep-tix-files doesn't work with v2-test

### ISSUE THREAD

**Issue by awasthishubh** [haskell/cabal#6938] opened 2020-07-03 20:00 UTC
**Description**
Command `cabal v2-test all --test-keep-tix-files` is supposed to keep the **tix** file that must be generated while running tests. This file is helpful in determining code-coverage using hpc.  
`cabal v1-test --keep-tix-files` works fine but I am working on updating Hackage Builder to use cabal v2 as a part of my GSoC project.

**Steps to reproduce the behaviour:**

```
# Download and extract tarball of the package
cd "loc_to_pkg"
cabal v2-test all --test-keep-tix-files`
```

**Expected behaviour**
A `test-pkg.tix` is expected to be present somewhere inside the package directory.
Instead, I was only able to find an empty folder at `dist-newstyle/build/x86_64-linux/ghc-8.6.5/async-2.2.2/t/test-async/hpc/vanilla/tix/test-async`

**System information**
 - Operating system: Ubuntu 20.04
 - Cabal: 3.2.0.0
 - GHC: 8.6.5

**Additional context**
I tested with pkg: [async-2.2.2](http://hackage.haskell.org/package/async-2.2.2/)

**Comment by Mikolaj** [comment] 2021-07-29 14:02
@awasthishubh: I'm unclear how to reproduce. I definitely see .tix files at `cabal-testsuite/PackageTests/Regression/T5213/dist-newstyle/build/x86_64-linux/ghc-8.8.3/cabal-gh5213-0.1/t/tests/hpc/vanilla/tix` after running tests. Do you mean the files should be there even when running without `--coverage`, but with `--test-keep-tix-files`?

**Comment by Mikolaj** [comment] 2021-08-02 14:32
@gbaz: perhaps you remember the details?

**Comment by awasthishubh** [comment] 2021-08-02 16:41
@Mikolaj I am sorry but I do not remember exact details anymore. As far as I remember, I wanted to have the tix files which was working with cabal v1 but not with cabal v2. 

`cabal v1-test --keep-tix-files` keeps the tix files
`cabal v2-test all --test-keep-tix-files` do not keeps them

It wasn't mention anywhere that I need to have `--coverage` as well (v1 do not need this). If adding the `--coverage` keeps the tix files, I guess it would have resolved my issue.

**Comment by Mikolaj** [comment] 2021-08-02 22:52
@awasthishubh: thank you. In that case, I will close the issue and if it turns out Hackage needs .tix file generated without .mix files or whatever the precise requirement may be, this can be reopened, with extra details.

**Closed by Mikolaj** 2021-08-02 22:52 UTC
Labels: Cabal: code-coverage, attention: pr-welcome
