### ISSUE TITLE
cabal-install-2.3 new-haddock regression (setup: internal error when calculating transitive package dependencies.)

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#5423] opened 2018-07-10 17:45 UTC
I originally noticed this issue when trying to [upgrade `singletons`' Travis setup](https://travis-ci.org/goldfirere/singletons/jobs/402254201#L4238) to use `cabal-install-head`. That is:

```
$ /opt/cabal/head/bin/cabal --version
cabal-install version 2.3.0.0
compiled using version 2.3.0.0 of the Cabal library
```

I've prepared a more minimal reproduction at https://github.com/RyanGlScott/cabal-gh5423. To reproduce the issue, do the following:

```
$ git clone https://github.com/RyanGlScott/cabal-gh5423
$ cd cabal-gh5423/
$ /opt/cabal/head/bin/cabal new-haddock cabal-gh5423:tests
Resolving dependencies...
Build profile: -w ghc-8.4.3 -O1
In order, the following will be built (use -v for more details):
 - cabal-gh5423-0.1 (first run)
[1 of 1] Compiling Main             ( /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/setup.hs, /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/Main.o )
Linking /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/setup ...
Configuring cabal-gh5423-0.1...
Found dependency closure
Preprocessing library for cabal-gh5423-0.1..
Running Haddock on library for cabal-gh5423-0.1..
Haddock coverage:
   0% (  0 /  1) in 'CabalSandbox'
  Missing documentation for:
    Module header
Documentation created:
/home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/doc/html/cabal-gh5423/index.html
Preprocessing test suite 'cabal-gh5423-tests' for cabal-gh5423-0.1..
Running Haddock on test suite 'cabal-gh5423-tests' for cabal-gh5423-0.1..
setup: internal error when calculating transitive package dependencies.
Debug info: []

cabal: Failed to build documentation for cabal-gh5423-0.1.
```

`cabal-gh5423` is a package with a library, test suite, and `custom-setup` script that looks like:

```haskell
module Main (main) where

import Distribution.PackageDescription
import Distribution.Simple
import Distribution.Simple.LocalBuildInfo
import Distribution.Simple.PackageIndex

main :: IO ()
main = defaultMainWithHooks simpleUserHooks
  { haddockHook = \pkg lbi hooks flags -> do
      blah pkg lbi
      haddockHook simpleUserHooks pkg lbi hooks flags
  }

blah :: PackageDescription -> LocalBuildInfo -> IO ()
blah pkg lbi =
  withLibLBI pkg lbi $ \_ libCLBI -> do
    let libDeps = map fst $ componentPackageDeps libCLBI
    case dependencyClosure (installedPkgs lbi) libDeps of
      Left p  -> p `seq` putStrLn "Found dependency closure"
      Right _ -> error "Broken dependency closure"
```

(In reality, `singletons` actually uses the computed dependency closure for something useful, but I've elided this for the sake of keeping things simple.)

**Comment by RyanGlScott** [comment] 2018-07-10 17:47
For comparison, it succeeds with `cabal-install-2.2`:

```
$ /opt/cabal/2.2/bin/cabal new-haddock cabal-gh5423:tests
Resolving dependencies...
Build profile: -w ghc-8.4.3 -O1
In order, the following will be built (use -v for more details):
 - cabal-gh5423-0.1 (first run)
[1 of 1] Compiling Main             ( /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/setup.hs, /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/Main.o )
Linking /home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/setup/setup ...
Configuring cabal-gh5423-0.1...
Found dependency closure
Preprocessing library for cabal-gh5423-0.1..
Running Haddock on library for cabal-gh5423-0.1..
Haddock coverage:
   0% (  0 /  1) in 'CabalSandbox'
  Missing documentation for:
    Module header
Documentation created:
/home/rgscott/Documents/Hacking/Haskell/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-8.4.3/cabal-gh5423-0.1/doc/html/cabal-gh5423/index.html
Preprocessing test suite 'cabal-gh5423-tests' for cabal-gh5423-0.1..
```

**Comment by hvr** [comment] 2018-10-04 11:39
maybe this was fixed as a side-effect of #5253

**Comment by 23Skidoo** [comment] 2018-10-04 12:12
Optimistically closing, please reopen if disagree

**Closed** 2018-10-04 12:12 UTC
Labels: cabal-install: nix-local-build, type: regression

**Comment by RyanGlScott** [comment] 2022-08-22 11:04
This issue is, unfortunately, preventing me from building `singletons-base` on CI at the moment. `singletons-base` uses a [custom `Setup.hs` script involving `dependencyClosure`](https://github.com/goldfirere/singletons/blob/a58eb76ad7066365e1224b562037b284560c0c02/singletons-base/Setup.hs#L61), and if I try to combine GHC 9.4.1 with `cabal-install-3.6.2.0`, then things break as above when building the Haddocks using `v2-haddock all --haddock-all`.

The closest existing issue that I can find to this is #1919, which has been fixed upstream (see #7827). It's not clear to me if I need to update the custom `Setup.hs` script somehow in order to avoid #1919. (In fact, another custom `Setup.hs` script user was [wondering the same thing](https://github.com/haskell/cabal/pull/7827#issuecomment-996611466).)

**Comment by Mikolaj** [comment] 2022-08-22 11:30
> It's not clear to me if I need to update the custom `Setup.hs` script somehow in order to avoid #1919.

I don't remember (assuming I understood it at the time). However, the fix is not present in cabal 3.6, but only in 3.8, so certainly using cabal 3.8 is required (which matches your test results?).

**Comment by RyanGlScott** [comment] 2022-08-22 11:35
> However, the fix is not present in cabal 3.6, but only in 3.8

I'm not sure it's that simple. As noted in https://github.com/haskell/cabal/issues/5423#issuecomment-1222190390, the bug doesn't surface if I use `cabal-3.6.2.0` + GHC 9.2.4.

**Comment by Mikolaj** [comment] 2022-08-22 11:45
Yes, we won't know until GHC 9.6 is released.

**Comment by ysangkok** [comment] 2023-04-17 21:03
@Mikolaj What will we not know until GHC 9.6 is released?

This is reproducable with cabal-install-3.10.1.0 and GHC 9.2.7:

```
janus@gorm ~/flipstone/cabal-gh5423
 % cabal haddock --haddock-tests -w ghc-9.2.7 
Build profile: -w ghc-9.2.7 -O1
In order, the following will be built (use -v for more details):
 - cabal-gh5423-0.1 (first run)
Found dependency closure
Preprocessing library for cabal-gh5423-0.1..
Running Haddock on library for cabal-gh5423-0.1..
   0% (  0 /  1) in 'CabalSandbox'
  Missing documentation for:
    Module header
Documentation created:
/home/janus/flipstone/cabal-gh5423/dist-newstyle/build/x86_64-linux/ghc-9.2.7/cabal-gh5423-0.1/doc/html/cabal-gh5423/index.html
Preprocessing test suite 'cabal-gh5423-tests' for cabal-gh5423-0.1..
Running Haddock on test suite 'cabal-gh5423-tests' for cabal-gh5423-0.1..
setup: internal error when calculating transitive package dependencies.
Debug info: []

Error: cabal: Failed to build documentation for cabal-gh5423-0.1.

janus@gorm ~/flipstone/cabal-gh5423
 % cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library
```

**Comment by Mikolaj** [comment] 2023-04-18 09:06
> @Mikolaj What will we not know until GHC 9.6 is released?

I have no idea!

However, given that fixes in many tools were needed, perhaps the best we can do is ensure newest versions of all tools do not exhibit the behaviour. Whether that includes the newest version of GHC, I'm not sure. But perhaps the usage of `ghc-9.2.7` implies the usage of an older haddock? Or bounds on `base` somewhere imply that older package are used? I guess, it might be useful to try to run the interesting examples with the haddock that comes with GHC 9.6 and also with `--allow-newer` to make sure `base` bounds don't interfere. Then we might conclude, e.g., that new cabal and new haddock are enough and GHC version only matters in that it should be compatible with new cabal and haddock.

**Comment by ysangkok** [comment] 2023-04-18 18:49
> with GHC 9.6 and also with --allow-newer

The allow-newer doesn't seem to change anything, because the internal error is still avoided:

```
% cabal-3.10.1.0 haddock --haddock-tests -w ghc-9.6.1 --allow-newer 
[...]
tests/Tests.hs:3:1: error:
    Could not find module ‘CabalSandbox’
    There are files missing in the ‘cabal-gh5423-0.1’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
3 | import CabalSandbox ()
  | ^^^^^^^^^^^^^^^^^^^^^^
```

I *am* not sure whether the CabalSandbox error is expected or not, do you know @RyanGlScott ?

Also, Ryan, you wrote

>  the bug doesn't surface if I use cabal-3.6.2.0 + GHC 9.2.4.

I am able to reproduce an internal error with this combination, am I doing something wrong?

```
 % cabal-3.6.2.0 haddock --haddock-tests -w ghc-9.2.4
[...]
setup: internal error when calculating transitive package dependencies.
```

Same with 9.2.7.

**Comment by RyanGlScott** [comment] 2023-04-18 19:04
> I am not sure whether the CabalSandbox error is expected or not, do you know @RyanGlScott ?

No, that is definitely _not_ expected. A normal `cabal test` invocation compiles without issues, so the fact that `cabal haddock --haddock-tests` does not compile smells like a bug.

> I _am_ able to reproduce an internal error with this combination, am I doing something wrong?

Now that you mention it, I am also able to reproduce this. Unfortunately, enough time has passed since I wrote my original comment in https://github.com/haskell/cabal/issues/5423#issuecomment-1222190390 that I don't know if this was a mistake on my part or if something else changed in the interim...
