### ISSUE TITLE
Make sandboxing the default unless user package-db is specified

### ISSUE THREAD

**Issue by bitemyapp** [haskell/cabal#2415] opened 2015-02-15 20:09 UTC
https://twitter.com/seanparsons/status/567052594041065474

Create sandbox if one doesn't exist in ./

Installing into user package-db is almost exclusively the province of expert users, failing to sandbox things trips new people up on a daily basis either because they didn't know or they simply forgot.

I forget sometimes too, then I'm annoyed I have to nuke my user package-db which sometimes had one or two things installed on purpose.

I am [doing my best to spread knowledge of sandboxes](http://howistart.org/posts/haskell/1) but the future is unevenly distributed and this is something that should just be fixed.

**Comment by seanparsons** [comment] 2015-02-15 20:11
For obvious reasons I support this, I find that I accidentally shoot my own foot off with this far too often.

**Comment by glguy** [comment] 2015-02-15 20:19
I don't want to see this default change, but you can do this yourself. Add this to your `~/.cabal/config`

```
require-sandbox: true
```

**Comment by bitemyapp** [comment] 2015-02-15 20:21
From @soupi

```
20:17 < suppi> definitely been there before discovering cabal sandboxes. 
               it was a mess. I had no idea what I was doing
```

**Comment by bitemyapp** [comment] 2015-02-15 20:26
The problem with asking people to change their cabal.config is three-fold:

1. If they knew how to do that, or to do it at all, we wouldn't need to do this because they'd know to use sandboxes.

2. Newbies often nuke their `~/.cabal` unnecessarily in a panic when things go wrong.

3. This is what happens when you try to install a package with that flag set and no sandbox exists:

```
[callen@pyrgos ~/Work/vector-0.10.12.2]$ cabal install
cabal: 'require-sandbox' is set to True, but no sandbox is present. Use
'--no-require-sandbox' if you want to override 'require-sandbox' temporarily.
```

That is not a solution to the UX problem. If the behavior of `require-sandbox` were changed to automatically create the sandbox (with a warning printed that it was doing so), and the default changed to `require-sandbox: True`, I would consider that a satisfactory resolution of this issue.

**Comment by seanparsons** [comment] 2015-02-15 20:48
Similar to this:
https://github.com/haskell/cabal/issues/1100
It would make a lot of sense that this is an automatic and transparent piece of functionality.

I'm thinking that if someone clones some source code from a repo it should "just work".

**Comment by lspitzner** [comment] 2015-02-16 01:15
This would break existing tutorials; consider necessary changes such as

~~~~
ghci -> cabal repl
ghc-pkg -> cabal sandbox hc-pkg --
cabal install -> cabal sandbox add-source (for local dependencies)
~~~~

While i personally have `require-sandbox: true` since quite some time now and endorse it for any non-completely-beginner activities, i vote against changing the default, especially given that:
- cabal has a good amount of non-trivial open issues surrounding sandboxes (#1899, #2333,  #1375 (which is 1.5 years old and marked urgent), and there are more..)
- (subjective) even after my attempts to improve the cabal commandline help, i believe that there is the need for a much better tutorial/introduction to cabal (the "users-guide" (who put that 's' there..) mentions a lot of stuff but is not well structured at all)
- stuff like installing executables in combination with sandboxes is not trivial (see the bash ("meh") script i currently use at https://github.com/lspitzner/cabal-exec-install).
- sandboxes might only be a temporary solution, being replaced by stackage/nixos which might be completely superior in handling dependencies in the long run.

**Comment by lspitzner** [comment] 2015-02-16 01:18
also, regarding

> Create sandbox if one doesn't exist in ./

Do you mean

> If there is a package in ./, create a sandbox..

?

(which touches on #2004)

Because, otherwise, users will be _completely_ confused once they automatically create a sandbox in a subdirectory of their package...

**Comment by bitemyapp** [comment] 2015-02-16 01:49
@lspitzner yeah I was thinking about this today, these tickets y'all are referencing are good catches. Perhaps there's an omnibus'ish PR that could sweep them up? Could we get a sense of how open the maintainers are to this?

@ttuegel

**Comment by puffnfresh** [comment] 2015-02-16 03:47
I do use require-sandbox but dislike having to tell my coworkers to do the same. Would still like it to automatically create sandboxes when I forget.

**Comment by ttuegel** [comment] 2015-02-16 04:57
@bitemyapp Individually those bugs aren't big, but I think sweeping them up in a single PR may be ambitious. Regardless of how they are partitioned, **if you tag me on a bug fix PR, I will do what it takes to get it in**. That goes double for documentation bugs, which take considerably less time to review.

As for changing `cabal-install` to create sandboxes by default: I am skeptical about changing it immediately, and I think the other maintainers will be, too. However, if you wanted to create an option such as `auto-create-sandbox: true`, I think we would be amenable to that. (Bikeshed the name as you wish.) We could ship `cabal-install` with the option disabled by default, but prominently advertised. If no new problems pop up in that release cycle, we could revisit making it the default. I know that's not the time frame any of you are looking for. Please consider a) what this will do to the workflow of users who intentionally do not use sandboxes, and b) that many (most? *all*?) of our users are used to blindly upgrading between major versions.

Despite the popularity of Stackage and NixOS, I do not think sandboxes will be a temporary solution. Stackage solves the version problem for users, but it doesn't address the developer's use cases for sandboxes. NixOS solves the version problem and tries to address the developer's use cases, but (as a NixOS dev) working on tightly-coupled Haskell projects with Nix is *very* painful compared to sandboxes.

**Comment by bitemyapp** [comment] 2015-02-16 05:19
@ttuegel Sandboxes being the most universal solution for user & developer Haskell workflows is largely why I care so much. This is very good guidance and suggestions, thank you.

**Comment by lspitzner** [comment] 2015-02-24 14:48
btw this seems to be a duplicate of #1101

**Comment by dcoutts** [comment] 2015-03-04 21:58
Right, dupe.

Personally I am not in favour of making sandboxing the default now. Sandboxing has plenty of ui problems, especially with how we do them right now. I think we should be more ambitious and move to a world of multiple consistent environments, and where cabal does the right thing when you ask to install something that is not consistent with your current environment, e.g. it'd suggest making a new environment (local or global named one).

**Comment by hvr** [comment] 2015-09-02 08:06
I'm also -1 on making sandboxes the default. Sandboxes do have their use, but we're using them for the wrong purpose most of the time, i.e. to work around the lack of a non-destructive/no-reinstall/multi-instance package db. But this is about to change, so there's no need to resign to making sandboxes the default.

**Comment by phadej** [comment] 2020-08-31 10:33
sandbox functionality is removed.

**Closed by phadej** 2020-08-31 10:33 UTC
Labels: cabal-install: sandbox, old-milestone: cabal-install 2.0, type: enhancement
