### ISSUE TITLE
lack of documentation of how to compile and run the tests for Cabal and cabal-install

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#2334] opened 2015-01-08 22:27 UTC
**the following is an error/dialogue arising because i did _not_ know how to run the tests properly**

reproduce:
check out HEAD, go to ./Cabal, and

```
> cabal sandbox init; cabal clean; cabal configure
[..]
> cabal test
cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.9999, now Cabal-1.22.0.0).
> cabal run
cabal: You need to re-run the 'configure' command. The version of Cabal being used has changed (was Cabal-1.9999, now Cabal-1.22.0.0).
> cat dist/setup-config | head -n1
Saved package config for Cabal-1.23.0.0 written by Cabal-1.9999 using ghc-7.8
```

`cabal` here refers to 1.22.0.0 or HEAD version; same result.
i know that `run` makes no sense for Cabal lib, and `test` would require `--enable-tests`, but that does not excuse the problems.

**Comment by lspitzner** [comment] 2015-01-08 22:31
and i am aware you are still fighting with the bootstrapping stuff in general; it is hard for me to tell if this is a duplicate; sorry if it is.

**Comment by ttuegel** [comment] 2015-01-08 22:35
Because of the `setup-config` format change in 1.22, you can't use an older cabal-install to build. You need to `ghc --make Setup; ./Setup configure` etc.

**Comment by lspitzner** [comment] 2015-01-08 22:39
building is not the problem. note that i _am_ using `cabal` executable >=1.22.0.0 in that session.

**Comment by ttuegel** [comment] 2015-01-08 22:42
Sorry, I didn't make my edit clear enough. You simply *cannot* do an in-tree build of Cabal using cabal-install. Cabal has to build itself, so it writes it's own `setup-config`. But, when you call `cabal <anything besides configure>`, it checks the `setup-config`, finds that it's the wrong version (the bootstrap version), and asks you to reconfigure. This has been the case since we made cabal-install read the `setup-config` itself (so it can reconfigure automatically, when the versions are the same.)

**Comment by ttuegel** [comment] 2015-01-08 22:45
Probably, we should just disable automatic reconfigure for packages not using the `Simple` build system.

**Comment by lspitzner** [comment] 2015-01-08 23:39
hmm ok i see, that worked, thanks. although stuff is kinda annoying if you wanna use sandboxes.
btw. `cabal build` _does_ succeed (in contrary to the `cabal <anything besides configure>` claim).

shouldn't this kind of change in how building works be announced on the mailing list? (i might have missed it in the reports around the release, but i don't think i did.)

also, `HACKING.md` needs updating; and the `README.md`'s don't tell how to run the tests either (i got it all working, but i am not even sure i used the supposed path. e.g. is there a way to use the bootstrap.sh to run the tests? i guess not..)

i am aware i am somewhat critical; i wasted time on this which i think could have been prevented with a bit more communication.

**Comment by lspitzner** [comment] 2015-01-08 23:47
more concretely, the paragraph HACKING.md:24ff needs rewriting.
Thinking about it, the `README.md`'s probably are fine as they are, as the intended audience for those is the library/executable user, not the developers.

**Comment by lspitzner** [comment] 2015-01-10 21:51
i hope repurposing the ticket in this way is ok.

**Comment by ttuegel** [comment] 2015-01-10 22:13
Actually, I'm looking into the build vs. test thing. They both call `reconfigure` in the same way, so the should either both fail or both work. The fact that one works and not the other suggests something isn't working as intended.

**Comment by ttuegel** [comment] 2015-01-11 20:31
I have diagnosed this problem somewhat further. It seems to have been introduced at the same time as sandboxes. The `reconfigure` function correctly ignores bad-version errors, so something must go wrong after that.

**Comment by ezyang** [comment] 2016-07-14 05:38
I wrote down how I run the tests, and posted it here: https://github.com/haskell/cabal/pull/3551 Maybe this solves your problem @lspitzner?

**Comment by ulysses4ever** [comment] 2022-07-12 18:06
I consider this issue resolved by https://github.com/haskell/cabal/blob/master/CONTRIBUTING.md#running-tests Should we close it?

**Comment by ttuegel** [comment] 2022-07-12 19:00
I agree!

**Closed by ttuegel** 2022-07-12 19:00 UTC
Labels: type: bug, documentation
