### ISSUE TITLE
Suggest --lib in cabal v2-install error message

### ISSUE THREAD

**Issue by blamario** [haskell/cabal#6237] opened 2019-09-12 15:09 UTC
As a newby user trying to experiment through `ghci` with, say, the `lens` library, the first step would be to install `lens`:

```
$ cabal install lens
Resolving dependencies...
cabal: Cannot build the executables in the package lens because it does not
contain any executables. Check the .cabal file for the package and make sure
that it properly declares the components that you expect.
```

After this failure, the next step would be to look at `cabal help install`, and then probably to give up. The error message should prominently suggest `--lib` as the workaround.

**Comment by typedrat** [comment] 2019-09-19 16:46
I don’t recall making any changes that would effect it. Do you know what commit added the message?

**Comment by fgaz** [comment] 2019-09-19 17:06
f6aaeeeae (what a nice hash)

**Comment by fgaz** [comment] 2019-09-19 17:11
That code is currently in the warnIfNoExes function, which gets called in installExes. Maybe it filters targets the wrong way now? I don't have much time to test it atm

**Comment by selinger** [comment] 2019-10-14 19:46
Please fix this as soon as possible, as the --lib option does not even appear in the cabal 3.0.0.0 (and later) documentation, e.g. here: https://www.haskell.org/cabal/users-guide/installing-packages.html#building-and-installing-packages

Is there some documentation that is actually up-to-date, and if yes, where? Thanks!

**Comment by zehle** [comment] 2020-02-28 17:39
I second fixing this. Had to find #6246 to know that "--lib" needed to be added.

**Comment by fgaz** [comment] 2020-02-29 08:53
If someone here has the time, a bisect would probably be helpful

**Comment by sgraf812** [comment] 2020-05-11 12:33
The warning from f6aaeeeae3daca0240a6192024934f4b2143412e doesn't appear in 3.0.0.0 because it landed after 3.0.0.0 was cut, which is the cabal-install that came with GHC 8.10.1 for me.

**Comment by TakodaS** [comment] 2021-08-28 15:12
As a haskell newbie, I got a step further. Running `cabal install --lib packagename`  gets me the following error:

```
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: ghc-8.10.4/installed-8.10.4 (user goal)
[__1] next goal: process (user goal)
[__1] rejecting: process-1.6.13.2, process-1.6.13.1, process-1.6.12.0
(constraint from user target requires ==1.6.11.0)
[__1] rejecting: process-1.6.11.0 (conflict: ghc =>
process==1.6.9.0/installed-1.6.9.0)
[__1] rejecting: process-1.6.10.0, process-1.6.9.0/installed-1.6.9.0,
process-1.6.9.0, process-1.6.8.2, process-1.6.8.1, process-1.6.8.0,
process-1.6.7.0, process-1.6.6.0, process-1.6.5.1, process-1.6.5.0,
process-1.6.4.0, process-1.6.3.0, process-1.6.2.0, process-1.6.1.0,
process-1.6.0.0, process-1.5.0.0, process-1.4.3.0, process-1.4.2.0,
process-1.4.1.0, process-1.4.0.0, process-1.3.0.0, process-1.2.3.0,
process-1.2.2.0, process-1.2.1.0, process-1.2.0.0, process-1.1.0.2,
process-1.1.0.1, process-1.1.0.0, process-1.0.1.5, process-1.0.1.4,
process-1.0.1.3, process-1.0.1.2, process-1.0.1.1, process-1.0.0.0,
process-1.6.13.0 (constraint from user target requires ==1.6.11.0)
[__1] fail (backjumping, conflict set: ghc, process)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: process, ghc
```

And then I gave up :)

**Comment by fgaz** [comment] 2021-08-28 15:24
@TakodaS what were you originally trying to do? `install --lib` is rarely what you want, especially in beginner situations.

For reference, here's the new warning that only suggests `--lib` as the least likely of two options:

https://github.com/haskell/cabal/blob/7d4ce4787cb3d4fe30d08953ad64d19456a77690/cabal-install/src/Distribution/Client/CmdInstall.hs#L681-L693

**Comment by Mikolaj** [comment] 2021-08-28 15:25
@TakodaS: did you, perchance, run your command while in a directory with a `cabal.project` file? And what was the package you tried to install?

Regarding the use case from ticket description, there are various alternatives described in https://github.com/haskell/cabal/issues/6481 and `cabal install --lib` seems to be the worst of them (at least in current form). Until we figure out an alternative acceptable to all users, we don't know what alternative to suggest in help messages. Also, quite possibly we won't be overloading `cabal install` for both exe and lib installation (and both from local packages and from Hackage).

**Comment by Mikolaj** [comment] 2021-08-28 18:13
I was just advised, for the original problem in the ticket description, the following incantation is the best: `cabal repl --build-depends foo`. Given that this is now described at https://cabal.readthedocs.io/en/latest/cabal-commands.html#cabal-v2-repl, could we close this issue? Does it work for everybody? Anything else we could fix? Any objections?

**Comment by fgaz** [comment] 2021-08-29 20:50
> could we close this issue?

The suggestion still does not appear, does it? that's a regression, and it seems a lot of people are stumbling into it (30 +1s on #6246)

**Comment by fgaz** [comment] 2021-08-29 20:57
Nevermind, it does!

```
> cabal install random
Resolving dependencies...
Up to date
Warning:
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: Installation might not be completed as desired! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The command "cabal install [TARGETS]" doesn't expose libraries.
* You might have wanted to add them as dependencies to your package. In this
case add "random" to the build-depends field(s) of your package's .cabal file.
* You might have wanted to add them to a GHC environment. In this case use
"cabal install --lib random". The "--lib" flag is provisional: see
https://github.com/haskell/cabal/issues/6481 for more information.
```

Maybe OP was using an older cabal? I'll close optimistically. If anyone (with recent cabal) still isn't getting that message please leave a comment

**Closed by fgaz** 2021-08-29 20:57 UTC
Labels: documentation, attention: pr-welcome, cabal-install: cmd/install, type: regression

**Comment by sfogarty** [comment] 2023-04-27 00:08
This issue still emerges when installing a package with no executables.

```
$ cabal install ansi-terminal
Wrote tarball sdist to
/users/sfogarty/functional-testing/weights-and-gates/dist-newstyle/sdist/weights-and-gates-0.1.0.0.tar.gz
Resolving dependencies...
cabal: Cannot build the executables in the package ansi-terminal because none
of the components are available to build: the executable
'ansi-terminal-example' is marked as 'buildable: False'

$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
```

It does not suggest to use `cabal install --lib ansi-terminal`, which does work to install the package.

**Comment by gbaz** [comment] 2023-04-27 01:22
You are using cabal-install 3.6.2.0. The current version of cabal-install is 3.10.1.0
