### ISSUE TITLE
'cabal install hoogle' failed

### ISSUE THREAD

**Issue by rebcabin** [haskell/cabal#5048] opened 2018-01-16 19:25 UTC
With a fresh installation of cabal and stack, I encounter the following failure: 

cabal: Entering directory '/var/folders/4k/fd__hfz56s322hx0yst7lygmk9sn9_/T/cabal-tmp-48162/hoogle-5.0.16'
Configuring hoogle-5.0.16...
Preprocessing library for hoogle-5.0.16..
Building library for hoogle-5.0.16..
[ 1 of 28] Compiling General.IString  ( src/General/IString.hs, dist/build/General/IString.o )
[ 2 of 28] Compiling General.Str      ( src/General/Str.hs, dist/build/General/Str.o )
[ 3 of 28] Compiling General.Conduit  ( src/General/Conduit.hs, dist/build/General/Conduit.o )
[ 4 of 28] Compiling General.Template ( src/General/Template.hs, dist/build/General/Template.o )
[ 5 of 28] Compiling General.Util     ( src/General/Util.hs, dist/build/General/Util.o )
[ 6 of 28] Compiling General.Timing   ( src/General/Timing.hs, dist/build/General/Timing.o )
[ 7 of 28] Compiling General.Log      ( src/General/Log.hs, dist/build/General/Log.o )
[ 8 of 28] Compiling Input.Download   ( src/Input/Download.hs, dist/build/Input/Download.o )

src/Input/Download.hs:38:9: error:
    • Couldn't match expected type ‘C.ResumableSource
                                      (ResourceT IO) Data.ByteString.Internal.ByteString’
                  with actual type ‘C.ConduitM
                                      i0 Data.ByteString.Internal.ByteString (ResourceT IO) ()’
    • In the first argument of ‘(C.$$+-)’, namely
        ‘C.responseBody response’
      In a stmt of a 'do' block:
        C.responseBody response C.$$+- sinkFile file
      In the second argument of ‘($)’, namely
        ‘do response <- C.http request manager
            C.responseBody response C.$$+- sinkFile file’
    • Relevant bindings include
        response :: C.Response
                      (C.ConduitM
                         i0 Data.ByteString.Internal.ByteString (ResourceT IO) ())
          (bound at src/Input/Download.hs:37:9)
   |
38 |         C.responseBody response C.$$+- sinkFile file
   |         ^^^^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '/var/folders/4k/fd__hfz56s322hx0yst7lygmk9sn9_/T/cabal-tmp-48162/hoogle-5.0.16'

**Comment by 23Skidoo** [comment] 2018-01-16 19:49
Probably some bounds are wrong.

**Comment by hvr** [comment] 2018-01-16 21:10
@23Skidoo that's a very diplomatic way to state this if you take a look at https://hackage.haskell.org/package/hoogle-5.0.16/dependencies ;-)

**Comment by 23Skidoo** [comment] 2018-01-17 03:10
@rebcabin Can you please open an issue on the hoogle bug tracker then?

**Comment by mgsloan** [comment] 2018-01-17 03:30
> With a fresh installation of cabal and stack, I encounter the following failure:

Since you mention having an install of stack, note that you are not using stack when using the `cabal` executable.  `stack install hoogle` works, and should pretty much always work.

If you are not in a stack project when you run the command, it will default to using the global project at `~/.stack/global-project/stack.yaml`.  Since that got initialized a while back, for me it is using `lts-9.12`, which has `hoogle-5.0.13` as listed [here](https://www.stackage.org/lts-9.12).  If you want the newer hoogle, you can do `stack install hoogle-5.0.16`.

If you want to run the same build plan I am, you can do `stack install --resolver lts-9.12 hoogle-5.0.16`.  This specifies exactly which versions you want, rather than leaving it up to the whims of constraint solving.

**Comment by gbaz** [comment] 2018-01-17 04:07
Michael, can you please not advise people on using non-cabal tools on the cabal issue tracker? This is off topic for the purpose of this tracker. As the problem seems to be elsewhere, I'm going to close the issue.

**Closed by gbaz** 2018-01-17 04:07 UTC

**Comment by mgsloan** [comment] 2018-01-17 04:27
@gbaz The user mentioned having installed stack, so I sought to clarify any potential misconceptions about how to use stack.  If a user is just talking about a problem with cabal-install, then sure I won't advise usage of other tools.

**Comment by 23Skidoo** [comment] 2018-01-17 07:14
See https://github.com/ndmitchell/hoogle/issues/234 and https://github.com/ndmitchell/hoogle/pull/235. This is caused by a missing upper bound in hoogle's .cabal file and a breaking change in `http-conduit-2.3`.
