### ISSUE TITLE
Add support for convenience libraries

### ISSUE THREAD

**Issue by bos** [haskell/cabal#269] opened 2012-05-24 05:13 UTC
(Imported from [Trac #276](http://hackage.haskell.org/trac/hackage/ticket/276), reported by rl on 2008-05-09)

I'd like to have a package with several binaries which all use a convenience library included in that same package. The convenience library should NOT be installed. For this to work, Cabal needs two things. Firstly, it must allow dependencies within a package such that I could describe the library and have the binaries depend on it. Secondly, it should have an "installable" flag, similar to "buildable". A thing that's not installable would be built but not installed. The same mechanism could be used for package-internal tools.

**Comment by BardurArantsson** [comment] 2015-06-25 18:01
Last comment 2008(!). And is this even reasonably feasible, given the apparent complexity wrt. static vs. dynamic[1]? "Create an app-specific library" does not seem too onerous a requirement, especially if #2631 comes to fruition.

[1] I don't know if "static" here includes C libraries, but if it does... glibc simply cannot be statically linked in any case.

**Comment by BardurArantsson** [comment] 2015-06-25 18:01
IOW: Close.

**Comment by dcoutts** [comment] 2015-06-27 22:14
No I think this is quite feasible and indeed still a good idea.

**Comment by BardurArantsson** [comment] 2015-08-21 20:51
Is anyone (realistically) going to implement it? I'm voting for "WONTFIX-UNLESS-SOMEONE-STEPS-UP".

(I don't necessarily think it's a bad idea, but issue trackers of GitHub's caliber aren't meant for "wishlist" items.)

**Comment by BartMassey** [comment] 2015-11-29 22:22
@BardurArantsson: Why the eagerness to get a valid issue closed? Maybe someone will come along five years from now looking for something to do and find this. Let's not make it harder to find by closing it.

I'm not sure why you think wishlist items don't belong in the issue tracker?

**Comment by martinvlk** [comment] 2015-11-30 06:19
I think even closed issues remain in the tracker, and can be found so this is not a reason to keep it open..

**Comment by BartMassey** [comment] 2015-11-30 10:24
@martinvik: People looking for something to work on rarely look in the closed issues.

**Comment by BardurArantsson** [comment] 2015-11-30 13:25
@BartMassey The likelihood of anyone randomly dropping by and picking this up is nil for all practical purposes. I refer to the fact that this has been open since 2008.

Meanwhile, every such item is causes a certain (small) amount of wasted time every time any one browses through the issue list. Given the above, I believe it's better to just close such issues.

(I have a whole rant about why bug trackers are not the place for wishlist items in general, but I'll spare you :) .)

**Comment by BardurArantsson** [comment] 2015-11-30 13:30
Btw, my half-baked theory on why next to no drop-by contributors do wishlist items is that people tend to want to scratch their own itch -- in which case it won't matter if there's an open issue. (Unless they're just trying to pad their own résumé, in which case they might as well work on something that matters to more people. There's plenty of more important issues to go round.)

**Comment by phadej** [comment] 2015-11-30 16:28
I'd rather add label `pr welcome`, to indicate that it's ok to implement this or that feature request and submit the pr.

That said, it's obvious that I'd only close issues when there is real need (obsolete, or fixed / implemented / or clearly wontfix). There are labels, which could be used to classify issues. IMHO *enchancement* and *milestone: ⊥* do the job quite well. The *pr welcome* -label might communicate it even better. No need to close with the message *"re-open if needed"*.

There are people, who want to contribute, but have no idea about where to start or what to do, and what is easy and what's not. The infrastructure hackathon is one of  the empirical proofs of that.

And returning to this feature: it might be *easy* task: as you don't need to register/copy the library bits, only executable(s). IIRC there was an issue related to that (more component oriented approach in `cabal-install`), which could solve this trivially.

**Comment by BardurArantsson** [comment] 2015-12-02 05:48
The problem is that if we don't have a *clear* guideline for exactly how to proceed on any given issue then "pr welcome" or "easy" issues are, I'd argue, even worse than useless because people will just dive in and immediately get discouraged because these things often unfortunately *aren't* easy due to the state of the cabal-install code base. Either that or we need some person who's willing to be designated "mentor" on said issue and who can help guide the person through. (Similar to a hackathon.) I don't deny that these people who want to help exist -- but I think there are more useful issues they could be working on! (See also below.)

The problem with labels is that they have no semantics associated with them by GH Issues... and the project doesn't seem to have any either? (Didn't do a particularly thorough search, but I couldn't find any description of what any of the labels in here actually *mean*.) I also have a whole rant about GH Issues... :).

I'm not necessarily saying that wishlist items should automatically be discarded/closed, but wishlist items with no action since 2008? C'mon, now! That's obviously a wishlist item that no more than 1+\epsilon people care about. (In general, I think there must be some sort of "deadline" for wishlist items, unless we're talking rare cases of wishlist items which are showing clear progress towards being solved.)

Btw, thanks for the description of a possible solution for this concrete issue. *THIS* is what should be front-and-center (i.e. in the issue description) for any "easy" or "pr welcome" type issue.

(This is a bit of side -- but related -- issue, but the project as a whole could definitely do better on the "pr welcome" front -- it certainly doesn't *appear* like PRs are particularly welcome at the moment. There are a *lot* of lingering PRs in the queue, many probably obsolete or not which will have to be redone because master has moved on... not encouraging for outsiders :/. I know people are doing their best, but... I think something needs to change.)

**Comment by ezyang** [comment] 2015-12-23 16:21
I reviewed the PR queue. If a PR has action-required on it, it means that the PR needs updates before it can go in (not JUST rebasing; it was CRed but there were things that needed to be changed.) Should we close those PRs to make the PR queue look more friendly? Phabricator does WAY better in this regard.

In any case, it is not easy to contribute modifications to Cabal. I wish it were easier, but Cabal is a big ball of wax and it's harder than it should be. Issues like this require a bit of refactoring to happen first, before the actual issue can be done. I don't really know what to do... except refactor more!

**Comment by BardurArantsson** [comment] 2015-12-27 11:32
@ezyang I think maybe doing the action-required -> close thing might be feasible, but it's Yet Another Informal Rule That All Project Members/Contributors Have To Rememember so I'd lean towards *not* doing it. I don't know Phabricator[1], but I don't find it surprising that it does this better -- almost *everything* does, probably including the old-fashioned mailing-lists-for-git-patches approach :).

Agreed re: re-factoring, but I think it'll need some concerted effort to get the overall code base into better shape. (I've been thinking on-and-off about a Free monad refactoring, but that's probably completely unrealistic without a complete rewrite.)

[1] I'm used to gerrit, myself. It works *way* better than this GitHub PR nonsense and it *doesn't* involve installing any new executables on your system (unlike Phabricator) :).

**Comment by ezyang** [comment] 2015-12-27 16:18
@BardurArantsson I tried using the "action-required" label to mark this, but no one could remember to add/remove this label as necessary (and non-contributors don't even have the rights to do it!)

I think close is better: we only need to educate people with commit bits how to do this (users will automatically know to reopen requests when they submit them.)

I have definitely also come to the conclusion that Cabal needs more monads(TM).

**Comment by phadej** [comment] 2015-12-28 16:08
I'm not sure how re-opening in github works; IIRC non-collaborator cannot reopen issue if collaborator have closed it

**Comment by ezyang** [comment] 2015-12-28 19:06
I guess that's this bug: https://github.com/isaacs/github/issues/361

So we can't do that.

**Comment by ezyang** [comment] 2016-01-02 22:33
I have a working implementation of this. I'll clean it up and PR.

**Comment by BartMassey** [comment] 2016-01-03 01:19
Thanks!

**Comment by ezyang** [comment] 2016-01-03 03:42
One thing is that my implementation "accidentally" supports installing the helper libraries too (although there's no way to refer to them, except through the real library, or dynamic linking.)

**Closed** 2016-03-29 21:48 UTC
Labels: enhancement, high-priority, library

**Comment by BartMassey** [comment] 2016-03-30 07:56
Again, thanks huge for this. It is really appreciated.

**Comment by 23Skidoo** [comment] 2016-03-30 13:05
Yes, thanks @ezyang!
