### ISSUE TITLE
HEAD broken: cannot satisfy ... is shadowd by

### ISSUE THREAD

**Issue by tuncer** [haskell/cabal#2857] opened 2015-10-09 15:45 UTC
This is what happens if you try to build xmonad 577d5ae968 with cabal b083151f2a01ad7245f21502fd20f21189ab7665:

```
Building data-default-instances-old-locale-0.0.1...
Preprocessing library data-default-instances-old-locale-0.0.1...
<command line>: cannot satisfy -package-id
data-default-class-0.0.1-Skyc55xH6PsvfDaSQxtau:
    data-default-class-0.0.1-Skyc55xH6PsvfDaSQxtau is shadowed by
package old-locale-1.0.0.7-Skyc55xH6PsvfDaSQxtau
    (use -v for more information)
Building data-default-instances-base-0.0.1...
Configuring data-default-instances-containers-0.0.1...
Installed data-default-instances-base-0.0.1
Building data-default-instances-containers-0.0.1...
Configuring data-default-instances-dlist-0.0.1...
Installed data-default-instances-containers-0.0.1
Building data-default-instances-dlist-0.0.1...
Installed utf8-string-1.0.1.1
Installed data-default-instances-dlist-0.0.1
cabal: Error: some packages failed to install:
X11-1.6.1.2 depends on data-default-instances-old-locale-0.0.1 which failed to
install.
data-default-0.5.3 depends on data-default-instances-old-locale-0.0.1 which
failed to install.
data-default-instances-old-locale-0.0.1 failed during the building phase. The
exception was:
ExitFailure 1
xmonad-0.12 depends on data-default-instances-old-locale-0.0.1 which failed to
install.
```

/cc @ezyang

**Comment by 23Skidoo** [comment] 2015-10-09 15:56
This may be a duplicate of #2856.

**Comment by ezyang** [comment] 2015-10-09 17:03
Something terrible has happened: we've computed the same IPID hash for data-default-class and old-locale! That shouldn't happen.

**Comment by ezyang** [comment] 2015-10-09 17:26
Please give the fix a try, and reopen this if it does not solve the problem.

**Closed** 2015-10-09 17:26 UTC

**Comment by tuncer** [comment] 2015-10-09 18:25
Thanks, the fix works.
