### ISSUE TITLE
Break up cabal-install

### ISSUE THREAD

**Issue by jfischoff** [haskell/cabal#1848] opened 2014-05-06 19:56 UTC
I would like to be able to use pieces of cabal-install as a library. For instance the dependency solver is useful even if you have a make/shake based build system. I am some clean surgery could break up cabal-install into useful libraries.

**Comment by BardurArantsson** [comment] 2015-11-07 10:19
Closing as duplicate of #1597 -- see discussion there. Please re-open if you think that this is in error.

**Closed by BardurArantsson** 2015-11-07 10:19 UTC
Labels: enhancement
