### ISSUE TITLE
Cabal install with `--disable-shared` can fail if TemplateHaskell is required

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#2423] opened 2015-02-19 00:15 UTC
Using `cabal` from git HEAD (also fails like this with earlier versions):

    HOME=/tmp/cabal-test cabal-install/dist/build/cabal/cabal update
    HOME=/tmp/cabal-test cabal-install/dist/build/cabal/cabal install --disable-shared vector

fails with:

    Loading package primitive-0.5.4.0 ... <command line>: can't load .so/.DLL for:
    libHSprimitive-0.5.4.0.so (libHSprimitive-0.5.4.0.so: cannot open shared object file:
    No such file or directory)

Turns out that `cabal` has dutifully built `primitive` as a static library only but because `vector` uses `TemplateHaskell`, compiling `vector` needs the shared library version of all its dependencies.

**Comment by 23Skidoo** [comment] 2015-02-19 01:46
Try adding `other-extensions: TemplateHaskell` to the library stanza of `vector.cabal`.

**Comment by erikd** [comment] 2015-02-19 08:03
I'm not the maintainer of `vector` and `vector` isn't even what I want to install, its a low level library that a whole bunch of other stuff depends on.

I have a Yesod based webapp and since I want the webapp binary to only depend on system libraries I tired (somewhat foolishly I now understand):

     cabal install --dependencies-only --disable-shared

and that caused a huge number of packge installs to fail because of the `vector` fail.

However if I add what you suggested to my webapp's cabal file and run thie `cabal install` line above everything comes up roses. Thanks!

I still think `cabal` either needs some UI warning niceness, or assumes `other-extensions: TemplateHaskell` when installing dependencies.

**Comment by ttuegel** [comment] 2015-02-28 04:34
Essentially a duplicate of #1562.

**Closed by ttuegel** 2015-02-28 04:34 UTC
Labels: duplicate
