### ISSUE TITLE
if can't be used in a flag block

### ISSUE THREAD

**Issue by S11001001** [haskell/cabal#2429] opened 2015-02-20 21:02 UTC
This patch to ermine-language/ermine#17

``` diff
--- a/ermine.cabal
+++ b/ermine.cabal
@@ -48,9 +48,13 @@ source-repository head
   type: git
   location: git://github.com/ekmett/ermine.git

+-- work around https://github.com/ermine-language/ermine/issues/17
 flag ekg
   manual: True
-  default: True
+  if os(windows)
+    default: False
+  else
+    default: True

 -- `cabal install --enable-tests -f-doctests` to disable doctest suite
 flag doctests
```

Yields this error at command line:

```
j:\scompall\src\ermine>cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 

j:\scompall\src\ermine>cabal configure --enable-tests
cabal: 'parseField' called on a non-field. This is possibly a bug in Cabal.
Please report it to the developers: https://github.com/haskell/cabal/issues/new
```

**Comment by grayjay** [comment] 2017-03-12 04:12
Closing as a duplicate of #2397.

**Closed by grayjay** 2017-03-12 04:12 UTC
Labels: Cabal: file format, Cabal: other, type: enhancement
