### ISSUE TITLE
cabal-1.22 fails to run tests when some are disabled

### ISSUE THREAD

**Issue by qnikst** [haskell/cabal#2385] opened 2015-01-24 20:32 UTC
Starting from cabal-1.22 if one of test-suites is disabled (`Buildable: False`) via flag then `cabal test` fails to run with message:

```
cabal: Cannot build the test suite 'test-name' because the component is
marked as disabled in the .cabal file.
```

**Comment by ttuegel** [comment] 2015-01-24 20:36
Duplicate of #2357.

**Closed by ttuegel** 2015-01-24 20:36 UTC
