### ISSUE TITLE
Include union of all hs-source-dirs in sdist

### ISSUE THREAD

**Issue by gibiansky** [haskell/cabal#2544] opened 2015-04-20 19:49 UTC
I am not sure if this is a bug, something that was overlooked, or intended behaviour.

If you have several source directories, one per GHC version, and then use `hs-source-dirs` to include the right one based on the current GHC version (`impl(ghc < 7.6)`), then the order of if statements makes a difference in what `cabal sdist` sticks in the tarball.

See https://github.com/gibiansky/IHaskell/pull/478#issuecomment-94550829.

It seems like perhaps the desired behaviour is that `cabal sdist` includes the union of *all* `hs-source-dirs`, since any of them may be required, depending on what the user's system is like. Is this something that was considered and rejected for a reason? Or is this a bug?

**Comment by 23Skidoo** [comment] 2015-04-20 19:56
Most likely a bug.

**Comment by sumitsahrawat** [comment] 2015-04-20 19:56
What's strange is that even though I was using GHC 7.10, the `hs-source-dirs` given listed first were being used.

**Comment by amigalemming** [comment] 2015-04-22 06:42
I use conditional `Hs-Source-Dirs` a lot in order to prevent CPP. In order to make this work I had to add the conditional modules to `Extra-Source-Files`. This is ugly and error prone. Thus I would consider it a long-standing bug. The union of all `Hs-Source-Dirs` sounds like the right thing to do.

**Comment by gibiansky** [comment] 2015-04-22 06:44
@amigalemming Good to hear you came to the same solution that we came to in IHaskell. Yeah, I guess this sounds like a bug.

**Comment by ttuegel** [comment] 2015-04-24 19:16
This is actually a duplicate of #367.

**Closed by ttuegel** 2015-04-24 19:16 UTC
Labels: bug, high-priority

**Comment by amigalemming** [comment] 2015-04-25 14:09
On Fri, 24 Apr 2015, Thomas Tuegel wrote:

> This is actually a duplicate of #367.

This looks like code from gnuplot.cabal. The ticket must have been opened 
by me.

**Comment by gibiansky** [comment] 2015-08-23 00:24
Any progress on this?

**Comment by 23Skidoo** [comment] 2015-08-23 00:26
@gibiansky Yes, see db754ed30066ec3518fde192c18091f1f210c266.
