### ISSUE TITLE
List of recursive dependencies-and-versions

### ISSUE THREAD

**Issue by eyeinsky** [haskell/cabal#7214] opened 2020-12-27 18:23 UTC
Is there a way to get a list of dependencies for a project with versions?

The intent is to download and search all the source code. Perhaps if the source is already under one single folder somewhere, then this would already solve quite a large part of the problem.

(Github offers a "Bug report" issue template, but this is a question and a feature request. Not sure how should I have gone about this.)

**Comment by fgaz** [comment] 2020-12-27 18:25
[cabal-plan](https://hackage.haskell.org/package/cabal-plan)

**Comment by andreasabel** [comment] 2021-08-25 15:43
Duplicate of #879.

**Closed** 2021-08-29 21:29 UTC
Labels: type: user-question
