### ISSUE TITLE
`cabal outdated` lists deprecated package versions

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7249] opened 2021-01-16 08:32 UTC
For e.g. [Agda-2.6.1.2](https://hackage.haskell.org/package/Agda-2.6.1.2) `cabal outdated` includes `binary`
```
$ cabal outdated
Outdated dependencies:
binary >=0.8.3.0 && <0.9 (latest: 0.10.0.0)
```
but both latest versions 0.9.0.0 and 0.10.0.0 of `binary` are deprecated, see https://hackage.haskell.org/package/binary/preferred .
> Deprecating a version adds a range which excludes just that version. 

So the effective latest version of `binary` is still 0.8.8.0 and `outdated` shouldn't print anything for `binary`.

Reproduce:
```
cabal unpack Agda-2.6.1.2
cd Agda-2.6.1.2
cabal outdated
```

Cabal versions 3.2.0.0 and 3.5.0.0 (5 January 2021).

**Comment by fendor** [comment] 2021-05-24 17:48
Duplicate of #5603

**Closed** 2021-06-05 20:54 UTC
Labels: attention: pr-welcome, cabal-install: cmd/outdated
