### ISSUE TITLE
Can't pass -x lang in cc-options

### ISSUE THREAD

**Issue by arjuncomar** [haskell/cabal#1507] opened 2013-09-14 21:12 UTC
Because cc-options aren't passed before the input/output files are specified, the -x lang option can't be used to set the language gcc should treat the input as. The -x lang option is position dependent and must be passed before the relevant input files. cc-options should therefore be set as *early* as possible, and definitely before input files are specified.

**Comment by ttuegel** [comment] 2015-04-23 23:18
Duplicate of #1405.

**Closed by ttuegel** 2015-04-23 23:18 UTC
