### ISSUE TITLE
cabal install forgets prefix from configure step

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#2740] opened 2015-07-28 00:43 UTC
```
cabal configure --prefix=/tmp/foo
cabal build
cabal install
```

**Expected result:** Executable is installed into `/tmp/foo/bin`.
**Actual result:** Executable ends up somewhere else. Haven't been able to figure out where :-/

The sequence of commands is very similar to the commonly used `configure && make && make install` known from from unix packages. That's why I tried it, expecting it to work the same way.

One workaround seems to be to pass `--prefix=` to all three commands. Though I see no reason why I should have to repeat myself.

**Comment by lspitzner** [comment] 2015-07-28 11:49
Firstly, `cabal` breaks with the `make` convention. Afaik, `cabal install` corresponds to

~~~~
cabal install --dependencies-only
cabal configure
cabal build
cabal copy
cabal register
~~~~

So it is completely unnecessary (and won't work in general) to `configure`/`build` before installing. Instead, call `install` (with whatever configuration flags you want).

Secondly, `configure` and `install` use different states internally (if you are using a sandbox at least). I.e. `cabal configure` affects only `build`, `run`, `repl`, `test` and `bench`.

Duplicate of #302.

**Closed** 2016-05-06 20:38 UTC
Labels: bug
