### ISSUE TITLE
Solver failure on 3.0 with distsdir from 2.4.1.0 due to outdated "compiler" cache

### ISSUE THREAD

**Issue by DanielG** [haskell/cabal#6163] opened 2019-07-27 11:30 UTC
**Describe the bug**

When running `v2-build` from the current `3.0` branch in a project with any `other-extensions` declared and where the project was last built with cabal-install-2.4.1.0 a solver failure will occur.

It seems to me the `dist-newstyle/cache/compiler` cache is not getting invalidated even though the new cabal version expects more info to be in there. If I remove that file everything is fine.  

**To Reproduce**

```
$ cabal init -m -n -p repro --is-executable
$ echo '  other-extensions: NondecreasingIndentation' >> repro.cabal

$ rm -r dist-newstyle
$ cabal-2.4.1.0 v2-build

$ cabal-3.0.0.0 v2-build # solver failure
Warning: Parsing the index cache failed (Unknown encoding for constructor).
Trying to regenerate the index cache...
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: repro (user goal)
[__0] rejecting: repro-0.1.0.0 (conflict: requires NondecreasingIndentation)
[__0] fail (backjumping, conflict set: repro)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: repro

$ rm dist-newstyle/cache/compiler
$ cabal-3.0.0.0 v2-build # works
```

**System informataion**
- OS: Debian buster 
 -  `ghc` version: 8.4.4

**Comment by DanielG** [comment] 2019-07-27 11:37
Seems this might actually be a problem with the `NondecreasingIndentation` extension specifically or at least some subset of options. `DeriveFunction` doesn't trigger this but `ImpredicativeTypes` also does.

My guess would be 3f497f2c9fe5e04f300a37204f821f14969bcd99 is related though.

**Comment by hvr** [comment] 2019-08-28 20:07
Duplicate of #6099

**Comment by 23Skidoo** [comment] 2019-10-16 10:18
Closing in favour of #6099.

**Closed** 2019-10-16 10:18 UTC
