### ISSUE TITLE
Real file glob for extra-source-files

### ISSUE THREAD

**Issue by bos** [haskell/cabal#852] opened 2012-05-24 05:52 UTC
(Imported from [Trac #862](http://hackage.haskell.org/trac/hackage/ticket/862), reported by guest on 2011-07-13)

For the [Yesod scaffolding tool]([https://github.com/gregwebs/yesod/tree/org](https://github.com/gregwebs/yesod/tree/org)) We have a directory structure of extra files. The current file glob syntax doesn't recurse into directories or recognize files with multiple suffixes. So I am left to manually do a find command and list all the files in the cabal file. The extra-source-files field needs a real shell glob syntax. This does not seem like a hard change to make, but some guidance is needed for the approach. I see there is a [glob package]([http://hackage.haskell.org/packages/archive/Glob/](http://hackage.haskell.org/packages/archive/Glob/)).

**Comment by ttuegel** [comment] 2015-02-25 19:36
Duplicate of #784. There are also two open pull requests regarding this issue.

**Closed by ttuegel** 2015-02-25 19:36 UTC
Labels: enhancement, library
