### ISSUE TITLE
--enable-profiling not recognized by new-build?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3442] opened 2016-05-19 05:41 UTC
How do I make new-build build a profiling-enabled version of my executable? Can it be done?

/cc @dcoutts

**Comment by hvr** [comment] 2016-05-19 08:03
`cabal new-configure --enable-executable-profiling` results in `cabal.project.local` containing

    executable-profiling: True

...doesn't that work?

**Comment by edsko** [comment] 2016-05-19 08:06
Doesn't appear to, no.

**Comment by ezyang** [comment] 2016-09-06 05:09
It's possible you're seeing some more subtle bug, e.g. #3485. Hard to say without a reproducing case, but maybe wait till we fix that one and see if that fixes your case.

**Comment by ezyang** [comment] 2016-09-06 06:08
Please add `constraints: Cabal >= 1.24` and tell us if you still see this problem.

**Comment by edsko** [comment] 2016-09-19 04:13
With `cabal-install-head` from @hvr (1.25+git20160918.1.c9e046e~xenial), this config works:

```
packages: ingest.cabal

profiling: True
executable-profiling: True
constraints: Cabal >= 1.24

program-options
  ghc-options: -fprof-auto 
```

**Comment by hvr** [comment] 2016-09-19 06:47
@edsko minor nitpick: `ghc-prof-options` should be used to override the default prof detail level, and even better yet, there's

 - `profiling-detail: all-functions` and
 - `library-profiling-detail: all-functions`

which are supposed to work in cabal.project files (in pkg.cabal files we can only use `ghc-prof-options`), where the levels: default, none, exported-functions, toplevel-functions, all-functions map to the corresponding `-fprof-auto*` flags...

**Comment by ezyang** [comment] 2016-09-19 13:13
OK @edsko, I think that confirms that this is a dupe of #3485.

@hvr, this clearly seems like a documentation failing. `ghc-prof-options` is not documented. Can we fix the docs.

**Comment by 23Skidoo** [comment] 2016-09-21 21:54
Closing in favour of #3790, which has now been fixed. Please reopen if disagree.

**Closed by 23Skidoo** 2016-09-21 21:54 UTC
Labels: blocked: info-needed, cabal-install: nix-local-build, resolution: duplicate, type: user-question

**Comment by ezyang** [comment] 2016-09-28 07:54
Also note that `executable-profiling: True` is unnecessary; `profiling` will automatically enable it.

**Comment by ezyang** [comment] 2016-09-28 08:14
Also, to be clear, `ghc-prof-options` is NOT supported in `cabal.project` format. So you can only put the flags in `ghc-options` or use Cabal's built-ins.
