### ISSUE TITLE
Cabal update crashes

### ISSUE THREAD

**Issue by HJvT** [haskell/cabal#2577] opened 2015-05-05 08:28 UTC
On my Windows 8.1, 64 bit system, the cabal-install that comes with MinGHC-7.10.1 crashes when I give command

```
cabal update
```

When I run the same command with a cabal-install that I installed myself, the update is successful. Note, that the MinGHC cabal.exe is 32 bit, and the one I compiled myself is 64 bit. The version of both cabal.exes is 1.22.2.0
I had these crashes before, with different versions of cabal-install.
A cabal.exe, compiled with MinGHC-7.10.1 in a sandbox, version 1.22.3.0, 32 bit, runs properly.

A gdb session:

```
> gdb cabal
GNU gdb (GDB) 7.6.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from C:\x\MinGHC-7.10.1\bin\cabal.exe...(no debugging symbols found)...done.
(gdb) r update
Starting program: C:\x\MinGHC-7.10.1\bin/cabal.exe update
[New Thread 8296.0x25dc]
[New Thread 8296.0x21d4]
[New Thread 8296.0x6e8]
[New Thread 8296.0x1b44]
Downloading the latest package list from hackage.haskell.org
warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

warning: Invalid parameter passed to C runtime function.

Skipping download: Local and remote files match.
[Inferior 1 (process 8296) exited normally]
(gdb)
```

When I run the self-compiled cabal.exe in gdb, no warning is given.

**Comment by 23Skidoo** [comment] 2015-05-05 08:44
Probably something to do with the `network` library.

> `warning: Invalid parameter passed to C runtime function.`

Is it possible to find out which one?

> ```
Skipping download: Local and remote files match.
[Inferior 1 (process 8296) exited normally]
```

Looks normal to me.

**Comment by HJvT** [comment] 2015-05-05 09:16
The command only finishes when run in gdb; without gdb, the package list is never updated

**Comment by 23Skidoo** [comment] 2015-05-05 09:19
It looks like it managed to download the etag, checked it against local etag copy and then skipped the download (due to etags being identical).

**Comment by HJvT** [comment] 2015-05-13 09:05
When run in gdb, I get the 
  warning: Invalid parameter passed to C runtime function.
messages; without gdb, I get a window saying the program crashed. When I run this version of cabal automatically each day, the package list is never updated.

**Comment by LukaHorvat** [comment] 2015-06-11 11:42
Is there any workaround for this? Same thing happens for me on Windows Server 2012 R2, 64bit

**Comment by bgamari** [comment] 2015-06-17 14:42
It [appears](https://msdn.microsoft.com/en-us/library/a9yf33zb.aspx) that it is possible to define a handler to catch this warning. It would be good if someone able to reproduce this could write a quick C shim with a handler dumping the information it is provided. It would at very least be very helpful to know which function this is coming from.

**Comment by LukaHorvat** [comment] 2015-06-17 17:56
I'm willing to do it but I wouldn't know how.
Is this something I could do outside of cabal or would I have to modify cabal's source and recompile?

**Comment by bgamari** [comment] 2015-06-22 15:21
It would probably involve writing a little C shim, exposing it via the FFI, and calling it in `main`.

**Comment by fakedrake** [comment] 2016-05-05 07:43
Any news on this?

**Comment by 23Skidoo** [comment] 2016-05-05 07:47
@fakedrake Does this still happen with `cabal-install` 1.24.0.0 binaries available here: https://www.haskell.org/cabal/download.html ?

**Comment by HJvT** [comment] 2021-05-20 00:58
As this is old and does not happen anymore, I think this issue can be closed.

**Comment by Mikolaj** [comment] 2021-05-20 07:38
@HJvT: thank you for originally reporting and for checking it's fixed now. Closing.

**Closed by Mikolaj** 2021-05-20 07:38 UTC
Labels: cabal-install: cmd/update, platform: windows, type: bug
