### ISSUE TITLE
Document verbose flag properlty

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6384] opened 2019-11-28 02:12 UTC
https://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-verbose only says about numeric properties, no textual `-vnormal`, nor explanation of flags?

- What `+nowrap` does, @hvr
- What `+markoutput` does, @ezyang?

**Comment by ezyang** [comment] 2019-12-04 15:28
Answered in https://github.com/haskell/cabal/issues/6383

**Comment by bacchanalia** [comment] 2022-02-17 17:27
duplicate of #4519

**Comment by jneira** [comment] 2022-07-03 13:57
closed as duplicate of #4519

**Closed by jneira** 2022-07-03 13:57 UTC
Labels: documentation, attention: pr-welcome
