### ISSUE TITLE
cabal list-bin is undocumented

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/cabal#7945] opened 2022-02-01 20:39 UTC
**Describe the bug**
As far as I see `cabal list-bin` is not mentioned anywhere in the docs.

**Expected behavior**
The command has some documentation.

**Comment by Mikolaj** [comment] 2022-02-01 20:53
Duplicate of #7774

But thank you for the ticket and please review the PR for #7774 when it lands.

**Comment by Mikolaj** [comment] 2022-02-01 20:54
Duplicate of #7774

**Closed by Mikolaj** 2022-02-01 20:53 UTC

**Comment by Mikolaj** [comment] 2022-02-01 20:54
Huh, apparently adding anything to the `Duplicate` comment blocks the marking as duplicate.

**Comment by ulysses4ever** [comment] 2022-02-01 20:57
Oh, should have found it. Thanks a lot!
