### ISSUE TITLE
fdLock invalid argument on WSL1

### ISSUE THREAD

**Issue by adpextwindong** [haskell/cabal#7528] opened 2021-08-11 13:53 UTC
Cabal v1-build under WSL1 causes an fdLock invalid argument error.

```
fdLock: invalid argument (Invalid argument)
```

**To Reproduce**

Running ```cabal v1-build``` under [Hackage-server's](https://github.com/haskell/hackage-server) Nix-shell ([commit 9e451cb](https://github.com/haskell/hackage-server/tree/9e451cb456730dfecfb1231e0dfd46410089f496)) on a WSL1 Ubuntu 20.04 system.
```
$ cabal v1-build
```

**System information**
```
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
Glasgow Haskell Compilation System, version 8.10.4
WSL1 Ubuntu 20.04
Nix-shell from hackage-server commit 9e451cb off the master branch
```

A partial strace log leading up to the fdlock:

```
read(13, "", 32752)                     = 0
close(13)                               = 0
unlink("/home/takumi/.cabal/packages/hackage.haskell.org/timestamp.json") = -1 ENOENT (No such file or directory)
futex(0x7f1640000be8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f1640000bf0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1722e38, FUTEX_WAKE_PRIVATE, 1) = 1
openat(AT_FDCWD, "/home/takumi/.cabal/packages/hackage.haskell.org/hackage-security-lock", O_RDWR|O_CREAT, 0666) = 13fcntl(13, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = -1 EINVAL (Invalid argument)
close(13)                               = 0
poll([{fd=2, events=POLLOUT}], 1, 0)    = 1 ([{fd=2, revents=POLLOUT}])
write(2, "fdLock: invalid argument (Invali"..., 44fdLock: invalid argument (Invalid argument)
) = 44
```

I'm not sure which WSL version is favored by Cabal so I will be testing WSL2 as well.

**Comment by Mikolaj** [comment] 2021-08-11 14:02
Hi @adpextwindong! Thank you for the report. Yes, I've heard people having similar problems with cabal on WSL1, but no problem with WSL2. Please let us know if that's the case for you, as well.

**Comment by phadej** [comment] 2021-08-12 17:58
This is duplicate of https://github.com/haskell/cabal/issues/6551

**Closed by phadej** 2021-08-12 17:58 UTC
