### ISSUE TITLE
Error bootstraping cabal-install with GHC 7.6.3: Missing dependencies

### ISSUE THREAD

**Issue by asr** [haskell/cabal#3434] opened 2016-05-15 12:52 UTC
Bootstraping cabal-install 1.24.0.0 with GHC 7.6.3, I got the following error:

```bash
./bootstrap.sh 
...
Configuring binary-0.8.3.0...
Setup: At least the following dependencies are missing:
bytestring >=0.10.2

Error during cabal-install bootstrap:
Configuring the binary package failed.
```

**Comment by asr** [comment] 2016-05-15 13:11
Bootstraping cabal-install 1.22.9.0 with GHC 7.6.3, I got the following error:

```
./bootstrap.sh
...
Configuring mtl-2.2.1...
Setup: At least the following dependencies are missing:
transformers ==0.4.*

Error during cabal-install bootstrap:
Configuring the mtl package failed.
```

**Comment by 23Skidoo** [comment] 2016-05-15 15:22
See also #3349.

**Comment by 23Skidoo** [comment] 2016-05-17 22:46
Fixed on `master`, but needs to be backported.

**Comment by 23Skidoo** [comment] 2016-05-24 13:46
Fixed in 7884fabf8e6b75131eb67fd5e5d6826e3a0114d5.

**Closed by 23Skidoo** 2016-05-24 13:46 UTC
Labels: bug, cabal-install

**Comment by asr** [comment] 2016-05-24 14:37
Thanks!

**Comment by madhavan020985** [comment] 2016-08-16 11:06
I tried source downloading cabal from https://www.haskell.org/cabal/download.html & tried to bootstrap. I hit the same error `bytestring` missing dependencies. How can i take 23Skidoo's fix?

**Comment by 23Skidoo** [comment] 2016-08-16 11:13
This is fixed on the 1.24 branch, but not in any released version. There will be a new point release of cabal-install/Cabal from the 1.24 branch soon (probably the first week of September), until then you can bootstrap from a Git checkout of the 1.24 branch.

**Comment by madhavan020985** [comment] 2016-08-16 16:57
thanks, Skidoo.. though i had to move to haskell 7.8 from haskell 7.6 due to the error `haddock: internal error: synifyKind,,,, Documenting the mtl package failed.`

**Comment by pm0kjp** [comment] 2017-02-08 17:07
@madhavan020985 et al.,  I'm having the same problem, not sure how to backtrack to haskell 7.6.  This is a brand new install of cabal-install-1.24.0.2, and upon bootstrapping I get the error 
```
haddock: internal error: synifyKind

Error during cabal-install bootstrap:
Documenting the mtl package failed.
```
I'm trying to set up a production server so the powers that be probably don't want me using an unreleased version of cabal-install.  So backtracking Haskell itself is the best bet.  I have only installed ghc, cabal, and cabal-install, along with a few other necessities.  This was my installation process so far:

```
yum install ghc
yum install optipng
yum install zlib-devel

wget https://www.haskell.org/cabal/release/cabal-1.24.2.0/Cabal-1.24.2.0.tar.gz
tar xzf Cabal-1.24.2.0.tar.gz

cd Cabal-1.24.2.0
ghc -threaded --make Setup
./Setup configure
./Setup build
sudo ./Setup install

wget https://www.haskell.org/cabal/release/cabal-install-1.24.0.2/cabal-install-1.24.0.2.tar.gz
tar xzf cabal-install-1.24.0.2.tar.gz
cd cabal-install-1.24.0.2

./bootstrap.sh
```

**Comment by 23Skidoo** [comment] 2017-02-08 17:18
@pm0kjp Try running `bootstrap.sh` with `--no-doc`. You may also want to try `EXTRA_CONFIGURE_OPTS="" ./bootstrap.sh --no-doc` to cut down on compilation time.

**Comment by pm0kjp** [comment] 2017-02-08 18:20
`EXTRA_CONFIGURE_OPTS="" ./bootstrap.sh --no-doc` did the trick!

Thanks @23Skidoo!

**Comment by barracuda156** [comment] 2024-04-01 15:31
Is it better to use Haskell Platform 2013.2.0.0, as described here: https://gist.github.com/wting/8498731
Or rather go with a standalone one?

I need to build it from source in any case.

**Comment by ulysses4ever** [comment] 2024-04-01 16:45
@barracuda156 Haskell Platform is discontinued. Please, use any modern installation method you can. Many people find ghcup helpful.

**Comment by barracuda156** [comment] 2024-04-01 16:57
> @barracuda156 Haskell Platform is discontinued. Please, use any modern installation method you can. Many people find ghcup helpful.

Thank you. The issue is that I need to use specifically 7.6.3 (at least for the time-being), so if I understand correctly, corresponding tools should be used.
