### ISSUE TITLE
Wrong cache invalidation (using PVP versions) with `cabal install` vs `cabal build`

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#7811] opened 2021-11-11 08:43 UTC
* Detected when `ghcup compile hls` was implemeted
* Quoting from https://github.com/haskell/haskell-language-server/issues/1431

> The reason is, because cabal install is semi-broken when you install from git, since it caches based on PVP versions and will not always pick up changes from dependencies via source-repository-package. That's why we switched to cabal build.

and

> I think the problem also exists for anything listed in packages, which is the case for e.g. ghcide.

We should investigate the bug and try to reproduce it consistently to avoid to have to use `cabal build` + `cabal list-bin`, workaround that does not play well with dynamic linking

More context:
* ghcup-hs pr with the change: https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/189
* ghcup-hs issue about compiling hls with dynamic linking: https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/245#note_390869

//cc @hasufell

**Comment by phadej** [comment] 2021-11-11 08:47
Duplicate of https://github.com/haskell/cabal/issues/6211 and https://github.com/haskell/cabal/issues/5782 which are marked fixed. Without a reproducer, I'm simply going to close this.

**Closed by phadej** 2021-11-11 08:47 UTC
Labels: type: bug, blocked: info-needed, blocked: needs repro

**Comment by jneira** [comment] 2021-11-11 08:55
Hmm hls nor its companions (ghcide, hls-plugin-api etc) dont use internal libraries :thinking:

**Comment by phadej** [comment] 2021-11-11 08:59
Then I don't think there's a bug.

> The reason is, because cabal install is semi-broken when you install from git, since it caches based on PVP versions 

Is definitely not true. Contents of the `sdist`ed tarball are part of unit-id hash.

This issue needs a reproducer, no point to keep the issue open indefinitely until.

**Comment by jneira** [comment] 2021-11-11 09:21
> This issue needs a reproducer, no point to keep the issue open indefinitely until.

hmm but does a bug report needs a reproducer to keep it opened? that is the rationale behind the `blocked: needs repro` label. 
should we close all issues labeled with it?

my intent was just work in getting such reproducer and close it if it is not possible...

**Comment by phadej** [comment] 2021-11-11 09:32
My opinon on `blocked: needs repro` that if they have been open for say few months, they can be closed. This is slightly different, as this looks like a duplicate.

**Comment by jneira** [comment] 2021-11-11 09:39
> My opinon on blocked: needs repro that if they have been open for say few months, they can be closed

agree

> This is slightly different, as this looks like a duplicate.

But, a duplicate of? I've spent some time searching the issue tracker to find it (but maybe i failed of course). 
Imo all reports have the right of be presumed innocent until proven guilty :slightly_smiling_face: 

But whatever, will reopen if i find the reproducer

**Comment by hasufell** [comment] 2021-11-11 12:27
I tried to reproduce it and I can't.

* https://github.com/haskell/cabal/blob/5b4258cbfa536b6362c4e20578ced51676206ea8/cabal-install/src/Distribution/Client/ProjectPlanning.hs#L963-L985
* https://github.com/haskell/cabal/blob/5b4258cbfa536b6362c4e20578ced51676206ea8/cabal-install/src/Distribution/Client/PackageHash.hs#L261

As you can see here... cabal hashes the entire contents of the source tarball. If you have the same PVP version, but different contents, it will rebuild the dependency. So the effect we observed was either due to something else or our assumptions were wrong.

**Comment by jneira** [comment] 2021-11-11 12:41
@hasufell thanks for check it, maybe returning to use cabal install in ghcup it will eventually trigger it again
