### ISSUE TITLE
Cabal does not consider reinstalling a installed package

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#9342] opened 2023-10-15 19:35 UTC
**Describe the bug**

It seems that under certain conditions, Cabal does not find a build plan that involves reinstalling a package that it finds installed (or something else is going on).

**To Reproduce**

Install ghc-9.8.1, clone `nomeata/cabal-force-upper-bound` at revision `4af49ba6915dfb7ec8f28daabb22cd8ea60f9add` and run
```
~/projekte/programming/haskell/cabal-force-upper-bound $ cabal build -w ghc-9.8.1 "--constraint=containers ^>=0.7" --allow-newer=containers
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: cabal-force-upper-bound-0.1 (user goal)
[__1] trying: text-2.1/installed-inplace (dependency of
cabal-force-upper-bound)
[__2] trying: deepseq-1.5.0.0/installed-inplace (dependency of text)
[__3] trying: binary-0.8.9.1/installed-inplace (dependency of text)
[__4] next goal: containers (dependency of cabal-force-upper-bound)
[__4] rejecting: containers-0.6.8/installed-inplace (constraint from command
line flag requires ^>=0.7)
[__4] rejecting: containers-0.7 (conflict: binary =>
containers==0.6.8/installed-inplace)
[__4] rejecting: containers-0.6.8, containers-0.6.7, containers-0.6.6,
containers-0.6.5.1, containers-0.6.4.1, containers-0.6.3.1,
containers-0.6.2.1, containers-0.6.1.1, containers-0.6.0.1,
containers-0.5.11.0, containers-0.5.10.2, containers-0.5.10.1,
containers-0.5.9.2, containers-0.5.8.2, containers-0.5.7.1,
containers-0.5.7.0, containers-0.5.6.3, containers-0.5.6.2,
containers-0.5.6.1, containers-0.5.6.0, containers-0.5.5.1,
containers-0.5.5.0, containers-0.5.4.0, containers-0.5.3.1,
containers-0.5.3.0, containers-0.5.2.1, containers-0.5.2.0,
containers-0.5.1.0, containers-0.5.0.0, containers-0.4.2.1,
containers-0.4.2.0, containers-0.4.1.0, containers-0.4.0.0,
containers-0.3.0.0, containers-0.2.0.1, containers-0.2.0.0,
containers-0.1.0.1, containers-0.1.0.0, containers-0.5.9.1, containers-0.5.8.1
(constraint from command line flag requires ^>=0.7)
[__4] fail (backjumping, conflict set: binary, cabal-force-upper-bound,
containers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: text, base, containers, binary,
cabal-force-upper-bound, deepseq, Cabal-syntax
Try running with --minimize-conflict-set to improve the error message.
```

And following the suggestion
```
$ cabal build -w ghc-9.8.1 "--constraint=containers ^>=0.7" --allow-newer=containers --minimize-conflict-set
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: cabal-force-upper-bound-0.1 (user goal)
[__1] trying: text-2.1/installed-inplace (dependency of
cabal-force-upper-bound)
[__2] next goal: containers (dependency of cabal-force-upper-bound)
[__2] rejecting: containers-0.6.8/installed-inplace (constraint from command
line flag requires ^>=0.7)
[__2] trying: containers-0.7
[__3] trying: base-4.19.0.0/installed-inplace (dependency of
cabal-force-upper-bound)
[__4] next goal: Cabal-syntax (dependency of cabal-force-upper-bound)
[__4] rejecting: Cabal-syntax-3.10.2.0/installed-inplace (conflict:
containers==0.7, Cabal-syntax => containers==0.6.8/installed-inplace)
[__4] rejecting: Cabal-syntax-3.10.1.0, Cabal-syntax-3.8.1.0 (conflict: text
=> bytestring==0.12.0.2/installed-inplace, Cabal-syntax =>
bytestring>=0.10.0.0 && <0.12)
[__4] rejecting: Cabal-syntax-3.6.0.0 (conflict: cabal-force-upper-bound =>
Cabal-syntax^>=3.8.1 || ^>=3.10.1)
[__4] fail (backjumping, conflict set: Cabal-syntax, cabal-force-upper-bound,
containers, text)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: text, cabal-force-upper-bound, base,
containers, Cabal-syntax
```

**Expected behavior**

I would expect it to try `text-2.1` from hackage, which wouldn’t insist on using the installed `binary` and `containers`, so that I can use the latest `containers` from hackage. 

Is it maybe always preferring the installed version over a hackage package of the same version?

In the second try, it seems it uses the installed `Cabal-syntax-3.10.2.0` and doesn’t consider rebuilding… 

Maybe the problem is elsewhere, in which case the error message could be improved.

**System information**
 - NixOS, also on Github runners
 - `cabal-install version 3.10.1.0`

**Additional context**

Also see <https://github.com/nomeata/cabal-force-upper-bound/actions/runs/6525119308/job/17717498203?pr=3>

**Comment by nomeata** [comment] 2023-10-15 19:35
Ah, but that maybe due to https://github.com/haskell/cabal/issues/9333. I wonder if that’s the cause in both cases, and the error message just isn’t so great. Maybe we can close this once https://github.com/haskell/cabal/issues/9333 is resolved.

**Comment by gbaz** [comment] 2023-10-16 00:43
I think we can close this regardless. Its only the lack of a package on hackage causing cabal to (rightfully) not try to rebuild it (in the second case).

In the first case, I believe the issue is not that its failing to try text from hackage, but just that there's a more complex conflict set it can't solve, regardless.

I could be wrong here, but I really just can't imagine the issue as reported is correct -- such a failure case would cause way more errors.

**Closed** 2023-10-16 06:33 UTC
Labels: type: bug, needs triage

**Comment by andreabedini** [comment] 2023-10-18 06:22
@nomeata

> I would expect it to try text-2.1 from hackage, which wouldn’t insist on using the installed binary and containers, so that I can use the latest containers from hackage.

Yes, it does exactly that. You can add `-v3` to see the solver inner working in full glory:

```
[__0] trying: cabal-force-upper-bound-0.1 (user goal)
...
[__5] trying: text-2.1/installed-dc8d (dependency of cabal-force-upper-bound)
...
[__9] trying: binary-0.8.9.1/installed-6c79 (dependency of text)
...
[_27] next goal: containers (dependency of cabal-force-upper-bound)
[_27] rejecting: containers-0.6.8/installed-3ad8 (constraint from command line flag requires ^>=0.7)
[_27] rejecting: containers-0.7 (conflict: binary => containers==0.6.8/installed-3ad8)
[_27] fail (backjumping, conflict set: binary, cabal-force-upper-bound, containers)
```
We need another choice for binary:
```
[__9] rejecting: binary-0.8.9.1, ... (conflict: text => binary==0.8.9.1/installed-6c79)
[__9] fail (backjumping, conflict set: binary, cabal-force-upper-bound, containers, text)
```
... which is impossible because we had choosen a pre-installed text.

Let's try another text
```
[__5] trying: text-2.1
[__6] trying: binary-0.8.9.1/installed-6c79 (dependency of text)
[__7] next goal: containers (dependency of cabal-force-upper-bound)
[__7] rejecting: containers-0.6.8/installed-3ad8 (constraint from command line flag requires ^>=0.7)
[__7] rejecting: containers-0.7 (conflict: binary => containers==0.6.8/installed-3ad8)
[__7] rejecting: containers-0.6.8, ... (constraint from command line flag requires ^>=0.7)
[__7] fail (backjumping, conflict set: binary, cabal-force-upper-bound, containers)
[__6] trying: binary-0.8.9.1
[__7] next goal: containers (dependency of cabal-force-upper-bound)
[__7] rejecting: containers-0.6.8/installed-3ad8 (constraint from command line flag requires ^>=0.7)
[__7] trying: containers-0.7
...
```
We will try again preinstalled binary and containers but then figure out that they won't work so we pick text, binary and containers from a source package.

The failure happens later on, when we need to pick Cabal-syntax.

```
[_35] next goal: Cabal-syntax (dependency of cabal-force-upper-bound)
[_35] rejecting: Cabal-syntax-3.10.2.0/installed-00a1 (conflict: binary==0.8.9.1, Cabal-syntax => binary==0.8.9.1/installed-6c79)
[_35] rejecting: Cabal-syntax-3.10.1.0 (conflict: bytestring==0.12.0.2/installed-bac6, Cabal-syntax => bytestring>=0.10.0.0 && <0.12)
```
Alright, the installed Cabal-syntax won't work because we have a source binary. So we need to pick a Cabal-syntax from source. This is where things get messy.

There is no Cabal-syntax source that allows the pre-installed bytestring (Cabal-syntax-3.10.1.0 has bytestring>=0.10.0.0 && <0.12 which I think we should review).

But the solver is stubborn and says "ok fine I'll compile bytestring too then!"

```
[_34] trying: bytestring-0.11.5.2
[_35] next goal: Cabal-syntax (dependency of cabal-force-upper-bound)
[_35] rejecting: Cabal-syntax-3.10.2.0/installed-00a1 (conflict: binary==0.8.9.1, Cabal-syntax => binary==0.8.9.1/installed-6c79)
[_35] rejecting: Cabal-syntax-3.10.1.0 (conflict: deepseq==1.5.0.0/installed-a0f3, Cabal-syntax => deepseq>=1.3.0.1 && <1.5)
[_35] skipping: Cabal-syntax-3.8.1.0 (has the same characteristics that caused the previous version to fail: excludes 'deepseq' version 1.5.0.0)
[_35] rejecting: Cabal-syntax-3.6.0.0 (conflict: cabal-force-upper-bound => Cabal-syntax^>=3.8.1 || ^>=3.10.1)
[_35] fail (backjumping, conflict set: Cabal-syntax, binary, cabal-force-upper-bound, deepseq)
```

but the same thing happens for deepseq and an evenly slightly older version of deepseq won't be compatible with base.
```
[_16] rejecting: deepseq-1.4.8.1 (conflict: base==4.19.0.0/installed-c1f2, deepseq => base>=4.9 && <4.19)
```

Going far back enough we find a old version of deepseq that could work, but then we fail on text.

```
[_16] trying: deepseq-1.3.0.1
[_17] next goal: Cabal-syntax (dependency of cabal-force-upper-bound)
[_17] rejecting: Cabal-syntax-3.10.2.0/installed-00a1 (conflict: deepseq => array>=0.1 && <0.5, Cabal-syntax => array==0.5.6.0/installed-6953)
[_17] rejecting: Cabal-syntax-3.10.1.0 (conflict: text==2.1, Cabal-syntax => text>=1.2.3.0 && <1.3 || >=2.0 && <2.1)
```

In the end, it's the constraints of Cabal(-syntax)-3.10.1.0 that make it fail, not much the fact that 3.10.2.0 is not uploaded to Hackage.

You can get a working plan with this
```
$ cabal build -v3 --dry-run -w ghc-9.8.1 "--constraint=containers ^>=0.7" --allow-newer=containers --allow-newer=Cabal{,-syntax}:{bytestring,deepseq,text}
```

Which seems to work ok (or at least it compiles).
