### ISSUE TITLE
cabal sdist does not work with conditional flags in executables

### ISSUE THREAD

**Issue by agocorona** [haskell/cabal#3851] opened 2016-09-16 21:11 UTC
I have

     executable   monitorService
       if !impl(ghcjs >=0.1)
         main-is :      MonitorService.hs
         build-depends: base >4 && <5, transient, transient-universe, transformers
         default-language:  Haskell2010
         ghc-options:  -threaded -rtsopts
         hs-source-dirs: src/Transient/Move/Services
       else
         main-is : void.hs
         build-depends: base

> cabal sdist
...
cabal.exe: MonitorService.hsvoid.hs doesn't exist

**Comment by 23Skidoo** [comment] 2016-09-16 22:28
Duplicate of #3313.

**Closed by 23Skidoo** 2016-09-16 22:28 UTC
