### ISSUE TITLE
Cannot install library dependencies

### ISSUE THREAD

**Issue by goldfirere** [haskell/cabal#6246] opened 2019-09-18 15:22 UTC
**Describe the bug**
I can't seem to globally install the dependencies of a local package.

**To Reproduce**
Navigate to the root directory of a cabalized package and run `cabal install --only-dependencies`. Witness the following error:

```
cabal: Cannot build the executables in the package units because it does not
contain any executables. Check the .cabal file for the package and make sure
that it properly declares the components that you expect.
```

I know there are no executables. I want the libraries installed into my global package database, just like happened with previous versions of `cabal`.

**Expected behavior**
I want the dependencies of my package to be installed in my global package database, so that when I run `ghci`, from any directory on my system, I can access them.

**System informataion**
 - `cabal` version 3.0.0.0

**Additional context**
Perhaps I am misusing `cabal`, but trying to educate myself hit #6245. Some background may be in #5650, which also describes why I care about the global database.

**Comment by goldfirere** [comment] 2019-09-18 21:51
Aha. I needed to pass `--lib`. Perhaps the error message should suggest this? In any case, I've gotten past this barrier.

**Comment by fgaz** [comment] 2019-09-19 06:45
Duplicate of #6237 (pinging @typedrat again)

**Comment by typedrat** [comment] 2019-09-19 16:46
I’ll look at it on the other issue.

**Closed by typedrat** 2019-09-19 16:46 UTC

**Comment by selinger** [comment] 2019-10-14 19:44
Please fix this as soon as possible, as it is a major usability issue. The Cabal 3.0.0.0 (and later) documentation clearly states that "cabal install [PACKAGE]" is the way to install a package, for example here: https://www.haskell.org/cabal/users-guide/installing-packages.html#building-and-installing-packages

It does not mention the existence of any --lib option at all. And most packages that I have ever installed are libraries, so why would the default be to expect executables in a package that doesn't contain them?

It looks to me like the documentation that claims to be for Cabal 3.0.0.0 is in fact for Cabal 2, as it contains many other instructions that don't work with Cabal 3.0.0.0 (e.g., "cabal sandbox init", which gives an "unrecognised command" error, or "cabal install package-0.0.0.0.tar.gz", which gives an "Invalid package ID" error.

Incidentally, where is the *actual* documentation for Cabal 3.0.0.0 located? Thanks!

**Comment by Vidydy** [comment] 2020-01-07 13:39
I had to find this thread to understand why I could not install packages. Running cabal install <package> I get:

> Resolving dependencies...
> cabal: Cannot build the executables in the package HDBC because none of the
> components are available to build: the executable 'runtests' is marked as
> 'buildable: False'

Adding "--lib" does fix the issue. Please update wikis and docs

**Comment by zehle** [comment] 2020-02-28 17:36
Same for me as for Vidydy. Adding "--lib" fixed it. Had to find this page to solve the problem.
