### ISSUE TITLE
optionally select the oldest available dependencies rather than the newest

### ISSUE THREAD

**Issue by bos** [haskell/cabal#653] opened 2012-05-24 05:41 UTC
(Imported from [Trac #661](http://hackage.haskell.org/trac/hackage/ticket/661), reported by @benmachine on 2010-04-19)

When developing a package, you want to specify as wide a range of build-depends as possible, but it's often quite tedious to keep checking if your latest development effort hasn't made your package incompatible with some ancient version of a library you use.

In view of this I think it would be helpful to have an option that asks cabal configure to pick the oldest possible version of each dependency, so you could quickly and easily ensure that at least the two endpoints are covered.

**Comment by ttuegel** [comment] 2015-02-28 04:43
Duplicate of #2228.

**Closed by ttuegel** 2015-02-28 04:43 UTC
Labels: cabal-install, duplicate, enhancement
