### ISSUE TITLE
Linking step may be skipped, resulting in stale executable

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#7711] opened 2021-10-07 14:51 UTC
This is on macOS Mojave, GHC 8.10.7, cabal from `master` (bb08616b0bd96aac880b2ceb37402bc8bd4a067a):

After changes to `cabal-install/src/Distribution/Client/Config.hs`, I build:
```
$ cabal build all -w ghc-8.10.7 --enable-tests
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cabal-install-3.7.0.0 (lib) (file src/Distribution/Client/Config.hs changed)
 - cabal-install-3.7.0.0 (test:unit-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:memory-usage-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:long-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:integration-tests2) (dependency rebuilt)
 - cabal-install-3.7.0.0 (exe:cabal) (dependency rebuilt)
Preprocessing library for cabal-install-3.7.0.0..
Building library for cabal-install-3.7.0.0..
[ 99 of 132] Compiling Distribution.Client.Config ( src/Distribution/Client/Config.hs, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.o, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.dyn_o )
Preprocessing test suite 'unit-tests' for cabal-install-3.7.0.0..
Building test suite 'unit-tests' for cabal-install-3.7.0.0..
Linking /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/t/unit-tests/build/unit-tests/unit-tests ...
Preprocessing test suite 'memory-usage-tests' for cabal-install-3.7.0.0..
Building test suite 'memory-usage-tests' for cabal-install-3.7.0.0..
Linking /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/t/memory-usage-tests/build/memory-usage-tests/memory-usage-tests ...
Preprocessing test suite 'long-tests' for cabal-install-3.7.0.0..
Building test suite 'long-tests' for cabal-install-3.7.0.0..
Linking /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/t/long-tests/build/long-tests/long-tests ...
Preprocessing test suite 'integration-tests2' for cabal-install-3.7.0.0..
Building test suite 'integration-tests2' for cabal-install-3.7.0.0..
Linking /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/t/integration-tests2/build/integration-tests2/integration-tests2 ...
Preprocessing executable 'cabal' for cabal-install-3.7.0.0..
Building executable 'cabal' for cabal-install-3.7.0.0..
Linking /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/x/cabal/build/cabal/cabal ...
```
After more changes, I build again:
```
$ cabal build all -w ghc-8.10.7 --enable-tests
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cabal-install-3.7.0.0 (lib) (file src/Distribution/Client/Config.hs changed)
 - cabal-install-3.7.0.0 (test:unit-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:memory-usage-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:long-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:integration-tests2) (dependency rebuilt)
 - cabal-install-3.7.0.0 (exe:cabal) (dependency rebuilt)
Preprocessing library for cabal-install-3.7.0.0..
Building library for cabal-install-3.7.0.0..
[ 99 of 132] Compiling Distribution.Client.Config ( src/Distribution/Client/Config.hs, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.o, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.dyn_o )
Preprocessing test suite 'unit-tests' for cabal-install-3.7.0.0..
Building test suite 'unit-tests' for cabal-install-3.7.0.0..
Preprocessing test suite 'memory-usage-tests' for cabal-install-3.7.0.0..
Building test suite 'memory-usage-tests' for cabal-install-3.7.0.0..
Preprocessing test suite 'long-tests' for cabal-install-3.7.0.0..
Building test suite 'long-tests' for cabal-install-3.7.0.0..
Preprocessing test suite 'integration-tests2' for cabal-install-3.7.0.0..
Building test suite 'integration-tests2' for cabal-install-3.7.0.0..
Preprocessing executable 'cabal' for cabal-install-3.7.0.0..
Building executable 'cabal' for cabal-install-3.7.0.0..
```
Notice how the `Linking` steps are omitted, thus, executables are not updated.

I interspersed a
```
$ cabal build cabal-install -w ghc-8.10.7 -O0
```
but this should not affect the `-O1` build, as build products end up in `noopt/` subtrees, or should it?

My config file has the standard settings plus:
```
install-method: copy
overwrite-policy: always
write-ghc-environment-files: never
```
(in particular, no individual settings about dynamic linking).

**Comment by andreasabel** [comment] 2021-10-07 14:58
> I'm not sure if `-O0` is the same as `--disable-optimization`. Can you confirm there indeed is something with proper timestamps in the `noopt/` subtree?

Yes the timestamps there are correct.

**Comment by andreasabel** [comment] 2021-10-07 17:55
Interestingly, after removing the build directory for `-O0`, namely `dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/noopt`, I am getting errors for `-O1`.  So it seems that these two modes are not actually separate, but some build products of one is used by the other.
```
$ cabal build cabal-install -w ghc-8.10.7 
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cabal-install-3.7.0.0 (lib) (file src/Distribution/Client/Config.hs changed)
 - cabal-install-3.7.0.0 (test:unit-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:memory-usage-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:long-tests) (dependency rebuilt)
 - cabal-install-3.7.0.0 (test:integration-tests2) (dependency rebuilt)
 - cabal-install-3.7.0.0 (exe:cabal) (dependency rebuilt)
Preprocessing library for cabal-install-3.7.0.0..
Building library for cabal-install-3.7.0.0..
[ 99 of 132] Compiling Distribution.Client.Config ( src/Distribution/Client/Config.hs, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.o, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/build/Distribution/Client/Config.dyn_o )
Preprocessing test suite 'unit-tests' for cabal-install-3.7.0.0..
Building test suite 'unit-tests' for cabal-install-3.7.0.0..
[ 1 of 33] Compiling UnitTests.Distribution.Client.ArbitraryInstances ( tests/UnitTests/Distribution/Client/ArbitraryInstances.hs, /Users/abel/bin/src/cabal/dist-newstyle/build/x86_64-osx/ghc-8.10.7/cabal-install-3.7.0.0/t/unit-tests/build/unit-tests/unit-tests-tmp/UnitTests/Distribution/Client/ArbitraryInstances.o ) [Distribution.Client.World changed]

tests/UnitTests/Distribution/Client/ArbitraryInstances.hs:22:1: error:
    Could not find module ‘Distribution.Client.Compat.Prelude’
    There are files missing in the ‘cabal-install-3.7.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
22 | import Distribution.Client.Compat.Prelude
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/UnitTests/Distribution/Client/ArbitraryInstances.hs:31:1: error:
    Could not find module ‘Distribution.Client.BuildReports.Types’
    There are files missing in the ‘cabal-install-3.7.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
31 | import Distribution.Client.BuildReports.Types            (BuildReport, InstallOutcome, Outcome, ReportLevel (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/UnitTests/Distribution/Client/ArbitraryInstances.hs:32:1: error:
    Could not find module ‘Distribution.Client.CmdInstall.ClientInstallFlags’
    There are files missing in the ‘cabal-install-3.7.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
32 | import Distribution.Client.CmdInstall.ClientInstallFlags (InstallMethod)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/UnitTests/Distribution/Client/ArbitraryInstances.hs:33:1: error:
    Could not find module ‘Distribution.Client.Glob’
    There are files missing in the ‘cabal-install-3.7.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
33 | import Distribution.Client.Glob                          (FilePathGlob (..), FilePathGlobRel (..), FilePathRoot (..), GlobPiece (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

tests/UnitTests/Distribution/Client/ArbitraryInstances.hs:34:1: error:
    Could not find module ‘Distribution.Client.IndexUtils.ActiveRepos’
    There are files missing in the ‘cabal-install-3.7.0.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
34 | import Distribution.Client.IndexUtils.ActiveRepos        (ActiveRepoEntry (..), ActiveRepos (..), CombineStrategy (..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

(ETC)
Error: cabal: Failed to build test:unit-tests from cabal-install-3.7.0.0.
```

**Comment by Mikolaj** [comment] 2022-09-09 18:15
This bug is quite disruptive for more complex development processes and it masks other similar bugs I describe in #8412 (now closed until the problems are no longer masked and we at least know how many distinct bugs there are). So I propose to look at this with high priority.

**Comment by Mikolaj** [comment] 2023-02-17 09:08
Two GHC issues that are fixed (to be released in GHC 9.4.5) and that are related to this (or to similar tickets about components not being recompiled when other components are change in multi-lib packages): https://gitlab.haskell.org/ghc/ghc/-/issues/22679 https://gitlab.haskell.org/ghc/ghc/-/issues/22675

I'm posting these, because if we stop spotting any similar errors after we switch to GHC 9.4.5 (and to GHC 9.6, I presume), we may want to, at some point, close the tickets and recommend newer GHCs to users that report such problems.

**Comment by alt-romes** [comment] 2023-11-13 18:42
I wasn't able to reproduce this with cabal HEAD and ghc 9.6.3 on macOS 14.
I'm trying with GHC 8.10.7 now

**Comment by Mikolaj** [comment] 2023-12-19 19:59
I have a new simple repro that survives both `cabal clean` and and wiping out `~/.cabal/store/ghc-9.8.1`. Cabal 3.10.2, GHC 9.8.1, Ancient Linux. How to repro:

```
git clone git@github.com:Mikolaj/horde-ad.git
cd horde-ad
git checkout repro-recompilation
cabal test simplifiedOnlyTest -ftest_seq --test-options='-p 2fooRrev3' --allow-newer --disable-optimization
```

at this point it should build, run and say `All 2 tests passed`. Then

```
git reset --hard HEAD^
cabal test simplifiedOnlyTest -ftest_seq --test-options='-p 2fooRrev3' --allow-newer --disable-optimization
```

What should happen is that the test should build, run and display `1 out of 2 tests failed` but, for me, all the tests still pass. If I however do

```
cabal clean
cabal test simplifiedOnlyTest -ftest_seq --test-options='-p 2fooRrev3' --allow-newer --disable-optimization
```

one of the the tests fails, as it should. It seems, though the changed file gets recompiled, the test executable is not relinked. This may be a GHC bug. One would need to run cabal with `-v2`, copy the GHC invocation from the log, massage it a bit, run it and see if GHC fails to link.

@alt-romes: could you check if this one reproduces for you?

I have many libraries in that cabal files, which may be related, but I verified that making the library, in which the change is made, non-named doesn't fix the problem.

**Comment by andreasabel** [comment] 2023-12-20 09:05
> What should happen is that the test should build, run and display `1 out of 2 tests failed` but, for me, all the tests still pass.

I can reproduce this.

**Comment by alt-romes** [comment] 2024-02-16 08:05
I unfortunately cannot reproduce this, as I cannot even get `All 2 tests passed`. I get `All 1 tests passed`, and from there it always passes even after checking out the bad commit...

**Comment by alt-romes** [comment] 2024-02-16 08:07
How should I be getting 2 tests run, when we say tell it to run just the `2fooRrev3` testcase, which is just one test?:
```
, testCase "2fooRrev3" testFooRrev3
```

**Comment by geekosaur** [comment] 2024-02-16 08:23
any chance this is related to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11178 ?

**Comment by Mikolaj** [comment] 2024-02-16 08:31
Let me reproduce my own repro...

**Comment by alt-romes** [comment] 2024-02-16 08:33
> any chance this is related to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11178 ?

That is a good guess @geekosaur. The change has been backported to 9.4.8 and 9.6.3, could you try those @Mikolaj ?

**Comment by Mikolaj** [comment] 2024-02-16 08:48
@alt-romes: you were right, I mangled the repro (wrong test name). It's now fixed.

This is with GHC 9.8.1. I will try 9.6.3 now and 9.6.4 afterwards.

**Comment by alt-romes** [comment] 2024-02-16 08:50
It turns out that the commit @geekosaur linked was not included in 9.8.1 (and has now been marked for backport).
That explains why I ran across this recently with 9.8, and makes @geekosaur's hypothesis even more likely to be right.

**Comment by Mikolaj** [comment] 2024-02-16 08:53
> How should I be getting 2 tests run, when we say tell it to run just the `2fooRrev3` testcase, which is just one test?:

This is a test name prefix, so sometimes it matches more than one test, but I mangled this while debugging and in this case only one test matches the prefix, just as you report. :)

**Comment by Mikolaj** [comment] 2024-02-16 08:54
I can't repro in GHC 9.6.3! Wonderful, I can just switch from GHC 9.8.1 to GHC 9.6.3 and the need to run `cabal clean` all the time is gone.

**Comment by alt-romes** [comment] 2024-02-16 09:04
I'm going to close this ticket since it has been fixed by the GHC patch mentioned above.
Again, the change is included in 9.4.8, 9.6.3, and is going to be backported to 9.8.2 too.

**Closed by alt-romes** 2024-02-16 09:04 UTC
Labels: type: bug, priority: high :fire:, recompilation, cabal-install: cmd/build, re: -O0

**Comment by Mikolaj** [comment] 2024-02-16 09:07
The bug is gone not only with GHC 9.6.3 but with GHC 9.6.4 and 9.4.8 as well. \o/

@alt-romes: could you try to repro once more in GHC 9.8.1, with the updated instructions, to make sure we nailed the bug and it's not just my hallucinations?

@andreasabel: could you try your original repro with GHC 9.6.3 or GHC 9.6.4 or 9.4.8?

**Comment by Mikolaj** [comment] 2024-03-17 23:18
While the bug for which I had the repro is gone in GHC 9.8.2, I still the other variant (described in https://github.com/haskell/cabal/issues/8412), which also requires building with -O1 and -O0 and not cleaning between builds. I don't have a ready repro for that and it's not as punishing (cleaning between changes in optimization levels is not too big a burden). If somebody is keen to investigate, I can try to make a repro.
