### ISSUE TITLE
Include hash of ghc --info in cabal-hash.txt

### ISSUE THREAD

**Issue by ElvishJerricco** [haskell/cabal#5326] opened 2018-05-15 13:04 UTC
My understanding is that `cabal-hash.txt` includes all the details which are to be hased for Nix style local builds. Given the Nix style philosophy, it might make sense for that hash to vary with the contents of `ghc --info`. Certainly we wouldn't want packages to have binary dependencies on different installations of the core libraries, for example.

**Comment by hvr** [comment] 2018-05-15 13:34
Duplicate of #5116

**Comment by 23Skidoo** [comment] 2018-05-15 13:42
Closing in favour of #5116.

**Closed by 23Skidoo** 2018-05-15 13:42 UTC
Labels: resolution: duplicate
