### ISSUE TITLE
A number of fields can't currently be placed inside of a `common` block

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#5565] opened 2018-09-04 07:47 UTC
For example: `main-is:` and `type:` from `executable`s and `test-suite`s respectively aren't currently allowed in `common` blocks.

**Comment by phadej** [comment] 2018-09-04 07:51
Duplicate of https://github.com/haskell/cabal/issues/5531

**Closed by phadej** 2018-09-04 07:51 UTC
