### ISSUE TITLE
leaving a module out of test-suite/other-modules yields a cryptic linker error

### ISSUE THREAD

**Issue by eallik** [haskell/cabal#2419] opened 2015-02-16 13:56 UTC
Consider https://github.com/eallik/mergesort

If the `TestProperties` module is accidentally left out of `test/suite/other-modules` in the `.cabal` file, `cabal test` yields a cryptic error message shown in `erroroutput.txt`; this is at commit c4dbd6c; commit 6887d16 fixes the problem and `cabal test` works just fine from then on.

My "complaint" here is that cabal should print a human friendly error message about the situation, instead of letting the linker fail; i.e. it should notice there's a problem, instead of handing over to the linker only for it to fail in a way that is almost completely undiagnosable for a beginner like myself.

**Comment by ttuegel** [comment] 2015-02-28 04:29
This is a duplicate of #1746.

**Closed by ttuegel** 2015-02-28 04:29 UTC
Labels: duplicate
