### ISSUE TITLE
Linker failure when building with profiling and -ticky

### ISSUE THREAD

**Issue by tswelsh** [haskell/cabal#5176] opened 2018-02-28 16:26 UTC
Not sure if this is the right place as it could be a GHC bug, but I'm not familiar enough with GHC to poke around just using GHC.  Given the cabal file:
```
name:                ticky-fail
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

executable ticky-fail
  main-is:             Main.hs
  ghc-options:         -ticky
  build-depends:       base
  default-language:    Haskell2010
```
and a trivial source file:
```
module Main where

main :: IO ()
main = return ()
```
compilation fails with a slew of linker errors when compiled like so:
```
$ cabal configure --enable-profiling
$ cabal build
```
It builds fine when configuring without `--enable-profiling`, or if `-ticky` is removed from `ghc-options`.  I haven't tried an earlier GHC via just cabal, but it originally came about in a stack project which was able to compile it on GHC 8.0.2.  The GHC 8.2.2 release notes do mention using a different linker if it's available, so that could be related.

This is with:
```
$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2
```

**Comment by jneira** [comment] 2022-06-19 20:04
I cant reproduce in windows wirh cabal-3.6.0.0 and ghc-8.10.7, so i am gonna close it optimistically, thanks for the report and reopen if it is reproduced with newer versions of cabal

**Closed by jneira** 2022-06-19 20:04 UTC
Labels: type: bug, Cabal: cmd/build
