### ISSUE TITLE
Don't use sdist in cabal v2-install

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#7383] opened 2021-05-06 17:46 UTC
**Describe the bug**
Currently `cabal v2-install` relies on `sdist` to create a hashable artifact. Not only is this slow but it can fail (e.g. if `cabal check` fails). We should find a better way to generate hashes.

**Comment by athas** [comment] 2021-05-09 06:55
I very much agree with this.  Is there a workaround that replicates the behaviour of `stack install` (i.e. do an incremental build and then copy the binary somewhere sensible)?

**Comment by phadej** [comment] 2021-05-09 08:16
cabal build yourprogram && cp $(cabal list-bin yourprogram) /somewhere/sensible
    
That however doesn't work if your program uses data-files, as `Paths_*` are pointing somewhere and aren't copied.

**Comment by athas** [comment] 2021-05-09 08:18
Fine by me!

**Comment by sergv** [comment] 2022-05-20 02:05
This issue seems to be a duplicate of https://github.com/haskell/cabal/issues/6919. The thread includes some motivation on why the `sdist` step might be useful at https://github.com/haskell/cabal/issues/6919#issuecomment-646207715.

**Comment by Mikolaj** [comment] 2022-05-20 08:00
Well spotted. Let's move the discussion there. Closing.

**Closed by Mikolaj** 2022-05-20 08:00 UTC
Labels: type: enhancement
