### ISSUE TITLE
default-extensions should be overridable by module extensions.

### ISSUE THREAD

**Issue by wdanilo** [haskell/cabal#5534] opened 2018-08-20 19:48 UTC
Hi, after using Haskell for many years I was amazed to discover today how broken are cabal's `default-extensions`. Basically they are passed to GHC as cmd arguments and thus they **override** per module extensions. So if you use `default-extensions` you cannot alter it per module - they are just a global, hardcoded config. This is very bad, because it just makes them not maintainable. We are right now moving to custom preprocessor instead, but it would be great to have Cabal with fixed behavior here.

**Comment by ChShersh** [comment] 2018-08-21 02:29
@wdanilo Could you please give an example of your issue and why current behaviour is problematic? I never had problems with `default-extensions`. And I don't quite understand what do you mean by saying _override_... 

For example, I can add the most useful extensions to `default-extensions` and then only add other extensions to modules where needed (and new extensions wan't be replaced by default extensions). If by some chance I want to have `SomeExtension` enabled for 99% of modules and disabled only for some modules, I can add `{-# LANGUAGE NoSomeExtension #-}` pragma to the top of the module.

**Comment by wdanilo** [comment] 2018-08-23 05:25
@ChShersh sure, look. I'm writing high performance code and I put `Strict` as my default extension so anyone from our team just defaults to it while creating new modules. The problem is that if someone wants now to create a very specific module without `Strict` enabled it is impossible to do so. Even if you create a file with `{-LANGUAGE NoStrict #-}` it will be discarded then which is very contr intuitive. And yep, it will be discarded, because `default-extensions` are passed as cmd args to GHC and they have priority over extensions defined in the head of the module. That was a surprise to me as well recently.

**Comment by ChShersh** [comment] 2018-08-23 05:40
@wdanilo Thanks for really useful behavior! That's a strange behavior indeed. I've checked this behavior with `GeneralizedNewtypeDeriving` enabled by default in `default-extensions` and then I used `{-# LANGUAGE NoGeneralizedNewtypeDeriving #-}` in the module and I've noticed that `default-extensions` doesn't override extensions in module. Probably we both should come up with minimal examples for this so we can see difference in behavior. I can imagine some part of logic that some extensions might be overridable and some are not. But that would be very sad and I don't want to make early conclusions.

**Comment by wdanilo** [comment] 2018-08-23 05:46
@ChShersh We've been chatting recently about it on IRC and I was surprised to hear that it works this way. Please try with something like `Strict` or `OverloadedStrings`. If it will still work on your side I'll make a minimal example.

**Comment by hvr** [comment] 2018-08-23 09:53
Fwiw, if `{-# LANGUAGE NoStrict #-}` inside a module fails to annihilate a `-XStrict` flag given on GHC's commandline, I'd consider this a GHC bug and there'd be little we could do on the cabal side about it :-/

**Comment by phadej** [comment] 2018-08-23 10:16
At least `OverloadedStrings` is annihilated. We do that for `Paths_package.hs`, and I guess it works as there were recent PRs for  that: https://github.com/haskell/cabal/pull/5054

**Comment by wdanilo** [comment] 2018-08-23 11:13
@hvr I was chatting about it on IRC and there people were considering this NOT ghc bug, because command line arguments should override everything ad should have the highest priority (according to them, I don't want to judge the design here). Just fyi.

**Comment by hvr** [comment] 2018-08-23 12:47
btw, one thing that could occur is that if you first enable `Strict` and then use the negative `NoStrict`; you're still left w/ `StrictData` as `Strict` implies `StrictData`, but `NoStrict` unfortunately doesn't imply `NoStrictData`

And in general, in-module pragmas act as if they were appended to the CLI in terms of evaluation order (which for the CLI arguments is left-to-right; so a later flag is interpreted *after* previous flags); IOW; you should observe the same behaviour as if you passed `ghc --make -XStrict -XNoData ...` on the commandline

**Comment by wdanilo** [comment] 2018-08-24 10:07
@hvr neither me nor anyone on IRC have thought about it. Interesting, that could indeed be the reason for that. We'll check it!

**Comment by jneira** [comment] 2021-05-18 14:24
looks like the ghc issue is stalled and not actionable
There are some suggestions arguing the responsibility could be attributed to the client code. Even we could consider add the workaround meanwhile is not resolved

**Comment by Mikolaj** [comment] 2021-05-18 15:56
I think the GHC issue discussion shows the problem is confusing names of extensions, so that they sound like reordering them should not affect the result but it does or that they should cancel each other but they don't. I guess the proper place to improve that, e.g., by better documentation, is GHC manual. I'd be for closing this issue and keeping the GHC issue open. In particular, the initial hypotheses in this issue turned out to be wrong, so the issue is probably misleading at this point. If nobody objects, I'd close it soon, but please chime in in the GHC issue and let tools authors know that automatic reordering of extensions is not trivial and they should query GHC info for that.

**Closed** 2021-05-22 21:54 UTC
Labels: blocked: ghc, resolution: not our bug, type: discussion, type: enhancement
