### ISSUE TITLE
cabal build --help reports wrong default for builddir

### ISSUE THREAD

**Issue by mpickering** [haskell/cabal#9231] opened 2023-09-04 10:35 UTC
If I run `cabal build --help` then the wrong default is listed for `build-dir`. 

```
 --builddir=DIR                 The directory where Cabal puts generated build
                                files (default dist)
```

I think this is because the `builddir` command is one inherited from the `Setup.hs` interface, where the default is `dist`. The default when using `cabal-install` is `dist-newstyle`.

**Comment by Mikolaj** [comment] 2023-09-04 11:58
This is a dupe of https://github.com/haskell/cabal/issues/7924 and implemented (but without enough reviews) in https://github.com/haskell/cabal/pull/8833. Closing.

**Closed by Mikolaj** 2023-09-04 11:58 UTC
Labels: type: bug, resolution: duplicate
