### ISSUE TITLE
Automate generating and uploading binaries for cabal?

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#3240] opened 2016-03-22 21:20 UTC
People get very confused that the releases include source bundles but the binaries sort of languish.

@hvr pointed out to me that Appveyor (which I guess we use for windows CI) seems to support automatic uploading of build artifacts? If someone wants to investigate that, we could help to hook up the space on h.o boxes for those artifacts to be dumped. This would at least give us an up-to-date binary story for windows. 

If that works out, we could investigate doing the same with travis for linux...

**Comment by hvr** [comment] 2016-03-22 21:21
See e.g. https://www.appveyor.com/docs/deployment/ftp

**Comment by 23Skidoo** [comment] 2016-03-22 21:45
I can maybe look into this during this weekend, since I already have some experience with using Travis for deployment. This will provide us only with x86-64 binaries, though (which is better than nothing, of course).

One other thing that is important is that Travis/AppVeyor shouldn't be given write permissions to everything under `haskell.org/cabal`, which the `cabal-site` account has at the moment.

**Comment by 23Skidoo** [comment] 2016-03-22 21:55
We can also use GitHub releases for deployment, though I am not sure I want to give Travis/AppVeyor push access to the repo either.

**Comment by 23Skidoo** [comment] 2016-03-29 13:05
Looks like I will be busy for quite a while, so this'll have to wait.

**Comment by jneira** [comment] 2021-06-23 20:00
Afaics GitHub actions are already generating and uploading binaries, so maybe we could close this one?

**Comment by Mikolaj** [comment] 2021-06-23 20:12
Indeed. And if something is missing with the current artefacts (I have no idea so far), a specific ticket should be opened. IMHO feel free to close after a few days.

**Comment by andreabedini** [comment] 2022-02-22 04:43
@jneira @Mikolaj let's merge this into #4637

**Comment by jneira** [comment] 2022-02-22 06:26
duplicate of #4637

**Closed by jneira** 2022-02-22 06:26 UTC
Labels: type: enhancement, blocked: info-needed, continuous-integration

**Comment by Mikolaj** [comment] 2022-02-22 09:07
Duplicate of #4637

**Comment by Mikolaj** [comment] 2022-02-22 09:07
haha, case matters, :facepalm:
