### ISSUE TITLE
`cabal v2-install --enable-profiling` does not profile

### ISSUE THREAD

**Issue by fommil** [haskell/cabal#5982] opened 2019-04-02 21:41 UTC
This is in cabal-install 2.4, even the latest commit on that branch.

In any project that can produce an executable, issue

```
cabal v2-install --enable-profiling
```

and confirm that the output binary can't produce profiling information.

e.g. (not a minimal example, just first thing that comes to hand.. this is the integration test for this app)

```
git clone https://github.com/symbiont-io/jaeger-flamegraph.git
cd jaeger-flamegraph
cabal v2-install --symlink-bindir=bin --enable-profiling -w ghc-8.4.4 jaeger-flamegraph
gzip -cd frontend.json.gz | bin/jaeger-flamegraph -a p1 +RTS -P -RTS | sort > frontend.trace.test
```

gives

```
jaeger-flamegraph: the flag -P requires the program to be built with -prof
```

Note that `v2-build --enable-profiling` works as expected.

**Comment by hvr** [comment] 2019-04-03 08:26
additional note, this happens also for non-local / non-project-context `v2-install`s:

```
cabal v2-install -w ghc-8.6.4 --enable-profiling uhttpc
```

will ignore the `--enable-profiling` flag too (same with `--enable-executable-profiling`)

and in fact, the symlinked `uhttpc-bench` executable is the very same (i.e. same nix-style hash entry) that

```
cabal v2-install -w ghc-8.6.4 uhttpc
```

symlinks. IOW, the 2nd invocation is a no-op.

**Comment by jneira** [comment] 2022-02-13 20:26
Closing as duplicate of #7297 where there is a diagnostic, possible solutionand workarounds

**Closed by jneira** 2022-02-13 20:26 UTC
Labels: type: bug, cabal-install: cmd/install
