### ISSUE TITLE
cabal-install 1.22.5 says log does not exist

### ISSUE THREAD

**Issue by gittywithexcitement** [haskell/cabal#2663] opened 2015-06-17 21:11 UTC
I get this error with the newer cabal-install

```
~/r/cabal-install> bin/cabal -V
cabal-install version 1.22.5.0
using version 1.22.4.0 of the Cabal library 

~/r/cabal-install> bin/cabal install classy-prelude 
Resolving dependencies...
Notice: installing into a sandbox located at
~/.stackage/sandboxes/ghc-7.10.1/nightly-2015-06-17
Failed to install adjunctions-4.2.1
Build log ( ~/.stackage/sandboxes/ghc-7.10.1/nightly-2015-06-17/logs/adjunctions-4.2.1.log ):
cabal:
~/.stackage/sandboxes/ghc-7.10.1/nightly-2015-06-17/logs/adjunctions-4.2.1.log:
does not exist
```

If I use an older cabal-install, 1.22.3.0 using Cabal 1.22.3.0

```
cabal install classy-prelude
```

works fine

**Comment by lspitzner** [comment] 2015-06-17 21:15
duplicate of #2658

@gittywithexcitement `-j1` is the trick to get the actual error.

**Comment by lspitzner** [comment] 2015-06-17 21:18
(1.22.6 should fix it)

**Closed** 2015-06-18 04:26 UTC
Labels: duplicate
