### ISSUE TITLE
Fail fast cabal install dependencies

### ISSUE THREAD

**Issue by flasheater** [haskell/cabal#2383] opened 2015-01-22 00:53 UTC
Doing ```cabal install``` on large projects can take significant amounts of time. However, build errors of dependencies get aggregated and shown at the end of the build, which is a waste of my time, especially if the error occurred early on.

I would have expected that upon first error, cabal aborts the whole build, presenting that error. 

My suggestion is to change the default behaviour in the case of an error to "fail fast", unless there is a good use case, that I am unaware of, for the aggregation behaviour.

If existing cabal users have come to depend on the aggregation, I suggest a new flag ```--fail-fast``` or similar.

**Comment by ttuegel** [comment] 2015-02-28 04:23
Duplicate of #1924.

**Closed by ttuegel** 2015-02-28 04:23 UTC
Labels: duplicate
