### ISSUE TITLE
`Cabal install --dependencies-only --allow-newer` fails with empty build logs (1.22.2.0 and GHC 7.8.3)

### ISSUE THREAD

**Issue by dredozubov** [haskell/cabal#2511] opened 2015-03-30 14:07 UTC
Issue seems to reproduce only with `--allow-newer` and GHC < 7.10. This behaviour is pretty frustrating.

All preparation steps i did:
```
% uname -a
Darwin airbender 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

% cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library

% ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

% rm -rf ~/.ghc
% rm -rf ~/.cabal
% rm -rf .cabal-sandbox
% cabal clean
cleaning...
% cabal sandbox init
Config file path source is default config file.
Config file /Users/dr/.cabal/config not found.
Writing default configuration to /Users/dr/.cabal/config
Writing a default package environment file to
/Users/dr/workspace/contractor/cabal.sandbox.config
Creating a new sandbox at /Users/dr/workspace/contractor/.cabal-sandbox
% cabal update
Downloading the latest package list from hackage.haskell.org
```

Then: [output](http://lpaste.net/6390758392662589440) (output is pretty large)

Build logs are empty:
```
% cat /Users/dr/workspace/contractor/.cabal-sandbox/logs/ansi-wl-pprint-0.6.7.2.log
% cat /Users/dr/workspace/contractor/.cabal-sandbox/logs/primitive-0.6.log
```

If i switch ghc to 7.10.1(which is strange) or remove `--allow-newer` it works.

**Comment by 23Skidoo** [comment] 2015-03-30 15:24
You need to install a newer version of the Cabal library than the one that comes with GHC 7.8. Use `cabal install Cabal`.

**Comment by 23Skidoo** [comment] 2015-03-30 15:24
Duplicate of #2023.

**Closed by 23Skidoo** 2015-03-30 15:24 UTC

**Comment by dredozubov** [comment] 2015-03-30 16:02
@23Skidoo I'm confused, how is it 1.22.2.0 not considered to be new?

**Comment by 23Skidoo** [comment] 2015-03-30 16:10
Your `cabal-install` is new, but your version of Cabal *library* is old. Check out `ghc-pkg list | grep Cabal`.

**Comment by dredozubov** [comment] 2015-03-30 16:11
Oh, that makes sense. Thanks for clarification.
