### ISSUE TITLE
Confusing error message cabal: Invalid package ID: . "<eitherParsec>" (line 1, column 2):

### ISSUE THREAD

**Issue by ivanperez-keera** [haskell/cabal#7643] opened 2021-09-13 20:39 UTC
**Describe the bug**
Running cabal install or cabal v2-install in a project directory results in a confusing error message

**To Reproduce**

```
$ cabal v2-install
cabal: Invalid package ID: .
"<eitherParsec>" (line 1, column 2):
unexpected all digits or a dot in a portion of package name
expecting "-"
$ cabal install
cabal: Invalid package ID: .
"<eitherParsec>" (line 1, column 2):
unexpected all digits or a dot in a portion of package name
expecting "-"
```

Some information of at least what file is being read.

**System information**
 - Mac OSX
 - cabal 3.6, GHC 8.6 (also tried with GHC 8.10; same result).

**Comment by Mikolaj** [comment] 2021-09-13 20:55
duplicate of #7331

**Comment by Mikolaj** [comment] 2021-09-13 20:55
And it's already being worked on there. But thank you for the report. :)

**Closed** 2021-09-13 20:55 UTC
Labels: resolution: duplicate
