### ISSUE TITLE
Trailing whitespace in generated cabal file

### ISSUE THREAD

**Issue by danielcompton** [haskell/cabal#2218] opened 2014-11-13 19:05 UTC
When creating a new cabal file with cabal init, there is trailing whitespace created on lines that are commented out. These should be trimmed before the file is created.

![screenshot of iterm 14-11-14 8 03 50 am](https://cloud.githubusercontent.com/assets/811954/5034555/ea044a00-6bd4-11e4-9699-4dc632c009d8.png)

**Comment by ttuegel** [comment] 2015-04-24 14:55
This seems to be a duplicate of #1966.

**Closed by ttuegel** 2015-04-24 14:55 UTC
Labels: init
