### ISSUE TITLE
Packages with both library and ancillary executable

### ISSUE THREAD

**Issue by jrp2014** [haskell/cabal#6920] opened 2020-06-19 12:05 UTC
The documentation (7. Package Description) says that

> Having both a library and executables in a package does not work very well; if the executables depend on the library, they must explicitly list all the modules they directly or indirectly import from that library. Fortunately, starting with Cabal 1.8.0.4, executables can also declare the package that they are in as a dependency, and Cabal will treat them as if they were in another package that depended on the library.

In my case I have a wrapper for a plugin package that doesn't depend on my plugin (library) at compile time, but does at run time.

If I don't declare the package as a dependency of my wrapper, I assume that cabal takes the wrapper to be the main product of the package and the plugin library doesn't get installed, unless I explicitly do a `cabal install --lib`.

If I do declare the package as a dependency of my wrapper, as suggested in the documentation, I get a warning when I build:

```
Warning: The package has an extraneous version range for a dependency on an
internal library: mypackage -any && ==0.3.5.2, mypackage -any && ==0.3.5.2.
This version range includes the current package but isn't needed as the
current package's library will always be used.
```
I'm not sure why cabal thinks that the library it internal as it is unnamed and so should be the package.

**What is the recommended recipe for shipping a wrapper exe with my library, but having the plugin library as the main product?**

PS:  the examples for combined lib+exe in the documentation don't work well as the exe and the lib usually live in different source directories, so just referring to the lib modules from `other-modules` in the executable stanza won't work.

**Comment by fgaz** [comment] 2020-06-19 14:02
Probably a duplicate of #5119

**Comment by jrp2014** [comment] 2020-06-19 15:51
Thanks.  Unfortunately the earlier threads don't seem to lead to any actionable information.

Eg, is this just a spurious warning that I can ignore and I am doing the right thing already?  Is there a workaround like tuning the build into a multi-package project?

**Comment by fgaz** [comment] 2020-06-19 17:26
Yes, if you didn't put version bounds on the intra-package dependency then it's spurious

**Comment by jrp2014** [comment] 2020-06-19 17:58
OK.  Thanks. And when users of the package download from hackage will they get the lib, the ancillary executable, or both?

**Comment by fgaz** [comment] 2020-12-15 09:58
You probably figured it out in the meantime, but users will get only the executable when using `cabal install` (technically the whole package is downloaded, but only the exe is installed). If they put the package name in `build-depends` instead they get your lib as dependency of their project.

**Comment by fgaz** [comment] 2020-12-15 09:59
I'm closing this but please reopen if I missed something

**Closed by fgaz** 2020-12-15 10:00 UTC
