### ISSUE TITLE
"Main.p_o.tmp: No such file or directory" while calling `ar` on `Main.p_o.tmp`

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#9334] opened 2023-10-14 21:15 UTC
The `ar` step fails with the following message in the ghcup-metadata pipeline:

```
*** systool:ar:
*** Ar:
"D:\a\_temp\foobarbaz\ghcup\ghc\9.6.3\lib\../mingw/bin/llvm-ar.exe" "qcL" "C:\\cabal\\script-builds\\%xfEvOiFMnTvjFvrlRdQhPuWQl\\build\\x86_64-windows\\ghc-9.6.3\\fake-package-0\\x\\script-main.hs\\build\\script-main.hs\\script-main.hs-tmp\Main.p_o.tmp" "C:\Users\RUNNER~1\AppData\Local\Temp\ghc3216_0\ghc_5.o" "C:\Users\RUNNER~1\AppData\Local\Temp\ghc3216_0\ghc_3.p_o"
D:/a/_temp/foobarbaz/ghcup/ghc/9.6.3/lib/../mingw/bin/llvm-ar.exe: error: C:\\cabal\\script-builds\\%xfEvOiFMnTvjFvrlRdQhPuWQl\\build\\x86_64-windows\\ghc-9.6.3\\fake-package-0\\x\\script-main.hs\\build\\script-main.hs\\script-main.hs-tmp\Main.p_o.tmp: No such file or directory

<no location info>: error:
    `llvm-ar.exe' failed in phase `Ar'. (Exit code: 1)
```

First encountered in https://github.com/haskell/ghcup-metadata/pull/127

**Comment by mpickering** [comment] 2023-11-16 09:20
The job where this fails is:
https://github.com/haskell/ghcup-metadata/actions/runs/6369779959/job/17290326630#step:3:15214

and the command seems to be :

```
cabal --verbose=0 run --enable-profiling ./main.hs -- +RTS -s
```

**Comment by ulysses4ever** [comment] 2023-11-16 19:37
#9452 tries to reproduce it in the CI by adding a test

**Comment by jasagredo** [comment] 2023-11-16 21:24
I think I found why this is failing. If I try to reproduce the same steps on my machine it doesn't fail, however if I introduce a `%` in the path then it fails with the same error.

I don't understand why cabal would produce a directory starting on % (in the error reported: `C:\\cabal\\script-builds\\%xfEvOiFMnTvjFvrlRdQhPuWQl`) but that seems to be the cause. I introduced the `%` by means of `--builddir`:
```
$ cabal run --enable-profiling Main.hs --verbose --ghc-options=-v --builddir "%123"
...
*** systool:ar:
*** Ar:
"C:\ghcup\ghc\9.6.3\lib\../mingw/bin/llvm-ar.exe" "qcL" "C:\\cabal\\script-builds\\d99686da9fae8161c6c95b8e44df81d5db8b92f51986dd9b56889e1b28121ecf\\%123\\build\\x86_64-windows\\ghc-9.6.3\\fake-package-0\\x\\cabal-script-Main.hs\\build\\cabal-script-Main.hs\\cabal-script-Main.hs-tmp\Main.p_o.tmp" "C:\msys64\tmp\ghc22672_0\ghc_5.o" "C:\msys64\tmp\ghc22672_0\ghc_3.p_o"
C:/ghcup/ghc/9.6.3/lib/../mingw/bin/llvm-ar.exe: error: C:\\cabal\\script-builds\\d99686da9fae8161c6c95b8e44df81d5db8b92f51986dd9b56889e1b28121ecf\\%123\\build\\x86_64-windows\\ghc-9.6.3\\fake-package-0\\x\\cabal-script-Main.hs\\build\\cabal-script-Main.hs\\cabal-script-Main.hs-tmp\Main.p_o.tmp: No such file or directory

<no location info>: error:
    `llvm-ar.exe' failed in phase `Ar'. (Exit code: 1)
```

However the file is there:
```
$ file /c/cabal/script-builds/d99686da9fae8161c6c95b8e44df81d5db8b92f51986dd9b56889e1b28121ecf/%123/build/x86_64-windows/ghc-9.6.3/fa
ke-package-0/x/cabal-script-Main.hs/build/cabal-script-Main.hs/cabal-script-Main.hs-tmp/Main.p_o
/c/cabal/script-builds/d99686da9fae8161c6c95b8e44df81d5db8b92f51986dd9b56889e1b28121ecf/%123/build/x86_64-windows/ghc-9.6.3/fake-package-0/x/cabal-script-Main.hs/build/cabal-script-Main.hs/cabal-script-Main.hs-tmp/Main.p_o: Intel amd64 COFF object file, not stripped, 5 sections, symbol offset=0xad7, 67 symbols, 1st section name ".text"
```

It seems `llvm-ar.exe` can't deal with `%` on the filepaths.

**Comment by ffaf1** [comment] 2023-11-16 21:33
Maybe it could be this?

https://github.com/haskell/cabal/blob/a134b265dd91e18599b431611df8dfbe3d5601dd/cabal-install/src/Distribution/Client/ScriptUtils.hs#L221-L235

**Comment by gbaz** [comment] 2023-11-16 21:34
great sleuthing both, and i bet that's the issue!

**Comment by jasagredo** [comment] 2023-11-16 21:53
By tweaking the name of the file I was able to get a hash that contains a `%`:
```
$ cabal run --enable-profiling ./moon.hs
C:/ghcup/ghc/9.6.3/lib/../mingw/bin/llvm-ar.exe: error: C:\\cabal\\script-builds\\%5nVnTgLeh7AaK3jOtq2ERexJN\\build\\x86_64-windows\\ghc-9.6.3\\fake-package-0\\x\\script-moon.hs\\build\\script-moon.hs\\script-moon.hs-tmp\Main.p_o.tmp: No such file or directory

<no location info>: error:
    `llvm-ar.exe' failed in phase `Ar'. (Exit code: 1)
```

**Comment by Kleidukos** [comment] 2023-11-17 10:34
Fantastic, we should definitely report this to llvm-ar

**Comment by mpickering** [comment] 2023-11-17 14:22
I think the cleanest way to fix this is to modify `getScriptHash` to:

```
showHashValue 
. truncateHash 20
$ readFileHashValue script_path

```

* `showHashValue`  renders the hash in base16 rather than base64, which avoids the `/` character.
* `truncateHash 20` gives the same resolution as unit ids.
* `readFileHashValue` will compute the hash of the contents of the file rather than the filepath - which will be more stable across CI runs and user machines as it doesn't involve dependency on the environment (`$PWD`).

It doesn't seem like there was a particular reason to use `showHashValueBase64` in the original MR or to hash the path rather than the contents of the file.

**Comment by mpickering** [comment] 2023-11-21 10:04
Yes it seems hashing the path is a better idea than hashing the contents. Don't let me block you on that.

**Comment by jasagredo** [comment] 2023-11-21 10:42
Alright, I will hash the path instead of the contents.

About the hashing algorithm I'm unsure how to justify this choice. I'm just picking a hashing strategy that follows the same logic as the rest of the hashing that happens for packages.

Same for tests, I'm unsure on what could we effectively test, because testing that there are no % or / in base16/hex is probably redundant.

**Comment by jasagredo** [comment] 2023-11-27 17:28
Can we close this as #9459 landed in master or were you going to try some more things @mpickering ?

**Comment by Kleidukos** [comment] 2023-11-29 10:57
Thank you everyone for working on this!

**Closed** 2023-11-29 10:57 UTC
Labels: type: bug, platform: windows, priority: high :fire:, status: consider closing
