### ISSUE TITLE
“lexical error (UTF-8 decoding error)” in WIndows 7

### ISSUE THREAD

**Issue by bos** [haskell/cabal#912] opened 2012-05-24 05:55 UTC
(Imported from [Trac #922](http://hackage.haskell.org/trac/hackage/ticket/922), reported by hamukazu on 2012-03-02)

<h4 id="Symptom">Symptom</h4>

When I type

<blockquote class="citation">
cabal install cabal

</blockquote>

it fails with the following error:

<blockquote class="citation">
Distribution\Compat\Exception.hs:0:4: lexical error (UTF-8 decoding error)

</blockquote>

<h4 id="Environment">Environment</h4>

It happens with 64 bit version of Windows 7.

It came to occur after I failed to install HXT. (I am not sure it is related.)

<h4 id="Workaround">Workaround</h4>

By setting

<blockquote class="citation">
set LANG=C

</blockquote>

in command line, cabal comes to work.

I regard this is just a workaround and this issue should be reported as a bug.

<h4 id="Relatedlinks">Related links</h4>

[http://stackoverflow.com/questions/9371438/cabal-install-complains-built-in04-lexical-error-utf-8-decoding-error/9533205#9533205](http://stackoverflow.com/questions/9371438/cabal-install-complains-built-in04-lexical-error-utf-8-decoding-error/9533205#9533205)
[http://trac.haskell.org/network/ticket/43](http://trac.haskell.org/network/ticket/43)

**Comment by jneira** [comment] 2022-07-10 20:42
Dont have access to a win 7 system to try to reproduce but it does not in windows 10
It seems to be a bug in ghc and its mingw c toolchain so newer ghc versions might not suffer from it. 
Definitely not a cabal bug, so closing.

**Closed by jneira** 2022-07-10 20:42 UTC
Labels: type: bug, platform: windows, cabal-install: other
