### ISSUE TITLE
Error building/installing cabal-helper-1.0.0.0

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#6483] opened 2020-01-17 07:14 UTC
**Describe the bug**
Alternating `cabal v2-build`and `cabal v2-install` over `cabal-helper-1.0.0.0` or a package that depends on it (in my case `haskell-ide-engine`) with a fresh cabal store throws a build error cause the dependency `cabal-plan` is added twice when compiling.

It worths to note that `cabal-helper`is using a private named lib: https://github.com/DanielG/cabal-helper/blob/master/cabal-helper.cabal#L116

The error is:

```
Preprocessing library for cabal-helper-1.0.0.0..
Building library for cabal-helper-1.0.0.0..
[1 of 3] Compiling Distribution.Helper ( lib\Distribution\Helper.hs, dist\build\Distribution\Helper.o )

lib\Distribution\Helper.hs:591:68: error:
    • Couldn't match expected type ‘cabal-plan-0.6.2.0:Cabal.Plan.PlanJson’
                  with actual type ‘PlanJson’
      NB: ‘PlanJson’
            is defined in ‘Cabal.Plan’ in package ‘cabal-plan-0.6.2.0’
          ‘cabal-plan-0.6.2.0:Cabal.Plan.PlanJson’
            is defined in ‘Cabal.Plan’ in package ‘cabal-plan-0.6.2.0’
    • In the first argument of ‘CabalInstall.planPackages’, namely
        ‘plan’
      In the second argument of ‘(<$>)’, namely
        ‘CabalInstall.planPackages plan’
      In a stmt of a 'do' block:
        Just pkgs <- NonEmpty.nonEmpty <$> CabalInstall.planPackages plan
    |
591 |       Just pkgs <- NonEmpty.nonEmpty <$> CabalInstall.planPackages plan
    |                                                                    ^^^^
```

**To Reproduce**
I can't reproduce it locally in a consistent way, but i've triggered it deleting the cabal store and make `cabal v2-build` and `cabal v2-install`. 
@fendor has experienced the issue in linux and me in windows
However it is reproduced consistently in azure ci for windows (not linux), see for example: https://dev.azure.com/jneira/haskell-ide-engine/_build/results?buildId=502&view=results

* removing the existent cabal store
* run `cabal v2-build` in the `haskell-ide-engine`repo
* run `cabal v2-install` 

The azure ci bash scripts of the build: https://github.com/jneira/haskell-ide-engine/blob/azure-cabal/.azure/windows-cabal.yml

**Expected behavior**

The build should finish correctly

**System information**
 - Several windows systems and linux ones
 - `cabal-3.0.0.0`, `ghc-8.6.5` and `ghc-8.4.4`

**Additional context**

You can workaround the issue removing the `cabal-plan-*` dirs inside the cabal store and running [@phadej script](https://github.com/phadej/cabal-extras/tree/master/cabal-store-check) to fix the store (or removing the entire store)
Related issues: #6412 and #5782

**Comment by phadej** [comment] 2020-01-17 09:47
I guess this is the same problem as https://github.com/haskell/cabal/issues/6211

Without consistent reproducer, I doubt it can be fixed easily. Note that #6211 uses internal library as well.

**Comment by phadej** [comment] 2020-01-17 09:47
I'm closing this as duplicate.

**Closed by phadej** 2020-01-17 09:47 UTC

**Comment by phadej** [comment] 2020-01-17 09:55
(I'm unable to reproduce it using `cabal-install-3.0.1.0 from hvr's ppa, which is https://github.com/haskell/cabal/releases/tag/cabal-install-v3.0.1.0-rc4, but it doesn't mean issue is fixed).

**Comment by hasufell** [comment] 2020-01-21 11:39
This sounds like a major bug to me if I cannot trust the build-store to be consistent. I just hit this as well in [hie](https://github.com/haskell/haskell-ide-engine/issues/1580). I will try to create a docker container with my state of the .cabal dir.

**Comment by Mikolaj** [comment] 2021-05-06 22:04
@hasufell: hi! We guess (https://github.com/haskell/cabal/issues/5782#issuecomment-833866532) this issue is fixed in new stable cabals --- could you perhaps try to reproduce locally your case with new cabal and confirm?

**Comment by hasufell** [comment] 2021-05-06 22:34
> @hasufell: hi! We guess (https://github.com/haskell/cabal/issues/5782#issuecomment-833866532) this issue is fixed in new stable cabals --- could you perhaps try to reproduce locally your case with new cabal and confirm?

The bug was never easy to reproduce. I haven't hit it in a long time though. Whether that means it's fixed: I don't know.

**Comment by Mikolaj** [comment] 2021-05-07 07:08
@hasufell: got it; thank you
