### ISSUE TITLE
Don't try and resolve dependencies for packages that are not buildable

### ISSUE THREAD

**Issue by bos** [haskell/cabal#559] opened 2012-05-24 05:35 UTC
(Imported from [Trac #566](http://hackage.haskell.org/trac/hackage/ticket/566), reported by @batterseapower on 2009-07-03)

I had a component like this:

<pre class="wiki">Executable edit-distance-benchmark
        Main-Is:                Text/EditDistance/Benchmark.hs
        if flag(splitBase)
                Build-Depends:  base &gt;= 3 &amp;&amp; &lt; 5, array &gt;= 0.1, random &gt;= 1.0, old-time &gt;= 1.0, process &gt;= 1.0,
                                parallel &gt;= 1.0, unix &gt;= 2.3
        else
                Build-Depends:  base &lt; 3,
                                parallel &gt;= 1.0, unix &gt;= 2.3
        if !flag(benchmark)
                Buildable:      False
        Ghc-Options:            -O2 -fvia-C -Wall
</pre>However, I've only just found out that this meant that you couldn't install any parts of my package on Windows, because Cabal tried to resolve the "unix" dependency even if "benchmark" was False (the default)!

I've solved this like so:

<pre class="wiki">Executable edit-distance-benchmark
        Main-Is:                Text/EditDistance/Benchmark.hs
        if !flag(benchmark)
                Buildable:      False
        else
                if flag(splitBase)
                        Build-Depends:  base &gt;= 3 &amp;&amp; &lt; 5, array &gt;= 0.1, random &gt;= 1.0, old-time &gt;= 1.0, process &gt;= 1.0,
                                        parallel &gt;= 1.0, unix &gt;= 2.3
                else
                        Build-Depends:  base &lt; 3,
                                        parallel &gt;= 1.0, unix &gt;= 2.3
        Ghc-Options:            -O2 -fvia-C -Wall
</pre>But really Cabal should not need to resolve dependencies for things that are not buildable.

**Comment by ttuegel** [comment] 2015-02-28 04:45
This is a duplicate of #1725.

**Closed by ttuegel** 2015-02-28 04:45 UTC
Labels: bug, duplicate, library
