### ISSUE TITLE
Cabal installation fail, but cabal get && cabal install working

### ISSUE THREAD

**Issue by Twinside** [haskell/cabal#2525] opened 2015-04-05 15:08 UTC
Hello,

I got some trouble installing a specific package with cabal, `vector-binary-instances`, Using
 
 * cabal-install 1.22.2.0
 * ghc 7.10.1
 * Windows 8.1

The following command fail:
~~~~
[16:53:24] ~/Desktop/test> cabal install vector-binary-instances
Resolving dependencies...
Notice: installing into a sandbox located at
D:\Users\Vince\Desktop\test\.cabal-sandbox
Configuring cereal-0.4.1.1...
Configuring primitive-0.6...
Building primitive-0.6...
Building cereal-0.4.1.1...
Installed primitive-0.6
Configuring vector-0.10.12.3...
Building vector-0.10.12.3...
Installed cereal-0.4.1.1
Installed vector-0.10.12.3
Configuring vector-binary-instances-0.2.1.0...
Building vector-binary-instances-0.2.1.0...
Failed to install vector-binary-instances-0.2.1.0
Build log ( D:\Users\Vince\Desktop\test\.cabal-sandbox\logs\vector-binary-instances-0.2.1.0.log ):
Building vector-binary-instances-0.2.1.0...
Preprocessing library vector-binary-instances-0.2.1.0...
[1 of 2] Compiling Data.Vector.Cereal ( Data\Vector\Cereal.hs, dist\dist-sandbox-78bfbd5c\build\Data\Vector\Cereal.o )
[2 of 2] Compiling Data.Vector.Binary ( Data\Vector\Binary.hs, dist\dist-sandbox-78bfbd5c\build\Data\Vector\Binary.o )
[1 of 2] Compiling Data.Vector.Cereal ( Data\Vector\Cereal.hs, dist\dist-sandbox-78bfbd5c\build\Data\Vector\Cereal.p_o )
[2 of 2] Compiling Data.Vector.Binary ( Data\Vector\Binary.hs, dist\dist-sandbox-78bfbd5c\build\Data\Vector\Binary.p_o )
C:\Program Files (x86)\MinGHC-7.10.1\ghc-7.10.1\mingw\bin\ar.exe: dist/dist-sandbox-78bfbd5c\build\libHSvector-binary-instances-0.2.1.0-BV5Xk9PwAa5I7Yv1uprGzJ.a-1572\libHSvector-binary-instances-0.2.1.0-BV5Xk9PwAa5I7Yv1uprGzJ.a: No such file or directory
Updating documentation index
D:\Users\Vince\Desktop\test\.cabal-sandbox\doc\i386-windows-ghc-7.10.1\index.html
cabal.exe: Error: some packages failed to install:
vector-binary-instances-0.2.1.0 failed during the building phase. The
exception was:
ExitFailure 1
~~~~

All the other packages installed flawlessly.

The strange thing is, doing the following actions with the same installation works perfectly:
~~~~
[16:55:13] ~/Desktop/test> cabal get vector-binary-instances
[16:55:22] ~/Desktop/test> cd .\vector-binary-instances-0.2.1.0
[16:55:24] ~/Desktop/test/vector-binary-instances-0.2.1.0> cabal sandbox init --sandbox=../.cabal-sandbox
[16:55:34] ~/Desktop/test/vector-binary-instances-0.2.1.0> cabal install
~~~~

The full log with verbose3 is available in this [gist](https://gist.github.com/Twinside/050bf8cc5e1c66a8d838).

**Comment by 23Skidoo** [comment] 2015-04-05 15:50
Probably a duplicate of #2502.

**Comment by 23Skidoo** [comment] 2015-04-06 13:25
Closing in favour of #2502.

**Closed by 23Skidoo** 2015-04-06 13:25 UTC
Labels: bug, duplicate, windows
