### ISSUE TITLE
cabal upload succeeds but doesn't terminate...

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1260] opened 2013-03-31 03:32 UTC
Hey All, 

i've been a recent build of cabal-install head  (built from head Mar 21st), and i noticed a funny problem when uploading a package to hackage today. Namely that cabal-install doesn't return / terminate after  successfully uploading.... 

my local code isn't using cabal sandbox for that project, if thats any help

**Comment by ttuegel** [comment] 2015-04-23 22:44
Was this bug ever reproduced?

**Comment by 23Skidoo** [comment] 2015-04-23 22:52
I never had time to look into it.

**Comment by ttuegel** [comment] 2015-04-23 22:56
@cartazio I'm closing this because it is so old and unconfirmed. You know where to find me if it continues to be a problem.

**Closed by ttuegel** 2015-04-23 22:56 UTC
Labels: bug, cabal-install
