### ISSUE TITLE
Got an error when install cabal-install.

### ISSUE THREAD

**Issue by daimajia** [haskell/cabal#3474] opened 2016-06-04 01:10 UTC
``` bash

# cabal install --global cabal-install -v
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Ready to install cabal-install-1.24.0.0
Waiting for install task to finish...
Extracting
/root/.cabal/packages/hackage.haskell.org/cabal-install/1.24.0.0/cabal-install-1.24.0.0.tar.gz
to /tmp/cabal-install-1.24.0.0-11923...
Updating cabal-install.cabal with the latest revision from the index.
creating /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup
creating /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist
creating /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup
/usr/bin/ghc --make /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/Setup.hs -o /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup/setup -odir /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup -hidir /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup -i -i/tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0 -package Cabal-1.16.0
[1 of 1] Compiling Main             ( /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/Setup.hs, /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup/Main.o )
Linking /tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup/setup ...
/tmp/cabal-install-1.24.0.0-11923/cabal-install-1.24.0.0/dist/setup/setup
configure --verbose=2 --ghc --global --flags=-old-directory
--flags=-old-bytestring --flags=network-uri --constraint=zlib ==0.6.1.1
--constraint=unix ==2.7.2.0 --constraint=time ==1.4.0.1 --constraint=tar
==0.5.0.3 --constraint=stm ==2.4.4.1 --constraint=random ==1.1
--constraint=process ==1.4.2.0 --constraint=pretty ==1.1.1.0
--constraint=network-uri ==2.6.1.0 --constraint=network ==2.6.2.1
--constraint=mtl ==2.2.1 --constraint=hashable ==1.2.4.0
--constraint=hackage-security ==0.5.1.0 --constraint=filepath ==1.3.0.1
--constraint=directory ==1.2.6.3 --constraint=cryptohash-sha256 ==0.11.100.0
--constraint=containers ==0.5.0.0 --constraint=bytestring ==0.10.8.1
--constraint=binary ==0.8.4.0 --constraint=base16-bytestring ==0.1.1.6
--constraint=base ==4.6.0.1 --constraint=async ==2.1.0 --constraint=array
==0.4.0.1 --constraint=HTTP ==4000.3.3 --constraint=Cabal ==1.24.0.0
--disable-tests --disable-benchmarks
Configuring cabal-install-1.24.0.0...
Flags chosen: network-uri=True, old-directory=False, old-bytestring=False
Dependency Cabal ==1.24.0.0: using Cabal-1.24.0.0
Dependency HTTP ==4000.3.3: using HTTP-4000.3.3
Dependency array ==0.4.0.1: using array-0.4.0.1
Dependency async ==2.1.0: using async-2.1.0
Dependency base ==4.6.0.1: using base-4.6.0.1
Dependency base16-bytestring ==0.1.1.6: using base16-bytestring-0.1.1.6
Dependency binary ==0.8.4.0: using binary-0.8.4.0
Dependency bytestring ==0.10.8.1: using bytestring-0.10.8.1
Dependency containers ==0.5.0.0: using containers-0.5.0.0
Dependency cryptohash-sha256 ==0.11.100.0: using cryptohash-sha256-0.11.100.0
Dependency directory ==1.2.6.3: using directory-1.2.6.3
Dependency filepath ==1.3.0.1: using filepath-1.3.0.1
Dependency hackage-security ==0.5.1.0: using hackage-security-0.5.1.0
Dependency hashable ==1.2.4.0: using hashable-1.2.4.0
Dependency mtl ==2.2.1: using mtl-2.2.1
Dependency network ==2.6.2.1: using network-2.6.2.1
Dependency network-uri ==2.6.1.0: using network-uri-2.6.1.0
Dependency pretty ==1.1.1.0: using pretty-1.1.1.0
Dependency process ==1.4.2.0: using process-1.4.2.0
Dependency random ==1.1: using random-1.1
Dependency stm ==2.4.4.1: using stm-2.4.4.1
Dependency tar ==0.5.0.3: using tar-0.5.0.3
Dependency time ==1.4.0.1: using time-1.4.0.1
Dependency unix ==2.7.2.0: using unix-2.7.2.0
Dependency zlib ==0.6.1.1: using zlib-0.6.1.1
Failed to install cabal-install-1.24.0.0
World file is already up to date.
cabal: Error: some packages failed to install:
cabal-install-1.24.0.0 failed during the configure step. The exception was:
ExitFailure 11

```

**Comment by 23Skidoo** [comment] 2016-06-04 01:23
Can you try running it with `-v3`? `ExitFailure 11` usually means that GHC terminated with a segmentation fault (see e.g. [here](http://osa1.net/posts/2014-05-27-worst-bug.html)), so this is most likely a bug in GHC.

**Comment by daimajia** [comment] 2016-06-04 17:24
Sorry for my late reply. I tried to install cabal-install on a 4GB memory machine, also failed. 

```bash
# cabal install cabal-install -v3
searching for ghc in path.
found ghc at /usr/bin/ghc
("/usr/bin/ghc",["--numeric-version"])
/usr/bin/ghc is version 7.6.3
looking for tool "ghc-pkg" near compiler in /usr/bin
found ghc-pkg in /usr/bin/ghc-pkg
("/usr/bin/ghc-pkg",["--version"])
/usr/bin/ghc-pkg is version 7.6.3
("/usr/bin/ghc",["--supported-languages"])
("/usr/bin/ghc",["--info"])
Reading installed packages...
("/usr/bin/ghc-pkg",["dump","--global","-v0"])
("/usr/bin/ghc-pkg",["dump","--user","-v0"])
("/usr/bin/ghc",["--print-libdir"])
Reading available packages...
Choosing modular solver.
Resolving dependencies...
[__0] trying: cabal-install-1.24.0.0
[__1] trying: base-4.6.0.1/installed-8aa...
[__2] trying: rts-1.0/installedbuil...
[__3] trying: integer-gmp-0.5.0.0/installed-2f1...
[__4] trying: ghc-prim-0.3.0.0/installed-d52...
[__5] trying: cabal-install-1.24.0.0:-old-directory
[__6] trying: cabal-install-1.24.0.0:-old-bytestring
[__7] trying: cabal-install-1.24.0.0:+network-uri
[__8] trying: cabal-install-1.24.0.0:!test
[__9] trying: unix-2.7.2.0/installed-857...
[_10] trying: network-2.6.2.1/installed-c1d...
[_11] trying: network-uri-2.6.1.0/installed-0a1...
[_12] trying: parsec-3.1.11/installed-ec2...
[_13] trying: text-1.2.2.1/installed-980...
[_14] trying: deepseq-1.3.0.1/installed-5cc...
[_15] trying: process-1.4.2.0/installed-34e...
[_16] trying: directory-1.2.6.3/installed-ddc...
[_17] trying: hackage-security-0.5.1.0/installed-a3a...
[_18] trying: transformers-0.5.2.0/installed-953...
[_19] trying: template-haskell-2.8.0.0/installed-a30...
[_20] trying: old-locale-1.0.0.5/installed-672...
[_21] trying: ed25519-0.0.5.0/installed-c94...
[_22] trying: base64-bytestring-1.0.0.1/installed-818...
[_23] trying: zlib-0.6.1.1/installed-f68...
[_24] trying: time-1.4.0.1/installed-10d...
[_25] trying: tar-0.5.0.3/installed-8d0...
[_26] trying: stm-2.4.2/installed-b5d...
[_27] trying: random-1.0.1.1/installed-43f...
[_28] trying: pretty-1.1.1.0/installed-661...
[_29] trying: mtl-2.2.1/installed-d4f...
[_30] trying: HTTP-4000.3.3/installed-9ff...
[_31] trying: hashable-1.2.4.0/installed-ca5...
[_32] trying: filepath-1.3.0.1/installed-b12...
[_33] trying: cryptohash-sha256-0.11.100.0/installed-32c...
[_34] trying: containers-0.5.0.0/installed-ab1...
[_35] trying: Cabal-1.24.0.0/installed-dba...
[_36] trying: bytestring-0.10.8.1/installed-422...
[_37] trying: binary-0.8.4.0/installed-a29...
[_38] trying: base16-bytestring-0.1.1.6/installed-bcb...
[_39] trying: array-0.4.0.1/installed-3b7...
[_40] trying: async-2.0.1.4/installed-3ea...
[_41] done
Ready to install cabal-install-1.24.0.0
Waiting for install task to finish...
Extracting
/root/.cabal/packages/hackage.haskell.org/cabal-install/1.24.0.0/cabal-install-1.24.0.0.tar.gz
to /tmp/cabal-install-1.24.0.0-20699...
Updating cabal-install.cabal with the latest revision from the index.
Using external setup method with build-type Custom
creating /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup
creating /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist
creating /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup
Using Cabal library version 1.16.0
Using /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/Setup.hs as
setup script.
Setup script is out of date, compiling...
("/usr/bin/ghc",["-v","--make","/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/Setup.hs","-o","/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/setup","-odir","/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup","-hidir","/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup","-i","-i/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0","-package","Cabal-1.16.0"])
Glasgow Haskell Compiler, Version 7.6.3, stage 2 booted by GHC version 7.6.3
Using binary package database: /usr/lib/ghc/package.conf.d/package.cache
Using binary package database: /root/.ghc/x86_64-linux-7.6.3/package.conf.d/package.cache
hiding package parsec-3.1.3 to avoid conflict with later version parsec-3.1.11
hiding package network-2.4.1.2 to avoid conflict with later version network-2.6.2.1
hiding package bytestring-0.10.0.2 to avoid conflict with later version bytestring-0.10.8.1
hiding package HTTP-4000.2.8 to avoid conflict with later version HTTP-4000.3.3
hiding package mtl-2.1.2 to avoid conflict with later version mtl-2.2.1
hiding package unix-2.6.0.1 to avoid conflict with later version unix-2.7.2.0
hiding package directory-1.2.0.1 to avoid conflict with later version directory-1.2.6.3
hiding package zlib-0.5.4.1 to avoid conflict with later version zlib-0.6.1.1
hiding package process-1.1.0.2 to avoid conflict with later version process-1.2.3.0
hiding package binary-0.5.1.1 to avoid conflict with later version binary-0.8.4.0
hiding package transformers-0.3.0.0 to avoid conflict with later version transformers-0.5.2.0
hiding package hashable-1.2.1.0 to avoid conflict with later version hashable-1.2.4.0
hiding package text-0.11.3.1 to avoid conflict with later version text-1.2.2.1
hiding package process-1.2.3.0 to avoid conflict with later version process-1.4.2.0
wired-in package ghc-prim mapped to ghc-prim-0.3.0.0-d5221a8c8a269b66ab9a07bdc23317dd
wired-in package integer-gmp mapped to integer-gmp-0.5.0.0-2f15426f5b53fe4c6490832f9b20d8d7
wired-in package base mapped to base-4.6.0.1-8aa5d403c45ea59dcd2c39f123e27d57
wired-in package rts mapped to builtin_rts
wired-in package template-haskell mapped to template-haskell-2.8.0.0-a3012803fde1dc362e555b35a1a78e6d
wired-in package dph-seq not found.
wired-in package dph-par not found.
Hsc static flags: -static
*** Chasing dependencies:
Chasing modules from: */tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/Setup.hs
Stable obj: []
Stable BCO: []
Ready for upsweep
  [NONREC
      ModSummary {
         ms_hs_date = 2016-06-04 17:21:56 UTC
         ms_mod = main:Main,
         ms_textual_imps = [import (implicit) Prelude,
                            import System.FilePath ( (</>) ),
                            import System.Process ( runProcess ),
                            import System.IO ( openFile, IOMode(WriteMode) ),
                            import Distribution.Verbosity ( Verbosity ),
                            import Distribution.Simple.Setup
                                ( buildVerbosity,
                                  copyDest,
                                  copyVerbosity,
                                  fromFlag,
                                  installVerbosity ),
                            import Distribution.Simple.Utils ( copyFiles, notice ),
                            import Distribution.Simple.LocalBuildInfo
                                ( LocalBuildInfo(..), absoluteInstallDirs ),
                            import Distribution.Simple.InstallDirs
                                ( mandir, CopyDest(NoCopyDest) ),
                            import Distribution.Simple
                                ( defaultMainWithHooks,
                                  simpleUserHooks,
                                  postBuild,
                                  postCopy,
                                  postInst ),
                            import Distribution.PackageDescription ( PackageDescription )]
         ms_srcimps = []
      }]
*** Deleting temp files:
Deleting:
compile: input file /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/Setup.hs
Created temporary directory: /tmp/ghc20717_0
*** Checking old interface for main:Main:
[1 of 1] Compiling Main             ( /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/Setup.hs, /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/Main.o )
*** Parser:
*** Renamer/typechecker:
*** Desugar:
Result size of Desugar (after optimization)
  = {terms: 198, types: 298, coercions: 0}
*** Simplifier:
Result size of Simplifier iteration=1
  = {terms: 194, types: 293, coercions: 0}
Result size of Simplifier = {terms: 194, types: 293, coercions: 0}
*** Tidy Core:
Result size of Tidy Core = {terms: 194, types: 293, coercions: 0}
writeBinIface: 1 Names
writeBinIface: 46 dict entries
*** CorePrep:
Result size of CorePrep = {terms: 270, types: 370, coercions: 0}
*** Stg2Stg:
*** CodeOutput:
*** CodeGen:
*** Assembler:
'/usr/bin/gcc' '-fno-stack-protector' '-Wl,--hash-size=31' '-Wl,--reduce-memory-overheads' '-I/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0' '-c' '/tmp/ghc20717_0/ghc20717_0.s' '-o' '/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/Main.o'
Upsweep completely successful.
*** Deleting temp files:
Deleting: /tmp/ghc20717_0/ghc20717_0.c /tmp/ghc20717_0/ghc20717_0.s
Warning: deleting non-existent /tmp/ghc20717_0/ghc20717_0.c
link: linkables are ...
LinkableM (2016-06-04 17:21:56 UTC) main:Main
   [DotO /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/Main.o]
Linking /tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/setup ...
*** C Compiler:
'/usr/bin/gcc' '-fno-stack-protector' '-Wl,--hash-size=31' '-Wl,--reduce-memory-overheads' '-c' '/tmp/ghc20717_0/ghc20717_0.c' '-o' '/tmp/ghc20717_0/ghc20717_0.o' '-DTABLES_NEXT_TO_CODE' '-I/usr/lib/ghc/include'
*** C Compiler:
'/usr/bin/gcc' '-fno-stack-protector' '-Wl,--hash-size=31' '-Wl,--reduce-memory-overheads' '-c' '/tmp/ghc20717_0/ghc20717_0.s' '-o' '/tmp/ghc20717_0/ghc20717_1.o' '-DTABLES_NEXT_TO_CODE' '-I/usr/lib/ghc/include'
*** Linker:
'/usr/bin/gcc' '-fno-stack-protector' '-Wl,--hash-size=31' '-Wl,--reduce-memory-overheads' '-o' '/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/setup' '/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/Main.o' '-L/root/.cabal/lib/process-1.4.2.0/ghc-7.6.3' '-L/root/.cabal/lib/directory-1.2.6.3/ghc-7.6.3' '-L/root/.cabal/lib/unix-2.7.2.0/ghc-7.6.3' '-L/root/.cabal/lib/bytestring-0.10.8.1/ghc-7.6.3' '-L/usr/lib/ghc/Cabal-1.16.0' '-L/usr/lib/ghc/process-1.1.0.2' '-L/usr/lib/ghc/pretty-1.1.1.0' '-L/usr/lib/ghc/old-time-1.1.0.1' '-L/usr/lib/ghc/directory-1.2.0.1' '-L/usr/lib/ghc/unix-2.6.0.1' '-L/usr/lib/ghc/bytestring-0.10.0.2' '-L/usr/lib/ghc/time-1.4.0.1' '-L/usr/lib/ghc/old-locale-1.0.0.5' '-L/usr/lib/ghc/filepath-1.3.0.1' '-L/usr/lib/ghc/containers-0.5.0.0' '-L/usr/lib/ghc/deepseq-1.3.0.1' '-L/usr/lib/ghc/array-0.4.0.1' '-L/usr/lib/ghc/base-4.6.0.1' '-L/usr/lib/ghc/integer-gmp-0.5.0.0' '-L/usr/lib/ghc/ghc-prim-0.3.0.0' '-L/usr/lib/ghc' '/tmp/ghc20717_0/ghc20717_0.o' '/tmp/ghc20717_0/ghc20717_1.o' '-lHSprocess-1.4.2.0' '-lHSdirectory-1.2.6.3' '-lHSunix-2.7.2.0' '-lrt' '-lutil' '-ldl' '-lpthread' '-lHSbytestring-0.10.8.1' '-lHSCabal-1.16.0' '-lHSprocess-1.1.0.2' '-lHSpretty-1.1.1.0' '-lHSold-time-1.1.0.1' '-lHSdirectory-1.2.0.1' '-lHSunix-2.6.0.1' '-lrt' '-lutil' '-ldl' '-lpthread' '-lHSbytestring-0.10.0.2' '-lHStime-1.4.0.1' '-lHSold-locale-1.0.0.5' '-lHSfilepath-1.3.0.1' '-lHScontainers-0.5.0.0' '-lHSdeepseq-1.3.0.1' '-lHSarray-0.4.0.1' '-lHSbase-4.6.0.1' '-lHSinteger-gmp-0.5.0.0' '-lgmp' '-lHSghc-prim-0.3.0.0' '-lHSrts' '-lffi' '-lm' '-lrt' '-ldl' '-u' 'ghczmprim_GHCziTypes_Izh_static_info' '-u' 'ghczmprim_GHCziTypes_Czh_static_info' '-u' 'ghczmprim_GHCziTypes_Fzh_static_info' '-u' 'ghczmprim_GHCziTypes_Dzh_static_info' '-u' 'base_GHCziPtr_Ptr_static_info' '-u' 'ghczmprim_GHCziTypes_Wzh_static_info' '-u' 'base_GHCziInt_I8zh_static_info' '-u' 'base_GHCziInt_I16zh_static_info' '-u' 'base_GHCziInt_I32zh_static_info' '-u' 'base_GHCziInt_I64zh_static_info' '-u' 'base_GHCziWord_W8zh_static_info' '-u' 'base_GHCziWord_W16zh_static_info' '-u' 'base_GHCziWord_W32zh_static_info' '-u' 'base_GHCziWord_W64zh_static_info' '-u' 'base_GHCziStable_StablePtr_static_info' '-u' 'ghczmprim_GHCziTypes_Izh_con_info' '-u' 'ghczmprim_GHCziTypes_Czh_con_info' '-u' 'ghczmprim_GHCziTypes_Fzh_con_info' '-u' 'ghczmprim_GHCziTypes_Dzh_con_info' '-u' 'base_GHCziPtr_Ptr_con_info' '-u' 'base_GHCziPtr_FunPtr_con_info' '-u' 'base_GHCziStable_StablePtr_con_info' '-u' 'ghczmprim_GHCziTypes_False_closure' '-u' 'ghczmprim_GHCziTypes_True_closure' '-u' 'base_GHCziPack_unpackCString_closure' '-u' 'base_GHCziIOziException_stackOverflow_closure' '-u' 'base_GHCziIOziException_heapOverflow_closure' '-u' 'base_ControlziExceptionziBase_nonTermination_closure' '-u' 'base_GHCziIOziException_blockedIndefinitelyOnMVar_closure' '-u' 'base_GHCziIOziException_blockedIndefinitelyOnSTM_closure' '-u' 'base_ControlziExceptionziBase_nestedAtomically_closure' '-u' 'base_GHCziWeak_runFinalizzerBatch_closure' '-u' 'base_GHCziTopHandler_flushStdHandles_closure' '-u' 'base_GHCziTopHandler_runIO_closure' '-u' 'base_GHCziTopHandler_runNonIO_closure' '-u' 'base_GHCziConcziIO_ensureIOManagerIsRunning_closure' '-u' 'base_GHCziConcziSync_runSparks_closure' '-u' 'base_GHCziConcziSignal_runHandlers_closure'
link: done
*** Deleting temp files:
Deleting: /tmp/ghc20717_0/ghc20717_1.o /tmp/ghc20717_0/ghc20717_0.s /tmp/ghc20717_0/ghc20717_0.o /tmp/ghc20717_0/ghc20717_0.c
*** Deleting temp dirs:
Deleting: /tmp/ghc20717_0
/tmp/cabal-install-1.24.0.0-20699/cabal-install-1.24.0.0/dist/setup/setup
configure --verbose=3 --ghc --prefix=/root/.cabal --user
--flags=-old-directory --flags=-old-bytestring --flags=network-uri
--constraint=zlib ==0.6.1.1 --constraint=unix ==2.7.2.0 --constraint=time
==1.4.0.1 --constraint=tar ==0.5.0.3 --constraint=stm ==2.4.2
--constraint=random ==1.0.1.1 --constraint=process ==1.4.2.0
--constraint=pretty ==1.1.1.0 --constraint=network-uri ==2.6.1.0
--constraint=network ==2.6.2.1 --constraint=mtl ==2.2.1 --constraint=hashable
==1.2.4.0 --constraint=hackage-security ==0.5.1.0 --constraint=filepath
==1.3.0.1 --constraint=directory ==1.2.6.3 --constraint=cryptohash-sha256
==0.11.100.0 --constraint=containers ==0.5.0.0 --constraint=bytestring
==0.10.8.1 --constraint=binary ==0.8.4.0 --constraint=base16-bytestring
==0.1.1.6 --constraint=base ==4.6.0.1 --constraint=async ==2.0.1.4
--constraint=array ==0.4.0.1 --constraint=HTTP ==4000.3.3 --constraint=Cabal
==1.24.0.0 --disable-tests --disable-benchmarks
Configuring cabal-install-1.24.0.0...
creating dist
searching for ghc in path.
found ghc at /usr/bin/ghc
("/usr/bin/ghc",["--numeric-version"])
/usr/bin/ghc is version 7.6.3
looking for tool "ghc-pkg" near compiler in /usr/bin
found ghc-pkg in /usr/bin/ghc-pkg
("/usr/bin/ghc-pkg",["--version"])
/usr/bin/ghc-pkg is version 7.6.3
("/usr/bin/ghc",["--supported-languages"])
("/usr/bin/ghc",["--info"])
Reading installed packages...
("/usr/bin/ghc-pkg",["dump","--global","-v0"])
("/usr/bin/ghc-pkg",["dump","--user","-v0"])
("/usr/bin/ghc",["--print-libdir"])
Flags chosen: network-uri=True, old-directory=False, old-bytestring=False
Dependency Cabal ==1.24.0.0: using Cabal-1.24.0.0
Dependency HTTP ==4000.3.3: using HTTP-4000.3.3
Dependency array ==0.4.0.1: using array-0.4.0.1
Dependency async ==2.0.1.4: using async-2.0.1.4
Dependency base ==4.6.0.1: using base-4.6.0.1
Dependency base16-bytestring ==0.1.1.6: using base16-bytestring-0.1.1.6
Dependency binary ==0.8.4.0: using binary-0.8.4.0
Dependency bytestring ==0.10.8.1: using bytestring-0.10.8.1
Dependency containers ==0.5.0.0: using containers-0.5.0.0
Dependency cryptohash-sha256 ==0.11.100.0: using cryptohash-sha256-0.11.100.0
Dependency directory ==1.2.6.3: using directory-1.2.6.3
Dependency filepath ==1.3.0.1: using filepath-1.3.0.1
Dependency hackage-security ==0.5.1.0: using hackage-security-0.5.1.0
Dependency hashable ==1.2.4.0: using hashable-1.2.4.0
Dependency mtl ==2.2.1: using mtl-2.2.1
Dependency network ==2.6.2.1: using network-2.6.2.1
Dependency network-uri ==2.6.1.0: using network-uri-2.6.1.0
Dependency pretty ==1.1.1.0: using pretty-1.1.1.0
Dependency process ==1.4.2.0: using process-1.4.2.0
Dependency random ==1.0.1.1: using random-1.0.1.1
Dependency stm ==2.4.2: using stm-2.4.2
Dependency tar ==0.5.0.3: using tar-0.5.0.3
Dependency time ==1.4.0.1: using time-1.4.0.1
Dependency unix ==2.7.2.0: using unix-2.7.2.0
Dependency zlib ==0.6.1.1: using zlib-0.6.1.1
searching for alex in path.
found alex at /usr/bin/alex
("/usr/bin/alex",["--version"])
/usr/bin/alex is version 3.1.0
searching for ar in path.
found ar at /usr/bin/ar
searching for c2hs in path.
Cannot find c2hs on the path
searching for cpphs in path.
Cannot find cpphs on the path
searching for ffihugs in path.
Cannot find ffihugs on the path
searching for gcc in path.
found gcc at /usr/bin/gcc
("/usr/bin/gcc",["-dumpversion"])
/usr/bin/gcc is version 4.8
searching for greencard in path.
Cannot find greencard on the path
searching for haddock in path.
found haddock at /usr/bin/haddock
("/usr/bin/haddock",["--version"])
/usr/bin/haddock is version 2.13.2
searching for happy in path.
found happy at /usr/bin/happy
("/usr/bin/happy",["--version"])
/usr/bin/happy is version 1.19.0
searching for hmake in path.
Cannot find hmake on the path
searching for hpc in path.
found hpc at /usr/bin/hpc
("/usr/bin/hpc",["version"])
/usr/bin/hpc is version 0.6
looking for tool "hsc2hs" near compiler in /usr/bin
found hsc2hs in /usr/bin/hsc2hs
("/usr/bin/hsc2hs",["--version"])
/usr/bin/hsc2hs is version 0.67
searching for HsColour in path.
Cannot find HsColour on the path
searching for hugs in path.
Cannot find hugs on the path
searching for jhc in path.
Cannot find jhc on the path
searching for ld in path.
found ld at /usr/bin/ld
("/usr/bin/ghc",["-c","/tmp/20730.c","-o","/tmp/20730.o"])
Failed to install cabal-install-1.24.0.0
Updating world file...
cabal: Error: some packages failed to install:
cabal-install-1.24.0.0 failed during the configure step. The exception was:
ExitFailure 11

```

**Comment by 23Skidoo** [comment] 2016-06-06 03:00
So it compiles the setup script successfully, then runs `./dist/setup/setup configure` and then dies when trying to run this command: `("/usr/bin/ghc",["-c","/tmp/20730.c","-o","/tmp/20730.o"])`.

I'd suggest trying a newer GHC version, 7.6.3 is a bit old at this point.

**Comment by ezyang** [comment] 2016-08-12 07:06
I'm going to close this for now, because none of us know how to reproduce, so it's unlikely that we'll make progress on this.

**Comment by 23Skidoo** [comment] 2016-08-12 11:41
Probably some configuration issue, e.g. `/tmp` mounted noexec.

**Comment by daimajia** [comment] 2016-08-16 03:43
@23Skidoo Sorry for my late reply. I used the latest version, the issue disappear. Thanks again.

**Comment by 23Skidoo** [comment] 2016-08-16 10:05
Great!

**Comment by bombless** [comment] 2016-11-22 05:16
I tried
```
$ sudo apt-get install haskell-platform
$ sudo apt-get install cabal-install
$ cabal update && cabal install cabal-install
```
and also met this problem.
Here's trailing output of `cabal install cabal-install -v3`:
```
Dependency tar ==0.5.0.3: using tar-0.5.0.3
Dependency time ==1.4.0.1: using time-1.4.0.1
Dependency unix ==2.7.2.1: using unix-2.7.2.1
Dependency zlib ==0.6.1.2: using zlib-0.6.1.2
searching for alex in path.
found alex at /usr/bin/alex
("/usr/bin/alex",["--version"])
/usr/bin/alex is version 3.1.0
searching for ar in path.
found ar at /usr/bin/ar
searching for c2hs in path.
Cannot find c2hs on the path
searching for cpphs in path.
Cannot find cpphs on the path
searching for ffihugs in path.
Cannot find ffihugs on the path
searching for gcc in path.
found gcc at /usr/bin/gcc
("/usr/bin/gcc",["-dumpversion"])
/usr/bin/gcc is version 4.8
searching for greencard in path.
Cannot find greencard on the path
searching for haddock in path.
found haddock at /usr/bin/haddock
("/usr/bin/haddock",["--version"])
/usr/bin/haddock is version 2.13.2
searching for happy in path.
found happy at /usr/bin/happy
("/usr/bin/happy",["--version"])
/usr/bin/happy is version 1.19.0
searching for hmake in path.
Cannot find hmake on the path
searching for hpc in path.
found hpc at /usr/bin/hpc
("/usr/bin/hpc",["version"])
/usr/bin/hpc is version 0.6
looking for tool "hsc2hs" near compiler in /usr/bin
found hsc2hs in /usr/bin/hsc2hs
("/usr/bin/hsc2hs",["--version"])
/usr/bin/hsc2hs is version 0.67
searching for HsColour in path.
Cannot find HsColour on the path
searching for hugs in path.
Cannot find hugs on the path
searching for jhc in path.
Cannot find jhc on the path
searching for ld in path.
found ld at /usr/bin/ld
("/usr/bin/ghc",["-c","/tmp/8823.c","-o","/tmp/8823.o"])
Failed to install cabal-install-1.24.0.1
World file is already up to date.
cabal: Error: some packages failed to install:
cabal-install-1.24.0.1 failed during the configure step. The exception was:
ExitFailure 11
```
Full output:
https://gist.github.com/bombless/e49952def29dbd135c0324bc10cf025c

I'm on Ubuntu 14.04.4 LTS

**Comment by bombless** [comment] 2016-11-22 05:23
hmm `apt-get install c2hs cpphs hscolour hugs` solves some error, I guess

**Comment by ezyang** [comment] 2016-11-25 04:30
OK, reopening. The fact that installing those packages solved the problem is a clue.

**Comment by ezyang** [comment] 2016-11-25 05:34
So, exit code 11 means it's segfaulting. #767 is a report about how we give bad error messages in this case; it's fixed in HEAD to report it's a segfault, but you won't have this fix yet. But if it's a segfault, installing extra packages is likely to be a red herring. If you look at that ticket, there are some possible GHC bugs which could be causing the segfault. What if you upgrade to a newer version of GHC? You can get a newer one using hvr's PPA; https://launchpad.net/~hvr/+archive/ubuntu/ghc

**Comment by ezyang** [comment] 2017-07-30 23:41
I think I managed to reproduce this failure today; build log is at: https://travis-ci.org/ezyang/cabal-release/jobs/259199236

Note that this was inside a 32-bit Trusty chroot.

**Comment by dp289m** [comment] 2020-02-20 04:58
Similar issue on AWS instance:
4.14.154-128.181.amzn2.x86_64 #1 SMP Sat Nov 16 21:49:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install haskell-platform --enablerepo=epel
sudo yum group install "Development Tools"
sudo yum install cmake
sudo yum install python3
sudo yum install python
cabal update
sudo cabal install Cabal cabal-install
sudo yum install  c2hs cpphs hscolour hugs
sudo cabal install Cabal cabal-install

Resolving dependencies...
[1 of 1] Compiling Main             ( /tmp/cabal-install-2.2.0.0-6826/cabal-install-2.2.0.0/Setup.hs, /tmp/cabal-install-2.2.0.0-6826/cabal-install-2.2.0.0/dist/setup/Main.o )
Linking /tmp/cabal-install-2.2.0.0-6826/cabal-install-2.2.0.0/dist/setup/setup ...
Warning: cabal-install.cabal: Ignoring unknown section type: custom-setup
Configuring cabal-install-2.2.0.0...
Failed to install cabal-install-2.2.0.0
cabal: Error: some packages failed to install:
cabal-install-2.2.0.0 failed during the configure step. The exception was:
ExitFailure 11

The rest of output is here: https://pastebin.com/UPqeYwHY

**Comment by harshdonga** [comment] 2021-09-16 10:54
After spending hours on installing/removing, the best way to install and configure latest cabal, ghc...

`
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
`

**Comment by Mikolaj** [comment] 2021-09-16 11:14
@harshdonga: OOI, what OS did you try to update GHC/cabal on?

Anyway, thank you for sharing the tip. Indeed, bootstrapping on old OSes (or even current, but with old GHCs) may be impossible and https://www.haskell.org/ghcup is a good bet. Closing the old issue on this note. Please open new ones with reproduction instructions of any current specific problems.

**Closed by Mikolaj** 2021-09-16 11:14 UTC
Labels: type: bug

**Comment by harshdonga** [comment] 2021-09-17 04:24
@Mikolaj 

OS : ubuntu 16.04 LTS
Previous : GHC version 7.10, cabal 1.22

After installing using ghcup,
GHC, cabal : latest

**Comment by Mikolaj** [comment] 2021-09-17 06:49
@harshdonga: thank you. I have the same old Ubuntu version. Indeed, no chance to build anything new with these ancient GHC and cabal versions, so good job finding ghcup. Have fun and good luck!
