### ISSUE TITLE
cabal01 test fails on 2.0.0.1

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4567] opened 2017-06-16 22:40 UTC
When bumping `ghc-8.2`'s `Cabal` submodule to 2.0.0.1 I noticed the following failure of the `cabal01` testcase,
```
=====> cabal01(normal) 1 of 1 [0, 0, 0]
cd "./cabal/cabal01/cabal01.run" && $MAKE -s --no-print-directory cabal01 VANILLA=--enable-library-vanilla PROF=--disable-library-profiling DYN=--enable-shared CLEANUP=1  
Wrong exit code for cabal01()(expected 0 , actual 2 )
Stdout ( cabal01 ):
Makefile:23: recipe for target 'cabal01' failed
Stderr ( cabal01 ):
<no location info>: error:
    module ‘main:Main’ is defined in multiple files: MainA.hs MainA.hs
make[2]: *** [cabal01] Error 1
*** unexpected failure for cabal01(normal)
```

**Comment by hvr** [comment] 2017-06-16 22:53
@bgamari the `test.cabal` file says

```
Name: test
Version: 1.0
Exposed-Modules: A
Other-Modules: B.A
C-Sources: hello.c, c_src/hello.c
Extensions: ForeignFunctionInterface
Build-depends: base>=1.0

Executable: testA
Other-Modules: A, MainA
Main-is: MainA.hs
Extensions: OverlappingInstances

Executable: testB
Other-Modules: B.A, B.MainB
Main-is: B/MainB.hs
```

It's an error to list `MainA` in other-modules if it's already mentioned via Main-is

**Comment by hvr** [comment] 2017-06-17 16:50
Ok, I think I see what's happening here, and I'm not sure we can do much here for such corner cases:

The problem is the combination (the same reasoning applies to `MainA`):

```
Other-Modules: B.A, B.MainB
Main-is: B/MainB.hs
```

The workaround from #4539 assumes that all entries in `other-modules` are in fact module names. But `B.MainB` violates that invariant as `MainB.hs` actually contains

```hs
module Main where

import A

main = print a
```

Consequently, there is *no* module named `B.MainB`, and that's why #5439 doesn't have any chance to work here. In order for #5439 to work (and for `other-modules` to make any sense), it would have to read like

```
Other-Modules: B.A, Main
Main-is: B/MainB.hs
```

Finally, I don't see a good way to workaround such a pathological corner-case of an invalid `.cabal` file, and I'm not sure it's worth to even try to.

**Comment by 23Skidoo** [comment] 2017-06-28 11:11
So this is a `wontfix` then?

**Comment by 23Skidoo** [comment] 2017-07-07 02:14
Closing as `wontfix`, please reopen if disagree.

**Closed by 23Skidoo** 2017-07-07 02:14 UTC
Labels: resolution: wontfix
