### ISSUE TITLE
Syntax for building all packages in the project?

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3013] opened 2015-12-30 11:52 UTC

**Comment by dcoutts** [comment] 2016-04-12 01:26
Suggestions?

**Comment by ezyang** [comment] 2016-04-12 04:08
Well, at least, if I run cabal new-build in a directory which has no Cabal files but the cabal.project file, everything else should be built. I suppose this should generalize such that if you are in a directory within a cabal project, but your current directory or parent directory does not contain a Cabal file, then with no arguments you should build everything.

Conversely, if your current directory or parent directory does contain a Cabal file, you should build all components in that package.

If your cabal.project is in the same directory as a Cabal file, I am not sure what should occur. I think you shouldn't build everything. But then how do you build everything? I suspect this case will not occur too often, and I don't know what the obvious thing to do in this case is.

**Comment by phadej** [comment] 2016-05-10 17:59
Duplicate of https://github.com/haskell/cabal/issues/3391, I close this one as the #3391 has recent discussion.

**Closed by phadej** 2016-05-10 17:59 UTC
Labels: nix-local-build
