### ISSUE TITLE
Command-line option `--builddir` causes error when used with new-install

### ISSUE THREAD

**Issue by tarleb** [haskell/cabal#5875] opened 2019-02-09 07:47 UTC
It seems that `--builddir` is not properly supported by new-install yet:

     % cabal new-install --builddir=${HOME}/tmp
    cabal: option `--builddir' is ambiguous; could be one of:
    --builddir=DIR The directory where Cabal puts generated build files (default
    dist)
    --builddir=DIR The directory where Cabal puts generated build files (default
    dist)

I note that neither of the above messages is correct, as the documented default for this value is `dist-newstyle`, not `dist`.

**Comment by jneira** [comment] 2022-03-26 13:57
Hi, thanks for report the issue.
I cant reproduce with newer versions of cabal so i am gonna close it. Feel free to reopen if you continue experiencing it.

**Closed by jneira** 2022-03-26 13:57 UTC
Labels: type: bug, re: builddir
