### ISSUE TITLE
Linker issues around `integer-gmp` on MacOS

### ISSUE THREAD

**Issue by harpocrates** [haskell/cabal#5222] opened 2018-03-19 20:14 UTC
I'm not really sure if this is a Cabal issue or a GHC one, but since old-build sometimes succeeds where new-build  segfaults, I'm going to assume it might be Cabal. I ran across this when trying to get the Haddock test suite to run with GHC 8.4.1, you can see what I tried there: https://github.com/haskell/haddock/issues/767.

I've only seen this happen on MacOS - everything worked just fine in my Ubuntu VM.

---

|          | binary GHC-8.4        | manually-built  GHC-8.4 |
| ------------- |-------------| -----|
| new-style  commands   | crash | won't compile |
| old-style commands     | crash      |   works |

For each cell in this table I started by building Haddock (either the `ghc-8.4` or the official `1.19.0.1` release branch - same result).

  * __new-style__:

         cabal new-build -w ghc-8.4

  * __old-style__:

         cabal sandbox init
         cabal sandbox add-source haddock-library
         cabal sandbox add-source haddock-api
         cabal install -j4 --dependencies-only -w ghc-8.4
         cabal configure -w ghc-8.4
         cabal build -j4

Then, I created a test file with some TH in it:

    -- Main.hs
    {-# LANGUAGE TemplateHaskell #-}
    main = pure ()
    pure []

Finally, I ran the compiled `haddock` with `Main.hs` as an argument:

  * __new-style__:

         ./dist-newstyle/build/x86_64-osx/ghc-8.4.1/haddock-2.19.0.1/c/haddock/build/haddock/haddock Main.hs

  * __old-style__:

         ./dist/build/haddock/haddock Main.hs

While I was able to get this to work with a manually-built GHC-8.4 and with the old-style commands, everything else crashed when I called when I tried to run the `haddock` binary with an error of the form:

```
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/atheriault/.stack/programs/x86_64-osx/ghc-8.4.1/lib/ghc-8.4.1/integer-gmp-1.0.1.0/HSinteger-gmp-1.0.1.0.o: unknown symbol `___gmp_rands'
haddock: unable to load package `integer-gmp-1.0.1.0'
```

**Comment by harpocrates** [comment] 2018-03-20 02:26
Woops! I goofed. I don't get an error with the new-style commands + manually built 8.4 - I get a compile error (sorry - I miscopied the summary from the Haddock thread): 

```
Building library for haddock-api-2.19.0.1..
<command line>: cannot satisfy -package-id ghc-paths-0.1.0.9-f1132a3630dfd069ac6c748c11485c2bc7a77709c7f89a58
360749883bab0d93:
    ghc-paths-0.1.0.9-f1132a3630dfd069ac6c748c11485c2bc7a77709c7f89a58360749883bab0d93 is unusable due to sha
dowed dependencies:
      base-4.11.0.0
    (use -v for more information)
cabal: Failed to build haddock-api-2.19.0.1 (which is required by exe:haddock
from haddock-2.19.0.1).
```

**Comment by angerman** [comment] 2018-03-20 02:48
@harpocrates that looks more like your `dist`/`dist-newstyle` folders are somehow messed up. You might want to nuke them and try again. I'm not sure cabal will clean them out properly if you use the same compiler version from two different places.

**Comment by harpocrates** [comment] 2018-03-20 02:53
@angerman I just did a fresh clone and `new-build` with only my manually built 8.4. I'm seeing exactly the same compile error as before.

**Comment by angerman** [comment] 2018-03-20 03:10
Hmm... I’ll try to reproduce this later.

**Comment by harpocrates** [comment] 2018-03-20 03:33
Worth mentioning this isn't a blocker for me anymore - I'm just falling back onto my Ubuntu VM whenever I hit this. That said, I'm willing to put time into stepping through any sort of debugging ideas people may have.

**Comment by LeventErkok** [comment] 2018-03-23 13:57
I'm still being hit by this, as it manifests itself on doctest: https://github.com/sol/doctest/issues/199

Essentially, with GHC 8.4.1, doctest on Mac OSX simply doesn't run. Replicating from that ticket, it fails with:

```
$ doctest Data/SBV/Examples/Polynomials/Polynomials.hs
doctest:
lookupSymbol failed in relocateSection (RELOC_GOT)
/usr/local/lib/ghc-8.4.1/integer-gmp-1.0.1.0/HSinteger-gmp-1.0.1.0.o: unknown symbol `___gmp_rands'
doctest: doctest: unable to load package `integer-gmp-1.0.1.0'
```

Any help would be most appreciated!

**Comment by simonmichael** [comment] 2018-03-26 17:31
I see the same thing with hledger-lib doctests on mac with GHC 8.4.1, but FWIW I am using stack and the GHC it installed, not cabal old or new-build.

**Comment by LeventErkok** [comment] 2018-04-03 18:48
anyone knows if GHC 8.4.2 will fix this problem?

**Comment by gbaz** [comment] 2018-04-03 18:51
@bgamari ?

**Comment by harpocrates** [comment] 2018-04-03 18:54
I opened a trac ticket for a very similar (maybe the same?) bug [here](https://ghc.haskell.org/trac/ghc/ticket/14972) and I _think_ that is going to be fixed in 8.4.2.

**Comment by LeventErkok** [comment] 2018-04-21 10:05
I'm afraid the problem is still there with ghc 8.4.2:

```
doctest:
lookupSymbol failed in relocateSection (RELOC_GOT)
/usr/local/lib/ghc-8.4.2/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
doctest: doctest: unable to load package `integer-gmp-1.0.2.0'
```

Can anyone else confirm?

**Comment by harpocrates** [comment] 2018-04-21 15:01
I can confirm. 😢

**Comment by LeventErkok** [comment] 2018-04-30 12:05
@harpocrates Since the GHC bug you referenced is already closed as fixed, should we open a new one? I’m happy to do so, but you have more context. Let me know.

**Comment by harpocrates** [comment] 2018-04-30 14:25
I've reported this as a GHC API bug: https://ghc.haskell.org/trac/ghc/ticket/15105.

**Comment by 23Skidoo** [comment] 2018-04-30 14:36
If this is a GHC bug, can this ticket be closed?

**Comment by 23Skidoo** [comment] 2018-06-08 17:10
Closing in favour of the

**Closed** 2018-06-11 02:10 UTC
Labels: platform: mac, resolution: invalid, type: bug
