### ISSUE TITLE
cabal sdist --project-file doesn't respect the option

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#7241] opened 2021-01-11 00:50 UTC
`cabal-install-3.4` is broken.

`cabal-install-3.2` doesn't work either.

**Comment by philderbeast** [comment] 2022-06-11 21:14
I'm finding this to be the case with `cabal-install-3.8` too.

```
> cabal sdist --help
Generate a source distribution file (.tar.gz).

Usage: cabal sdist [FLAGS] [PACKAGES]

Generates tarballs of project packages suitable for upload to Hackage.

Flags for sdist:
 --project-file=FILE            Set the name of the cabal.project file to
                                search for in parent directories
 -z, --ignore-project           Ignore local project configuration
```

**Comment by gbaz** [comment] 2022-06-11 21:39
I would have thought this would be resolved by https://github.com/haskell/cabal/pull/8109 ?

**Comment by philderbeast** [comment] 2022-06-11 22:32
Still a problem with cabal I installed with ghcup.

```
cabal --version
cabal-install version 3.8.0.20220526
compiled using version 3.8.0.20220526 of the Cabal library
```

I'll install from source and try that too.

**Comment by philderbeast** [comment] 2022-06-15 16:14
Looking now, which of these branches should I try?

![Screen Shot 2022-06-15 at 12 14 19 PM](https://user-images.githubusercontent.com/633283/173875747-49f063c7-579b-4a1c-9b12-32aceb0f0864.png)

**Comment by philderbeast** [comment] 2022-06-16 19:54
I'm on branch `cabal-install-v3.8.1.0-rc1`. Before I attempt a reproduction I'd like to make sure I understand the help.

```
> cabal --version
cabal-install version 3.8.0.20220526
compiled using version 3.8.0.20220526 of the Cabal library

> cabal sdist --help
Generate a source distribution file (.tar.gz).

Usage: cabal sdist [FLAGS] [PACKAGES]

Generates tarballs of project packages suitable for upload to Hackage.

Flags for sdist:
 -h, --help                     Show this help text
 --project-file=FILE            Set the name of the cabal.project file to
                                search for in parent directories
 -z, --ignore-project           Ignore local project configuration
 -v, --verbose[=n]              Control verbosity (n is 0--3, default
                                verbosity level is 1)
 --builddir=DIR                 The directory where Cabal puts generated build
                                files (default dist)
 -l, --list-only                Just list the sources, do not make a tarball
 --null-sep                     Separate the source files with NUL bytes
                                rather than newlines.
 -o, --output-directory=PATH    Choose the output directory of this command.
                                '-' sends all output to stdout
```

>`--project-file=FILE`
> Set the name of the cabal.project file to search for in parent directories

Can I use this to refer to a project file in the current directory?

If I set `--project-file=foo.project` then is the default `cabal.project` now ignored?

What are the relative relationships allowed between `*.project` and `*.cabal` files? Does a `*.project` have to be a sibling or parent of all `*.cabal` files it includes?

If I set both `--project-file=foo.project` and `--ignore-project` then is `foo.project` ignored. What about `cabal.project`? If I have one of those too, is that ignored as well?

**Comment by philderbeast** [comment] 2022-06-16 20:10
> Can I use this to refer to a project file in the current directory? I find the rendered help unclear but the haddocks are better.

https://github.com/haskell/cabal/blob/42da82097e4bbf00fddbdeeca32f4c3aada76c18/cabal-install/src/Distribution/Client/ProjectFlags.hs#L19-L27

**Comment by philderbeast** [comment] 2022-06-16 20:13
> `--ignore-project`
> Ignore local project configuration

This is very brief. It is clearer what is going on by looking at comments in the source that don't get surfaced to `cabal sdist --help` or the haddocks.

https://github.com/haskell/cabal/blob/42da82097e4bbf00fddbdeeca32f4c3aada76c18/cabal-install/src/Distribution/Client/ProjectFlags.hs#L48-L52

**Comment by philderbeast** [comment] 2022-06-16 20:17
Here's the latest from the user's guide.

```rst
.. option:: --ignore-project
    
    Ignores the local ``cabal.project`` file and uses the default
    configuration with the local ``foo.cabal`` file. Note that
    if this flag is set while the ``--project-file`` flag is also
    set then this flag will be ignored.
```

**Comment by philderbeast** [comment] 2022-06-17 20:04
With #8226 I've added a minimal reproduction of the set up I had where I noticed this problem.

For the backstory, I squished a set of packages into one package (using public sub-libraries) and ended up with two projects, `cabal.project` for building the loose set of packages and `cabal.sublib.project` for building a single package with its `*.cabal` file in the root folder. All the loose package `*.cabal` files were in subdirectories.

I'm not sure how to wire the files I've added into a test suite. Any pointers about where to start?

**Comment by Mikolaj** [comment] 2022-06-20 11:03
> I would have thought this would be resolved by #8109 ?

I think it focused on `--ignore-project` and also testing `--project-file` was hard due to it being set by the testing harness IIUC, so only the standard project files name was tested IIRC.

**Comment by Mikolaj** [comment] 2022-06-20 11:09
> This is very brief. It is explained more in source comments that don't get surfaced to `cabal sdist --help` or the haddocks.

Right, this needs to be documented better.

> Here's the latest from the user's guide.

Please kindly verify it agrees with #8109.

**Comment by gbaz** [comment] 2022-09-29 01:29
I tested this on HEAD and it and --ignore-project appear to work. The patch didn't make it into 3.8.1.0 I guess?

I'll optimistically close on that basis.

**Closed by gbaz** 2022-09-29 01:29 UTC
Labels: type: bug, cabal-install: cmd/sdist

**Comment by gbaz** [comment] 2022-09-29 01:52
(note that one needs to run `cabal clean` between `sdist` calls to properly test the behavior with different project file flags, as there's some caching of the configuration -- that's probably a separate thing we want to fix)

**Comment by philderbeast** [comment] 2023-12-15 18:35
> I think it focused on `--ignore-project` and also testing `--project-file` was hard due to it being set by the testing harness IIUC, so only the standard project files name was tested IIRC.

@Mikolaj, I was able to use `withProjectFile` for this:

https://github.com/haskell/cabal/blob/747806633e14770bd5791223bec7ab574706a614/cabal-testsuite/src/Test/Cabal/Prelude.hs#L344-L346

**Comment by Mikolaj** [comment] 2023-12-15 21:20
In #8226? Good to know, thanks.

**Comment by philderbeast** [comment] 2023-12-15 21:28
Yes, added today in #8226.
