### ISSUE TITLE
Add support to clean build cache of a specific local package

### ISSUE THREAD

**Issue by shivaraj-bh** [haskell/cabal#9918] opened 2024-04-22 14:43 UTC
**Describe the feature request**
Add support to clean build cache of a specific local package with `cabal clean`. haskell-stack already does this, see: https://docs.haskellstack.org/en/stable/GUIDE/#the-stack-clean-command

**Additional context**
This would enable more fine-grained control over the build caches that the user can clean

**Comment by michaelpj** [comment] 2024-04-24 09:32
Dupe of https://github.com/haskell/cabal/issues/7506 ?

**Closed** 2024-04-24 10:06 UTC
Labels: type: enhancement
