### ISSUE TITLE
hs-source-dirs does not accept a leading comma

### ISSUE THREAD

**Issue by andrewthad** [haskell/cabal#5959] opened 2019-03-24 14:50 UTC
We can do this:

    build-depends:
      , HUnit 
      , QuickCheck                                                       
      , automata

But not this:

    hs-source-dirs:
      , test
      , common         

This feels inconsistent.

**Comment by phadej** [comment] 2019-03-24 18:51
Duplicate of https://github.com/haskell/cabal/issues/5713 which is resolved in https://github.com/haskell/cabal/pull/5714

**Closed by phadej** 2019-03-24 18:51 UTC
