### ISSUE TITLE
Don't include deprecated versions when calculating "latest" version of a package

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#4325] opened 2017-02-14 15:23 UTC
Just now, I was baffled by this behavior:

```
$ cabal install xml-conduit --allow-newer --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
xml-conduit-1.4.0.4 (latest: 1.5.0)
```

Why would `cabal-install` not choose the later 1.5.0 version of `xml-conduit`, even after I told it `--allow-newer`? I then realized (after looking at the [`xml-conduit` Hackage page](http://hackage.haskell.org/package/xml-conduit)) that `xml-conduit-1.5.0` had been marked as deprecated.

It's thus sensible that `cabal-install` doesn't choose `xml-conduit-1.5.0` in the install plan, but it still misleadingly suggests that there's a later version that you might want to install in `--dry-run`. Can this behavior be tweaked to account for deprecated packages? `cabal-install` already appears to do so for `cabal list --installed`:

```
* xml-conduit
    Synopsis: Pure-Haskell utilities for dealing with XML with the conduit
              package.
    Default available version: 1.4.0.4
    Installed versions: 1.4.0.4
    Homepage: http://github.com/snoyberg/xml
    License:  MIT
```

Since it lists the "Default available version" as 1.4.0.4., not 1.5.0.

**Comment by 23Skidoo** [comment] 2017-02-14 15:34
Yes, makes sense.

**Comment by 23Skidoo** [comment] 2017-02-14 15:38
Though it looks like 1.5.0 is not deprecated, just non-preferred.

**Comment by hvr** [comment] 2017-05-18 14:09
@23Skidoo fwiw, we don't have enough information in the index tarball to distinguish between deprecated and unpreferred versions.

**Comment by RyanGlScott** [comment] 2019-02-07 11:56
See also #5603.

**Comment by fendor** [comment] 2021-06-05 22:08
I can't reproduce the cabal message anymore and can't find other commands that are not honouring `preferred-versions` file, so I think we can close this for now?

**Closed by fendor** 2021-06-05 22:08 UTC
Labels: cabal-install: solver, type: enhancement
