### ISSUE TITLE
toConfiguredComponent: unix (Windows)

### ISSUE THREAD

**Issue by alexbiehl** [haskell/cabal#3978] opened 2016-10-13 08:26 UTC
Trying `new-build` with cabal-install from HEAD on a project of mine: 

    $ cabal new-build hunt-searchengine

Results in: 

    $ Resolving dependencies...
    $ toConfiguredComponent: unix
    $ CallStack (from HasCallStack):
    $ error, called at .\Distribution\Backpack\ConfiguredComponent.hs:131:20 in
    $ Cabal-1.25.0.0-2vbl2DGycuL3ehQ9RJKv1s:Distribution.Backpack.ConfiguredComponent

I would `cabal` expect to fail on building `unix` (since I am on Windows) instead of some internal error.

**Comment by 23Skidoo** [comment] 2016-10-13 08:33
@ezyang, can you please look into this?

**Comment by ezyang** [comment] 2016-10-13 17:50
@alexbiehl Any chance I can get some -v logs?

**Comment by alexbiehl** [comment] 2016-10-13 18:24
Yes of course, I will hand them in tomorrow.

Edward Z. Yang <notifications@github.com> schrieb am Do., 13. Okt. 2016,
19:50:

**Comment by alexbiehl** [comment] 2016-10-14 06:33
`cabal new-build hunt-searchengine -v3` with `dist-newstyle` deleted first:
https://gist.github.com/alexbiehl/b303b584dcf636b54d2b84392088c20d

And here the same command as a subsequent run (with a `dist-newstyle` present). Not sure if needed though. 
https://gist.github.com/alexbiehl/47c2b561de69cf4b0085eb55cbfdc4ba

I have one question to add: 

Somewhere in the logs it says `targets: html-hunter, hunt-client, hunt-crawler, hunt-searchengine, hunt-server, hunt-server-cli`. But I only requested to build `hunt-searchengine` which does not depend on any of the other targets. Is this something weird or is it just listing all available targets?

**Comment by ezyang** [comment] 2016-10-14 06:42
new-build will solve for ALL local packages in your project, so that when you decide to build some of the other ones, it doesn't have to resolve.

**Comment by ezyang** [comment] 2016-10-14 07:30
If you can, apply this patch and then give me the non-verbose log?

{{{
diff --git a/Cabal/Distribution/Backpack/ConfiguredComponent.hs b/Cabal/Distribution/Backpack/ConfiguredComponent.hs
index 184b8bb..86cb899 100644
--- a/Cabal/Distribution/Backpack/ConfiguredComponent.hs
+++ b/Cabal/Distribution/Backpack/ConfiguredComponent.hs
@@ -128,7 +128,8 @@ toConfiguredComponent pkg_descr this_cid
     bi = componentBuildInfo component
     find_it :: PackageName -> VersionRange -> (ComponentId, PackageId)
     find_it name reqVer =
-        fromMaybe (error ("toConfiguredComponent: " ++ display name)) $
+        fromMaybe (error ("toConfiguredComponent: " ++ display (packageName pkg_descr) ++
+                            " " ++ display name)) $
             lookup_name lib_map <|>
             lookup_name external_lib_map
       where
}}}

**Comment by alexbiehl** [comment] 2016-10-14 07:42
$ cabal new-build hunt-searchengine
    Resolving dependencies...
    toConfiguredComponent: hxt-cache unix
    CallStack (from HasCallStack):
    error, called at .\Distribution\Backpack\ConfiguredComponent.hs:131:20 in
    Cabal-1.25.0.0-2vbl2DGycuL3ehQ9RJKv1s:Distribution.Backpack.ConfiguredComponent

**Comment by ezyang** [comment] 2016-10-14 07:57
So, I guess this is not a direct dependency of hunt-searchengine, but one of the other packages that are local?

**Comment by alexbiehl** [comment] 2016-10-14 08:24
Yes, right. `hxt-cache` is the offender here.

**Comment by ezyang** [comment] 2016-10-14 08:26
I guess I have some guesses how I might reproduce this locally. I guess this is not urgent, since you can just remove the unbuildable packages from your project?

**Comment by alexbiehl** [comment] 2016-10-14 08:32
No not urgent. I already filled a pull-request for `hxt-cache` and use a modifed copy.

**Comment by ezyang** [comment] 2016-10-16 22:35
OK, the bug seems to be somehow related to `buildable`. Min repro:

```
name: p
version: 0.1
build-type: Simple
cabal-version: >= 1.25

library
    buildable: False
```

Stick this in a package with a building package (say `q`), and then run `cabal new-build q`.

**Comment by ezyang** [comment] 2016-10-16 23:21
OK, so here's the problem: when the library of a pckage is marked as non-buildable, new-build does NOT eagerly fail. In 1.24, the error would only happen if you tried to build it, or anything that depended on it:

```
cabal: Unknown build target 'lib:p'.
There is no library component 'p' or component 'lib'.
```

or

```
cabal: No executables, libraries, tests, or benchmarks found. Nothing to do.
```

I suppose that's reasonable behavior; it lets you build some part of your project even when other parts are non-buildable. 

But when I refactored this code for Backpack, I assumed that I would only ever get plans with packages that depended upon buildable things. Thus the assert failure! The library doesn't exist and never was configured. 

I guess one way we could fix this is to have the solver reject a package if the library is marked as non-buildable (as opposed to executables/tests/etc. May god have mercy on your soul if you have a non-buildable library with a buildable executable.) But maybe this is not so good for you because it means that you can't develop a project if any of the local deps transitively depends on a non-buildable thing. But maybe you didn't care so much about this case?

By the way, `unix` also has `build-depends: buildable < 0`, so you might wonder why the solver didn't fail? Well, that's because when `buildable: False` we ignore the `build-depends`. This is desirable for executables but not for libraries.

**Comment by dcoutts** [comment] 2016-10-18 19:22
@ezyang fyi, I've seen the same error `toConfiguredComponent: blah`, but I don't think it was the same problem as unix here. Can we add any more detail to this internal error so we can get better info if we hit it again in future.

**Comment by ezyang** [comment] 2016-10-21 21:43
@dcoutts Do you have a repro?

**Closed** 2016-10-22 18:43 UTC
Labels: cabal-install: Backpack, cabal-install: solver, Cabal: Backpack, meta: ezyang, type: bug

**Comment by phadej** [comment] 2018-05-11 22:53
I get this error when

```
% cabal new-build -w ghc-7.8.4 --enable-tests all
Resolving dependencies...
Error:
    Dependency on unbuildable library from http-client
    In the stanza 'library'
    In the package 'http-client-tls-0.3.5.3'
```

with `servant` 0c66b9c0559721ea682cd0d1fa35f403ec075cda

**Comment by phadej** [comment] 2018-05-11 23:01
Now I see the problem: http://hdiff.luite.com/cgit/http-client/diff?id=0.5.12.1&id2=0.5.12

**Comment by grayjay** [comment] 2018-05-15 05:26
I opened an issue for the new type of failure: #5325
