### ISSUE TITLE
`cabal new-test` freezes with certain dependencies

### ISSUE THREAD

**Issue by AhriWindway** [haskell/cabal#5265] opened 2018-04-16 14:55 UTC
I have problem with cabal trying to build `hedgehog` and `tasty-hedgehog`. When `cabal new-test` is launched in my project, my virtual machine freezes and process never ends.
The last output after `configuring haskell-lexer-1.0.1` is:
```
Language/Haskell/Lexer/Lex.hs:5355:10: warning: [-Wunused-matches]
    Defined but not used: ‘err’
     |
5355 | state212 err as iis@(i:is) =
     |          ^^^

Language/Haskell/Lexer/Lex.hs:5359:9: warning: [-Wname-shadowing]
    This binding for ‘err’ shadows the existing binding
      bound at Language/Haskell/Lexer/Lex.hs:5355:10
     |
5359 |   where err _ _ = output Special as (start1 iis)
     |         ^^^

Language/Haskell/Lexer/Lex.hs:5362:10: warning: [-Wunused-matches]
    Defined but not used: ‘err’
     |
5362 | state213 err as is = nestedComment as is state214
     |          ^^^

Language/Haskell/Lexer/Lex.hs:5365:10: warning: [-Wunused-matches]
    Defined but not used: ‘err’
     |
5365 | state214 err as is = output NestedComment as (start1 is)

```

Here is the minimal repository: https://github.com/AhriWindway/haskell-test
If I delete `hedgehog` and `tasty-hedgehog` dependencies, it starts to work fine. 
It is launched on virtual machine with Ubuntu 16.04.3. Cabal and GHC are installed like this:
```
sudo add-apt-repository ppa:hvr/ghc
sudo apt update
sudo apt install ghc-8.2.2 cabal-install-head
```

And after that in the project folder:
```
cabal new-update
cabal new-test
```

What I've tried:
* Delete cabal folder and start again - nothing changed.
```
rm -rf ~/.cabal
cabal new-update
cabal new-test
```
* Created a new virtual machine from the same image. Then repeated all steps and it didn't work.
* BUT on my old virtual machine(from the same image) with the same cabal and ghc versions everything works perfectly fine.
```
cabal-install version 2.3.0.0
compiled using version 2.3.0.0 of the Cabal library 
```
```
The Glorious Glasgow Haskell Compilation System, version 8.2.2
```

**Comment by hvr** [comment] 2018-04-17 06:31
`haskell-lexer` takes over 1GiB ram to compile. How much memory does your VM have? Does  `cabal new-test -j1` cause your VM to freeze as well?

**Comment by AhriWindway** [comment] 2018-04-17 17:49
Oh, I didn't change default RAM value in VMware and it was 1GiB, I set it to 2GiBs and after that it worked.
With 1GiB RAM `cabal new-test -j1` doesn't change anything.

Thanks!

**Comment by grayjay** [comment] 2018-05-02 05:55
It sounds like the issue is resolved, so I'll close this.

**Closed by grayjay** 2018-05-02 05:55 UTC
