### ISSUE TITLE
Can we make errors like missing -dev libraries more obvious?

### ISSUE THREAD

**Issue by nh2** [haskell/cabal#1152] opened 2012-12-15 15:17 UTC
Regularly when I install packages with many dependencies, I get something like this:

```
checking for OpenAL/alc.h... no
configure: error: in `/tmp/OpenAL-1.4.0.1-20242/OpenAL-1.4.0.1':
configure: error: no OpenAL headers found, so this package cannot be built
See `config.log' for more details
Failed to install OpenAL-1.4.0.1
Downloading gloss-1.7.6.5...
...
Updating documentation index /home/niklas/.cabal/share/doc/index.html
cabal: Error: some packages failed to install:
ALUT-2.2.0.0 depends on OpenAL-1.4.0.1 which failed to install.
OpenAL-1.4.0.1 failed during the configure step. The exception was:
ExitFailure 1
edge-0.8.16 depends on OpenAL-1.4.0.1 which failed to install.
```

Here, the installation of a package failed due to missing `openal-dev` libraries; after that, cabal continues to install other packages, which is good.

The problem is that at the end, I mainly see

```
OpenAL-1.4.0.1 failed during the configure step. The exception was:
ExitFailure 1
```

Which is not very informative. I have to scroll up through all of the cabal output, looking for something that looks like an error.

Could we make finding the location of the error easier? I am thinking of
- Showing the errorneous command and its output again at the end
- Writing a log file to `~/.cabal` and mentioning it at the end of a failed `cabal install`
- Using colours (that might be useful in general).

**Comment by ntc2** [comment] 2016-01-29 22:20
There's a duplicate with more subscribers here: https://github.com/haskell/cabal/issues/2580

**Comment by jneira** [comment] 2022-06-28 21:08
Closing as duplicate of #2580,thanks for the suggestion

**Closed by jneira** 2022-06-28 21:08 UTC
Labels: type: enhancement, old-milestone: cabal-install 2.0
