### ISSUE TITLE
Cabal scripts are not cached

### ISSUE THREAD

**Issue by dschrempf** [haskell/cabal#7618] opened 2021-09-04 13:28 UTC
Hello,

I have a short script using `/usr/bin/env cabal`. Whenever I run this script in Bash, the dependencies are resolved and the script gets compiled, even when there was no change to the script (nor to the used projects). It would be nice, if the second and sub-sequent calls to the script are fast, and don't take 10 second like the first one.

I use cabal-install version 3.4.0.0.

**Comment by jneira** [comment] 2021-09-04 13:48
hi! thanks for reporting the issue, I think it is a duplicate of https://github.com/haskell/cabal/issues/6354
so I will close this if you don't mind

**Closed** 2021-09-04 13:49 UTC
Labels: type: enhancement, cabal-install: cmd/run, type: performance

**Comment by dschrempf** [comment] 2021-09-04 13:54
Thank you! Sorry, I did not find this other issue.
