### ISSUE TITLE
undefined, called at ./Distribution/Client/ProjectPlanning.hs:1435:32 in

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#3520] opened 2016-07-05 00:39 UTC
When trying `pointed-5` with `cabal-1.25` of `93c196a93a394533c9e2c2d59f029d65d4b1cc0b`

```
% cabal-1.25 new-build -fcomonad -fcontainers -fkan-extensions -fsemigroupoids -fsemigroups -fstm -ftagged -f-transformers -funodered-containers
Resolving dependencies...
Prelude.undefined
CallStack (from HasCallStack):
error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
undefined, called at ./Distribution/Client/ProjectPlanning.hs:1435:32 in
main:Distribution.Client.ProjectPlanning
```

```hs
1432 pruneInstallPlanToTargets :: Map InstalledPackageId [PackageTarget]             
1433                           -> ElaboratedInstallPlan -> ElaboratedInstallPlan     
1434 pruneInstallPlanToTargets perPkgTargetsMap =                                    
1435     either (\_ -> assert False undefined) id                                    
1436   . InstallPlan.new (IndependentGoals False)                                    
1437   . PackageIndex.fromList                                                       
1438     -- We have to do this in two passes                                         
1439   . pruneInstallPlanPass2                                                       
1440   . pruneInstallPlanPass1 perPkgTargetsMap                                      
1441   . InstallPlan.toList  
```

**Comment by ezyang** [comment] 2016-09-03 05:56
I can't reproduce with 00408a4ee0a24f5e5018f76fd9bc4d209c4fb99f, nor with c2c5d36b7f265acabff63dad9c917a343c7640dc. So... fixed in HEAD? (Please reopen if you still see this.)

**Closed by ezyang** 2016-09-03 05:56 UTC
Labels: cabal-install: nix-local-build, cabal-install: solver, type: bug
