### ISSUE TITLE
cabal v2-install --lib failing

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#6205] opened 2019-08-22 03:19 UTC
**Describe the bug**
cabal v2-install --lib is throwing a pattern match error.

**To Reproduce**

```
C:\Users\WDAGUtilityAccount>where ghc-pkg
C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.6.5\bin\ghc-pkg.exe

C:\Users\WDAGUtilityAccount>cabal v2-install network --lib
Resolving dependencies...
Up to date
Distribution\Simple\GHC.hs:1967:5-56: Irrefutable pattern failed for pattern Just ghcPkgProg
```

**Expected behavior**
No crash and package installed.

**System informataion**
 - Windows 10

```
C:\Users\WDAGUtilityAccount>ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

C:\Users\WDAGUtilityAccount>cabal --version
cabal-install version 3.1.0.0
compiled using version 3.1.0.0 of the Cabal library
```

**Comment by DanielG** [comment] 2019-08-22 05:12
Duplicate of #6195

**Closed by DanielG** 2019-08-22 05:12 UTC
Labels: cabal-install: cmd/install, platform: windows, resolution: duplicate
