### ISSUE TITLE
config paths should support $home $xdghome $xdgcache and $xdgconfig

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5998] opened 2019-04-11 10:15 UTC
So we can have user-independent e.g.

```
installdir: $home/.cabal/bin
```

---

Merijn volunteered to implement this:

```
12:55 <merijn> phadej: Before I get to that I will first have to implement XDG and $HOME variable support for .cabal/config so I can finally have portable system independent cabal files
```

**Comment by hvr** [comment] 2019-04-11 11:11
Duplicate of #1857

**Comment by Mikolaj** [comment] 2021-06-25 19:15
Closing, as this is an old duplicate and related to #680, which is now in active development.

**Closed by Mikolaj** 2021-06-25 19:15 UTC
Labels: cabal-install: cmd/user-config, type: enhancement

**Comment by merijn** [comment] 2025-04-04 19:24
@Mikolaj Could you elaborate how #680 solves this? I was looking into updating my config and checked on this issue, happy to see it closed. But as far as I can tell from the documentation (and #1857 still being open), this issue doesn't seem to have been solved at all?

**Comment by gbaz** [comment] 2025-04-04 19:30
agreed, sadly i think we should reopen. shouldn't be too hard to implement though...

**Comment by Mikolaj** [comment] 2025-04-05 07:56
@merijn: I haven't looked closer but you are probably right, we now support XDG, but not to that extent. Maybe let's focus this discussion exclusively in https://github.com/haskell/cabal/issues/1857, though? If anything from this ticket is essential, please feel free to copy there.
