### ISSUE TITLE
optionally install Cabal when bootsrapping in a sandbox

### ISSUE THREAD

**Issue by accursoft** [haskell/cabal#2575] opened 2015-05-04 10:50 UTC
I build cabal-install with `--sandbox` to avoid polluting the global/user package database. However, the Cabal package is special, and should be installed.

An extra option such as `--install-cabal=(global|user)` could install Cabal in conjunction with `--sandbox`.

**Comment by 23Skidoo** [comment] 2015-05-04 11:04
Why not just use `cabal install Cabal`?

**Comment by accursoft** [comment] 2015-05-04 11:16
That would work in normal circumstances, although it would mean compiling Cabal again.

In my case I'm building GHC on docker and removing the bundled Cabal from the GHC layer to save space. So `bootstrap.sh` will fail if I don't install Cabal first, because ghc can't find the Cabal package when building other packages' `Setup`.

Building `Setup` with the sandbox package db might be a solution, and probably a good idea in any case.

**Comment by 23Skidoo** [comment] 2015-05-04 11:40
>  I'm building GHC on docker and removing the bundled Cabal from the GHC layer to save space

So you are removing Cabal and then trying to build `cabal-install`. Isn't it easier to build `cabal-install` first and then remove Cabal? Note that without Cabal installed you won't be able to `cabal install` packages with `build-type: Custom`.

**Comment by 23Skidoo** [comment] 2015-05-04 11:50
> That would work in normal circumstances, although it would mean compiling Cabal again.

Not sure how you intended to install Cabal without compiling it. In any case, `tar xzvf Cabal-$VERSION.tar.gz`, `cd $CABAL_VERSION` and `runghc Setup configure,build,install` should work even when Cabal is not installed.

**Comment by accursoft** [comment] 2015-05-04 12:01
> Not sure how you intended to install Cabal without compiling it.

Without compiling it twice - once by `bootstrap.sh`, and again by `cabal install Cabal`.

>  In any case, tar xzvf Cabal-$VERSION.tar.gz, cd $CABAL_VERSION and runghc Setup configure,build,install should work even when Cabal is not installed.

That's what I'm doing as a workaround.

**Comment by 23Skidoo** [comment] 2015-05-04 12:51
For some reason I thought that you wanted to make this an argument for `cabal sandbox init`. In the case of the bootstrap script, the problem seems to be that we're installing `deepseq`, `binary` and `time` before installing `Cabal`:

```
do_pkg "deepseq" ${DEEPSEQ_VER} ${DEEPSEQ_VER_REGEXP}
do_pkg "binary" ${BINARY_VER} ${BINARY_VER_REGEXP}
do_pkg "time" ${TIME_VER} ${TIME_VER_REGEXP}
do_pkg "Cabal" ${CABAL_VER} ${CABAL_VER_REGEXP}
```

**Comment by accursoft** [comment] 2015-05-04 12:55
That's OK, they don't need Cabal. However, subsequent packages which do need Cabal won't find it if it's only installed in the sandbox.

**Comment by accursoft** [comment] 2015-05-04 14:32
I should point out that this is related to a much more common issue:

1. Install GHC that was released some time ago.
2. Download latest `cabal-install` from Hackage.
3. `bootstrap.sh --sandbox`
4. Three weeks later `cabal install foo` fails with an odd error from `Setup`.

The problem is that `Setup` is being built with the outdated `Cabal` that came with GHC. Building `cabal-install` in a sandbox and not updating the `Cabal` package is liable to leave the system in an invalid state, which may only become apparent much later, and in a manner which is extremely difficult to diagnose.

**Comment by 23Skidoo** [comment] 2015-05-04 14:54
If the user forgot to do `cabal install Cabal`, why will she remember about `--install-cabal`?

Re: double compilation - `--install-cabal` won't help with that because `--sandbox` ignores everything in user and global package DB.

If the problem is that `cabal install Cabal` doesn't work when Cabal is not installed, we should fix that.

**Comment by accursoft** [comment] 2015-05-04 15:14
> If the user forgot to do `cabal install Cabal`, why will she remember about `--install-cabal`?

`--sandbox` without `--install-cabal` should probably trigger a warning, if not an error.

> --sandbox ignores everything in user and global package DB.

```
# ./bootstrap.sh --no-doc --sandbox
Using gcc for C compiler. If this is not what you want, set CC.
Using /usr/lib/gcc/x86_64-linux-gnu/4.9/collect2 instead.
Bootstrapping in sandbox at '/cabal-install-1.22.3.0/.cabal-sandbox'.
Checking installed packages for ghc-7.10.1...
deepseq is already installed and the version is ok.
binary is already installed and the version is ok.
time is already installed and the version is ok.
Cabal is already installed and the version is ok.
transformers is already installed and the version is ok.
mtl is already installed and the version is ok.
text is already installed and the version is ok.
parsec is already installed and the version is ok.
network is already installed and the version is ok.
old-locale is already installed and the version is ok.
old-time is already installed and the version is ok.
HTTP is already installed and the version is ok.
zlib is already installed and the version is ok.
random is already installed and the version is ok.
stm is already installed and the version is ok.
```

**Comment by 23Skidoo** [comment] 2015-05-04 15:39
> ```
deepseq is already installed and the version is ok
...
```

These are libraries that come with GHC, they can't be ignored.

**Comment by accursoft** [comment] 2015-05-04 15:40
HTTP and zlib didn't come with GHC.

**Comment by 23Skidoo** [comment] 2015-05-04 15:53
What's the output of `ghc-pkg list`? This may be a bug in `--sandbox`.

**Comment by accursoft** [comment] 2015-05-04 16:03
```
/usr/local/lib/ghc-7.10.1/package.conf.d:
    Cabal-1.22.3.0
    HTTP-4000.2.19
    array-0.5.1.0
    base-4.8.0.0
    bin-package-db-0.0.0.0
    binary-0.7.3.0
    rts-1.0
    bytestring-0.10.6.0
    containers-0.5.6.2
    deepseq-1.4.1.1
    directory-1.2.2.0
    filepath-1.4.0.0
    (ghc-7.10.1)
    ghc-prim-0.4.0.0
    haskeline-0.7.2.1
    hoopl-3.10.0.2
    hpc-0.6.0.2
    integer-gmp-1.0.0.0
    mtl-2.2.1
    network-2.6.0.2
    network-uri-2.6.0.3
    old-locale-1.0.0.7
    old-time-1.1.0.3
    parsec-3.1.9
    pretty-1.1.2.0
    process-1.2.3.0
    random-1.1
    stm-2.4.4
    template-haskell-2.10.0.0
    terminfo-0.4.0.1
    text-1.2.0.4
    time-1.5.0.1
    transformers-0.4.2.0
    transformers-0.4.3.0
    unix-2.7.1.0
    zlib-0.5.4.2
```

**Comment by 23Skidoo** [comment] 2015-05-04 20:29
So you installed zlib and HTTP into GHC's package DB, but that is not always the case. For example, on my system GHC lives under `~/bin` (so GHC's package DB is distinct from `/usr/local/lib/...` that `cabal install --global` uses) and on Windows `cabal install --global` puts libraries under `%PROGRAMFILES%\Haskell` instead of `%GHCDIR%\lib`. I also believe that on Linux the "normal" place for libraries that come with GHC is `/usr/lib/ghc-$VERSION`, not `/usr/local/lib/...`.

**Comment by accursoft** [comment] 2015-05-05 07:01
@23Skidoo I wholeheartedly agree with your factual statements, but I'm not clear what you mean to imply with them.

**Comment by accursoft** [comment] 2015-05-05 07:02
To summarise, the issues raised so far are:

 - If `Cabal

**Comment by 23Skidoo** [comment] 2015-05-05 07:15
I mean to imply that in general, `--install-cabal` won't help with double compilation. If we install Cabal to the global or user package DB first, we will also need to install it into sandbox to compile sandboxed `cabal-install`.

So here's what needs to be done to close this ticket:

* `bootstrap.sh --sandbox` should warn that the user needs to run `cabal install Cabal`.
* `cabal install Cabal` should work even without Cabal installed (if it doesn't).

**Comment by accursoft** [comment] 2015-05-05 07:30
`--install-cabal` would avoid double compilation because `Cabal` would only be installed in the global/user packge db, not the sandbox. (This is dependent on the current state of affairs whereby `Setup` is built without the sandbox, which may change.)

**Comment by accursoft** [comment] 2015-05-05 07:33
This would be the equivalent of installing `Cabal` with `--ignore-sandbox`.

**Comment by 23Skidoo** [comment] 2015-05-05 07:34
> because `Cabal` would only be installed in the global/user packge db, not the sandbox

We need `Cabal` in the sandbox to compile `cabal-install`. Global/user package dbs are ignored when using `--sandbox`.

**Comment by accursoft** [comment] 2015-05-05 08:08
Ah, I'm following what you said earlier now. I hadn't been aware that GHC and cabal `--global` use different package dbs. Installing GHC from source puts it in `/usr/local` by default, so they've always been the same on my system. I guess package maintainers separate them.

In other words, when [cabal](https://www.haskell.org/cabal/users-guide/installing-packages.html) says "global package database", it's different to what [GHC](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/packages.html#package-databases) calls the "global package database", although these will happen to be the same thing if GHC was installed from source with default paths. GHC's global package database is used in sandboxes, but cabal's isn't, unless it also happens to be GHC's database.

Is this documented anywhere? Do they have the same definition for "user package database"?

**Comment by 23Skidoo** [comment] 2015-05-05 08:57
Paths that Cabal uses [are documented in the manual](https://www.haskell.org/cabal/users-guide/installing-packages.html). Maybe we should say something about GHC's built-in package DB there.

**Comment by accursoft** [comment] 2015-05-05 09:03
It does mention the global `prefix`, but is it clear anywhere that this refers to the package database, and not just installation paths?

**Comment by 23Skidoo** [comment] 2016-05-19 06:46
Bootstrap script now installs Cabal when being run from a Git clone (9ef5abef756183b08f7fc387dd82542a55f956e6).

**Comment by jneira** [comment] 2022-05-05 20:41
sandbox functionality hasbeen removed so i think the feature is no longer applicable, thanks!

**Closed by jneira** 2022-05-05 20:41 UTC
Labels: type: enhancement, cabal-install: bootstrap
