### ISSUE TITLE
``cabal gen-bounds`` cannot take a -w argument

### ISSUE THREAD

**Issue by kozross** [haskell/cabal#6229] opened 2019-09-09 05:20 UTC
**Describe the bug**

``cabal gen-bounds`` seems to want a globally-installed GHC. Unlike the ``v2-*`` options, which can all be fed a ``-w`` argument to specify where GHC can be found, ``gen-bounds`` does not accept ``-w`` to specify where a local GHC is.

**To Reproduce**

```
$ cabal gen-bounds # no globally-installed GHC
# watch the error regarding no GHC
$ cabal gen-bounds -w /home/koz/ghc-86/bin/ghc
# watch the error regarding -w not being acceptable
```

**Expected behavior**

``gen-bounds`` should accept ``-w`` with a path to a GHC binary and do its thing.

**System information**

 - **Operating system:** Linux
 - **Cabal version:** 3.0.0.0
- **GHC version:** 8.6.5

**Additional context**

'System information' appears to be mis-spelled in your issue template.

**Comment by hvr** [comment] 2019-09-10 11:17
Duplicate of #4956

**Comment by jneira** [comment] 2021-09-05 14:20
closing this as duplicate of#4956, which is more generic but takes in account gen-bounds, @kozross thanks for opening the issue!

**Closed by jneira** 2021-09-05 14:20 UTC
Labels: type: enhancement
