### ISSUE TITLE
MacOS: cabal config about parallel jobs broken

### ISSUE THREAD

**Issue by mouse07410** [haskell/cabal#7691] opened 2021-09-28 17:05 UTC
**Describe the bug**
`$ncpus` has no value on Mac, therefore `jobs: $ncpus` in `~/.cabal/config` sets `jobs` to empty string instead of number of jobs to run in parallel.

**To Reproduce**
Try the following shell script on Mac:
```sh
#!/bin/bash

Z=$ncpus

echo "ncpus = $Z"
```
and observe result.

**Expected behavior**
Set `jobs` to some meaningful value on Mac, so Cabal parallelizes the build when possible. For example, in shell:
```sh
$ alias ncpus='sysctl -n hw.ncpu'
$ ncpus
20
```
The above returns the number of logical CPUs.

But I've no idea how to "encode" the above invocation into the YAML `~/.cabal/config`, short of fixing `jobs` to an arbitrary number less than 20 (my actual number of logical CPUs).

**System information**
 - macOS Big Sur 11.6, Xcode-13
 - `cabal-3.6.0.0`, `ghc-9.0.1`

**Comment by gbaz** [comment] 2021-09-28 17:11
I believe this ticket is incorrect. $ncpus is not a shell variable. It is an input which cabal handles specially directly. 

c.f.

https://github.com/haskell/cabal/blob/c66a1260f86c9c2f16dc319604f766fd8f756045/Cabal/src/Distribution/Simple/Setup.hs#L2195-L2199

**Comment by Mikolaj** [comment] 2021-09-28 17:13
@mouse07410: when you compile, can you observe many package being built at once? If so, everything is probably fine. If not, please reopen with details.

**Comment by mouse07410** [comment] 2021-09-28 17:15
> when you compile, can you observe many package being built at once?

How would you propose doing this?

When I did (during the build) `ps -ef | grep ghc | wc -l`, I got `1`. 

> If not, please reopen with details.

I don't seem to be able to re-open the ticket, I only see the "Comment" button.

**Comment by mouse07410** [comment] 2021-09-28 17:21
And no, looking at the build sequence, it does **not** look like it's working in parallel (to remind, there are 20 logical CPUs):
```
$ cabal install ormolu
Resolving dependencies...
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - ghc-lib-parser-9.0.1.20210324 (lib) (requires download & build)
 - gitrev-1.3.1 (lib) (requires download & build)
 - ormolu-0.3.0.1 (lib) (requires download & build)
 - ormolu-0.3.0.1 (exe:ormolu) (requires download & build)
Downloading  gitrev-1.3.1
Downloaded   gitrev-1.3.1
Downloading  ghc-lib-parser-9.0.1.20210324
Starting     gitrev-1.3.1 (lib)
Building     gitrev-1.3.1 (lib)
Installing   gitrev-1.3.1 (lib)
Completed    gitrev-1.3.1 (lib)
Downloaded   ghc-lib-parser-9.0.1.20210324
Downloading  ormolu-0.3.0.1
Starting     ghc-lib-parser-9.0.1.20210324 (lib)
Building     ghc-lib-parser-9.0.1.20210324 (lib)
Downloaded   ormolu-0.3.0.1
.  .  .  .  .
```

**Comment by Mikolaj** [comment] 2021-09-28 17:22
That's not enough dependencies --- they may depend among themselves. Try something like hlint.

**Comment by Mikolaj** [comment] 2021-09-28 17:23
> I don't seem to be able to re-open the ticket, I only see the "Comment" button.

In that case, I'm sorry for closing unilaterally. Let me re-open.

**Comment by mouse07410** [comment] 2021-09-28 17:23
> Try something like `hlint`.

Too late - already installed. ;-)

How about `pandoc`? It's next in my "to-install" queue. ;-)

**Comment by mouse07410** [comment] 2021-09-28 17:25
```
$ cabal install pandoc
Resolving dependencies...
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - Glob-0.10.1 (lib) (requires build)
 - HsYAML-0.2.1.0 (lib) (requires download & build)
 - JuicyPixels-3.3.5 (lib) (requires download & build)
 - SHA-1.6.4.4 (lib) (requires download & build)
 - blaze-builder-0.4.2.1 (lib) (requires build)
 - base16-bytestring-1.0.1.0 (lib) (requires download & build)
 .  .  .  .  .
Downloading  unicode-data-0.1.0.1
Starting     byteorder-1.0.4 (all, legacy fallback)
Starting     cabal-doctest-1.0.8 (lib)
Starting     cookie-0.4.5 (lib)
Starting     base64-bytestring-1.2.1.0 (lib)
Starting     mime-types-0.1.0.9 (lib)
Starting     case-insensitive-1.2.1.0 (lib)
Starting     hourglass-0.2.12 (lib)
Starting     Glob-0.10.1 (lib)
Starting     basement-0.0.12 (lib)
Starting     blaze-builder-0.4.2.1 (lib)
Downloaded   unicode-data-0.1.0.1
Downloading  base16-bytestring-1.0.1.0
Starting     unicode-data-0.1.0.1 (lib)
Downloaded   base16-bytestring-1.0.1.0
Downloading  digest-0.0.1.3
Starting     base16-bytestring-1.0.1.0 (lib)
Downloaded   digest-0.0.1.3
Downloading  th-lift-0.8.2
Starting     digest-0.0.1.3 (lib)
Downloaded   th-lift-0.8.2
Downloading  temporary-1.3
Downloaded   temporary-1.3
Downloading  doclayout-0.3.0.2
Building     base64-bytestring-1.2.1.0 (lib)
Downloaded   doclayout-0.3.0.2
Downloading  hslua-1.3.0.1
Building     mime-types-0.1.0.9 (lib)
Building     cabal-doctest-1.0.8 (lib)
Building     cookie-0.4.5 (lib)
Building     byteorder-1.0.4 (all, legacy fallback)
Starting     doclayout-0.3.0.2 (lib)
Building     blaze-builder-0.4.2.1 (lib)
Building     hourglass-0.2.12 (lib)
Building     Glob-0.10.1 (lib)
Building     basement-0.0.12 (lib)
Building     case-insensitive-1.2.1.0 (lib)
Building     unicode-data-0.1.0.1 (lib)
Downloaded   hslua-1.3.0.1
Downloading  hslua-module-system-0.2.2.1
.  .  .  .  .
```

Does the above tell you anything useful wrt. the ticket issue?

**Comment by gbaz** [comment] 2021-09-28 17:30
It suggests that everything is working fine! A whole bunch of things have started to build at once.

**Comment by Mikolaj** [comment] 2021-09-28 19:54
I'm glad it ended well. @mouse07410: do you feel like closing the ticket? it's your job now. :)

**Comment by mouse07410** [comment] 2021-09-28 23:22
Thank you!

**Closed** 2021-09-28 23:22 UTC
Labels: type: user-question, platform: mac

**Comment by jneira** [comment] 2021-09-29 05:23
Only want to note that the root cause of the confusion has been the pervasive use of linux idioms which are not aplicable to the rest of os's supported by the tool. Maybe use something not related with any real tool would make clear it is computed by cabal independently from the host os.

**Comment by Mikolaj** [comment] 2021-09-29 08:53
On linux `$ncpus` is void as well. I think the idea was that people would guess that this is a meta-variable filled in somehow. If you just say said NCPUS, nobody would know what that is or people would think this is a text value.

**Comment by mouse07410** [comment] 2021-09-29 12:50
>  I think the idea was that people would guess that this is a meta-variable filled in somehow.

I had no idea that it was possible to even pass meta-variables to Cabal, especially through a YAML file.

Documenting, aka - explaining this would be the best, IMHO.

**Comment by jneira** [comment] 2021-09-29 14:01
> especially through a YAML file.

just in case, afaik global config is not YAML but a custom format

**Comment by mouse07410** [comment] 2021-09-29 14:35
OK, I would still prefer a short two-line comment in `~/.cabal/config` that would say something like 
```
Run given number of jobs simultaneously when building. If $ncpus is specified, run the number of jobs equal to the number of CPUs.
```

But I concede that what's in https://cabal.readthedocs.io/en/3.6/cabal-project.html?highlight=ncpus#cfg-field-jobs is adequate and sufficient.

**Comment by Mikolaj** [comment] 2021-09-29 14:39
No, no, no, the fact we have docs is wonderful, but now let's use them to document the variable on the spot in ~/.cabal/config. Just as @mouse07410 proposes.  I don't see anything in @fgaz's helpful tip that would suggest a vote against the extra comment at the spot.
