### ISSUE TITLE
new-build: Repeating build fails

### ISSUE THREAD

**Issue by BardurArantsson** [haskell/cabal#3637] opened 2016-07-28 15:19 UTC
Repeating a new-build command twice fails on my project with the error message

```
improveInstallPlanWithUpToDatePackages: dep on non lib package
CallStack (from HasCallStack):
error, called at ./Distribution/Client/ProjectBuilding.hs:358:7 in
main:Distribution.Client.ProjectBuilding
```

the second time I run the build. The command I'm running is

```
cabal new-build cqrs-{core,example,memory,postgresql,testkit}
```

and the repository is current 'master' here: https://github.com/BardurArantsson/cqrs/tree/master

**Comment by BardurArantsson** [comment] 2016-07-28 15:20
Oh, and the exact cabal-install version I'm running is commit b7b666efd295c091bea4b2b7e8789d1da35086be

**Comment by 23Skidoo** [comment] 2016-07-28 15:23
Any chance we can get a small test case?

**Comment by BardurArantsson** [comment] 2016-07-28 15:24
I have absolutely no idea how I would go about making such a test case as I'm not familiar with any of the new-build stuff :).

Maybe someone who is can chime in on what I could try?

**Comment by 23Skidoo** [comment] 2016-07-28 15:27
OK, since your library is open source the issue should be reproducible.

**Comment by BardurArantsson** [comment] 2016-07-28 15:27
Hopefully, yes.

**Comment by ezyang** [comment] 2016-07-28 19:02
TBF, this is a lot of deps ;) (currently building...)

**Comment by ezyang** [comment] 2016-07-28 19:24
I cannot repro. I am also on b7b666efd295c091bea4b2b7e8789d1da35086be

Do I have to edit some files?

**Comment by BardurArantsson** [comment] 2016-07-28 19:31
No, all my files are exactly as in that repo.

I'm assuming you did the "repeat the command" bit? (Just making sure.)

If it doesn't reproduce for you then some global state must be "leakin in" somewhere... Hum.

OK, I'll try wiping everything I can and try to build again. Anything I should wipe besides `~/.cabal` and `~/.ghc`...?

**Comment by ezyang** [comment] 2016-07-28 19:36
```
ezyang@sabre:~/Dev/labs/cqrs$ cabal new-build cqrs-{core,example,memory,postgresql,testkit}
In order, the following will be built (use -v for more details):
cqrs-example-0.11.0
Preprocessing executable 'cqrs-example' for cqrs-example-0.11.0...
ezyang@sabre:~/Dev/labs/cqrs$ cabal new-build cqrs-{core,example,memory,postgresql,testkit}
In order, the following will be built (use -v for more details):
cqrs-example-0.11.0
Preprocessing executable 'cqrs-example' for cqrs-example-0.11.0...
```

For some reason new-build is repeatedly building cqrs-example, which does seem like a bug.

Before you wipe everything, first try wiping `dist-newstyle` and trying again.

**Comment by BardurArantsson** [comment] 2016-07-28 20:13
I did try dist-newstyle, but same result :( .

I'll try the "full wipe" tomorrow and report back.

**Comment by BardurArantsson** [comment] 2016-07-29 15:16
OK, I've tried the full wipe of ~/.ghc and ~/.cabal. Issue remains.

Can you think of any other system-wide state that might influence this?

@ezyang : Just out of curiousity... did you do a completely clean build? (That is, with ~/.ghc and ~ /.cabal at least moved out of the way.)

**Comment by ezyang** [comment] 2016-07-31 04:23
Actually, I've reproduced this, but on a different project! The problem goes away if you make a modification to the project in question.

**Comment by grayjay** [comment] 2016-07-31 04:26
I just encountered this when building cabal with `cabal new-build cabal`.  I was using commit 9fea99d.

**Comment by ezyang** [comment] 2016-07-31 04:31
So, for #3644, I'm going to be rewriting this chunk of code. Maybe the problem will go away after I've done so.

**Comment by ezyang** [comment] 2016-07-31 07:56
OK... my guess what is going on is that `improveInstallPlanWithUpToDatePackages` used to handle the case where there was no cached `InstalledPackageInfo`, but when Duncan refactored it, he made it partial in this case.

Unfortunately, we do have to handle this case, because an inplace executable may be improved such that we don't need to rebuild it. I'll have to analyze `preexisting` more carefully to understand what we need to do here.

The steps to reproduce should be to build a package with an executable but no library twice.

**Comment by ezyang** [comment] 2016-07-31 08:05
So I guess there are two possible ways to fix this:

1. Add a new case to `GenericPlanPackage` to represent installed executables (which don't have an `InstalledPackageInfo`)
2. Don't bother updating the `InstallPlan`. It shouldn't matter if we have an "updated" entry in it, because no one can depend on it, and so we'll never actually query for it.

**Comment by ezyang** [comment] 2016-08-21 18:55
This is now fixed.

**Closed by ezyang** 2016-08-21 18:55 UTC
Labels: cabal-install: nix-local-build
