### ISSUE TITLE
setup-Configure-Cabal wrongly resolves path to gcc on Windows

### ISSUE THREAD

**Issue by semenov-vladyslav** [haskell/cabal#3613] opened 2016-07-24 23:51 UTC
On my system ghc is located in 'C:\usr\ghc-8.0.1\'. 
When trying to install 'network' (and some other) package cabal (cabal-install version 1.22.9.0 using version 1.22.3.0 of the Cabal library; version of the 'Cabal' package is 1.24.0.0) fails to configure. 
config.log contains the line:
   $ ./configure --with-compiler=ghc <other-args> CC=C:\usr\GHC-80~1.1?
The 'C:\usr\GHC-80~1.1?' path is invalid, and 'C:\usr\GHC-80~1.1' is dos-path to 'C:\usr\ghc-8.0.1'.
It seems that setup-Configure-Cabal-1.24.0.0-x86_64-windows-ghc-8.0.1.exe cannot correctly resolve path to ghc (and gcc). 
Renaming 'C:\usr\ghc-8.0.1\' to 'C:\usr\ghc8\' solves the problem (or making symlink and exporting only 'C:\usr\ghc8\' in PATH).

**Comment by ezyang** [comment] 2016-07-24 23:57
I think this is a duplicate of #3487. If you run `which sh` from your shell what do you get? If it's cygwin that's why it can't figure it out.

**Comment by semenov-vladyslav** [comment] 2016-07-25 00:08
I believe it is a duplicate. `which sh` returns 'C:\MinGW\msys\1.0\bin\sh.exe'. The short path 'C:\usr\GHC-80~1.1' is ok, it's the question mark after it that makes the problem.

**Comment by ezyang** [comment] 2016-07-25 00:48
Hmm, well, I wonder where the question mark is coming from! Seems like a different bug.

**Comment by NovaDenizen** [comment] 2016-08-02 05:42
This was probably #3649

**Comment by ezyang** [comment] 2016-08-02 05:46
Agreed.

**Closed by ezyang** 2016-08-02 05:46 UTC
Labels: platform: windows, type: bug
