### ISSUE TITLE
Rip out world files

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#7623] opened 2021-09-06 21:30 UTC
The "world" files are long deprecated and never were widely used or supported in v1, and the options are now totally useless in v2. We can't rip out all v1 code yet, but it would be a good cleanup pass to delete the options and references to world files throughout the cabal codebase.

**Comment by phadej** [comment] 2021-09-06 23:30
Duplicate of https://github.com/haskell/cabal/issues/6767

**Closed** 2021-09-07 03:49 UTC
Labels: attention: pr-welcome, type: refactor
