### ISSUE TITLE
adopt XDG basedir spec

### ISSUE THREAD

**Issue by bos** [haskell/cabal#680] opened 2012-05-24 05:42 UTC
(Imported from [Trac #688](http://hackage.haskell.org/trac/hackage/ticket/688), reported by guest on 2010-05-12)

I want to be able to tell <tt>cabal</tt> to read the configuration from a different place than <tt>$HOME/.cabal/config</tt>.

The ultimate goal is to get rid of the non-standard <tt>.cabal</tt> directory altogether, so far careful <tt>--package-db</tt>/<tt>--prefix</tt> etc. juggling served me well; <tt>config</tt> is the last remaining file there.

<pre class="wiki">&gt; cabal --version
cabal-install version 0.8.2
using version 1.8.0.2 of the Cabal library
</pre>

**Comment by Earnestly** [comment] 2015-06-19 13:22
The only difference is by needing `CABAL_CONFIG` we add to our already bloated
`environ`s.  For reference here are a few:

```
export SLRNHOME=$XDG_CONFIG_HOME/slrn
export _RR_TRACE_DIR=$XDG_DATA_HOME/rr
export CARGO_HOME=$XDG_DATA_HOME/cargo
export GNUPGHOME=$XDG_CONFIG_HOME/gnupg
export INPUTRC=$XDG_CONFIG_HOME/inputrc
export RLWRAP_HOME=$XDG_DATA_HOME/rlwrap
export LYNX_CFG_PATH=$XDG_CONFIG_HOME/lynx
export DVDCSS_CACHE =$XDG_CACHE_HOME/dvdcss
export TIGRC_USER=$XDG_CONFIG_HOME/tig/tigrc
export WEECHAT_HOME=$XDG_CONFIG_HOME/weechat
export PERL_CPANM_HOME=$XDG_CACHE_HOME/cpanm
export GIMP2_DIRECTORY=$XDG_CONFIG_HOME/gimp
export ELINKS_CONFDIR=$XDG_CONFIG_HOME/elinks
export CABAL_CONFIG=$XDG_DATA_HOME/cabal/config
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie
export LESSHISTFILE=$XDG_CACHE_HOME/less/history
export XAUTHORITY=$XDG_RUNTIME_DIR/x11/xauthority
export XCOMPOSEFILE=$XDG_CONFIG_HOME/x11/xcompose
export GUILE_HISTORY=$XDG_CONFIG_HOME/guile/history
export VIMPERATOR_RUNTIME=$XDG_CONFIG_HOME/vimperator
export PENTADACTYL_RUNTIME=$XDG_CONFIG_HOME/pentadactyl
export NOTMUCH_CONFIG=$XDG_CONFIG_HOME/notmuch/notmuchrc
export GTK2_RC_FILES=$XDG_CONFIG_HOME/gtk-2.0/settings.ini
export TERMINFO_DIRS=$XDG_DATA_HOME/terminfo:/usr/share/terminfo
export UNCRUSTIFY_CONFIG=$XDG_CONFIG_HOME/uncrustify/uncrustify.cfg
```

These are just the ones I use, there are much more.

**Comment by rkraneis** [comment] 2018-01-30 09:40
So no improvements here? Another reason for adopting the XDG scheme is that backup tools know about these and already exclude e.g. .cache from backups. I'm now hunting around to see which of its 3GiB cabal actually needs :-(

**Comment by hvr** [comment] 2018-01-30 20:07
@rkraneis I think this mostly needs somebody to take the lead: design a reasonable migration/fallback scheme, and implement it.

**Comment by SlySven** [comment] 2020-01-19 00:04
I was browsing this topic researching what the XDG file location concept says about *binaries* - not to much as it seems - and I found that @Earnestly wrote a few years back:
> ... We'll get there eventually, compilers are one of the few remaining bastions supporting the [UNIX v2 bug that is "dotfiles"](https://web.archive.org/web/20190211031031/https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp) 

however the original link was a Google+ one that has now been expunged from the Interweb thingummyjig - but I tracked down a wayback machine archive and fitted it into this post. HTH a *tiny* bit...

**Comment by xerus2000** [comment] 2021-04-13 11:29
Until PRs are done, I updated the entry in the Arch wiki with easy environment variables ;) https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial

**Comment by athas** [comment] 2021-05-09 08:04
I'm idly poking at this now.  Did someone ever draft a design or migration path?  Let me suggest the following:

* The Cabal configuration file goes in `$XDG_CONFIG_HOME/cabal/config`.
* `cabal install` binaries go in `$HOME/.local/bin` (from [the systemd file-hierarchy spec](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html)).
* Everything else goes in `$XDG_CACHE_HOME/cabal`).

This might break people, of course.  So if `CABAL_DIR` exists, then the current behaviour will be maintained (everything in `CABAL_DIR)`.  Further, as a (hopefully temporary) migration path, if `$HOME/.cabal` exists, then that will interpreted as `CABAL_DIR` being set to `$HOME/.cabal`.

**Comment by athas** [comment] 2021-05-09 08:05
I have no idea what the situation is on Windows.  Maybe current behaviour should just be preserved there.

**Comment by phadej** [comment] 2021-05-09 08:11
Something not mentioned previously. Users are able to configure using `CABAL_CONFIG` and having user specific paths in their `cabal.config`. E.g. mine looks like:

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/

remote-build-reporting: anonymous
remote-repo-cache:      /cabal/packages

write-ghc-environment-files: always

build-summary:     /cabal/logs/build.log
extra-prog-path:   /cabal/bin
installdir:        /cabal/bin
logs-dir:          /cabal/logs
store-dir:         /cabal/store
symlink-bindir:    /cabal/bin
world-file:        /cabal/world

install-dirs user
  prefix: /cabal
```

Changing defaults is more or less a communication issue.

**Comment by athas** [comment] 2021-05-09 08:15
I don't *think* the code for that will need to be modified.  XDG migration is only about the defaults, anyway.  From hacking a bit on the code, I think the largest unknown challenge is that there seems to be some parts of the code that assume a single "root" `cabal` directory from which other paths can be computed.  I'm not yet sure how deep that goes.

**Comment by phadej** [comment] 2021-05-09 08:26
Shouldn't go deep, as all **used** paths should be configurable. Their defaults are computed using `CABAL_DIR`.

**Comment by fgaz** [comment] 2021-05-09 08:52
> Everything else goes in $XDG_CACHE_HOME/cabal

If the cache is cleaned, this can break projects and installed executables, so I'd suggest XDG_DATA_HOME instead

**Comment by athas** [comment] 2021-05-09 08:55
I don't have a strong opinion on that.  I tried looking at whether XDG has firm guidance on what distinguishes "data" from "cache", but I couldn't quickly find any.  My intuition was that "cache" is for things that can be recreated, while "data" is for things that might be unique.

**Comment by phadej** [comment] 2021-05-09 09:05
@fgaz `XDG_DATA_HOME` is wrong, as it cannot be shared between machines, thus `XDG_STATE_HOME`.

**Comment by fgaz** [comment] 2021-05-09 09:05
First of all let's get more granular: `packages` can for sure go in `cache`, and maybe logs too, while `store` is the problem.

* Installed executables (especially symlinked ones) can depend on it
* It may contain some installed package that is not easily replicated (not saying it's a good idea to get into this situation but it can happen)
* There could be similar concerns for projects

on the other hand

* people probably don't want to back up the store together with all their other data files (though maybe they do due to the reasons above?)
* if executables do not have data files (probably the majority?) and are installed with --install-method=copy, they will continue to work
* difficult-to-recreate store paths sounds like a rare occurrence

I'd say that it's better to err on the safe side and put it into data, but I don't have a strong opinion either

**Comment by phadej** [comment] 2021-05-09 09:05
This discussion is split now between this and #7386. Let's decide where to discuss.

**Comment by athas** [comment] 2021-05-09 09:07
There's a lot of these XDG issues (e.g. also #1857).  I'd suggest closing all but one (say, this one), and then keep the design discussion here (not in the PRs, which might be closed or replaced if a better one shows up).

**Comment by phadej** [comment] 2021-05-09 09:09
#1857 is own issue. It's about being able to say `store-dir: $home/foobar` - it just happens to mention XDG. (If implemented, it would make default config user-independent, which would be great - but the issues can be resolved independently).

**Comment by fgaz** [comment] 2021-05-09 09:14
I see that it's only a proposal by debian for now: https://wiki.debian.org/XDGBaseDirectorySpecification

Do we want to use a specification that is not stable yet? I say yes, it solves a real need.

**Comment by athas** [comment] 2021-06-25 15:51
Is the conclusion that using `XDG_STATE_DIR` is desirable?  If so, `directory` needs to be patched first.

**Comment by athas** [comment] 2021-06-25 15:53
I see it has already been reported: https://github.com/haskell/directory/issues/119

**Comment by Mikolaj** [comment] 2021-06-25 19:07
Yes, I think that's the conclusion. I also agree it's a good idea to discuss spec here and implementation in the PR. I will close any duplicate issues and link here from any related issues.

**Comment by athas** [comment] 2021-06-25 20:50
I submitted a patch to `directory` for adding support for `XDG_STATE_HOME`.  We'll see how that goes.  The draft `cabal` design as I understand it is then:

* The Cabal configuration file goes in `$XDG_CONFIG_HOME/cabal/config`.
* `cabal install` binaries go in `$HOME/.local/bin` (from the systemd file-hierarchy spec).
* Packages and logs (the current `~/.cabal/packages` and `~/.cabal/logs`) go in `XDG_CACHE_HOME/cabal`.
* Everything else (just `~/.cabal/store`?) goes in `$XDG_STATE_HOME/cabal`

People with more Cabal experience can probably judge whether this is a sensible design.  There's still two questions to answer:

1) What about Windows?  The above will work on Windows because `directory` supplies fascimiles of the XDG paths, but I'm not sure it's actually what users would want.

2) A migration path for people who have already set `CABAL_DIR` or `CABAL_CONFIG`.  I think these variables should just take precedence over XDG, if set.

**Comment by Mikolaj** [comment] 2021-06-25 23:20
The `CABAL_DIR` is being discussed at #7455 and I think we should stick to that or discuss there.

**Comment by hasufell** [comment] 2021-07-09 18:58
> cabal install binaries go in $HOME/.local/bin (from the systemd file-hierarchy spec).

`$HOME/.local/bin` is accepted in XDG spec: https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/38

Note that stack also installs into this directory... I'm generally not a fan of this directory anymore. It has caused problems for ghcup as well to the point that I'd like to remove XDG support from it. As an example: if you'd enable XDG for both cabal and ghcup and then run `cabal install --overwrite-policy=always --install-method=copy cabal-install`, then you'll cause confusion for ghcup by overwriting `~/.local/bin/cabal`.

But I'm sure many users already set this as their default installation directory, so yeah.

> A migration path for people who have already set CABAL_DIR or CABAL_CONFIG. I think these variables should just take precedence over XDG, if set.

Yes. `ghcup` on windows sets `CABAL_DIR` to a short path to avoid MAX_PATH issues. Following the XDG emulations will likely cause problems on windows.

**Comment by Mikolaj** [comment] 2021-07-09 21:24
@hasufell: thank you for the remarks. That's very valuable. Let's discuss how to avoid the problems.

There are at least two partially independent proposals here. One is XDG, the other is using the config file instead of environment variables (except `CABAL_CONFIG`).

**Comment by athas** [comment] 2021-09-04 08:29
I think using `$HOME/.local/bin` is preferable, even though it runs the risk of conflicts.  Conflicts will always happen when you have a shared resource, but the Unix/Linux world is for better or for worse standardising on this directory.  I don't think it's to the advantage of cabal to be different.

(I would also suggest `cabal install` adopt common conventions from other tools, namely copying and overwriting by default, but that's unrelated to XDG).

**Comment by hasufell** [comment] 2021-09-04 08:54
> I think using `$HOME/.local/bin` is preferable, even though it runs the risk of conflicts.  Conflicts will always happen when you have a shared resource, but the Unix/Linux world is for better or for worse standardising on this directory.  I don't think it's to the advantage of cabal to be different.
> 

I'm not sure. All of the other XDG directories are usually used in a way where programs create a program specific subdirectory, exactly to avoid conflicts. 

`~/.local/bin` is the only one that breaks this.

Imagine all apps installing their data files into the same dir without subdirectories. Not a great idea.

The only reason this works for `/usr/bin` is because there's only one program installing into it: your package manager.

**Comment by athas** [comment] 2021-09-04 09:19
My argument is not that `$HOME/.local/bin` is a good design.  My argument is that it's the de facto standard.  It is used by build tools that are held in high regard by their respective user communities (e.g. `cargo`, `stack`), and complaints are few.  Is this a fight that `cabal` cares about?

**Comment by hasufell** [comment] 2021-09-04 10:26
> My argument is not that `$HOME/.local/bin` is a good design.  My argument is that it's the de facto standard.

Supporting the XDG standard isn't hard. Making it the default is a different thing.

**Comment by Mikolaj** [comment] 2021-11-15 08:51
#7819 is an argument for making XDG the default, isn't it?

**Comment by Mikolaj** [comment] 2021-11-15 09:56
@phadej explained in #7819 that the relation is not so direct, because we need to support both XDG (>= 9.2) and non-XDG ghcs, so GHC XDG and overall XDG needs to be separated anyway.

**Comment by ulysses4ever** [comment] 2022-07-24 15:47
@athas are you still interested in working on this?

**Comment by athas** [comment] 2022-07-24 15:53
Yes, but I don't have the time in the near term.  It's not difficult to implement, but I got demotivated by having to untangle dependencies in the test suites.

**Comment by Mikolaj** [comment] 2022-07-25 06:02
No rush. Please do share the dependencies troubles next time you encounter them.

**Comment by athas** [comment] 2022-09-30 09:33
The implementation of this is in #7386 and is pretty much ready to be merged.  There's still room to litigate the specific XDG directories though.

I don't have any real issue with the current design (summarised in #7386 and its updated documentation, and also above in this thread), but I should note that the use of `XDG_STATE_HOME` to keep the Cabal store does seem a bit unusual.  `XDG_STATE_HOME` is not used much by anything (likely because it is so new), and I've seen remarks that it's mostly intended for transient and lightweight state like "current state of the application that can be reused on a restart (view, layout, open files, undo history, …)".  In particular, nothing seems to store large files there (which Cabal will certainly do).  The classic alternative would be `XDG_DATA_HOME` (`~/.local/share`) which is heavily used for all kinds of random data by many programs (e.g. Evolution seems to store email and calendar info there, and all of Steam lives there as well), but it can be argued that this was never supposed to be the point of that directory (it was intended to be more like `/usr/share`, i.e. mostly read-only data files).  This isn't necessarily a problem, and will only be so in the exotic case where a user decides to put `XDG_STATE_HOME` on a separate file system with very little space, but I feel it should be recorded for posterity.

**Comment by athas** [comment] 2022-09-30 09:35
Oh, and another thing: the change in #7386 affects all operating systems, including Windows.  I don't think any Windows users have weighed in on whether this is appropriate.  `directory` implements the XDG directories on Windows as best it can, but I have no idea whether what it does is actually useful.  It might be a better design to keep using a single unified Cabal directory on Windows - I really don't know.

**Comment by athas** [comment] 2022-09-30 20:40
Implemented in 7386.

**Closed by athas** 2022-09-30 20:40 UTC
Labels: type: enhancement, platform: linux, cabal-install: other
