### ISSUE TITLE
Options that change how tests are run should not cause a rebuild

### ISSUE THREAD

**Issue by erikd** [haskell/cabal#6267] opened 2019-09-30 22:55 UTC
**Describe the bug**
Building my project and the running the tests, causes the test command to rebuild everything.

I like to see the output of my test suites so I use `--test-show-details=direct` and I have multiple test suites and to avoid them all running at the same time (and having their output all come out at once) I use `-j1`.

**To Reproduce**
Using cabal version 3.0:
```
$ cabal build all
$ cabal test all -j1 --test-show-details=direct
```
If I run the same two commands again, the `build` command will rebuild everything and then the `test` command will again rebuild everything.

**Expected behavior**
The `test` command should only build the stuff that has not been built.

**System informataion**
 - Linuix
 - cabal 3.0
 - ghc 8.6.5

Related: https://github.com/haskell/cabal/issues/6129 https://github.com/haskell/cabal/issues/6069

**Comment by robx** [comment] 2021-06-16 13:54
I see something similar with test-options, which makes `cabal test` rather painful to use as a test runner. Changing a test filter passed through `test-options` raises the test overhead from 1s to 5s. (Happy to file separately if desired.)

<details><summary>test log</summary>

```
$ time cabal test --test-options='-t noexist' # ran the same thing before
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - configurator-pg-0.2.5 (test:tests) (first run)
Preprocessing test suite 'tests' for configurator-pg-0.2.5..
Building test suite 'tests' for configurator-pg-0.2.5..
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to:
/s/configurator-pg/dist-newstyle/build/x86_64-osx/ghc-8.10.4/configurator-pg-0.2.5/t/tests/test/configurator-pg-0.2.5-tests.log
1 of 1 test suites (1 of 1 test cases) passed.

real	0m0.850s
user	0m0.639s
sys	0m0.167s
$ time cabal test --test-options='-t reallynoexist'
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - configurator-pg-0.2.5 (lib) (configuration changed)
 - configurator-pg-0.2.5 (test:tests) (configuration changed)
Configuring library for configurator-pg-0.2.5..
Preprocessing library for configurator-pg-0.2.5..
Building library for configurator-pg-0.2.5..
Configuring test suite 'tests' for configurator-pg-0.2.5..
Warning: The package has an extraneous version range for a dependency on an
internal library: configurator-pg >=0 && ==0.2.5. This version range includes
the current package but isn't needed as the current package's library will
always be used.
Preprocessing test suite 'tests' for configurator-pg-0.2.5..
Building test suite 'tests' for configurator-pg-0.2.5..
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to:
/s/configurator-pg/dist-newstyle/build/x86_64-osx/ghc-8.10.4/configurator-pg-0.2.5/t/tests/test/configurator-pg-0.2.5-tests.log
1 of 1 test suites (1 of 1 test cases) passed.

real	0m4.885s
user	0m3.253s
sys	0m1.235s
```

</details>

**Comment by Mikolaj** [comment] 2021-06-16 15:27
To help you (and people searching and finding this issue) out until this is solved in cabal itself, is building and then repeatedly running the test executable directly from its path, with suitable options, a sufficient workaround?

**Comment by fgaz** [comment] 2021-06-17 14:05
Duplicate of #6114 ?

**Comment by robx** [comment] 2021-06-21 13:53
> Duplicate of #6114 ?

Seems like this is a part of #6114, though by my reading this might be better off as a separate issue? (Namely test-options shouldn't be a solver input, while enable-tests should be?)

**Closed** 2021-09-02 21:53 UTC
Labels: type: enhancement, attention: pr-welcome, cabal-install: cmd/test
