### ISSUE TITLE
assert, called at ./Distribution/Client/ProjectOrchestration.hs:757:5

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#5656] opened 2018-11-02 20:10 UTC
I guess this is because I did not give an explicit target, but a nice error message would be nice:
```
~/build/haskell/cabal $ git rev-parse HEAD
85546533d5c21ed18fb2e40eda9a1c3dfb34ced3
~/build/haskell/cabal $ cabal new-install
Resolving dependencies...
Assertion failed
CallStack (from HasCallStack):
  assert, called at ./Distribution/Client/ProjectOrchestration.hs:757:5 in main:Distribution.Client.ProjectOrchestration
```

**Comment by fgaz** [comment] 2018-11-02 22:29
Duplicate of #5630

**Closed by fgaz** 2018-11-02 22:29 UTC
Labels: resolution: duplicate
