### ISSUE TITLE
cabal: 'parseField' called on a non-field

### ISSUE THREAD

**Issue by HJvT** [haskell/cabal#2260] opened 2014-12-08 13:18 UTC
I received the following message from cabal-install:

~~~~Text
C:\[...]\GitHub\GeBoP> cabal sdist
cabal: 'parseField' called on a non-field. This is possibly a bug in Cabal.
Please report it to the developers: https://github.com/haskell/cabal/issues/new

C:\[...]\GitHub\GeBoP> cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.1 of the Cabal library
~~~~

This happened after I added the following to the .cabal file:

~~~~Text
Source-repository head
  Type:         git
  Location      git://github.com/wxHaskell/GeBoP.git
~~~~

The full .cabal file that caused this:

~~~~Text
Name:           GeBoP
Synopsis:       Several games
Description: 
  The games: Ataxx, Bamp, Halma, Hez, Kram, Nim, Reversi, TicTacToe, and Zenix
Homepage:       http://www.haskell.org/haskellwiki/GeBoP
Version:        1.7.4
License:        BSD3
License-file:   LICENSE.txt
Author:         Maarten Löffler
Maintainer:     wxHaskell developer mailing list <wxhaskell-devel@lists.sourceforge.net>
Stability:      Stable
Cabal-Version:  >= 1.2
Build-type:     Simple
Category:       Game
Tested-with:    GHC == 7.6.3, GHC == 7.8.3
Source-repository head
  Type:         git
  Location      git://github.com/wxHaskell/GeBoP.git
Extra-Source-Files:
                changelog.txt
                readme.txt,
                Ataxx.hs,
                Bamp.hs,
                Game.hs,
                GUI.hs,
                Halma.hs,
                Hex.hs,
                HSL.hs,
                Inf.hs,
                Kram.hs,
                Nim.hs,
                Reversi.hs,
                TicTacToe.hs,
                Tools.hs,
                Zenix.hs

Data-dir:       .
Data-files:     gebop.ico, 
                brain.ico,
                images/blue.bmp,
                images/blue_mask.bmp,
                images/brain.bmp,
                images/brain_mask.bmp,
                images/brown.bmp,
                images/brown_mask.bmp,
                images/computer.bmp,
                images/computer_mask.bmp,
                images/empty.bmp,
                images/empty_mask.bmp,
                images/gebop.bmp,
                images/green.bmp,
                images/green_mask.bmp,
                images/grey.bmp,
                images/grey_mask.bmp,
                images/high_blue.bmp,
                images/high_brown.bmp,
                images/high_green.bmp,
                images/high_grey.bmp,
                images/high_purple.bmp,
                images/high_red.bmp,
                images/high_small_blue.bmp,
                images/high_small_brown.bmp,
                images/high_small_green.bmp,
                images/high_small_grey.bmp,
                images/high_small_purple.bmp,
                images/high_small_red.bmp,
                images/human.bmp,
                images/human_mask.bmp,
                images/marble.bmp,
                images/purple.bmp,
                images/purple_mask.bmp,
                images/red.bmp,
                images/red_mask.bmp,
                images/small_blue.bmp,
                images/small_blue_mask.bmp,
                images/small_brain.bmp,
                images/small_brain_mask.bmp,
                images/small_brown.bmp,
                images/small_brown_mask.bmp,
                images/small_green.bmp,
                images/small_green_mask.bmp,
                images/small_grey.bmp,
                images/small_grey_mask.bmp,
                images/small_purple.bmp,
                images/small_purple_mask.bmp,
                images/small_red.bmp,
                images/small_red_mask.bmp,
                images/turn.bmp,
                images/turn_mask.bmp,
                images/winner.bmp,
                images/winner_mask.bmp,
                help/brain.html,
                help/gebop.bmp,
                help/index.html,
                help/info_ataxx.html,
                help/info_bamp.html,
                help/info_halma.html,
                help/info_hex.html,
                help/info_kram.html,
                help/info_nim.html,
                help/info_reversi.html,
                help/info_tictactoe.html,
                help/info_zenix.html,
                help/rules_ataxx.html,
                help/rules_bamp.html,
                help/rules_halma.html,
                help/rules_hex.html,
                help/rules_kram.html,
                help/rules_nim.html,
                help/rules_reversi.html,
                help/rules_tictactoe.html,
                help/rules_zenix.html

Executable gebop
  Build-Depends:
                array     >= 0.4  && < 0.6,
                base      >= 4.5  && < 4.8, 
                directory >= 1.1  && < 1.3,
                random    >= 1.0  && < 1.1,
                wx        >= 0.11,
                wxcore    >= 0.11

  Main-Is:      Main.hs
  GHC-Options:  -Wall -optc-static-libgcc

-- The following can only work, when GeBoP stops printing trace data:
--  if os(mingw32)
--    GHC-Options: "-optl-mwindows"
~~~~

**Comment by ttuegel** [comment] 2015-04-24 15:03
Duplicate of #1127.

**Closed by ttuegel** 2015-04-24 15:03 UTC
