### ISSUE TITLE
cabal update tells me to "cabal install cabal-install" which fails

### ISSUE THREAD

**Issue by Brrrknee** [haskell/cabal#2509] opened 2015-03-29 06:55 UTC
*I check the status of cabal
C:\WINDOWS\system32>cabal update
Downloading the latest package list from hackage.haskell.org
Note: there is a new version of cabal-install available.
To upgrade, run: cabal install cabal-install

C:\WINDOWS\system32>cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library

*I run "cabal install cabal-install" and get
C:\WINDOWS\system32>cabal install cabal-install
Resolving dependencies...
Downloading Cabal-1.22.2.0...
Configuring Cabal-1.22.2.0...
Building Cabal-1.22.2.0...
Installed Cabal-1.22.2.0
Downloading cabal-install-1.22.2.0...
Configuring cabal-install-1.22.2.0...
Failed to install cabal-install-1.22.2.0
... error is 

Configuring cabal-install-1.22.2.0...
setup-Cabal-1.18.1.3-x86_64-windows-ghc-7.8.3.exe: does not exist
cabal: Error: some packages failed to install:
cabal-install-1.22.2.0 failed during the configure step. The exception was:
ExitFailure 1

the file does exist in the Roaming subdir; why would cabal-install not see it? the log file is in a peer directory /logs ...
![image](https://cloud.githubusercontent.com/assets/11205856/6884456/3c2dce34-d5b9-11e4-963b-74abae396e92.png)

**Comment by jebramwell** [comment] 2015-03-31 17:17
some searching turned up a solution.  You need to rearrange your PATH environment variable so that the mingw path is at the beginning.  The real issue has something to do with other paths with mingw- or cygwin- in them.  Either way I rearranged by PATH variable, logged off an back in then the cabal install cabal-install ran without error.  However it seems to not change the version that is actually used since cabal --version still returns 1.18.1.3.

**Comment by 23Skidoo** [comment] 2015-03-31 17:21
Known issue. We removed this message because people kept having PATH problem.

**Comment by 23Skidoo** [comment] 2015-03-31 17:23
Oops, I've mistaken this for another bug.

**Comment by 23Skidoo** [comment] 2015-03-31 17:25
> However it seems to not change the version that is actually used since cabal --version still returns 1.18.1.3. 

You need to edit `PATH` again and put the location where the newly installed `cabal-install` exe is (`%APPDATA%/cabal/bin`) at the front.

**Comment by 23Skidoo** [comment] 2015-03-31 17:30
> You need to rearrange your PATH environment variable so that the mingw path is at the beginning. The real issue has something to do with other paths with mingw- or cygwin- in them.

If this fixes it, then this seems to be a duplicate of #1528, which was fixed long ago. HP should use a more recent  `cabal-install` version.

**Comment by 23Skidoo** [comment] 2015-03-31 17:32
Yes, it looks like that fix is not on the 1.18 branch.

**Closed by 23Skidoo** 2015-03-31 17:32 UTC
Labels: duplicate

**Comment by Brrrknee** [comment] 2015-03-31 18:35
thanks for the path info.  from the path variables, it seems that the cabal is updating the **personal** environment vars, and Haskell-Platform updated the **system** vars. 

Personal has, at the front:
<code>C:\Users\Bern\AppData\Roaming\cabal\bin;</code>
while these are at the end:
<code>c:\dev-CPP\bin;
C:\Users\Bern\AppData\Roaming\npm</code>

while HP put these at front of system path, 
<code>C:\Program Files\Haskell\bin;
C:\Program Files\Haskell Platform\2014.2.0.0\lib\extralibs\bin;
C:\Program Files\Haskell Platform\2014.2.0.0\bin;
</code>
and this as the last: 
<code>C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin</code>

which (or both) of these needs to be changed, just the system/mingw ?

**Comment by 23Skidoo** [comment] 2015-03-31 23:34
You need to make sure that the default `gcc` comes from `C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin`.
