### ISSUE TITLE
cabal sdist runs alex and happy on the maintainers machine

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1685] opened 2014-02-14 06:44 UTC
cabal sdist runs alex and happy on the maintainers machine, and I think that any `.y` `.x` files should be processed in the client users side. Otherwise, when a breaking change happens to alex and happy and associated GHC versions, like 7.8, every lib maintainer which has a lib using  alex and happy have to prepare a fresh sdist using a newer alex and happy, (they have to do this even if nothing in the code has otherwise changed!!!)

I've hit this with pandoc jgm/pandoc#1136
and others have it it with language-c haskell/c2hs#64#issuecomment-35059925 (which seems to be unmaintained)

**Comment by ttuegel** [comment] 2015-02-28 04:49
Duplicate of #130 (literally the oldest issue).

**Closed by ttuegel** 2015-02-28 04:49 UTC
Labels: duplicate
