### ISSUE TITLE
Cabal unnecessarily requires configuration of unused packages in a project

### ISSUE THREAD

**Issue by expipiplus1** [haskell/cabal#6639] opened 2020-04-02 08:53 UTC
**Describe the bug**

Sometimes cabal unnecessarily wants to configure other packages in a project when they are not required by the command being run.

**To Reproduce**

- Create a cabal project with a package, `myPackage`, in `./.` and another package, `myBrokenPackage`, in `./myBrokenPackage`
  - Make sure that `myBrokenPackage` can't be configured for some reason
  - Make sure that `myPackage` does not depend on `myBrokenPackage` 
  - Add these packages to `cabal.project`
- run `cabal repl myPackage`
- Observe that cabal does not enter a repl because `myBrokenPackage` is unable to be configured
- Remove the reference to `myBrokenPackage` in `cabal.project`
- Observe that `cabal repl myPackage` is successful

**Expected behavior**

I would expect cabal to not try to configure `myBrokenPackage` and not fail to run commands which do not depend on `myBrokenPackage`.

**System information**

```
 $ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library

 $ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.2
```

**Comment by phadej** [comment] 2020-04-02 08:55
The `optional-packages: */*.cabal` is there in the default `cabal.project.`

"Fixing" this would be change of behavior. Ping @hvr and @dcoutts

**Comment by expipiplus1** [comment] 2020-04-02 09:05
@phadej sorry, but I'm not sure what you mean by optional-packages. Putting `myBrokenPackage` in `optional-packages` doesn't work, exactly as described here https://github.com/haskell/cabal/issues/4712

**Comment by phadej** [comment] 2020-04-02 09:27
I understood wrong. You want `myBrokenPackage` to be in the `packages: ...` of your `cabal.project`, but be omitted when it's not required?

This is difficult and probably won't be supported. We ask for all packages to be in the install plan to make it *stable*, i.e. not cause reconfiguration (e.g. picking different dependencies) when you run different commands.

There is an issue to support conditionals in `cabal.project`, so you could have one `cabal.project` for different GHCs (if all packages don't work with all GHCs you work with) or operating systems. Until then, one could use different project files and `--project-file=` option to pick different ones (it's ok for scripts)

**Comment by expipiplus1** [comment] 2020-04-02 09:43
> I understood wrong. You want `myBrokenPackage` to be in the `packages: ...` of your `cabal.project`, but be omitted when it's not required?

Exactly. But perhaps more loosely I'd be happy for it to be omitted if it's not required *and* not able to be configured.

> This is difficult and probably won't be supported. We ask for all packages to be in the install plan to make it _stable_, i.e. not cause reconfiguration (e.g. picking different dependencies) when you run different commands.

Sure, I suppose that makes sense, although I wonder if there's some weaker notion of stability which would work here, or if there could be some option to allow my desired behavior.

This is by no means a pressing issue, just a nit. It feels like one of those situations where "computer says no" and there's a very mechanical solution.

> There is an issue to support conditionals in `cabal.project`, so you could have one `cabal.project` for different GHCs (if all packages don't work with all GHCs you work with) or operating systems. Until then, one could use different project files and `--project-file=` option to pick different ones (it's ok for scripts)

Not sure that will work for my particular case, where I just don't have the necessary packages installed to build `myBrokenPackage`.

**Comment by phadej** [comment] 2020-04-02 10:12
> Not sure that will work for my particular case, where I just don't have the necessary packages installed to build myBrokenPackage.

I don't understand that? What you mean?

**Comment by expipiplus1** [comment] 2020-04-02 11:06
In my specific case I get this error: 

```
 $ cabal repl
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: myBrokenPackage-0.0.0 (user goal)
[__1] unknown package: xeno (dependency of myBrokenPackage)
[__1] fail (backjumping, conflict set: myBrokenPackage, xeno)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: myBrokenPackage, xeno
```

Perhaps I should have used the work `dependency` instead of `package` and `resolving dependencies` instead of `configuring`

**Comment by phadej** [comment] 2020-04-02 14:24
Why you don't have `hackage.haskell.org` repository setting? It looks like you have some very special setup (Nix?), in which case I'm not sure anymore if the problem is `cabal`s or that setups.

I'd suggest just removing `myBrokenPackage` from `cabal.project` - there's no way you can make it work without modifying an environment too.

**Comment by expipiplus1** [comment] 2020-04-02 14:34
> Why you don't have `hackage.haskell.org` repository setting? It looks like you have some very special setup (Nix?), in which case I'm not sure anymore if the problem is `cabal`s or that setups.

I am provisioning my packages with Nix here, although it's not inconceivable that this might happen while using packages not on Hackage.

> I'd suggest just removing `myBrokenPackage` from `cabal.project` - there's no way you can make it work without modifying an environment too.

That's exactly what I meant by the "mechanical solution" earlier. It sounds like it might be best to stick with this fix for now unless there's an easy-to-implement option for enabling the behavior I was expecting in the cards.

**Comment by phadej** [comment] 2020-04-02 14:46
I don't think there is a simple solution.

Changing behavior so solving is not "greedy" for all packages, i.e. require all specified packages to be present in the install plan will be confusing in other use cases. There is already a confusion point that tests and benchmarks are not mandatory, therefore `cabal test` might fail with incomprehensible error, unless you do `--enable-tests`, after which you might get your test running, but dependencies rebuilt **or** a proper solver error.

I don't want make that even more if the reason is more convenience. Let's keep `cabal` behavior predicatable.

**Closed by phadej** 2020-04-02 14:46 UTC
