### ISSUE TITLE
postInst hook isn't happening

### ISSUE THREAD

**Issue by DanBurton** [haskell/cabal#2579] opened 2015-05-06 20:46 UTC
Tried `cabal install fay` with `cabal-install-1.20.0.3` and `cabal-install-1.22.3.0`. They ran Fay's `preConf` hook, but not Fay's `postInst` hook. (See: https://github.com/faylang/fay/blob/master/Setup.hs)

**Comment by 23Skidoo** [comment] 2015-05-07 07:41
Duplicate of #1805.

**Closed by 23Skidoo** 2015-05-07 07:41 UTC
Labels: duplicate
