### ISSUE TITLE
Simplify "no version matching constraint" error

### ISSUE THREAD

**Issue by tom-bop** [haskell/cabal#5568] opened 2018-09-06 16:44 UTC
I accidentally tried to depend on a brand-new version of a package from Hackage before `cabal update`ing.

It would be great to get an error like:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
The constraint "mandrill==0.5.3.5" matches no package versions.
Maybe you need to `cabal update`?
```

But I actually got something with a lot more noise than signal:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: schools-server-0.1.0.0 (user goal)
next goal: mandrill (dependency of schools-server-0.1.0.0)
rejecting: mandrill-0.5.3.4, mandrill-0.5.3.3, mandrill-0.5.3.2,
mandrill-0.5.3.1, mandrill-0.5.3.0, mandrill-0.5.2.3, mandrill-0.5.2.2,
mandrill-0.5.2.1, mandrill-0.5.2.0, mandrill-0.5.1.0, mandrill-0.5.0.0,
mandrill-0.4.1.0, mandrill-0.4.0.0, mandrill-0.3.0.0, mandrill-0.2.2.1,
mandrill-0.2.2.0, mandrill-0.2.1.0, mandrill-0.2.0.0, mandrill-0.1.1.0,
mandrill-0.1.0.2, mandrill-0.1.0.1, mandrill-0.1.0.0 (conflict: schools-server
=> mandrill==0.5.3.5)
Dependency tree exhaustively searched.
```

**Comment by hvr** [comment] 2018-09-06 17:05
cc @grayjay

**Comment by grayjay** [comment] 2018-09-08 05:41
This is a duplicate of #4251.  I think the part of the message that rejects mandrill should be simplified like you suggested, but the message should also continue to mention the package that depends on mandrill, in case its constraint is incorrect.

**Comment by grayjay** [comment] 2018-09-14 04:07
Duplicate of #4251

**Closed by grayjay** 2018-09-14 04:07 UTC
Labels: cabal-install: solver, type: enhancement
