### ISSUE TITLE
cabal new-repl doesn't run cabal new-build, triggers linker failure/error

### ISSUE THREAD

**Issue by EleanorWhite** [haskell/cabal#3673] opened 2016-08-06 17:25 UTC
When trying out using cabal new-repl with a checkout / clone of the following repo
https://github.com/cartazio/ralist/commit/8644f1003a925b31bc88b7a59163979161713bf9
I get the error 
```
$ cabal new-repl
Resolving dependencies...
In order, the following will be built (use -v for more details):
ralist-0.1.0.0
Configuring ralist-0.1.0.0...
cabal: '/opt/ghc/8.0.1/bin/ghc' exited with an error:
<command line>: Failed to load interface for ‘Data.RAList’
Perhaps you meant
Data.List (from base-4.9.0.0)
Data.OldList
Use -v to see a list of the files searched for.
```

if I run cabal new-build first theres no problem 

```
> cabal new-build
In order, the following will be built (use -v for more details):
ralist-0.1.0.0
Preprocessing library ralist-0.1.0.0...
[1 of 1] Compiling Data.RAList      ( Data/RAList.hs, /home/nwhite/ralist-test-learn/dist-newstyle/build/ralist-0.1.0.0/build/Data/RAList.o )
[1 of 1] Compiling Data.RAList      ( Data/RAList.hs, ~/ralist-test-learn/dist-newstyle/build/ralist-0.1.0.0/build/Data/RAList.p_o )
Creating package registration file:
~/ralist-test-learn/dist-newstyle/tmp/package-registration-16816927771714636915
 ~/ralist-test-learn> cabal new-repl
In order, the following will be built (use -v for more details):
ralist-0.1.0.0
Preprocessing library ralist-0.1.0.0...
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Data.RAList      ( Data/RAList.hs, interpreted )
Ok, modules loaded: Data.RAList.
*Data.RAList> 

```

**Comment by ezyang** [comment] 2016-08-09 11:12
Confirm I can reproduce on cabal-install-1.24.0.0

**Comment by ezyang** [comment] 2016-08-10 00:31
It looks like this is fixed in HEAD, though I don't know which commit fixed it.

**Comment by ezyang** [comment] 2016-08-11 04:27
Closing for now, because it's fixed in HEAD and there's an easy enough workaround.

**Closed by ezyang** 2016-08-11 04:27 UTC
Labels: component: nix-local-build, type: bug
