### ISSUE TITLE
Could use a better error message when the package simply doesn't exist in the package list

### ISSUE THREAD

**Issue by Rufflewind** [haskell/cabal#4328] opened 2017-02-15 07:12 UTC
I typed `cabal install time-1.8` and forgot to do `cabal update`.  The error message made it *seem* like there was a dependency resolution error, when in fact the real problem is that `time-1.8` is unknown.  I think the resolver should just bail early if one of the `==` constraints leads to something that simply doesn't exist.

```
cabal: Could not resolve dependencies:
next goal: time (user goal)
rejecting: time-1.7.0.1, time-1.7, time-1.6.0.1/installed-1.6...,
time-1.6.0.1, time-1.6, time-1.5.0.1, time-1.5, time-1.4.2, time-1.4.1,
time-1.4.0.2, time-1.4.0.1, time-1.4, time-1.3, time-1.2.0.5, time-1.2.0.4,
time-1.2.0.3, time-1.2.0.2, time-1.2.0.1, time-1.2, time-1.1.4, time-1.1.3,
time-1.1.2.4, time-1.1.2.3, time-1.1.2.2, time-1.1.2.1, time-1.1.2.0, time-1.0
(constraint from user target requires ==1.8)
Dependency tree exhaustively searched.
```

**Comment by ezyang** [comment] 2017-02-16 01:25
In general, the error message here is a bit silly because you're never really interested in all of the versions we rejected when there's an exact bound that failed to be satisfied...

CC @grayjay

**Comment by grayjay** [comment] 2017-02-26 23:06
I can think of two ways to handle this issue:

- Print a warning if any of the constraints don't match any packages before running the solver.  We should still run the solver, because constraints can also be used to prevent cabal from installing specific packages.  We perform a similar check here: https://github.com/haskell/cabal/blob/63ccb88ccace60d973216fc9e1bf406e8a7a055a/cabal-install/Distribution/Client/Configure.hs#L270

- Print a specialized message (and suggest running `update`) every time the solver rejects all versions of a package because they aren't new enough.  I think that we should continue to print all of the rejected versions in the verbose log, because they are useful for debugging.

The second solution is more general, because it would also handle constraints from other packages' `build-depends` fields, as in #4251.

**Comment by ezyang** [comment] 2017-03-07 03:04
Yeah, I like the second solution, it's pretty common to `git pull` but forget to update, and then have a `build-depends` make the solution unsat.

**Comment by grayjay** [comment] 2018-09-08 05:48
Closing as a duplicate of #4251, since the issues are very similar and they could both be solved by simplifying the message when the solver rejects all versions of a package.

**Closed by grayjay** 2018-09-08 05:48 UTC
Labels: cabal-install: solver, type: enhancement
