### ISSUE TITLE
Error executing cabal using msys2 bash due to path case sensitiveness 

### ISSUE THREAD

**Issue by augustss** [haskell/cabal#7400] opened 2021-05-18 23:55 UTC
The documentation at haskell.org/cabal says to do this
```
mkdir myproject && cd myproject
cabal init
cabal run
```

Doing that gives you the error message:

```
Use the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.
```

System:
Windows10, Mingw2
```
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4
```

**Comment by jneira** [comment] 2021-05-19 05:34
I cant reproduce using windows cmd:

```
D:\ws\haskell\issues>mkdir myproject && cd myproject

D:\ws\haskell\issues\myproject>cabal init

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Generating myproject.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

D:\ws\haskell\issues\myproject>cabal run
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - myproject-0.1.0.0 (exe:myproject) (first run)
Configuring executable 'myproject' for myproject-0.1.0.0..
Preprocessing executable 'myproject' for myproject-0.1.0.0..
Building executable 'myproject' for myproject-0.1.0.0..
[1 of 1] Compiling Main             ( app\Main.hs, D:\ws\haskell\issues\myproje
t\dist-newstyle\build\x86_64-windows\ghc-8.8.4\myproject-0.1.0.0\x\myproject\bu
ld\myproject\myproject-tmp\Main.o )
Linking D:\ws\haskell\issues\myproject\dist-newstyle\build\x86_64-windows\ghc-8
8.4\myproject-0.1.0.0\x\myproject\build\myproject\myproject.exe ...
Hello, Haskell!
```

nor within a mysys2 console:

```
user@machine MINGW64 /d/ws/haskell/issues
# mkdir myproject2 && cd myproject2

user@machine MINGW64 /d/ws/haskell/issues/myproject2
# cabal init

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Generating myproject2.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.

user@machine MINGW64 /d/ws/haskell/issues/myproject2
# cabal run
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - myproject2-0.1.0.0 (exe:myproject2) (first run)
Configuring executable 'myproject2' for myproject2-0.1.0.0..
Preprocessing executable 'myproject2' for myproject2-0.1.0.0..
Building executable 'myproject2' for myproject2-0.1.0.0..
[1 of 1] Compiling Main             ( app\Main.hs, D:\ws\haskell\issues\myproject2\dist-newstyle\build\x86_64-windows\ghc-8.8.4\myproject2-0.1.0.0\x\myproject2\build\myproject2\myproject2-tmp\Main.o )
Linking D:\ws\haskell\issues\myproject2\dist-newstyle\build\x86_64-windows\ghc-8.8.4\myproject2-0.1.0.0\x\myproject2\build\myproject2\myproject2.exe ...
Hello, Haskell!
```

maybe you have a cabal config file (.cabal or cabal.project) in any parent directory?

**Comment by augustss** [comment] 2021-05-19 20:46
There is no .cabal nor cabal.project in any parent directory.
Can I run in some way that will provide more information?

**Comment by augustss** [comment] 2021-05-19 20:52
Hmmm, maybe the global cabal config is wrong (~/AppData/Roaming/cabal/config).
Let me experiment.

**Comment by augustss** [comment] 2021-05-19 20:59
I removed the global cabal config.  Same result. :(

```sh
~$ mkdir myproject && cd myproject
myproject$ cabal init
Config file path source is default config file.
Config file C:\Users\lennart.augustsson\AppData\Roaming\cabal\config not
found.
Writing default configuration to
C:\Users\lennart.augustsson\AppData\Roaming\cabal\config
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.RemoteRepo {remoteRepoName = RepoName
"hackage.haskell.org", remoteRepoURI = http://hackage.haskell.org/,
remoteRepoSecure = Just True, remoteRepoRootKeys =
["fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0","1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42","2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3","0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d","51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921"],
remoteRepoKeyThreshold = 3, remoteRepoShouldTryHttps = True}

Guessing dependencies...

Generating LICENSE...
Warning: unknown license type, you must put a copy in LICENSE yourself.
Generating CHANGELOG.md...
Generating app\Main.hs...
Generating myproject.cabal...

Warning: no synopsis given. You should edit the .cabal file and add one.
You may want to edit the .cabal file and add a Description field.
myproject$ cabal run
cabal.exe: No targets given and there is no package in the current directory.
Use the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

myproject$
```

**Comment by augustss** [comment] 2021-05-19 21:03
More findings.  It works in Windows PowerShell, but not in MSYS2.

**Comment by augustss** [comment] 2021-05-19 21:55
I've tracked down the problem.  In cabal-install/Distribution/Client/TargetSelector.hs there is a function isPkgDirCwd trying to compare two file names.  Unfortunately, dir="C:\\Users\\lennart.augustsson\\myproject" and cwd="C:\\users\\lennart.augustsson\\myproject".  So they differ in case on the U/u.  Since file names are case insensitive on Windows these should be equal, but they are not.
Perhaps use System.FilePath.equalFilePaths instead?

**Comment by jasagredo** [comment] 2024-07-18 21:36
This is already the case:
```
compareFilePath
  :: (Applicative m, Monad m)
  => DirActions m
  -> FilePath
  -> FilePath
  -> m Bool
compareFilePath DirActions{..} fp1 fp2
  | equalFilePath fp1 fp2 = pure True -- avoid unnecessary IO if we can match earlier
  | otherwise = do
      c1 <- canonicalizePath fp1
      c2 <- canonicalizePath fp2
      pure $ equalFilePath c1 c2
```

And docs say:
```
equalFilePath :: FilePath -> FilePath -> Bool
Defined in ‘System.FilePath.Windows’ (filepath-1.4.200.1)

Equality of two FILEPATH s. If you call System.Directory.canonicalizePath first this has a much better chance of working. Note that this doesn't follow symlinks or DOSNAM~1s.

Similar to normalise , this does not expand ".." , because of symlinks.

         x == y ==> equalFilePath x y
         normalise x == normalise y ==> equalFilePath x y
         equalFilePath "foo" "foo/"
         not (equalFilePath "/a/../c" "/c")
         not (equalFilePath "foo" "/foo")
Posix:   not (equalFilePath "foo" "FOO")
Windows: equalFilePath "foo" "FOO"
Windows: not (equalFilePath "C:" "C:/")
```

So it will take care of this case. Closing.

**Closed by jasagredo** 2024-07-18 21:36 UTC
Labels: type: bug, platform: windows, attention: pr-welcome
