### ISSUE TITLE
cabal install is producing rather useless error messages

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#1914] opened 2014-06-01 22:05 UTC
Consider this example, and now go figure out what the actual problem is:

```
$ cabal install websockets
Resolving dependencies...
Notice: installing into a sandbox located at /project/.cabal-sandbox
Downloading websockets-0.8.2.3...
Failed to install websockets-0.8.2.3
Last 10 lines of the build log ( /project/.cabal-sandbox/logs/websockets-0.8.2.3.log ):
cabal:
/project/.cabal-sandbox/logs/websockets-0.8.2.3.log:
does not exist
```

**Comment by crockeea** [comment] 2015-02-26 19:10
I think I just got the same behavior:

```
# ~ $ cabal update
Downloading the latest package list from hackage.haskell.org
# ~ $ cabal install hdevtools
Resolving dependencies...
Downloading cmdargs-0.10.12...
Downloading ghc-paths-0.1.0.9...
Failed to install ghc-paths-0.1.0.9
Build log ( ~/.cabal/logs/ghc-paths-0.1.0.9.log ):
cabal: ~/.cabal/logs/ghc-paths-0.1.0.9.log: does not exist
# ~ $ cabal install ghc-paths
Resolving dependencies...
Downloading ghc-paths-0.1.0.9...
Configuring ghc-paths-0.1.0.9...
Building ghc-paths-0.1.0.9...
Installed ghc-paths-0.1.0.9
```

So ghc-paths failed to install, then immediately installed without complaint.

**Comment by tendril** [comment] 2015-04-12 06:48
I encountered this issue; the cause was that packages in the repo-cache were owned by root and not readable by the user account.

Deleting the package from the repo-cache resolved the issue

Improved error reporting would help a great deal.

**Comment by Blaisorblade** [comment] 2015-11-18 13:34
`cabal update` also suffers this problem — it prints "does not exist" on a network failure (in my actual scenario, we needed a proxy but none was set; FWIW, this user suffered this problem for months).
I've fixed the problem thanks to http://www.yesodweb.com/blog/2015/06/cabals-does-not-exist-error-message

So I managed to trigger (a variant of) this error in a simple way — just set a non-existent proxy (I use `http_proxy=http://127.0.0.1`). This might be a bit more convenient to reproduce.

> cabal install -v3 probably produces a better message.
Unfortunately not, in either case. Traces below.

```
$ http_proxy=http://127.0.0.1 cabal update -v3
Downloading the latest package list from hackage.haskell.org
Sending:
GET http://hackage.haskell.org/packages/archive/00-index.tar.gz HTTP/1.1
User-Agent: cabal-install/1.20.0.3 (osx; x86_64)
If-None-Match: "2ed1a621df9edcca3a9f3a9c3a4335c3"
Host: hackage.haskell.org

proxy uri host: 127.0.0.1, port:
Creating new connection to 127.0.0.1
cabal: does not exist
```

```
$ http_proxy=http://127.0.0.1 cabal install -v3 base-orphans
Searching for ghc in path.
Found ghc at /usr/bin/ghc
("/usr/bin/ghc",["--numeric-version"])
/usr/bin/ghc is version 7.8.3
looking for tool ghc-pkg near compiler in /usr/bin
found ghc-pkg in /usr/bin/ghc-pkg
("/usr/bin/ghc-pkg",["--version"])
/usr/bin/ghc-pkg is version 7.8.3
("/usr/bin/ghc",["--supported-languages"])
("/usr/bin/ghc",["--info"])
Reading installed packages...
("/usr/bin/ghc-pkg",["dump","--global","-v0"])
("/usr/bin/ghc-pkg",["dump","--user","-v0"])
("/usr/bin/ghc",["--print-libdir"])
Reading available packages...
Choosing modular solver.
Resolving dependencies...
[__0] trying: base-orphans-0.4.4 (user goal)
[__1] trying: base-4.7.0.1/installed-df2... (dependency of base-orphans-0.4.4)
[__2] trying: rts-1.0/installedbuil... (dependency of base-4.7.0.1/installed-df2...)
[__3] trying: integer-gmp-0.5.1.0/installed-d42... (dependency of base-4.7.0.1/installed-df2...)
[__4] trying: base-orphans-0.4.4:!test
[__5] next goal: ghc-prim (dependency of base-orphans-0.4.4)
[__5] trying: ghc-prim-0.3.1.0/installed-954...
[__6] done
Ready to install base-orphans-0.4.4
Downloading base-orphans-0.4.4...
Sending:
GET
http://hackage.haskell.org/packages/archive/base-orphans/0.4.4/base-orphans-0.4.4.tar.gz
HTTP/1.1
User-Agent: cabal-install/1.20.0.3 (osx; x86_64)
Host: hackage.haskell.org

proxy uri host: 127.0.0.1, port:
Creating new connection to 127.0.0.1
Waiting for install task to finish...
Failed to install base-orphans-0.4.4
Build log ( /Users/pgiarrusso/.cabal/logs/base-orphans-0.4.4.log ):
cabal: /Users/pgiarrusso/.cabal/logs/base-orphans-0.4.4.log: does not exist
```

**Comment by Blaisorblade** [comment] 2016-08-16 19:28
Closing in favor of more "synthetic" #3073.

**Closed by Blaisorblade** 2016-08-16 19:28 UTC
Labels: type: bug
