### ISSUE TITLE
Support for `cabal repl src/Foo/Bar.hs`

### ISSUE THREAD

**Issue by sol** [haskell/cabal#1825] opened 2014-04-29 04:19 UTC
It would be neat if you could specify a source file to `cabal repl`, e.g.

```
cabal repl src/Foo/Bar.hs
```
would result in `cabal repl` passing `src/Foo/Bar.hs` as an argument to `ghci`.

**Comment by ttuegel** [comment] 2015-04-24 00:12
Duplicate of #1793.

**Closed by ttuegel** 2015-04-24 00:12 UTC

**Comment by sol** [comment] 2015-04-24 01:51
For what it's worth, I don't need that anymore.  Generally, I recommend using `cabal exec ghci` instead.

**Comment by eyeinsky** [comment] 2015-05-24 12:52
@sol I apologise for misusing this issue thread, but when doing `cabal exec ghci`, then how do you load the language extensions from the cabal file? `cabal repl` on the other hand does this..

**Comment by sol** [comment] 2015-05-24 13:46
I have a `.ghci` file in the repo (see e.g. https://github.com/hspec/hspec/blob/master/hspec-core/.ghci).  A pretty generic version that works for most projects would be:

```
:set -isrc -itest

-- for generated source files
:set -idist/build/

-- for Paths_<package-name>.hs
:set -idist/build/autogen

:set -optP-includedist/build/autogen/cabal_macros.h
```

In that `.ghci` file you can put language extensions, too, e.g.:

    :set -XOverloadedStrings

But I think it's better style to have language pragmas at the top of individual source files instead.

**Comment by lspitzner** [comment] 2015-05-24 13:56
@eyeinsky i don't think you can. `cabal exec` only exposes the package db, no settings from the cabal file. So currently -unfortunately- `cabal exec ghci` forwards too little information to ghci, and `cabal repl` too much (all the module names).

**Comment by eyeinsky** [comment] 2015-05-24 14:18
Thanks for the replies. Generating the `.ghci` on the fly seems like a way to go now for now. Having `cabal repl` do it would be nicer though..
