### ISSUE TITLE
cabal-install fails to detect .cabal

### ISSUE THREAD

**Issue by YoEight** [haskell/cabal#2441] opened 2015-02-26 08:46 UTC
```
yoeight@rannock cep [master] $ cabal build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal
```

```
yoeight@rannock cep [master] $ cabal configure
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal
```

```
yoeight@rannock cep [master] $ ls
cabal.sandbox.config  castor-stories  cep.cabal  default.nix  examples  gikoo  LICENSE  Setup.hs  src
```

Weird thing is, when I delete `cabal.sandbox.config`, it detects `cep.cabal`. This used to work. I didn't upgrade cabal nor ghc in the process.

cabal-install version 1.20.0.6
using version 1.20.0.3 of the Cabal library 
GHC: 7.8.4
OS: Archlinux (3.18.6-1-ARCH)

**Comment by YoEight** [comment] 2015-02-26 08:56
Note that I can't let my working machine in that's state. So I will clean everything up, and download the Internet. I will not able to provide more useful information.

**Comment by YoEight** [comment] 2015-02-26 08:59
add some verbose output before proceding

```
yoeight@rannock cep [master] $ cabal build -v3
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Using a sandbox located at /home/yoeight/code/project/.cabal-sandbox
Searching for ghc in path.
Found ghc at /home/yoeight/ghc/bin/ghc
("/home/yoeight/ghc/bin/ghc",["--numeric-version"])
/home/yoeight/ghc/bin/ghc is version 7.8.4
looking for tool ghc-pkg near compiler in /home/yoeight/ghc/bin
found ghc-pkg in /home/yoeight/ghc/bin/ghc-pkg
("/home/yoeight/ghc/bin/ghc-pkg",["--version"])
/home/yoeight/ghc/bin/ghc-pkg is version 7.8.4
("/home/yoeight/ghc/bin/ghc",["--supported-languages"])
("/home/yoeight/ghc/bin/ghc",["--info"])
The package database already exists:
/home/yoeight/code/project/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d
Reading available packages...
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal
```

```
yoeight@rannock cep [master] $ cabal configure -v3
Using a sandbox located at /home/yoeight/code/project/.cabal-sandbox
Searching for ghc in path.
Found ghc at /home/yoeight/ghc/bin/ghc
("/home/yoeight/ghc/bin/ghc",["--numeric-version"])
/home/yoeight/ghc/bin/ghc is version 7.8.4
looking for tool ghc-pkg near compiler in /home/yoeight/ghc/bin
found ghc-pkg in /home/yoeight/ghc/bin/ghc-pkg
("/home/yoeight/ghc/bin/ghc-pkg",["--version"])
/home/yoeight/ghc/bin/ghc-pkg is version 7.8.4
("/home/yoeight/ghc/bin/ghc",["--supported-languages"])
("/home/yoeight/ghc/bin/ghc",["--info"])
The package database already exists:
/home/yoeight/code/project/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d
Reading available packages...
cabal: No cabal file found.
Please create a package description file <pkgname>.cabal
```

**Comment by 23Skidoo** [comment] 2015-02-26 11:49
What are the contents of `~/.cabal/config` / `cabal.sandbox.config`?

**Comment by YoEight** [comment] 2015-02-26 13:10
`~/.cabal/config`

```
-- This is the configuration file for the 'cabal' command line tool.

-- The available configuration options are listed below.
-- Some of them have default values listed.

-- Lines (like this one) beginning with '--' are comments.
-- Be careful with spaces and indentation because they are
-- used to indicate layout for nested sections.


-- require-sandbox: False
-- ignore-sandbox: False
remote-repo: hackage.haskell.org:http://hackage.haskell.org/packages/archive
remote-repo-cache: /home/yoeight/.cabal/packages
-- local-repo:
-- logs-dir:
world-file: /home/yoeight/.cabal/world
-- verbose: 1
-- compiler: ghc
-- with-compiler:
-- with-hc-pkg:
-- scratchdir:
-- program-prefix: 
-- program-suffix: 
-- library-vanilla: True
-- library-profiling: False
-- shared:
-- executable-dynamic: False
-- executable-profiling: False
-- optimization: True
-- library-for-ghci: False
-- split-objs: False
-- executable-stripping: True
-- library-stripping: True
-- user-install: True
-- package-db:
-- flags:
-- extra-include-dirs:
-- extra-lib-dirs:
extra-prog-path: /home/yoeight/.cabal/bin
-- tests: False
-- library-coverage: False
-- exact-configuration: False
-- benchmarks: False
-- cabal-lib-version:
-- constraint:
-- preference:
-- solver: choose
-- allow-newer: False
-- documentation: False
-- doc-index-file: $datadir/doc/index.html
-- max-backjumps: 2000
-- reorder-goals: False
-- shadow-installed-packages: False
-- strong-flags: False
-- reinstall: False
-- avoid-reinstalls: False
-- force-reinstalls: False
-- upgrade-dependencies: False
-- root-cmd:
-- symlink-bindir:
build-summary: /home/yoeight/.cabal/logs/build.log
-- build-log:
remote-build-reporting: anonymous
-- one-shot: False
-- run-tests:
jobs: $ncpus
-- username:
-- password:

haddock
  -- keep-temp-files: False
  -- hoogle: False
  -- html: False
  -- html-location:
  -- executables: False
  -- tests: False
  -- benchmarks: False
  -- all:
  -- internal: False
  -- css:
  -- hyperlink-source: False
  -- hscolour-css:
  -- contents-location:

install-dirs user
  -- prefix: /home/yoeight/.cabal
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $arch-$os-$compiler/$pkgid
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $arch-$os-$compiler/$pkgid
  -- docdir: $datadir/doc/$arch-$os-$compiler/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

install-dirs global
  -- prefix: /usr/local
  -- bindir: $prefix/bin
  -- libdir: $prefix/lib
  -- libsubdir: $arch-$os-$compiler/$pkgid
  -- libexecdir: $prefix/libexec
  -- datadir: $prefix/share
  -- datasubdir: $arch-$os-$compiler/$pkgid
  -- docdir: $datadir/doc/$arch-$os-$compiler/$pkgid
  -- htmldir: $docdir/html
  -- haddockdir: $htmldir
  -- sysconfdir: $prefix/etc

program-locations
  -- alex-location:
  -- ar-location:
  -- c2hs-location:
  -- cpphs-location:
  -- ffihugs-location:
  -- gcc-location:
  -- ghc-location:
  -- ghc-pkg-location:
  -- greencard-location:
  -- haddock-location:
  -- happy-location:
  -- haskell-suite-location:
  -- haskell-suite-pkg-location:
  -- hmake-location:
  -- hpc-location:
  -- hsc2hs-location:
  -- hscolour-location:
  -- hugs-location:
  -- jhc-location:
  -- ld-location:
  -- lhc-location:
  -- lhc-pkg-location:
  -- nhc98-location:
  -- pkg-config-location:
  -- strip-location:
  -- tar-location:
  -- uhc-location:

program-default-options
  -- alex-options:
  -- ar-options:
  -- c2hs-options:
  -- cpphs-options:
  -- ffihugs-options:
  -- gcc-options:
  -- ghc-options:
  -- ghc-pkg-options:
  -- greencard-options:
  -- haddock-options:
  -- happy-options:
  -- haskell-suite-options:
  -- haskell-suite-pkg-options:
  -- hmake-options:
  -- hpc-options:
  -- hsc2hs-options:
  -- hscolour-options:
  -- hugs-options:
  -- jhc-options:
  -- ld-options:
  -- lhc-options:
  -- lhc-pkg-options:
  -- nhc98-options:
  -- pkg-config-options:
  -- strip-options:
  -- tar-options:
  -- uhc-options:
```

`cabal.sandbox.config`

```
-- This is a Cabal package environment file.
-- THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY.
-- Please create a 'cabal.config' file in the same directory
-- if you want to change the default settings for this sandbox.


local-repo: /home/yoeight/code/project/.cabal-sandbox/packages
logs-dir: /home/yoeight/code/project/.cabal-sandbox/logs
world-file: /home/yoeight/code/project/.cabal-sandbox/world
user-install: False
package-db: /home/yoeight/code/project/.cabal-sandbox/x86_64-linux-ghc-7.8.4-packages.conf.d
build-summary: /home/yoeight/code/project/.cabal-sandbox/logs/build.log

install-dirs
  prefix: /home/yoeight/code/project/.cabal-sandbox
  bindir: $prefix/bin
  libdir: $prefix/lib
  libsubdir: $arch-$os-$compiler/$pkgid
  libexecdir: $prefix/libexec
  datadir: $prefix/share
  datasubdir: $arch-$os-$compiler/$pkgid
  docdir: $datadir/doc/$arch-$os-$compiler/$pkgid
  htmldir: $docdir/html
  haddockdir: $htmldir
  sysconfdir: $prefix/etc

```

**Comment by erikd** [comment] 2015-03-04 21:21
@YoEight Would it be possible to you to bundle up ( as a tar-gzip or zip file) a minimal set of files that trigger this problem and make it available to the cabal devs?

**Comment by spl** [comment] 2015-03-09 06:17
I ran into this problem, too. Nothing had changed in my `.cabal` file in a long time. If I see it again, I'll try to dig more into identifying the potential problem.

```
cabal-install version 1.20.0.3
using version 1.20.0.1 of the Cabal library
The Glorious Glasgow Haskell Compilation System, version 7.8.3
```

**Comment by bwo** [comment] 2017-03-18 19:43
Another person affected here. It's like it just forgets.

**Comment by amock** [comment] 2019-02-06 19:39
I ran into what seems to be the same issue when trying to install cabal-install 2.4.1.0 on a FreeBSD system.  I installed the ghc 8.6.3 binary from haskell.org/ghc and then ran bootstrap.sh for cabal-install, which failed with `Please create a package description file <pkgname>.cabal`.  I also tried modifying `bootstrap.sh` to use `runghc` instead of compiling `Setup.hs` and that made the install succeed, but the resulting `cabal` command wouldn't work due to trying to create `~/.cabal` and its sub-directories that already exist.  I was able to reproduce on a fresh FreeBSD 12.0 install.

**Comment by jneira** [comment] 2021-07-17 17:01
there is no sandboxes anymore so the initial issue is not reproducible with newer cabal versions
otoh the bootstrap has been rewriter so not sure if the new one will suffer the last comment error
@amock I am gonna close this one, if you have the chance to try the new bootstrap and it has the same issue, please, open a new issue

**Closed by jneira** 2021-07-17 17:01 UTC
Labels: blocked: info-needed, cabal-install: sandbox, type: bug
