### ISSUE TITLE
Getting started instructions contain command that results in error

### ISSUE THREAD

**Issue by TheBicPen** [haskell/cabal#8014] opened 2022-02-24 15:50 UTC
**Describe the bug**
The "getting started" docs contain instructions to run a command that gives an error:
>1.2.1. Initializing the application[¶](https://cabal.readthedocs.io/en/latest/getting-started.html#initializing-the-application)
Start by initialising our myfirstapp project, these instructions work in unix shells and PowerShell (if you’re on Windows).
`cabal init myfirstapp -n`

**To Reproduce**
Following the guide, run:
```
$ cabal init myfirstapp -n
cabal: 'init' doesn't take any extra arguments: myfirstapp
```

**Expected behavior**
Following the "getting started" instructions should not cause an error.

**System information**
 - Ubuntu 20.04 LTS (WSL2)
 - cabal: 3.6.2
 - ghc: 8.10.7

**Comment by fgaz** [comment] 2022-02-24 16:25
You're looking at the instructions for the unreleased master branch, for 3.6 see https://cabal.readthedocs.io/en/3.6/getting-started.html#initializing-the-application

**Comment by TheBicPen** [comment] 2022-02-24 16:31
I got to that page by following the link from https://www.haskell.org/ghcup/install/ so maybe that page should be updated to point to the stable release so new users don't get confused.

**Comment by jneira** [comment] 2022-02-24 16:38
> I got to that page by following the link from https://www.haskell.org/ghcup/install/ so maybe that page should be updated to point to the stable release so new users don't get confused.

is there stable link for read the docs? at least no in https://cabal.readthedocs.io/en/stable/getting-started.html

**Comment by hasufell** [comment] 2022-02-24 17:27
> EDIT: https://cabal.readthedocs.io/ redirects to https://cabal.readthedocs.io/en/3.6/ so it could be used i suppose

That's not a link to the getting started section

**Comment by jneira** [comment] 2022-02-24 17:51
it seems you need tags following strictly semantic versioning to have stable links
https://docs.readthedocs.io/en/stable/versions.html

**Comment by fgaz** [comment] 2022-02-24 18:11
Or we could have a redirect, but then we'd have to remember to update _that_ too

**Comment by jneira** [comment] 2022-02-24 19:18
if we have to add one more thing to the long list of non written steps to do a release, I would go for the stable branch, it could have some value in its own, rtd apart

**Comment by hasufell** [comment] 2022-02-24 19:29
The easiest thing is to not automatically publish to readthedocs from master, but only on actual releases.

**Comment by Mikolaj** [comment] 2022-02-24 20:02
That's a good idea. Our CI already publishes to https://cabal--8010.org.readthedocs.build/en/8010/ so we may point devs and users that want to experiment with master to this address in the README. Then we need to remember to publish to latest on release.

**Comment by Martinsos** [comment] 2022-02-24 21:09
Are there instructions on what to do on release? If it consists of multiple manual steps, it might be best to write them down in one spot and then there is no ambiguity about it, you just follow the instructions and update them if they are lacking.
We are doing this at Wasp at the moment, I don't see any downsides to it: https://github.com/wasp-lang/wasp/tree/main/waspc#typicall-release-process .

**Comment by hasufell** [comment] 2022-02-25 10:17
> Are there instructions on what to do on release? 

https://github.com/haskell/cabal/blob/master/release-checklist.md

**Comment by Mikolaj** [comment] 2022-02-25 10:29
These are ancient. @emilypi promised to publish the instructions she composed when releasing 3.6.0, 3.6.1 and 3.6.2, so it's only a matter of time until they arrive.

**Comment by Martinsos** [comment] 2022-02-25 10:59
> These are ancient. @emilypi promised to publish the instructions she composed when releasing 3.6.0, 3.6.1 and 3.6.2, so it's only a matter of time until they arrive.

That would be great I guess -> then you don't have to worry about how complex the release process is, since it is written down and can be reproduced consistently, and main focus can be put on providing the bets user experience regarding the readthedocs.

**Comment by jneira** [comment] 2022-02-25 11:19
> That's a good idea. Our CI already publishes to https://cabal--8010.org.readthedocs.build/en/8010/ so we may point devs and users that want to experiment with master to this address in the README. Then we need to remember to publish to latest on release.

Not sure, rtd publishes automatically the default branch as latest. I think you can disable it in rtd admin page but imo it will be much less discoverable via prs links. Also it will be less clear what is, well, the latest version, although you can go to the last pr merged (supposing we do not do direct commits on master)

**Comment by fgaz** [comment] 2022-02-25 11:27
Also there probably are a lot of /en/latest links around the web, and we don't want to break them

**Comment by Mikolaj** [comment] 2022-02-25 11:37
We definitely don't want to break them, but to swap the docs at /latest to the 3.6.2 version.

**Comment by jneira** [comment] 2022-02-25 11:43
> but to swap the docs at /latest to the 3.6.2 version.

following rtd defaults (so expected by usres?) /stable would be 3.6.2 and /latest would be master, but we dont have stable.
According to docs the unique way to get stable is doing tags following semantic versioning (which we dont do and i guess dont want to do) os creating a branch named stable

**Comment by hasufell** [comment] 2022-02-25 11:44
> We definitely don't want to break them, but to swap the docs at /latest to the 3.6.2 version.

Just create a semver tag then and let's move on with our lives: `3.6.2.0 -> 3.6.2+0`

**Comment by jneira** [comment] 2022-02-25 11:45
the problem is cabal dont have even 3.6.2.0 but Cabal-3.6.2.0 and cabal-install-3.6.2.0

**Comment by hasufell** [comment] 2022-02-25 11:48
> the problem is cabal dont have even 3.6.2.0 but Cabal-3.6.2.0 and cabal-install-3.6.2.0

There's no problem. Just push the tag.

**Comment by jneira** [comment] 2022-02-25 11:59
sounds good to me, what would be chosen? Cabal or cabal-install (if they are different)? :wink: 
i would say cabal-install but not sure

**Comment by Mikolaj** [comment] 2022-02-25 12:06
I vote for cabal-install.

**Comment by Mikolaj** [comment] 2022-02-25 12:07
Because the docs are mostly about `cabal` the binary, not about the Cabal library and, I'm not sure, probably not a lot about Custom setup and Cabal code for that.

**Comment by hasufell** [comment] 2022-02-25 12:08
I already pushed a tag, but I have no admin rights on RTD. So someone else has to sort that out.

Using my fork on RTD I get a `stable` tag automatically: https://readthedocs.org/projects/cabal-hasufell/versions/

So this is a configuration error.

**Comment by jneira** [comment] 2022-02-25 12:19
i was trying the same and i observed before pushing a new tag rtd tried to use the tag 2.4 for stable (the last tag suitable to?) and the compilation miserably fails:

```

Note: switching to 'origin/2.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 5c7eea01 Merge pull request #5861 from m-renaud/mrenaud-docs-common-in-quickstart
Tiempo del comando: 0s Regresar: 0
git clean -d -f -f
python3.7 -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable
/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/bin/python -m pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.2
cat Cabal/doc/conf.py
/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v4.4.0

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/lib/python3.7/site-packages/sphinx/config.py", line 339, in eval_config_file
    code = compile(f.read(), filename.encode(fs_encoding), 'exec')
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/checkouts/stable/Cabal/doc/conf.py", line 173
    sig = re.sub(ur'<([-a-zA-Z ]+)>', ur'⟨\1⟩', sig)
                                   ^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/lib/python3.7/site-packages/sphinx/application.py", line 209, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/lib/python3.7/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jneira-cabal/envs/stable/lib/python3.7/site-packages/sphinx/config.py", line 343, in eval_config_file
    raise ConfigError(msg % err) from err
sphinx.errors.ConfigError: There is a syntax error in your configuration file: invalid syntax (conf.py, line 173)


Configuration error:
There is a syntax error in your configuration file: invalid syntax (conf.py, line 173) 
```

as hasufell already tried pushing `git tag 3.6.2+0 cabal-install-v3.6.2.0` makes it work

**Comment by jneira** [comment] 2022-02-25 12:38
> So this is a configuration error.

Yeah i guess the stable version is disabled, it seems @Mikolaj is [admin of the cabal rtd project](https://readthedocs.org/profiles/MikolajKonarski/): would you mind to take a look? thanks!

**Comment by Mikolaj** [comment] 2022-02-25 12:44
Oh, am I? I enabled 'stable'. Please let me know what to do next.

**Closed** 2022-02-25 12:51 UTC
Labels: type: enhancement, type: user-question, documentation, re: readthedocs

**Comment by jneira** [comment] 2022-02-25 13:15
lovely, thanks @Mikolaj , i think still we should:
* change ghcup to point to stable
* remember to push a semver compliant tag in each release :wink:

**Comment by Mikolaj** [comment] 2022-02-25 13:43
Wow, and the commit hash reporte in the admin rtd panel for `stable` even agrees with @hasufell's tag: 2eeabab7

**Comment by Mikolaj** [comment] 2022-02-25 13:46
> * change ghcup to point to stable

It seems to still point to latest. @hasufell?

**Comment by hasufell** [comment] 2022-02-25 14:27
> It seems to still point to latest. @hasufell?

It doesn't

**Comment by Mikolaj** [comment] 2022-02-25 14:35
I mean the [cabal-install](https://cabal.readthedocs.io/en/latest/) link here: https://www.haskell.org/ghcup/install/

**Comment by hasufell** [comment] 2022-02-25 15:08
> I mean the [cabal-install](https://cabal.readthedocs.io/en/latest/) link here: https://www.haskell.org/ghcup/install/

Fixed. I also changed the links for HLS and stack. It appers RTD isn't that scrict with semantic versioning as it claims, since HLS 1.6.1.1 tag is accepted (that's not valid semver).

So maybe 3.6.2.0 is fine for cabal tags too.

**Comment by Mikolaj** [comment] 2022-02-25 15:33
Confirmed the fix to the link I provided. 

Thanks. Good to know.
