### ISSUE TITLE
cabal-install head ignores sigint (ctr+c) but responds to sigsusp (ctrl+z), sometimes (don't have a reproducable test case yet)

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#1345] opened 2013-05-23 06:07 UTC
i'm testing out using cabal-install head (head as of now, so hash 2f32275413f786e315e7076fa2d8e366c02dd9a4) sandboxing, and i've had an instance of ctrl+c not killing cabal in a sandboxed build, but ctrl+z suspending it correctly

 (still trying to figure out how to reproduce this problem though, so this may be a useless ticket if i cant reproduce )

**Comment by gracjan** [comment] 2015-03-02 10:56
Yes, #1448 strikes again. This is super annoying. How come that it returned?

**Comment by jsl** [comment] 2015-03-03 04:03
I just tested this issue with Cabal 1.22.0. Results:

* Ctrl-C does kill `cabal install --only-dependencies --enable-tests`, so that is **working correctly**
* Ctrl-C does kill `cabal build`, so that is **working correctly**

@gracjan I responded to your comment on #1448. It would help to get some more info on that ticket  since I can't reproduce the issue you mentioned with a current cabal. 

In the meantime, @cartazio it seems like the issue in this ticket has probably been resolved, since I can kill cabal with Ctrl-C during builds and installs on a recent version. Would you mind closing this ticket unless this is something you're still experiencing?

Thanks a lot!

**Comment by 23Skidoo** [comment] 2015-03-03 04:41
It likely depends on the version of `process` `cabal-install` was compiled with. Old versions don't have the `delegate_ctlc` feature, but we still support them.

**Comment by 23Skidoo** [comment] 2015-03-03 04:42
Optimistically closing.

**Closed by 23Skidoo** 2015-03-03 04:42 UTC
