### ISSUE TITLE
build-tool-depends in setup-depends

### ISSUE THREAD

**Issue by nomeata** [haskell/cabal#5540] opened 2018-08-23 16:45 UTC
While trying to use `cabal` to build a project that the author has setup with `stack`, I found myself wanting to add `build-tool-depends` to `setup-depends`:

```
custom-setup
  setup-depends:
      base
    , Cabal
    , containers
    , directory
    , filepath
    , genapply
    , process
  build-tool-depends:
    genapply:genapply
```

but Cabal seems to not know how to handle `build-tool-depends` in `custom-setup`. Is that intentional, or an oversight?

**Comment by hvr** [comment] 2018-08-23 17:02
Duplicate of #4648

**Comment by 23Skidoo** [comment] 2018-08-29 15:57
Closing in favour of #4648.

**Closed** 2018-08-29 15:57 UTC
Labels: resolution: duplicate
