### ISSUE TITLE
Foreign libraries can't be built on m1; misleading message

### ISSUE THREAD

**Issue by vmchale** [haskell/cabal#7837] opened 2021-11-25 14:06 UTC
**Describe the bug**

Foreign libraries don't build on mac aarch64.

**To Reproduce**

```
cabal get -s perceptual-hash
cd perceptual-hash
cabal v2-build
cabal-3.6.2.0: Cannot build some foreign libraries: Building foreign libraries
is currently only supported on OSX, Linux and Windows
```

**Expected behavior**

Foreign libraries would build, or if not, it would give a better message.

**System information**
 - darwin, m1 (aarch64)
 - ghc 9.2.1, cabal 3.6.2.0

**Comment by Mikolaj** [comment] 2021-11-25 14:33
I think it's this one: #7763? Should be fixed at some not too distant point...

**Comment by Mikolaj** [comment] 2021-11-29 09:50
Duplicate of #7763

**Closed** 2022-02-15 20:54 UTC
Labels: resolution: duplicate
