### ISSUE TITLE
cabal install <packages> fails with ghc error

### ISSUE THREAD

**Issue by drewboardman** [haskell/cabal#6521] opened 2020-02-02 16:54 UTC
**Describe the bug**
Cabal fails to install packages with `ghc` error.

**To Reproduce**

**NOTE**: This also fails on `cabal new-install snap snap-templates`

```
$ cabal install snap snap-templates
...
...
...
cabal: Failed to build distributive-0.6.1 (which is required by snap-1.1.2.0).
The failure occurred during the configure step. The exception was:
dieVerbatim: user error (cabal: '/home/drew/.ghcup/bin/ghc' exited with an
error:

/tmp/cabal-install.-25560/dist-newstyle/tmp/src-25562/distributive-0.6.1/dist/setup/setup.hs:12:1:
error:
Could not find module ‘Distribution.Extra.Doctest’
There are files missing in the ‘cabal-doctest-1.0.8’ package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
|
12 | import Distribution.Extra.Doctest ( defaultMainWithDoctests )
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)

drew@pizza ~/code $ ghc-pkg -v0 check
drew@pizza ~/code $ ghc-pkg -v check
GHC package manager version 8.6.5
Timestamp 2020-02-01 19:08:08.967753776 UTC for /home/drew/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/package.conf.d/package.cache
using cache: /home/drew/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/package.conf.d/package.cache
db stack: ["/home/drew/.ghc/x86_64-linux-8.6.5/package.conf.d","/home/drew/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/package.conf.d"]
flag db stack: ["/home/drew/.ghc/x86_64-linux-8.6.5/package.conf.d","/home/drew/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/package.conf.d"]
```

**System information**
 - Operating system: Arch Linux kernel version 5.4
```
$ uname -a
Linux pizza 5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux
```
 - `cabal`, `ghc` versions

```
$ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```

**Additional context**
On arch linux, there is a linkage issue - so my `~/.cabal/config` has the following added to it:

```haskell
library-vanilla: False
shared: True
executable-dynamic: True
 ghc-options:
   -dynamic
```

**Comment by emlautarom1** [comment] 2020-03-29 04:00
Cannot reproduce with `cabal 3.0.0.0` and `ghc v8.8.3`

Try running `cabal update`. Also, there are currently some dependency conflicts between `snap` and `snap-templates` regarding `hashable`:

```
cabal.exe: Could not resolve dependencies:
[__0] trying: snap-1.1.3.0 (user goal)
[__1] trying: hashable-1.3.0.0 (dependency of snap)
[__2] trying: base-4.13.0.0/installed-4.1... (dependency of snap)
[__3] next goal: snap-templates (user goal)
[__3] rejecting: snap-templates-1.0.0.2, snap-templates-1.0.0.1,
snap-templates-1.0.0.0 (conflict: hashable==1.3.0.0, snap-templates =>
hashable(>=1.1 && <1.2) || (>=1.2.0.6 && <1.3))
[__3] fail (backjumping, conflict set: hashable, snap-templates)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, hashable, snap, snap-templates
Try running with --minimize-conflict-set to improve the error message.
```

**TL:DR:** Try with `cabal update` & `cabal install snap snap-templates --allow-newer`

**Comment by yssource** [comment] 2020-04-04 04:12
The same error happens to me also.

```
library-vanilla: False
shared: True
executable-dynamic: True
 ghc-options:
   -dynamic
```

```
cabal: Failed to build distributive-0.6.1 (which is required by snap-1.1.3.0).
The failure occurred during the configure step. The exception was:
dieVerbatim: user error (cabal: '/home/jimmy/.ghcup/bin/ghc' exited with an
error:

/tmp/cabal-install.-228795/dist-newstyle/tmp/src-228796/distributive-0.6.1/dist/setup/setup.hs:12:1:
error:
Could not find module ‘Distribution.Extra.Doctest’
There are files missing in the ‘cabal-doctest-1.0.8’ package,
try running 'ghc-pkg check'.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
12 | import Distribution.Extra.Doctest ( defaultMainWithDoctests )
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
Failed to build entropy-0.4.1.5 (which is required by snap-1.1.3.0). The
failure occurred during the configure step. The exception was:
dieVerbatim: user error (cabal: '/home/jimmy/.ghcup/bin/ghc' exited with an
error:
ld.lld: error: can't create dynamic relocation R_X86_64_32S against symbol:
stg_bh_upd_frame_info in readonly segment; recompile object files with -fPIC
or pass '-Wl,-z,notext' to allow text relocations in the output
```

**Comment by panaC** [comment] 2021-02-05 18:04
same error for me too

```
library-vanilla: False
shared: True
executable-dynamic: True
 ghc-options:
   -dynamic
```
```
cabal: Failed to build bytes-0.17 (which is required by exe:gol from
gol-0.1.0.0). The failure occurred during the configure step. The exception
was:
dieVerbatim: user error (cabal: '/usr/bin/ghc' exited with an error:

/home/pierre/Documents/haskell/gol/dist-newstyle/tmp/src-14536/bytes-0.17/dist/setup/setup.hs:4:8:
error:
Could not find module ‘Prelude’
There are files missing in the ‘base-4.14.1.0’ package,
try running 'ghc-pkg check'.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
4 | module Main (main) where
| ^^^^

/home/pierre/Documents/haskell/gol/dist-newstyle/tmp/src-14536/bytes-0.17/dist/setup/setup.hs:12:1:
error:
Could not find module ‘Distribution.Extra.Doctest’
There are files missing in the ‘cabal-doctest-1.0.8’ package,
try running 'ghc-pkg check'.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
12 | import Distribution.Extra.Doctest ( defaultMainWithDoctests )
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
)
```

```
$ uname -a
Linux 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
```
```
$ cabal --version 
cabal-install version 3.2.0.0
compiled using version 3.2.1.0 of the Cabal library 
$ ghc --version   
The Glorious Glasgow Haskell Compilation System, version 8.10.3
````

do you have an idea ?

**Comment by fgaz** [comment] 2021-02-05 19:27
This is due to the way arch linux packages Haskell stuff. Look at the arch wiki, there should be some info there.

**Comment by fgaz** [comment] 2021-02-05 21:48
To elaborate, Arch Linux Haskell packages are linked dynamically, which makes some sense from an user's perspective, but requires some arrangements from developers.

Relevant Arch Wiki page: https://wiki.archlinux.org/index.php/Haskell
Particularly the sections [Configuring Cabal for dynamic linking](https://wiki.archlinux.org/index.php/Haskell#Configuring_Cabal_for_dynamic_linking), [Alternate installations](https://wiki.archlinux.org/index.php/Haskell#Alternate_installations), [Static linking](https://wiki.archlinux.org/index.php/Haskell#Static_linking)

I'll close this since that's the probable cause. If not, please leave a comment

**Closed by fgaz** 2021-02-05 21:48 UTC

**Comment by panaC** [comment] 2021-02-06 07:17
many thanks

it works with `cabal build --ghc-options=-dynamic`
