### ISSUE TITLE
"cabal install --reinstall" does not reinstall

### ISSUE THREAD

**Issue by hasufell** [haskell/cabal#3304] opened 2016-04-09 20:15 UTC
This is in a sandbox with the following cabal versions:
```
# cabal --version
cabal-install version 1.22.8.0
using version 1.22.5.0 of the Cabal library 
```

Failure:
```
# cabal configure --enable-library-profiling --enable-executable-profiling --enable-benchmarks
Resolving dependencies...
Configuring hsfm-0.0.0.1...
# cabal install --only-dependencies --enable-library-profiling --reinstall 
Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
```

The project cabal file is located here: https://github.com/hasufell/hsfm/blob/master/hsfm.cabal

It seems to be a mixture of improper error messages and hidden failures. There __is__ `--reinstall`. Very annoying.

**Comment by 23Skidoo** [comment] 2016-04-11 20:17
Duplicate of #1175.

**Closed by 23Skidoo** 2016-04-11 20:17 UTC
Labels: duplicate
