### ISSUE TITLE
Improper detection/reporting of illegal module name

### ISSUE THREAD

**Issue by Lokathor** [haskell/cabal#4177] opened 2016-12-19 05:45 UTC
Using this code:
https://github.com/Lokathor/galaxy-break/tree/b66d6dfb58f63167b6006cdb5b18cf85f87c54ad

I tried to have a compiler flag named Win32 that determined if `Control.Console` imported `Control.Console.Win32` or some other module. However, the CPP eats up the Win32 part of the import and then the import is left trying to import `Control.Console.` (note the trailing dot), which is an invalid module name. However, instead of reporting the name as invalid, it just silently converts the import to `Control.Console` (without the dot) and then says that the module is trying to import itself in the error message.

It was also requested that I include that cabal should hopefully do the same sanity check that GHC does: that the file name matches the module name, which would have caught this.

**Comment by MarcelineVQ** [comment] 2016-12-19 06:23
The -DWin32 CPP flag shouldn't eat up the name entirely, but replace it with 1 since it's set or 0 when it isn't. CPP is affected but this can be reproduced with it off entirely. 

It is true that an . with nothing after it will also display the behavior in op's issue though:
`import Control.Console.` or `import Control.Console.1` will reproduce it without -XCPP

Missing text after the . or any number after the . behaves as shown above, truncation of the import declaration. Letters or symbols after the dot will result in expected parse errors. Minimal examples:
```
module Lib where
import Lib.3213213
```
```
module Lib where
import Lib.
```

**Comment by ezyang** [comment] 2016-12-19 16:23
@Lokathor, @MarcelineVQ I'm sorry but I don't quite understand. It looks like it shouldn't be too hard to make a minimal test case: could you post one and steps to reproduce the problem, and what the expected behavior is?

**Comment by MarcelineVQ** [comment] 2016-12-19 22:22
This doesn't look like a Cabal issue after all:
`echo "module Lib where import Lib. " > test.hs && ghc test.hs`
`echo "module Lib where import Lib.123 " > test.hs && ghc test.hs`
Or for Lokathor's problem:
`echo "{-# LANGUAGE CPP #-} module Lib where import Lib.Foo " > test.hs && ghc test.hs -DFoo`

Will all result in:
```
Module imports form a cycle:
  module ‘Lib’ (test.hs) imports itself
```
I would expect a trailing . `import Lib.` or numbers after a . `import Lib.123` to be a parse error as they don't follow modid lexeme rules.
There doesn't seem to be a related trac ticket for this so I'll go ahead and put one together.

**Comment by 23Skidoo** [comment] 2017-10-15 12:42
Closing as a GHC issue. Is there a GHC Trac ticket?

**Closed by 23Skidoo** 2017-10-15 12:42 UTC
Labels: Cabal: cmd/build, resolution: invalid, type: bug
