### ISSUE TITLE
Add a warning for unknown modules that were compiled

### ISSUE THREAD

**Issue by bos** [haskell/cabal#381] opened 2012-05-24 05:20 UTC
(Imported from [Trac #388](http://hackage.haskell.org/trac/hackage/ticket/388), reported by jcpetruzza on 2008-11-01)

Let's say you are working on a new version of a library; you add a new internal (i.e. non-exposed) module but you forget to update the package description. You locally test your changes, everything works fine so you install it. Now, since the new module is not listed in <tt>other-modules</tt> it will not be included in the final library. Therefore, when you try to use it you get rather cryptic linker errors. It can take a while until you realize where the problem is coming from.

The proposal is to look, during build, for compiled modules under the <tt>dist</tt> directory that are not included in the final library and warn the user about  their presence.

**Comment by ttuegel** [comment] 2015-04-23 14:54
Duplicate of #1746.

**Closed by ttuegel** 2015-04-23 14:54 UTC
Labels: enhancement, library
