### ISSUE TITLE
Warning: The package has an extraneous version range for a dependency on an internal library: containers-tests -any && ==0, containers-tests -any && ==0...

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#6012] opened 2019-04-24 07:16 UTC

**Comment by 23Skidoo** [comment] 2019-04-25 07:17
I think we already have a ticket for this.

**Comment by 23Skidoo** [comment] 2019-04-26 17:28
Closing as a duplicate of #5119.

**Closed by 23Skidoo** 2019-04-26 17:28 UTC
Labels: resolution: duplicate
