### ISSUE TITLE
Please give us an option to tell cabal sdist explicitly that -O2 is okay

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#2796] opened 2015-08-27 05:01 UTC
There currently doesn't seem to be a way to tell `cabal sdist` to trust me about -O2.

This means it _always_ returns 1.

Since it cries wolf I can't use it in automated tools as part of my testing process to validate more interesting parts of the tar ball are all present.

**Comment by 23Skidoo** [comment] 2015-08-27 05:18
You mean `ghc-options: -O2`? IIUC, it's already supposed to work this way.

```
       -- | Like PackageDistSuspicious but will only display warnings
       -- rather than causing abnormal exit.
     | PackageDistSuspiciousWarn { explanation :: String }
```

So looks like a bug.

**Comment by sznurek** [comment] 2015-10-03 14:05
@ekmett Did you mean `cabal check` instead of `cabal sdist`? On my machine `cabal sdist` does not give any warnings. Anyway, `cabal check` ends with exit code 1, listing only `-O2` warning.

@23Skidoo I am happy to work on this issue. Should I be assigned to it?

**Comment by 23Skidoo** [comment] 2015-10-04 22:21
Closing, since this apparently can't be reproduced.

@ekmett Feel free to reopen if you can provide a failing test case.

**Closed by 23Skidoo** 2015-10-04 22:21 UTC
Labels: bug
