### ISSUE TITLE
Allow cabal-install's package build location to be set

### ISSUE THREAD

**Issue by bos** [haskell/cabal#661] opened 2012-05-24 05:41 UTC
(Imported from [Trac #669](http://hackage.haskell.org/trac/hackage/ticket/669), reported by @dcoutts on 2010-04-29)

Apparently some systems mount /tmp such that one cannot create and run executables. This is clearly problematic for cabal-install because it needs somewhere to build packages.

[http://article.gmane.org/gmane.comp.lang.haskell.cafe/73517](http://article.gmane.org/gmane.comp.lang.haskell.cafe/73517)

It may be useful for cabal-install to have a config setting to specify where to do package builds (for downloaded packages). If not specified this would default to the temp dir as now.

**Comment by ttuegel** [comment] 2015-02-28 04:43
Duplicate of #2422.

**Closed by ttuegel** 2015-02-28 04:43 UTC
Labels: cabal-install, duplicate, enhancement
