### ISSUE TITLE
track installed files to allow uninstall

### ISSUE THREAD

**Issue by bos** [haskell/cabal#227] opened 2012-05-24 05:10 UTC
(Imported from [Trac #234](http://hackage.haskell.org/trac/hackage/ticket/234), reported by @dcoutts on 2008-02-11)

<tt>cabal-install</tt> needs to be able to track all the files it installs so that it'll be possible to uninstall packages.

The copy/install code should be extended to be able to generate a list of files and hashes of files that will be installed. <tt>cabal-install</tt> could use that to write out a manifest file and use that later to allow uninstalling.

One solution might be to restructure the install code to gather the source files that it would install rather than just doing it. Once that list of files is known we can copy them all in one go, and do other things like check for clashing target files and generate manifests etc.

**Comment by BardurArantsson** [comment] 2015-06-25 17:38
Cabal-install is not a package manager. IMO this is a non-goal and the issue should be closed.

(Btw, sandboxes can already serve as a workaround if you really want something that's trivial to remove.)

**Comment by 23Skidoo** [comment] 2015-06-26 15:32
> Cabal-install is not a package manager. IMO this is a non-goal

I don't think there's any deep technical or philosophical reason for not having this feature, it's just that it was never implemented.

**Comment by BardurArantsson** [comment] 2015-08-22 09:57
Even if it were easily or even trivially(!) implementable... this is not the remit of not-a-package-manager, IMO. Also, given lack of activity on this issue, I still suggest closing this issue.

(Anyone is still free to implement this if they want. I just think that having this issue lying around is pure noise.)

**Comment by mietek** [comment] 2015-08-23 00:02
I disagree both with your premise and your conclusion.  Implementing this seems necessary to solve issues such as #220, #779, and #1896.

**Comment by BardurArantsson** [comment] 2015-08-28 05:45
Can you please explain how this is necessary for implementing any of the issues you mentioned? (This issue is about tracking *files* -- or at least originally was about that.)

**Comment by BardurArantsson** [comment] 2015-08-28 05:49
Also... what, specifically, do you disagree with?

**Comment by fgaz** [comment] 2021-01-14 10:49
@phadej duplicate of / overlapping with #3333?

**Comment by gbaz** [comment] 2021-08-28 04:49
closing on that basis

**Closed by gbaz** 2021-08-28 04:49 UTC
Labels: type: enhancement, cabal-install: other
