### ISSUE TITLE
--allow-newer with Setup.hs configure?

### ISSUE THREAD

**Issue by adamse** [haskell/cabal#7859] opened 2021-12-08 10:44 UTC
Docs list `--allow-newer` under flags that [`runhaskell Setup.hs configure` supports][1], but it doesn't seem to actually do anything. The only way I've found to break the bounds with `Setup.hs configure` is to use `--exact-configuration` and specify everything.

[1]: https://cabal.readthedocs.io/en/3.6/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-allow-newer

**Comment by fgaz** [comment] 2021-12-08 11:14
Duplicate of #5407. See also #4203 #3581 #4527.

We do need to update the docs though...

**Comment by adamse** [comment] 2021-12-08 11:29
Thanks for the history, I imagined it was deliberate. All I want is for the docs to reflect reality so I don't go down the path of trying --allow-newer a third time :)

**Comment by adamse** [comment] 2021-12-08 11:34
It looks like the `--allow-newer` current docs should maybe be moved to be under "cabal-install Commands"?

**Comment by Mikolaj** [comment] 2021-12-08 11:41
Indeed, from the tickets @fgaz mentioned, it looks deliberate. Yes, moving and amending the docs seems a good idea.

**Comment by adamse** [comment] 2021-12-08 11:46
Actually quite a lot of the flags currently documented under Setup.hs seem like they shouldn’t be there.

**Closed** 2021-12-22 13:22 UTC
Labels: documentation, attention: pr-welcome, Cabal: cmd/configure
