### ISSUE TITLE
os conditionals not supported in custom-setup

### ISSUE THREAD

**Issue by joeyh** [haskell/cabal#4852] opened 2017-10-27 18:34 UTC
My Setup.hs needs WIn32 to build on windows. So, I tried adding to its custom-setup stanza:

```
  custom-setup
    Setup-Depends: base (>= 4.5)
  if os(Windows)
    Setup-Depends: Win32
```

cabal fails to parse that:

> 
> 'parseField' called on a non-field. This is possibly a bug in Cabal.
> Please report it to the developers: https://github.com/haskell/cabal/issues/new
> CallStack (from HasCallStack):
>   error, called at ./Distribution/PackageDescription/Utils.hs:21:16 in Cabal-2.0.0.2-B4YxsRmpeLCDyDZ1N9nEz7:Distribution.PackageDescription.Utils- exit 1
> 

cabal-install version 2.0.0.0  
compiled using version 2.0.0.2 of the Cabal library

**Comment by phadej** [comment] 2017-10-27 18:37
The current solution is to abstract custom-setup code into own package.

**Comment by phadej** [comment] 2017-10-27 18:39
... alternatively you could use something like `unix-compat`, it might be good enough for you.

**Comment by joeyh** [comment] 2017-10-27 19:28
Unfortunately, I'm working around a bug in unix-compat with Win32..

-- 
see shy jo

**Comment by 23Skidoo** [comment] 2017-11-03 14:26
@dcoutts, do you think this should be supported? IIRC, the decision to keep the format of `custom-setup` simple was deliberate.

**Comment by grayjay** [comment] 2017-12-04 01:46
I think this is a duplicate of #4286.

**Closed by grayjay** 2017-12-04 01:46 UTC
Labels: cabal-install: stanza/custom-setup, type: discussion, type: enhancement
