### ISSUE TITLE
Add pvp-check command

### ISSUE THREAD

**Issue by tibbe** [haskell/cabal#1826] opened 2014-04-29 13:58 UTC
To alleviate some of the issues people have with the [Package Versioning Policy](http://www.haskell.org/haskellwiki/Package_versioning_policy), we should provide a command to help users bump their versions correctly. Example usage:

```
$ cd network
$ cabal pvp-check http://hackage.haskell.org/package/network-2.5.0.0/network-2.5.0.0.tar.gz
The package version number should be bumped to 2.5.1.0 (minor bump).
The following new functions were added: `foo', `bar'
```

We could combine this with a new .cabal file field, `pvp-version` (where 1.0 is the current PVP), which allows users to specify that they follow the PVP. If this field is set, we could have `cabal check` reject a package if the version or the dependencies aren't specified correctly.

**Comment by ttuegel** [comment] 2015-04-24 00:13
Duplicate of #1703.

**Closed by ttuegel** 2015-04-24 00:13 UTC
