### ISSUE TITLE
v2-upload doesn't exist, but can act stange

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#5779] opened 2018-12-07 20:30 UTC
example from today 

```
14:22:16 ~/W/p/a/vector (remove-weird-pseud-memset|✚1) $ cabal v2-upload dist-newstyle/sdist/vector-0.12.0.2.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.6.2 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (exe:script) (first run)
Configuring executable 'script' for fake-package-0..
Preprocessing executable 'script' for fake-package-0..
Building executable 'script' for fake-package-0..

Main.hs:1:1: error: lexical error at character '\US'
  |
Ѣ$;���Mv�֔�XNsN��(ܿ�)6n�d
_�.��i�q������Q�����������!�9����G������8aO߼i1�س$O/��wW�$����Y�I�ۗ�b6Nt�x����������U���[�����w���Y��o���������%~^��
  | ^
```

**Comment by cartazio** [comment] 2018-12-07 20:34
this is cabal 2.4

NOTE: there IS no cabal v2-upload, but somehow things get strange if i try to do additional arguments

**Comment by cartazio** [comment] 2018-12-07 20:38
this seems like some sort of cli parsing bug that goes crazy

**Comment by fgaz** [comment] 2018-12-10 11:38
Probably a duplicate of #5600

**Comment by hvr** [comment] 2019-01-07 22:13
duplicate of #5600

**Closed by hvr** 2019-01-07 22:13 UTC
