### ISSUE TITLE
cabal new-test doesn't work with library-coverage for components with other-modules

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/cabal#5213] opened 2018-03-14 15:23 UTC
```
$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.1.0 of the Cabal library
```

I'll work on preparing a minimal example in a bit. In the meantime, you can trigger this issue with `scotty-0.11.0`:

```
$ cabal get scotty-0.11.0
Unpacking to scotty-0.11.0/
$ cd scotty-0.11.0/
$ cat > cabal.project << EOF
> packages: .
> package scotty
>   library-coverage: true
> EOF
$ cabal new-test
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - scotty-0.11.0 (lib) (first run)
 - scotty-0.11.0 (test:spec) (first run)
Configuring library for scotty-0.11.0..
Preprocessing library for scotty-0.11.0..
Building library for scotty-0.11.0..
<build output elided>
Configuring test suite 'spec' for scotty-0.11.0..
Preprocessing test suite 'spec' for scotty-0.11.0..
Building test suite 'spec' for scotty-0.11.0..
<build output elided>
Running 1 test suites...
Test suite spec: RUNNING...
<test output elided>
Test suite spec: PASS
Test suite logged to:
/home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/test/scotty-0.11.0-spec.log
hpc: can not find scotty-0.11.0-inplace/Web.Scotty.Util in ./.hpc, /home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/hpc/vanilla/mix/scotty-0.11.0, /home/ryanglscott/Documents/Hacking/Haskell/scotty-0.11.0/dist-newstyle/build/x86_64-linux/ghc-8.2.2/scotty-0.11.0/c/spec/hpc/vanilla/mix/spec
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.0.3:Trace.Hpc.Mix
cabal: Tests failed for test:spec from scotty-0.11.0.
```

This error doesn't happen for another project, `wai-middleware-static-0.8.1`. Unlike `scotty`, `wai-middleware-static` has no `other-modules`, so I suspect that is the culprit here.

**Comment by RyanGlScott** [comment] 2018-03-14 15:31
A minimal reproducer can be found at https://github.com/RyanGlScott/cabal-gh5213:

```
$ git clone https://github.com/RyanGlScott/cabal-gh5213
Cloning into 'cabal-gh5213'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 16 (delta 1), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
$ cd cabal-gh5213/
$ cabal new-test
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - cabal-gh5213-0.1 (lib) (first run)
 - cabal-gh5213-0.1 (test:tests) (first run)
Configuring library for cabal-gh5213-0.1..
Preprocessing library for cabal-gh5213-0.1..
Building library for cabal-gh5213-0.1..
[1 of 2] Compiling CabalGH5213Other ( src/CabalGH5213Other.hs, /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/build/CabalGH5213Other.o )
[2 of 2] Compiling CabalGH5213Exposed ( src/CabalGH5213Exposed.hs, /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/build/CabalGH5213Exposed.o )
Configuring test suite 'tests' for cabal-gh5213-0.1..
Preprocessing test suite 'tests' for cabal-gh5213-0.1..
Building test suite 'tests' for cabal-gh5213-0.1..
[1 of 1] Compiling Main             ( tests/Main.hs, /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/build/tests/tests-tmp/Main.o )
Linking /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/build/tests/tests ...
Running 1 test suites...
Test suite tests: RUNNING...
42
Test suite tests: PASS
Test suite logged to:
/home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/test/cabal-gh5213-0.1-tests.log
hpc: can not find cabal-gh5213-0.1-inplace/CabalGH5213Other in ./.hpc, /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/mix/cabal-gh5213-0.1, /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/mix/tests
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.0.3:Trace.Hpc.Mix
cabal: Tests failed for test:tests from cabal-gh5213-0.1.
```

**Comment by RyanGlScott** [comment] 2018-03-14 16:36
`-v3` revealed that this is how `hpc` is being invoked:

```
/opt/ghc/8.2.2/bin/hpc markup /home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/tix/tests/tests.tix '--destdir=/home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/html/tests' '--hpcdir=/home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/mix/tests' '--hpcdir=/home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/mix/cabal-gh5213-0.1' '--exclude=Main'
```

It's worth noting that `CabalGH5213Other.mix` _is_ being created:

```
$ find dist-newstyle/ -wholename "*cabal-gh5213-0.1-inplace/CabalGH5213Other*"
dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/hpc/dyn/mix/cabal-gh5213-0.1/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix
dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/hpc/vanilla/mix/cabal-gh5213-0.1/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix
```

I'm not sure why `hpc` can't find it, though, especially since it's passed `'--hpcdir=/home/ryanglscott/Documents/Hacking/Haskell/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/c/tests/hpc/vanilla/mix/cabal-gh5213-0.1'`.

**Comment by hvr** [comment] 2018-03-14 17:24
I quick `strace` reveals, that `hpc` is looking at e.g.

```
open("./.hpc/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix", O_RDONLY|O_NOCTTY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
open("./dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/t/tests/hpc/vanilla/mix/cabal-gh5213-0.1/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix", O_RDONLY|O_NOCTTY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
open("./dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/t/tests/hpc/vanilla/mix/tests/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix", O_RDONLY|O_NOCTTY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
```

whereas it should have been looking at

```
./dist-newstyle/build/x86_64-linux/ghc-8.2.2/cabal-gh5213-0.1/hpc/vanilla/mix/cabal-gh5213-0.1/cabal-gh5213-0.1-inplace/CabalGH5213Other.mix
```

**Comment by hvr** [comment] 2018-09-05 14:17
I forgot to tackle this in time for 2.4, but I'll try to get to this within the next 1-2 weeks; but it's probably not going to be ready in time for the cabal-install 2.4.0.0 rls; more like 2.4.1.0

**Comment by vu3rdd** [comment] 2018-09-05 14:56
Thanks @hvr.

**Comment by erikd** [comment] 2019-02-05 07:08
Just hit this myself with cabal 2.4.1.0. Is that expected?

**Comment by 23Skidoo** [comment] 2019-02-05 10:14
"Expected" in the sense that it's a known issue, yes.

**Comment by cartazio** [comment] 2019-05-03 23:53
https://github.com/haskell/cabal/issues/4798 is related right?

**Comment by cartazio** [comment] 2019-05-04 00:00
a related problem folks with fancy code setups hit is when they try to do coverage and have local/not hackage deps, and naively cabal tries do enable coverage on the local package. the work around for now is to set --disable-coverage for that local dep in the cabal.project file.  But i think thats an issue that might be related. but probably merits its own ticket

**Comment by cartazio** [comment] 2020-02-14 23:24
quoting @davean
```
5:53 PM <davean> ocharles: you can specificly disable coverage on the other parts of the project and it will work
5:54 PM <davean> package reflex-time
5:54 PM <davean>   coverage: False
5:54 PM <davean>   library-coverage: False
5:54 PM <davean> as an example
5:55 PM <davean> It should, of course, work to have coverage for all of them
5:55 PM <davean> it just doesn't
```
a near term improvment would be ANY sort of warning saying "this is a known issue, heres what you need to do "

**Comment by cartazio** [comment] 2020-02-14 23:24
cc @ocharles

**Comment by Mikolaj** [comment] 2021-06-30 11:23
This quite likely got fixed in #7250 and/or #7358, which are both merged. Could somebody please check, e.g., using a dev releast that can be obtained as in https://github.com/haskell/cabal/issues/7458#issuecomment-869494367?

**Comment by RyanGlScott** [comment] 2021-06-30 23:47
I downloaded a `cabal` artifact from commit f0d0594bae4f8e3e1ae1bdacef6217a4fc4e136d per the instructions in https://github.com/haskell/cabal/issues/7458#issuecomment-869494367:

```
$ ~/Software/cabal --version
cabal-install version 3.5
compiled using version 3.5.0.0 of the Cabal library
```

However, I am still able to reproduce the bug when using the minimal example from https://github.com/haskell/cabal/issues/5213#issuecomment-373064062:

```
$ ~/Software/cabal new-test
Resolving dependencies...
Build profile: -w ghc-9.0.1 -O1
In order, the following will be built (use -v for more details):
 - cabal-gh5213-0.1 (lib) (first run)
 - cabal-gh5213-0.1 (test:tests) (first run)
Configuring library for cabal-gh5213-0.1..
Preprocessing library for cabal-gh5213-0.1..
Building library for cabal-gh5213-0.1..
[1 of 2] Compiling CabalGH5213Other ( src/CabalGH5213Other.hs, /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/build/CabalGH5213Other.o, /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/build/CabalGH5213Other.dyn_o )
[2 of 2] Compiling CabalGH5213Exposed ( src/CabalGH5213Exposed.hs, /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/build/CabalGH5213Exposed.o, /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/build/CabalGH5213Exposed.dyn_o )
Configuring test suite 'tests' for cabal-gh5213-0.1..
Warning: The package has an extraneous version range for a dependency on an
internal library: cabal-gh5213 >=0 && ==0.1. This version range includes the
current package but isn't needed as the current package's library will always
be used.
Preprocessing test suite 'tests' for cabal-gh5213-0.1..
Building test suite 'tests' for cabal-gh5213-0.1..
[1 of 1] Compiling Main             ( tests/Main.hs, /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/t/tests/build/tests/tests-tmp/Main.o )
Linking /home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/t/tests/build/tests/tests ...
Running 1 test suites...
Test suite tests: RUNNING...
Test suite tests: PASS
Test suite logged to:
/home/ryanglscott/Software/cabal-gh5213/dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/t/tests/test/cabal-gh5213-0.1-tests.log
hpc: can not find cabal-gh5213-0.1-inplace/CabalGH5213Exposed in ./.hpc, ./dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/t/tests/hpc/vanilla/mix/cabal-gh5213-0.1, ./dist-newstyle/build/x86_64-linux/ghc-9.0.1/cabal-gh5213-0.1/t/tests/hpc/vanilla/mix/tests
CallStack (from HasCallStack):
  error, called at libraries/hpc/Trace/Hpc/Mix.hs:122:15 in hpc-0.6.1.0:Trace.Hpc.Mix
cabal: Tests failed for test:tests from cabal-gh5213-0.1.
```

**Comment by Mikolaj** [comment] 2021-07-01 00:00
@RyanGlScott: thank you very much for verifying. A similar issue turned out to be fixed by the PRs but this one still holds. Good to know and since it's already marked as high priority, just a shout out to whomever feels heroic enough to tackle it. I dare say, with the recent changes, it may be easier to diagnose and code-dive now.

**Comment by Mikolaj** [comment] 2021-07-01 09:10
BTW, once the crash (probably caused by wrong paths given to hpc, as @hvr discovered) is fixed, are `other` modules supposed to be presented in the `hpc markup` report, or only `exposed` modules? I'm guessing the latter is now the case:

https://github.com/haskell/cabal/blob/f0d0594bae4f8e3e1ae1bdacef6217a4fc4e136d/Cabal/src/Distribution/Simple/Hpc.hs#L116-L119

but I think I'd be interested in dead or not tested enough code in my hidden library modules as well. OTOH, perhaps people are only interested in whether their tests hit all API entry points and don't care about particular code paths?

**Comment by Mikolaj** [comment] 2021-07-03 14:14
I'm stuck at this point. I can't find the library component `distPref` directory readily available anywhere. It seems we need to pass it explicitly to the test component somehow, e.g,. extend the `TestComponentLocalBuildInfo` variant of `ComponentLocalBuildInfo` with an extra field. However, I don't know what, if any, data structure keeps the stuff from previous components so that we can store the path there when building the main library and then put it into `TestComponentLocalBuildInfo` when starting the build of the test component. Hints welcome.

**Comment by gbaz** [comment] 2021-07-03 19:14
Ok so this is the offending bit: https://github.com/haskell/cabal/blob/a39d590e01636a14986d34cd204079cba45b2d02/Cabal/src/Distribution/Simple/Test/ExeV10.hs#L156

And we need to calculate and pass a second distPref as well, for the lib component.

The correct dir is accidentally (in a sense) the dataDir of the LocalBuildInfo. A hack would be to use that. A more correct thing would be to put a (potentially list) of dirs in the localBuildInfo for hpcdirs, calculated just as the dataDir is, but not risking being overridden by some flag. In either case, its the LocalBuildInfo and not the ComponentLocalBuildInfo that I think should be modified...

**Comment by Mikolaj** [comment] 2021-07-15 16:29
Given that `dataDir` doesn't work, I've gone the way of passing the correct directory as an extra field of `LocalBuildInfo`, but I'm stuck again. Namely, the incorrect directory (the one with spurious `t/nameOfTestComponent/`) is created in one go here

https://github.com/haskell/cabal/blob/master/cabal-install/src/Distribution/Client/DistDirLayout.hs#L193-L205

and nowhere else is, e.g., `distParamCompilerId` used. So the correct directory is not created anywhere in cabal at all. I'm guessing GHC creates is independently and this is how hpc knows where to store the .mix files (BTW, if that's true, that is quite fragile). I could create it independently as well, but I'd rather avoid that and creating it once and passing additionally from cabal-install to Cabal seems like a lot of extra code and polluted APIs. I hope I'm missing something.

**Comment by gbaz** [comment] 2021-07-15 19:03
I think its fine for now to rely on ghc's behavior here. Arguably we should upstream flags to ghc so that we can control where mix files end up (it seems hardwired for now) but I'm fine hardcoding in something that matches ghc's hardcoding for now. cc @bgamari

**Comment by Mikolaj** [comment] 2021-07-21 22:32
Note to self (I'm not stuck): I think I've fixed the place in the code that we suspected of being buggy, but it still fails and in the same way. I think I was right the correct directory is not created in cabal code, but I think I was wrong it's created (hardwired) in GHC --- in fact, it seems we create the director via calls to `Hpc.mixDir` in Cabal/src/Distribution/Simple/GHC.hs. bit we create a wrong one, similarly as in the place we originally indicated as erroneous. So I guess I need to hack the correct directory (by dropping the last two components of path, the `t/test/` in both places (actually, it seems in 3 or 4 places total. I think I will create a separate hacky function and apply it whenever we can tell the HPC processing is for tests, not a library.

**Comment by Mikolaj** [comment] 2021-07-24 11:28
I ended up adding a hack to the very `Hpc.mixDir` function, because the error occurred more than 4 times when running the cabal-gh5213 test, so fixing it at each spot would incur a lot of noise. I think, unless we start using a Haskell compiler called "t", this hack should not backfire (famous last words). For hints of a proper solution, see also the PR.

**Comment by Mikolaj** [comment] 2021-07-24 21:17
I tried testing the PR with multiple libraries, but it fails with "cabal: Error: test coverage is only supported for packages with a library", so I guess this case is not handled yet anyway. From what I've seen in the code and what I comment above, it probably wouldn't work without extra fixes, but I'm not sure. See #6440 and #6397.

**Closed** 2021-07-29 10:11 UTC
Labels: cabal-install: nix-local-build, meta: hvr, priority: high :fire:, type: bug

**Comment by Mikolaj** [comment] 2021-07-29 17:34
A note for the future principled fix: @bgamari points to where the HCP path we pass to GHC is extended (again!) and used by it: ./compiler/GHC/HsToCore/Coverage.hs:writeMixEntries. It would make sense to pass only the root dist path (currently not available in components except the main library) and in other parts of cabal follow the GHC way of adding suffixes to it (in order to avoid overwriting same name modules from different internal libraries), assuming HCP itself can handle subdirectories.
