### ISSUE TITLE
depsolver error messages have become incomprehensible

### ISSUE THREAD

**Issue by bos** [haskell/cabal#1005] opened 2012-08-15 19:00 UTC
Trying to build [criterion HEAD](https://github.com/bos/criterion) using GHC 7.6.1 RC this morning, I am confronted by this output from cabal-install's depsolver.

I have absolutely no idea what it means, how to identify what's broken, or how to fix it. This is really bad.

```
cabal: Could not resolve dependencies:
next goal: criterion (user goal)
rejecting: criterion-0.6.0.1 (global constraint requires ==0.6.0.0)
trying: criterion-0.6.0.0
trying: parsec-3.1.3 (dependency of criterion-0.6.0.0)
next goal: text (dependency of parsec-3.1.3)
rejecting: text-0.11.2.3/installed-157... (conflict: vector-algorithms =>
bytestring==0.9.2.1/installed-375..., text =>
bytestring==0.10.0.0/installed-35d...)
trying: text-0.11.2.2
rejecting: text-0.11.2.2:-integer-simple (conflict: base =>
integer-gmp==0.5.0.0/installed-56b..., text-0.11.2.2:integer-simple =>
integer-gmp>=0.2 && <0.5)
trying: text-0.11.2.2:+integer-simple
next goal: integer-simple (dependency of text-0.11.2.2:+integer-simple)
```

**Comment by jsl** [comment] 2015-02-28 15:38
I imagine the error messages have improved considerably since this was reported. I'm also not sure exactly what HEAD of the criterion library was when this was reported so this is tricky to reproduce. I propose closing, and opening other tickets if there are specific issues with the solver.

**Closed** 2015-02-28 17:30 UTC
Labels: cabal-install
