### ISSUE TITLE
documentation Links in Extension.hs should be updated

### ISSUE THREAD

**Issue by p-alik** [haskell/cabal#4582] opened 2017-07-03 14:45 UTC
I stumbled over the issue by following the PackageImports[extension link](https://github.com/haskell/cabal/blob/master/Cabal/Language/Haskell/Extension.hs#L455). 

http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html#package-imports
should be replaced by
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#ghc-flag--XPackageImports

It seems to be a general issue.
https://ghc.haskell.org/trac/ghc/wiki/Commentary/Packages/PackageImportsProposal for instance used the same outdated link.

**Comment by 23Skidoo** [comment] 2017-07-03 16:41
Thanks! This is caused by GHC's move to Sphinx for documentation which broke old links.

**Comment by p-alik** [comment] 2017-07-03 20:34
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#ghc-flag--XRankNTypes

It looks like new [Glasgow Haskell Compiler Users Guide](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html) doesn't offer documentation for:
- PolymorphicComponents
- Generics
- ImplicitPrelude
- ExtensibleRecords
- RestrictedTypeSynonyms
- HereDocuments
- InterruptibleFFI
- CApiFFI
- TraditionalRecordSyntax
- MonoPatBinds
- ExtendedDefaultRules

If you think participation in [this way](https://github.com/p-alik/cabal/commit/930ecf5b7beda5453d37d310af426fcd3e543a94) would be helpful, I would complete the updates for a PR.

**Comment by 23Skidoo** [comment] 2017-07-03 20:58
Sure, a PR fixing broken links would be very welcome.

**Comment by p-alik** [comment] 2017-07-04 12:42
no targets for:
- NewQualifiedOperators
- NondecreasingIndentation
- SafeImports
- ParallelArrays
- AutoDeriveTypeable

**Comment by p-alik** [comment] 2017-07-05 13:04
Beside the changes in #4584 there are 14 404-links.

- http://www.haskell.org/ghc/docs/latest/html/users_guide/other-type-extensions.html#universal-quantification
- http://www.haskell.org/ghc/docs/latest/html/users_guide/generic-classes.html
- http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html#rebindable-syntax
- http://cvs.haskell.org/Hugs/pages/users_guide/hugs-only.html#TREX
- http://cvs.haskell.org/Hugs/pages/users_guide/restricted-synonyms.html
- http://cvs.haskell.org/Hugs/pages/users_guide/here-documents.html
- http://www.haskell.org/ghc/docs/latest/html/users_guide/ffi.html#ffi-interruptible
- http://www.haskell.org/ghc/docs/latest/html/users_guide/ffi.html#ffi-capi
- http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html#traditional-record-syntax
- http://www.haskell.org/ghc/docs/latest/html/users_guide/data-type-extensions.html#gadt
- http://www.haskell.org/ghc/docs/latest/html/users_guide/monomorphism.html#id630981
- http://www.haskell.org/ghc/docs/latest/html/users_guide/bugs-and-infelicities.html#infelicities-syntax
- http://www.haskell.org/ghc/docs/latest/html/users_guide/safe-haskell.html#safe-imports
- http://www.haskell.org/ghc/docs/latest/html/users_guide/deriving.html#auto-derive-typeable

**Comment by 23Skidoo** [comment] 2017-07-05 13:10
The Hugs ones are actually still up, you just need to replace `Hugs` with `hugs`.

**Comment by 23Skidoo** [comment] 2017-07-05 13:11
> http://www.haskell.org/ghc/docs/latest/html/users_guide/bugs-and-infelicities.html#infelicities-syntax

This one is now https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/bugs.html#lexical-syntax

**Comment by 23Skidoo** [comment] 2017-07-05 13:14
> http://www.haskell.org/ghc/docs/latest/html/users_guide/ffi.html#ffi-interruptible

Interruptible FFI: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ffi-chap.html#interruptible-foreign-calls

> http://www.haskell.org/ghc/docs/latest/html/users_guide/ffi.html#ffi-capi

CAPI: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ffi-chap.html#the-capi-calling-convention

**Comment by 23Skidoo** [comment] 2017-07-05 13:22
> http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html#traditional-record-syntax

Traditional record syntax: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#traditional-record-syntax

**Comment by p-alik** [comment] 2017-07-05 13:25
I'll do a separate PR for remaining links.

**Comment by 23Skidoo** [comment] 2017-07-05 13:26
> http://www.haskell.org/ghc/docs/latest/html/users_guide/safe-haskell.html#safe-imports
Safe imports: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#safe-imports

**Comment by p-alik** [comment] 2017-07-06 06:17
http://www.haskell.org/ghc/docs/latest/html/users_guide/other-type-extensions.html#universal-quantification

No particular link for latest, but - if you have no objection - it could be replaced by
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#arbitrary-rank-polymorphism

**Comment by p-alik** [comment] 2017-07-06 06:21
http://www.haskell.org/ghc/docs/latest/html/users_guide/generic-classes.html
is now
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#generic-classes

**Comment by p-alik** [comment] 2017-07-06 06:31
http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html#rebindable-syntax
is now
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#syntactic-extensions

but there is nothing about `ImplicitPrelude`. Only
- `RebindableSyntax`
- `NoImplicitPrelude`

**Comment by p-alik** [comment] 2017-07-06 06:38
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#generalised-algebraic-data-types-gadts

instead of  http://www.haskell.org/ghc/docs/latest/html/users_guide/data-type-extensions.html#gadt

**Comment by p-alik** [comment] 2017-07-06 06:49
https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#switching-off-the-dreaded-monomorphism-restriction
istead of http://www.haskell.org/ghc/docs/latest/html/users_guide/monomorphism.html#id630981
but there is nothing about `MonoPatBinds`

**Comment by p-alik** [comment] 2017-07-06 06:57
no `AutoDeriveTypeable` in latest.
Only in https://downloads.haskell.org/~ghc/7.8.2/docs/html/users_guide/deriving.html#auto-derive-typeable

is https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#deriving-typeable-instances
suitable replacement for http://www.haskell.org/ghc/docs/latest/html/users_guide/deriving.html#auto-derive-typeable ?

**Comment by 23Skidoo** [comment] 2017-07-07 02:13
This has all been fixed now.

**Closed by 23Skidoo** 2017-07-07 02:13 UTC
Labels: documentation, meta: easy, newcomer, newcomer: 2-one-file-change
