### ISSUE TITLE
Cabal incorrectly rejects non-broken packages

### ISSUE THREAD

**Issue by poscat0x04** [haskell/cabal#7272] opened 2021-02-06 16:46 UTC
**Describe the bug**
Cabal incorrectly rejects non-broken packages thinking that they are broken. Using `ghc-pkg` shows that the package is indeed not broken.

output:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: attoparsec-0.13.2.4 (user goal)
[__1] trying: text-1.2.4.1/installed-1.2.4.1 (dependency of attoparsec)
[__2] trying: template-haskell-2.16.0.0/installed-2.16.0.0 (dependency of
text)
[__3] trying: binary-0.8.8.0/installed-0.8.8.0 (dependency of text)
[__4] trying: base-4.14.1.0/installed-4.14.1.0 (dependency of attoparsec)
[__5] trying: attoparsec-benchmarks-0 (user goal)
[__6] trying: criterion-1.5.9.0/installed-C9mpHH1rRghAQlbzxXz9e6 (dependency
of attoparsec-benchmarks)
[__7] trying: microstache-1.0.1.2/installed-3f78h8A7ede9YlVZgGwiJr (dependency
of criterion)
[__8] trying: criterion-measurement-0.1.2.0/installed-IRYmq6ZKZQfIj3kMCWTbj2
(dependency of criterion)
[__9] next goal: cassava (dependency of criterion)
[__9] rejecting: cassava-0.5.2.0/installed-FWgpCA4uSFjJDMANj8lgto (package is
broken)
[__9] rejecting: cassava-0.5.2.0, cassava-0.5.1.0, cassava-0.5.0.0,
cassava-0.4.5.1, cassava-0.4.5.0, cassava-0.4.4.0, cassava-0.4.3.1,
cassava-0.4.3.0, cassava-0.4.2.4, cassava-0.4.2.3, cassava-0.4.2.2,
cassava-0.4.2.1, cassava-0.4.2.0, cassava-0.4.1.0, cassava-0.4.0.0,
cassava-0.3.0.1, cassava-0.3.0.0, cassava-0.2.2.0, cassava-0.2.1.2,
cassava-0.2.1.1, cassava-0.2.1.0, cassava-0.2.0.0, cassava-0.1.0.1,
cassava-0.1.0.0 (conflict: criterion =>
cassava==0.5.2.0/installed-FWgpCA4uSFjJDMANj8lgto)
[__9] fail (backjumping, conflict set: cassava, criterion)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: aeson, base, criterion, hashable,
cassava, th-abstraction, attoparsec, template-haskell, text, microstache,
binary, attoparsec-benchmarks, hastache, criterion-measurement, primitive
Try running with --minimize-conflict-set to improve the error message.
```

**To Reproduce**

```
clone attoparsec
cabal build
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by phadej** [comment] 2021-02-06 16:58
I suspect you have a local package in project which overrides a dependency of installed `cassava`.

Please build the most recent tip of `3.4` branch (or `master`), they print which package causes installed package to be considered broken.

**Comment by fgaz** [comment] 2021-02-16 09:13
Cannot reproduce with cabal 3.4 and

```
cabal get -s attoparsec
cd attoparsec
cabal configure
```

**Comment by Mikolaj** [comment] 2021-05-27 12:36
@poscat0x04: could you try to repro with cabal 3.4 (or newer) and close the issue if it works now? If you are too busy, I will close it after some respectful delay.

**Comment by Mikolaj** [comment] 2021-06-01 08:58
Closing, respectfully. :)

Please reopen if the problem reappears.

**Closed by Mikolaj** 2021-06-01 08:58 UTC
Labels: blocked: info-needed
