### ISSUE TITLE
'cabal haddock --executables' causes "cabal: internal error when calculating transative package dependencies."

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#1085] opened 2012-10-25 22:15 UTC
Here's the branch with which the bug happens:

https://github.com/Mikolaj/haskell-linux-perf/blob/haddock-bug/linux-perf.cabal

Here's the IRC transcript with the description of the problem:

```
20:08 < mikolaj> hmm, just got 
20:08 < mikolaj> Documentation created: dist/doc/html/linux-perf/ghc-events-perf/index.html
20:08 < mikolaj> Preprocessing executable 'dump-perf' for linux-perf-0.2...
20:08 < mikolaj> cabal: internal error when calculating transative package dependencies.
20:08 < mikolaj> Debug info: []
20:08 < mikolaj> notice "transative" BTW
20:09 < mikolaj> cabal-install version 1.16.0
20:09 < mikolaj> using version 1.16.0.1 of the Cabal library 
20:09 < mikolaj> Haddock version 2.12.0, (c) Simon Marlow 2006
20:09 < mikolaj> Ported to use the GHC API by David Waern 2006-2008
20:10 < mikolaj> hmm, Google is silent, but seems like a haddock bug
20:11 < mikolaj> despite "cabal: internal error"
20:11 < mikolaj> sorry for the spam
22:01 < kosmikus> interesting
22:02 < kosmikus> mikolaj: funnily enough, git grep returns 6(!) references for "transative" :)
22:04 < kosmikus> but none of these seem to be in an error message
22:07 < kosmikus> oh, the first one is :)
22:07 < kosmikus> ok, so it's from Distribution.Simple.Haddock
22:07 < kosmikus> I have little knowledge of that code
22:21 < kosmikus> mikolaj: ok, so this is a result of a call to dependencyClosure
22:21 < kosmikus> and the docs of that function say: -- \* Note that if the result is @Right []@ it is because at least one of
22:21 < kosmikus> -- the original given 'PackageId's do not occur in the index.
22:44 < mikolaj> kosmikus: hah, thanks for looking; still no idea, since the exe builds ok, but it's not important; I just wanted to make sure the tiny docs in that file use correct haddock mardown; fortunately for all other files it 
                 works OK
22:47 < kosmikus> mikolaj: it seems that a package appears in the dependency closure that's not installed
22:48 < kosmikus> is there any flag magic in this package?
22:51 < mikolaj> here's the cabal file: https://github.com/Mikolaj/haskell-linux-perf/blob/haddock-bug/linux-perf.cabal
22:52 < mikolaj> that's the offending file: https://github.com/Mikolaj/haskell-linux-perf/blob/haddock-bug/dump-perf/dump-perf.hs
22:52 < mikolaj> and the only magic I can see is the option here: cabal haddock --executables
22:53 < mikolaj> I suppose the --executables mode is not that well tested...
22:57 < kosmikus> mmm
22:57 < kosmikus> it could be the dependency on the Library that confuses it
22:57 < kosmikus> because that will indeed not be in the index
22:58 < mikolaj> oh, indeed all the other exes do not use the lib
22:58 < kosmikus> worth reporting as a bug
```

And below is the whole transcript of `cabal haddock --executables -v3`.

```
~/r/haskell-linux-perf$ cabal haddock --executables -v3
Using internal setup method with build-type Simple and args:
["haddock","--verbose=3","--executables"]
Running Haddock for linux-perf-0.2...
("/usr/local/bin/haddock",["--ghc-version"])
creating dist/build
creating dist/build/autogen
("/usr/local/bin/ghc",["--print-libdir"])
Preprocessing library linux-perf-0.2...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0, mtl-2.1.2,
transformers-0.3.0.0
copy Profiling/Linux/Perf.hs to dist/build/tmp-26517/Profiling/Linux/Perf.hs
copy Profiling/Linux/Perf/Types.hs to
dist/build/tmp-26517/Profiling/Linux/Perf/Types.hs
copy dist/build/Profiling/Linux/Perf/Parse.hs to
dist/build/tmp-26517/dist/build/Profiling/Linux/Perf/Parse.hs
copy Profiling/Linux/Perf/Pretty.hs to
dist/build/tmp-26517/Profiling/Linux/Perf/Pretty.hs
creating dist/doc/html/linux-perf
("/usr/local/bin/haddock",["--prologue=dist/doc/html/linux-perf/haddock-prolog26517.txt","--dump-interface=dist/doc/html/linux-perf/linux-perf.haddock","--optghc=-package-name","--optghc=linux-perf-0.2","--html","--read-interface=/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1,/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1/array.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0,/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0/base.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/binary-0.5.1.1,/usr/local/share/doc/ghc/html/libraries/binary-0.5.1.1/binary.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0,/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0/bytestring.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/containers-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/containers-0.5.0.0/containers.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1/deepseq.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0,/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0/ghc-prim.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0/integer-gmp.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/pretty-1.1.1.0,/usr/local/share/doc/ghc/html/libraries/pretty-1.1.1.0/pretty.haddock","--odir=dist/doc/html/linux-perf/","--title=linux-perf-0.2: Read files generated by perf on Linux","--optghc=-fbuilding-cabal-package","--optghc=-O","--optghc=-odir","--optghc=dist/build/tmp-26517","--optghc=-hidir","--optghc=dist/build/tmp-26517","--optghc=-stubdir","--optghc=dist/build/tmp-26517","--optghc=-i","--optghc=-idist/build","--optghc=-i.","--optghc=-idist/build/autogen","--optghc=-Idist/build/autogen","--optghc=-Idist/build","--optghc=-IProfiling/Linux/Perf","--optghc=-optP-include","--optghc=-optPdist/build/autogen/cabal_macros.h","--optghc=-hide-all-packages","--optghc=-package-id","--optghc=base-4.6.0.0-79f30dfeaf8c488e8f0395d17c535080","--optghc=-package-id","--optghc=binary-0.5.1.1-b32a15839a74b4b2f44c284ab455d0dc","--optghc=-package-id","--optghc=bytestring-0.10.0.0-041c458a492de0addc7b125e2947991f","--optghc=-package-id","--optghc=containers-0.5.0.0-e0dd75b6101dcabf20a70b020fd1455b","--optghc=-package-id","--optghc=mtl-2.1.2-25dca0019d088a7438da0485cd8b4e7a","--optghc=-package-id","--optghc=pretty-1.1.1.0-60eca8bfc1d4038fc780e8f79dbc3d47","--optghc=-XHaskell98","-B/usr/local/lib/ghc-7.6.1","dist/build/tmp-26517/Profiling/Linux/Perf.hs","dist/build/tmp-26517/Profiling/Linux/Perf/Types.hs","dist/build/tmp-26517/dist/build/Profiling/Linux/Perf/Parse.hs","dist/build/tmp-26517/Profiling/Linux/Perf/Pretty.hs"])
Haddock coverage:
 100% (  4 /  4) in 'Profiling.Linux.Perf.Pretty'
  97% ( 31 / 32) in 'Profiling.Linux.Perf.Types'
 100% (  7 /  7) in 'Profiling.Linux.Perf.Parse'
 100% ( 11 / 11) in 'Profiling.Linux.Perf'
Documentation created: dist/doc/html/linux-perf/index.html
Preprocessing executable 'ghc-events-perf-sync' for linux-perf-0.2...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0, ghc-events-0.4.2.0,
mtl-2.1.2, transformers-0.3.0.0
copy ghc-events-perf/ghc-events-perf-sync.hs to
dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-sync.hs
creating dist/doc/html/linux-perf/ghc-events-perf-sync
("/usr/local/bin/haddock",["--prologue=dist/doc/html/linux-perf/ghc-events-perf-sync/haddock-prolog26517.txt","--dump-interface=dist/doc/html/linux-perf/ghc-events-perf-sync/linux-perf.haddock","--optghc=-package-name","--optghc=linux-perf-0.2","--html","--read-interface=/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1,/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1/array.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0,/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0/base.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/binary-0.5.1.1,/usr/local/share/doc/ghc/html/libraries/binary-0.5.1.1/binary.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0,/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0/bytestring.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/containers-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/containers-0.5.0.0/containers.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1/deepseq.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0,/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0/directory.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1/filepath.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0,/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0/ghc-prim.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0/integer-gmp.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5,/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5/old-locale.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/process-1.1.0.2,/usr/local/share/doc/ghc/html/libraries/process-1.1.0.2/process.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1,/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1/time.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0,/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0/unix.haddock","--odir=dist/doc/html/linux-perf/ghc-events-perf-sync","--title=ghc-events-perf-sync","--optghc=-fbuilding-cabal-package","--optghc=-O","--optghc=-odir","--optghc=dist/build/tmp-26517","--optghc=-hidir","--optghc=dist/build/tmp-26517","--optghc=-stubdir","--optghc=dist/build/tmp-26517","--optghc=-i","--optghc=-idist/build","--optghc=-ighc-events-perf","--optghc=-idist/build/autogen","--optghc=-Idist/build/autogen","--optghc=-Idist/build","--optghc=-optP-include","--optghc=-optPdist/build/autogen/cabal_macros.h","--optghc=-hide-all-packages","--optghc=-package-id","--optghc=base-4.6.0.0-79f30dfeaf8c488e8f0395d17c535080","--optghc=-package-id","--optghc=containers-0.5.0.0-e0dd75b6101dcabf20a70b020fd1455b","--optghc=-package-id","--optghc=ghc-events-0.4.2.0-c8d0abea85ba9be2c4496bcc483b719a","--optghc=-package-id","--optghc=process-1.1.0.2-03ae5757aa509ffbe497f42660cba52c","--optghc=-XHaskell98","--optghc=-rtsopts","--optghc=-Wall","--optghc=-fwarn-orphans","--optghc=-fwarn-tabs","--optghc=-fwarn-incomplete-uni-patterns","--optghc=-fwarn-incomplete-record-updates","--optghc=-fwarn-monomorphism-restriction","--optghc=-fwarn-unrecognised-pragmas","--optghc=-fno-warn-auto-orphans","--optghc=-fno-warn-implicit-prelude","-B/usr/local/lib/ghc-7.6.1","dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-sync.hs"])
Haddock coverage:
  71% ( 10 / 14) in 'Main'
Warning: Main: could not find link destinations for:
    GHC.RTS.EventTypes.EventLog GHC.RTS.EventTypes.Event GHC.RTS.EventTypes.EventType
Documentation created:
dist/doc/html/linux-perf/ghc-events-perf-sync/index.html
Preprocessing executable 'ghc-events-perf-record' for linux-perf-0.2...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0
copy ghc-events-perf/ghc-events-perf-record.hs to
dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-record.hs
creating dist/doc/html/linux-perf/ghc-events-perf-record
("/usr/local/bin/haddock",["--prologue=dist/doc/html/linux-perf/ghc-events-perf-record/haddock-prolog26517.txt","--dump-interface=dist/doc/html/linux-perf/ghc-events-perf-record/linux-perf.haddock","--optghc=-package-name","--optghc=linux-perf-0.2","--html","--read-interface=/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1,/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1/array.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0,/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0/base.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0,/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0/bytestring.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1/deepseq.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0,/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0/directory.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1/filepath.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0,/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0/ghc-prim.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0/integer-gmp.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5,/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5/old-locale.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1,/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1/time.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0,/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0/unix.haddock","--odir=dist/doc/html/linux-perf/ghc-events-perf-record","--title=ghc-events-perf-record","--optghc=-fbuilding-cabal-package","--optghc=-O","--optghc=-odir","--optghc=dist/build/tmp-26517","--optghc=-hidir","--optghc=dist/build/tmp-26517","--optghc=-stubdir","--optghc=dist/build/tmp-26517","--optghc=-i","--optghc=-idist/build","--optghc=-ighc-events-perf","--optghc=-idist/build/autogen","--optghc=-Idist/build/autogen","--optghc=-Idist/build","--optghc=-optP-include","--optghc=-optPdist/build/autogen/cabal_macros.h","--optghc=-hide-all-packages","--optghc=-package-id","--optghc=base-4.6.0.0-79f30dfeaf8c488e8f0395d17c535080","--optghc=-package-id","--optghc=directory-1.2.0.0-f9eae21e71a6e8b1c5d0f490726dad1b","--optghc=-package-id","--optghc=filepath-1.3.0.1-2c4d917e81bff7e614bd53f8f5b93fee","--optghc=-package-id","--optghc=unix-2.6.0.0-7ebf7dd27ae9d97b00f6f9654b4b25b2","--optghc=-XHaskell98","--optghc=-rtsopts","--optghc=-Wall","--optghc=-fwarn-orphans","--optghc=-fwarn-tabs","--optghc=-fwarn-incomplete-uni-patterns","--optghc=-fwarn-incomplete-record-updates","--optghc=-fwarn-monomorphism-restriction","--optghc=-fwarn-unrecognised-pragmas","--optghc=-fno-warn-auto-orphans","--optghc=-fno-warn-implicit-prelude","-B/usr/local/lib/ghc-7.6.1","dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-record.hs"])
Haddock coverage:

dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-record.hs:250:3: Warning:
    Defined but not used: `syscalls1'

dist/build/tmp-26517/ghc-events-perf/ghc-events-perf-record.hs:303:3: Warning:
    Defined but not used: `syscalls2'
  61% ( 11 / 18) in 'Main'
Documentation created:
dist/doc/html/linux-perf/ghc-events-perf-record/index.html
Preprocessing executable 'ghc-events-perf' for linux-perf-0.2...
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: rts-1.0
copy ghc-events-perf/ghc-events-perf.hs to
dist/build/tmp-26517/ghc-events-perf/ghc-events-perf.hs
creating dist/doc/html/linux-perf/ghc-events-perf
("/usr/local/bin/haddock",["--prologue=dist/doc/html/linux-perf/ghc-events-perf/haddock-prolog26517.txt","--dump-interface=dist/doc/html/linux-perf/ghc-events-perf/linux-perf.haddock","--optghc=-package-name","--optghc=linux-perf-0.2","--html","--read-interface=/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1,/usr/local/share/doc/ghc/html/libraries/array-0.4.0.1/array.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0,/usr/local/share/doc/ghc/html/libraries/base-4.6.0.0/base.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0,/usr/local/share/doc/ghc/html/libraries/bytestring-0.10.0.0/bytestring.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/deepseq-1.3.0.1/deepseq.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0,/usr/local/share/doc/ghc/html/libraries/directory-1.2.0.0/directory.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1,/usr/local/share/doc/ghc/html/libraries/filepath-1.3.0.1/filepath.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0,/usr/local/share/doc/ghc/html/libraries/ghc-prim-0.3.0.0/ghc-prim.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0,/usr/local/share/doc/ghc/html/libraries/integer-gmp-0.5.0.0/integer-gmp.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5,/usr/local/share/doc/ghc/html/libraries/old-locale-1.0.0.5/old-locale.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/process-1.1.0.2,/usr/local/share/doc/ghc/html/libraries/process-1.1.0.2/process.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1,/usr/local/share/doc/ghc/html/libraries/time-1.4.0.1/time.haddock","--read-interface=/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0,/usr/local/share/doc/ghc/html/libraries/unix-2.6.0.0/unix.haddock","--odir=dist/doc/html/linux-perf/ghc-events-perf","--title=ghc-events-perf","--optghc=-fbuilding-cabal-package","--optghc=-O","--optghc=-odir","--optghc=dist/build/tmp-26517","--optghc=-hidir","--optghc=dist/build/tmp-26517","--optghc=-stubdir","--optghc=dist/build/tmp-26517","--optghc=-i","--optghc=-idist/build","--optghc=-ighc-events-perf","--optghc=-idist/build/autogen","--optghc=-Idist/build/autogen","--optghc=-Idist/build","--optghc=-optP-include","--optghc=-optPdist/build/autogen/cabal_macros.h","--optghc=-hide-all-packages","--optghc=-package-id","--optghc=base-4.6.0.0-79f30dfeaf8c488e8f0395d17c535080","--optghc=-package-id","--optghc=filepath-1.3.0.1-2c4d917e81bff7e614bd53f8f5b93fee","--optghc=-package-id","--optghc=process-1.1.0.2-03ae5757aa509ffbe497f42660cba52c","--optghc=-package-id","--optghc=unix-2.6.0.0-7ebf7dd27ae9d97b00f6f9654b4b25b2","--optghc=-XHaskell98","--optghc=-Wall","--optghc=-fwarn-orphans","--optghc=-fwarn-tabs","--optghc=-fwarn-incomplete-uni-patterns","--optghc=-fwarn-incomplete-record-updates","--optghc=-fwarn-monomorphism-restriction","--optghc=-fwarn-unrecognised-pragmas","--optghc=-fno-warn-auto-orphans","--optghc=-fno-warn-implicit-prelude","-B/usr/local/lib/ghc-7.6.1","dist/build/tmp-26517/ghc-events-perf/ghc-events-perf.hs"])
Haddock coverage:
  20% (  1 /  5) in 'Main'
Documentation created: dist/doc/html/linux-perf/ghc-events-perf/index.html
Preprocessing executable 'dump-perf' for linux-perf-0.2...
cabal: internal error when calculating transative package dependencies.
Debug info: []
~/r/haskell-linux-perf$ 
```

**Comment by abooij** [comment] 2017-01-14 15:34
The problem is that the `dump-perf` executable depends on the `linux-perf` library, which is an internal dependency.

**Comment by Mikolaj** [comment] 2017-11-07 15:43
The  problem persists with cabal-install 2.0.0.0

```
Documentation created: dist/doc/html/LambdaHack/index.html
creating dist/build/LambdaHack
creating dist/build/LambdaHack/autogen
creating dist/build/LambdaHack/autogen
Preprocessing executable 'LambdaHack' for LambdaHack-0.7.0.0..
Running Haddock on executable 'LambdaHack' for LambdaHack-0.7.0.0..
CallStack (from HasCallStack):
  withTempDirectoryEx, called at libraries/Cabal/Cabal/Distribution/Simple/Haddock.hs:203:13 in Cabal-2.0.0.2:Distribution.Simple.Haddock
  f, called at libraries/Cabal/Cabal/Distribution/Simple/LocalBuildInfo.hs:198:9 in Cabal-2.0.0.2:Distribution.Simple.LocalBuildInfo
  f, called at libraries/Cabal/Cabal/Distribution/Types/LocalBuildInfo.hs:257:19 in Cabal-2.0.0.2:Distribution.Types.LocalBuildInfo
  withAllTargetsInBuildOrder', called at libraries/Cabal/Cabal/Distribution/Simple/LocalBuildInfo.hs:197:5 in Cabal-2.0.0.2:Distribution.Simple.LocalBuildInfo
  withAllComponentsInBuildOrder, called at libraries/Cabal/Cabal/Distribution/Simple/Haddock.hs:197:5 in Cabal-2.0.0.2:Distribution.Simple.Haddock
  haddock, called at libraries/Cabal/Cabal/Distribution/Simple.hs:582:35 in Cabal-2.0.0.2:Distribution.Simple
  haddockHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:148:5 in Cabal-2.0.0.2:Distribution.Simple.UserHooks
  cmd_hook, called at libraries/Cabal/Cabal/Distribution/Simple.hs:452:38 in Cabal-2.0.0.2:Distribution.Simple
  cmd_hook, called at libraries/Cabal/Cabal/Distribution/Simple.hs:469:4 in Cabal-2.0.0.2:Distribution.Simple
  hookedActionWithArgs, called at libraries/Cabal/Cabal/Distribution/Simple.hs:451:5 in Cabal-2.0.0.2:Distribution.Simple
  hookedAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:323:3 in Cabal-2.0.0.2:Distribution.Simple
  haddockAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:50 in Cabal-2.0.0.2:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:124:19 in Cabal-2.0.0.2:Distribution.Simple
  defaultMainArgs, called at ./Distribution/Client/SetupWrapper.hs:428:29 in main:Distribution.Client.SetupWrapper
cabal: internal error when calculating transitive package dependencies.
Debug info: []
```

**Comment by 23Skidoo** [comment] 2017-12-22 15:21
Closing as a duplicate of #1919, which seems to have more comments.

**Closed by 23Skidoo** 2017-12-22 15:21 UTC
Labels: Cabal: cmd/haddock, meta: 23Skidoo, type: bug
