### ISSUE TITLE
cabal init -l BSD-3-Clause prints error message forever

### ISSUE THREAD

**Issue by leifmetcalf** [haskell/cabal#6227] opened 2019-09-07 20:59 UTC
**Describe the bug**

```
$ cabal init -l BSD-3-Clause

The license must be alphanumeric. If your license name has many words, the convention is to use camel case (e.g. PublicDomain). Please choose a different license.

The license must be alphanumeric. If your license name has many words, the convention is to use camel case (e.g. PublicDomain). Please choose a different license.

The license must be alphanumeric. If your license name has many words, the convention is to use camel case (e.g. PublicDomain). Please choose a different license.

...
```
`cabal init -l a-1` gives the same repeating error.
`cabal init -l a-1-a` gives the same repeating error.
`cabal init -l a-a` does not, it returns
```
Cannot parse license: a-a-1
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:42:24 in Cabal-3.0.0.0-fb617b94c4973e1d5149e5c5439c47b4e57443a0819f354a288475aa6cef5eae:Distribution.ReadE
```

**System information**
 - Ubuntu `19.04`
 - cabal-install `3.0.0.0`
 - ghc `8.6.5`

**Comment by v0d1ch** [comment] 2020-03-27 14:16
I would like to tackle this one

**Comment by emilypi** [comment] 2021-01-28 02:14
I can confirm that this seems to be fixed as of https://github.com/haskell/cabal/commit/2fa83023606e89f933bfe0d8779ea805f44b08eb. 

I had the same problem, now get an error upon upgrade.

**Closed** 2021-03-30 00:11 UTC
Labels: cabal-install: cmd/init, type: bug
