### ISSUE TITLE
Cabal should offer a suggestion for how to resolve dep when a package doesn't exist at all in cached index

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2816] opened 2015-09-10 01:05 UTC
Recently I attempted to build Stack and I got this error:

```
[ezyang@hs01 stack]$ cabal install
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-0.1.4.1 (user goal)
next goal: binary-tagged (dependency of stack-0.1.4.1)
```

The reason was that I hadn't run `cabal update`. It would be helpful if Cabal gave a little tip about this.

**Comment by grayjay** [comment] 2016-01-29 21:34
This is a duplicate of #2179.

**Closed by grayjay** 2016-01-29 21:34 UTC
Labels: cabal-install, easy, enhancement
