### ISSUE TITLE
`cabal sandbox init --sandbox<tab>` creates sandbox named `--list-options`

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#3648] opened 2016-07-31 15:10 UTC
There must be a more reliable approach to this whole bash-completion. seems way too easy to break at every corner.

**Comment by lspitzner** [comment] 2016-07-31 15:13
my bash-completion is that of master branch (minus the new-build addition, which is irrelevant).

**Comment by 0xmohit** [comment] 2016-08-06 15:44
The culprit appears to be `eval "${cmd[@]}"` [here](https://github.com/haskell/cabal/blob/master/cabal-install/bash-completion/cabal#L91).

Wondering if `--dry-run` should also be passed along.

**Comment by 23Skidoo** [comment] 2016-08-06 16:01
The problem is that `sandbox init` and other subcommands don't support `--list-options`. I believe that if #1257 was implemented, bash completion would work as is.

**Comment by gbaz** [comment] 2021-08-28 04:46
closing as obsolete

**Closed by gbaz** 2021-08-28 04:46 UTC
Labels: type: bug, cabal-install: autocomplete
