### ISSUE TITLE
--preference is  not taken into account for packages that have preferred versions on Hackage

### ISSUE THREAD

**Issue by sol** [haskell/cabal#2922] opened 2015-11-13 08:11 UTC
Steps to reproduce:

```
$ cabal sandbox init && cabal install primitive --dry-run --preference="primitive == 0.5.4.0"
Writing a default package environment file to
~/foo/cabal.sandbox.config
Creating a new sandbox at ~/foo/.cabal-sandbox
Resolving dependencies...
In order, the following would be installed (use -v for more details):
primitive-0.6.1.0
```

**Comment by sol** [comment] 2015-11-13 08:12
cc @kosmikus

**Comment by kosmikus** [comment] 2015-11-13 08:21
Looks like preferences aren't properly merged before they're applied. And Hackage preferences being applied last (which is probably just an accident) then gives them priority.

Should probably be relatively easy to fix.

**Comment by lspitzner** [comment] 2015-11-16 21:55
duplicate of #2645, is it not?

**Comment by 23Skidoo** [comment] 2015-11-17 04:50
Closing in favour of #2645.

**Closed by 23Skidoo** 2015-11-17 04:50 UTC
Labels: cabal-install, duplicate, easy, solver
