### ISSUE TITLE
Suggestion: make `cabal new-install` install to ~/.local/bin (or use XDG directories more generally)

### ISSUE THREAD

**Issue by athas** [haskell/cabal#5614] opened 2018-10-09 10:17 UTC
For as long as I've been using Cabal, `cabal install` has installed to `~/.cabal/bin`.  This is fine if you know that's what it does, as it is little work to add it to your `PATH`.  It *is* still work, though, and most other languages/build tools seem to be standardising on `~/.local/bin` (it is part of [the systemd file-hierarchy spec](https://www.freedesktop.org/software/systemd/man/file-hierarchy.html) which is slowly becoming the default as far as I can see).  I think it would be better if `cabal install` installed to this location as well, as it would increase the likelyhood that the installation directory is already on the PATH of the user.

**Comment by athas** [comment] 2019-11-04 09:41
This missed 3.0, unfortunately.  Is there still interest in doing this or should I close the issue?  I still personally think the use of ~/.cabal/bin is a UX defect.

**Comment by Mikolaj** [comment] 2021-06-25 19:17
Duplicate of #680.

**Closed by Mikolaj** 2021-06-25 19:17 UTC

**Comment by Mikolaj** [comment] 2021-06-25 19:21
Duplicate of #680.

**Comment by Mikolaj** [comment] 2021-06-25 19:21
Duplicate of #680
