### ISSUE TITLE
Spurious warning about internal library dependency?

### ISSUE THREAD

**Issue by glguy** [haskell/cabal#4169] opened 2016-12-14 18:02 UTC
When trying to build https://github.com/glguy/advent2016/blob/master/advent2016.cabal with today's cabal-install from the master branch I get what I think might be spurious warnings about internal dependencies

Also I'm getting interleaved output of these warnings due to concurrent builds.

```
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - advent2016-0.1.0.0 (lib) (first run)
 - advent2016-0.1.0.0 (exe:Day14) (first run)
 - advent2016-0.1.0.0 (exe:Day13) (first run)
 - advent2016-0.1.0.0 (exe:Day12) (first run)
 - advent2016-0.1.0.0 (exe:Day11) (first run)
 - advent2016-0.1.0.0 (exe:Day10) (first run)
 - advent2016-0.1.0.0 (exe:Day09) (first run)
 - advent2016-0.1.0.0 (exe:Day08) (first run)
 - advent2016-0.1.0.0 (exe:Day07) (first run)
 - advent2016-0.1.0.0 (exe:Day06) (first run)
 - advent2016-0.1.0.0 (exe:Day05) (first run)
 - advent2016-0.1.0.0 (exe:Day04) (first run)
 - advent2016-0.1.0.0 (exe:Day03) (first run)
 - advent2016-0.1.0.0 (exe:Day02) (first run)
 - advent2016-0.1.0.0 (exe:Day01) (first run)
Configuring component lib from advent2016-0.1.0.0...
Configuring component exe:Day14 from advent2016-0.1.0.0...
Preprocessing executable 'Day14' for advent2016-0.1.0.0...
Preprocessing library advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day14.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day14/build/Day14/Day14-tmp/Main.o )
[1 of 3] Compiling GridCoord        ( lib/GridCoord.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/build/GridCoord.o )
[2 of 3] Compiling Search           ( lib/Search.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/build/Search.o )
[3 of 3] Compiling Common           ( lib/Common.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/build/Common.o )
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day14/build/Day14/Day14 ...
Configuring component exe:Day13 from advent2016-0.1.0.0...
Configuring component exe:Day12 from advent2016-0.1.0.0...
Configuring component exe:Day11 from advent2016-0.1.0.0...
Configuring component exe:Day09 from advent2016-0.1.0.0...
Configuring component exe:Day08 from advent2016-0.1.0.0...
Configuring component exe:Day07 from advent2016-0.1.0.0...
Configuring component exe:Day10 from advent2016-0.1.0.0...
Configuring component exe:Day06 from advent2016-0.1.0.0...
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internalWarning: The package ha
s lai bvrearrsyi:o na drvaenngte2 0f1o6r  -aa ndye p&e&n d=e=n0c.y1 .o0n. 0a,n  aidnvteenrtn2a0l16 -any && ==0.1.0.
0,library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,

aaddvveent2016 -anyn &t&2 0==0.1.0.01, 6a d-vent20a16n y- a&n&y  =&&= 0=.=10..01..00,. 0, advent2016 -any &&advent20
1=6= 0-.a1n.y0 .&0&,  =a=d0v.e1n.t02.001,6  a-davneyn t&2&0 1=6= 0-.a1n.y0 .&0&, advent2016
 =-=a0n.y1 .&0&. 0=,=0.1.0.0,
a dvaednvte2n0t126 0-1a6ny  -&a&ny && ==0.1.0.0, adven t=2=001.61 .-0.0, advent2016 -any a&n&y  =&=&0 .1.==0.1.0.0,0.0, advent2016
 a-davneyn t2&0&16 -any && =
=0=.=10..01..00,. 0a,d vaednvte2n0t162 0-1a6n y- a&n& y= =&0&. 1=.=00..01,. 0a.d0v,e natd2v0e1n6t 2-0a1n6y  -&a&ny && ==0
.=1=.00..10.,0.0, advent2016 -any && ==0
.a1d.v0e.n0t,2 0a1d6v e-natn20y1 6& &- an=y= 0&.&1 .=0=.00..1 .T0.h0i,s version range has no
 asdevmeanntt2i0c1 6m e-aannyi n&g&  a=n=d0.
1c.a0.n0 .b eT hriesm voevresdi.o
n range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Preprocessing executable 'Day07' for advent2016-0.1.0.0...
Preprocessing executable 'Day11' for advent2016-0.1.0.0...
Preprocessing executable 'Day12' for advent2016-0.1.0.0...
Preprocessing executable 'Day13' for advent2016-0.1.0.0...
Preprocessing executable 'Day06' for advent2016-0.1.0.0...
Preprocessing executable 'Day09' for advent2016-0.1.0.0...
Preprocessing executable 'Day10' for advent2016-0.1.0.0...
Preprocessing executable 'Day08' for advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day13.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day13/build/Day13/Day13-tmp/Main.o )
[1 of 1] Compiling Main             ( Day12.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day12/build/Day12/Day12-tmp/Main.o )
[1 of 1] Compiling Main             ( Day11.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day11/build/Day11/Day11-tmp/Main.o )
[1 of 1] Compiling Main             ( Day06.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day06/build/Day06/Day06-tmp/Main.o )
[1 of 1] Compiling Main             ( Day07.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day07/build/Day07/Day07-tmp/Main.o )
[1 of 1] Compiling Main             ( Day09.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day09/build/Day09/Day09-tmp/Main.o )
[1 of 1] Compiling Main             ( Day10.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day10/build/Day10/Day10-tmp/Main.o )
[1 of 1] Compiling Main             ( Day08.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day08/build/Day08/Day08-tmp/Main.o )
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day13/build/Day13/Day13 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day06/build/Day06/Day06 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day11/build/Day11/Day11 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day09/build/Day09/Day09 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day07/build/Day07/Day07 ...
Configuring component exe:Day05 from advent2016-0.1.0.0...
Configuring component exe:Day04 from advent2016-0.1.0.0...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day10/build/Day10/Day10 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day08/build/Day08/Day08 ...
Configuring component exe:Day03 from advent2016-0.1.0.0...
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day12/build/Day12/Day12 ...
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Preprocessing executable 'Day05' for advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day05.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day05/build/Day05/Day05-tmp/Main.o )
Configuring component exe:Day02 from advent2016-0.1.0.0...
Preprocessing executable 'Day04' for advent2016-0.1.0.0...
Configuring component exe:Day01 from advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day04.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day04/build/Day04/Day04-tmp/Main.o )
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day05/build/Day05/Day05 ...
Preprocessing executable 'Day03' for advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day03.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day03/build/Day03/Day03-tmp/Main.o )
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Warning: The package has a version range for a dependency on an internal
library: advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any &&
==0.1.0.0, advent2016 -any && ==0.1.0.0, advent2016 -any && ==0.1.0.0,
advent2016 -any && ==0.1.0.0. This version range has no semantic meaning and
can be removed.
Preprocessing executable 'Day02' for advent2016-0.1.0.0...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day04/build/Day04/Day04 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day03/build/Day03/Day03 ...
[1 of 1] Compiling Main             ( Day02.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day02/build/Day02/Day02-tmp/Main.o )
Preprocessing executable 'Day01' for advent2016-0.1.0.0...
[1 of 1] Compiling Main             ( Day01.hs, /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day01/build/Day01/Day01-tmp/Main.o )
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day02/build/Day02/Day02 ...
Linking /Users/emertens/Source/advent2016/dist-newstyle/build/x86_64-osx/ghc-8.0.1/advent2016-0.1.0.0/c/Day01/build/Day01/Day01 ...
argolis:~/Source/advent2016
$ 
```

**Comment by 23Skidoo** [comment] 2016-12-14 18:06
Yep, I've also seen multiple times. Would be nice to fix for 2.0.

**Comment by ezyang** [comment] 2016-12-14 18:09
I think the problem is cabal-install is editing the Cabal file to add an extra constraint (based on the dep solve result?) but it's also editing internal deps. I think the right thing to do is to not edit in this way.

**Comment by quasicomputational** [comment] 2018-09-01 07:50
Related: #5119.

**Comment by fgaz** [comment] 2020-05-22 11:52
Closing as duplicate of #5119, which contains the majority of info

**Closed by fgaz** 2020-05-22 11:52 UTC
Labels: type: bug
