### ISSUE TITLE
cabal configure && cabal build of Cabal fails with corrupt package config file with top-level Cabal-1.20.0.2/3

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#2114] opened 2014-09-18 21:44 UTC
When using most recent released Cabal:

```
[ezyang@hs01 Cabal]$ cabal configure
Resolving dependencies...
(snip)
[ezyang@hs01 Cabal]$ cabal build
Saved package config file seems to be corrupt. Configuring with default flags.
If this fails, please run configure manually.
```

This seems to be related to Cabal's bootstrapping process, since if you run `dist/setup/setup build` it works fine.

**Comment by RyanGlScott** [comment] 2016-01-19 14:54
This is still happening for me with `cabal-install-1.23` and `Cabal-1.23` from [hvr's PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc) whenever I do a `cabal configure` followed by a `cabal build` of certain libraries with a `Custom` build type. I can replicate this with @ekmett's [`gc`](https://github.com/ekmett/gc) repo pretty easily, since the library has no dependencies:

```
$ cabal get gc
Downloading gc-0...
Unpacking to gc-0/
$ cd gc-0/
$ /opt/cabal/1.24/bin/cabal configure --with-ghc /opt/ghc/8.0.1/bin/ghc
Resolving dependencies...
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
Linking ./dist/setup/setup ...
Configuring gc-0...
$ /opt/cabal/1.24/bin/cabal build
Saved package config file seems to be corrupt. Configuring with default flags.
If this fails, please run configure manually.
Resolving dependencies...
Configuring gc-0...
Building gc-0...
Preprocessing library gc-0...
[1 of 1] Compiling System.Mem.Manager ( src/System/Mem/Manager.hs, dist/build/System/Mem/Manager.o )
$ /opt/cabal/1.24/bin/cabal --version
cabal-install version 1.23.0.0
compiled using version 1.23.0.0 of the Cabal library
```

This issue also [prevents `lens` from building successfully](https://travis-ci.org/ekmett/lens/jobs/103009076#L479) on Travis with GHC 8.0.1-rc.

**Comment by ezyang** [comment] 2016-01-19 17:28
Yep, I can repro.

**Comment by ezyang** [comment] 2016-01-19 17:40
I believe that the problem is that the Cabal library shipped with GHC 8.0, and the Cabal library that hvr's PPA built with have incompatible `LocalBuildInfo` formats, but the same version number (since it's the 1.23.0.0 development series.) There's not much we can do here, and the problem should go away when we make proper releases and stop doing snapshots. At least, this is why the problem is happening on my system.

@RyanGlScott Here is a workaround for you:

1. Grab a copy of HEAD Cabal
2. "cabal install Cabal -w ghc-8.0"
3. "cabal install cabal-install -w ghc-8.0" (In my experience, this will pick out the user-installed Cabal even if they have the same version, but if it does not then your bug will not be fixed)
4. Try again

**Comment by RyanGlScott** [comment] 2016-01-19 19:27
Sorry for being vague: I am using GHC 8.0.1 (version `8.0.0.20160111+git.0.497454f-10~vivid `, built on 2016-01-11) and `cabal-install-1.24` (version `1.23+git20160113.0.ccd618e~vivid`, built on 2016-01-14) from the PPA. (I also tried `cabal-install-head`, version `1.23+git20160113.0.ccd618e~vivid`, built on 2016-01-13, and experienced the same issue with GHC 8.0.1).

And your workaround does, indeed, work!

**Comment by ezyang** [comment] 2016-01-19 21:22
OK, I guess there's not much Cabal can do (because multiple versions of Cabal with the same version number are... not supposed to happen), but maybe we can adopt some sort of better release management practices (e.g. after GHC 8.0.1 was released, we should have immediately bumped the version number) so I'll leave this open for now.

**Comment by ttuegel** [comment] 2016-01-19 21:32
> maybe we can adopt some sort of better release management practices (e.g. after GHC 8.0.1 was released, we should have immediately bumped the version number)

I think it would minimize everyone's pain if we commit ourselves to bumping (at least) the patch level whenever the `LocalBuildInfo` format changes. Yes, we might end up with `Cabal-1.25.0.134` in some development branch, but who really cares?

**Comment by ezyang** [comment] 2016-01-19 21:59
I'm OK with this, but I'd prefer it if we could figure out how to get Travis to bleat if you change any of the binary formats. Here's a proposal:

1. For every data structure which has a binary format which is shared across the Cabal/cabal-install boundary, we keep checked in a binary serialized version of it based on some sentinel value (it could be `mempty`, or it could be a custom value we write for each of them.)
2. We add a script to re-generate these binary serialized versions and admonishes you to bump the version.
3. Travis checks if this binary serialized version has changed (similar to the current `misc` script for checking if `other-files` is correct.)

FWIW, we should NOT bump the patch level, this is a BC-incompatible change so we should bump the appropriate number.

**Comment by hvr** [comment] 2016-01-19 22:22
bumping some part of the dev-branch sounds good to me, that would also help in other scenarios when using multiple dev-branch snapshot builds...

**Comment by ezyang** [comment] 2016-01-19 22:28
Also note: bumping the version forces a rebuild of EVERYTHING. So we don't want to do it too frequently.

**Comment by ttuegel** [comment] 2016-01-20 00:52
> FWIW, we should NOT bump the patch level, this is a BC-incompatible change so we should bump the appropriate number.

If we're going to follow the PVP, we would bump the major version, i.e. `1.25 -> 1.27` every time one of the types changes. I don't think we need to follow the PVP for *development* versions as long as we document what we are doing. I was going to suggest we bump patch (`1.25.0.0 -> 1.25.0.1`) for internal changes and minor (`1.25.0.1 -> 1.25.1.0`) for release candidates, since that's the problem here. Note that our development versions *already* ignore the PVP, so transitioning to a documented system that still ignores the PVP is a net gain and not a regression.

> Also note: bumping the version forces a rebuild of EVERYTHING. So we don't want to do it too frequently.

I'm not sure what everything we're talking about. For a development version of Cabal, that should just trigger a rebuild of Cabal and cabal-install, but that doesn't seem like a big deal to me. Could you clarify?

**Comment by ezyang** [comment] 2016-01-20 00:56
That's what I mean. It is modestly annoying to rebuild all of Cabal (12min) so I avoid it when I can. But you are right, it is not such a big deal. (It would be a big deal if you had to do it every edit or commit.)

**Comment by ttuegel** [comment] 2016-01-20 01:19
> That's what I mean. It is modestly annoying to rebuild all of Cabal (12min) so I avoid it when I can. But you are right, it is not such a big deal. (It would be a big deal if you had to do it every edit or commit.)

Oh yes, I see what you mean. I really just mean changing the version every time a binary-incompatible change gets merged back into master.

**Comment by 23Skidoo** [comment] 2016-02-22 23:28
Closing in favour of #3181.

**Closed by 23Skidoo** 2016-02-22 23:28 UTC
Labels: cabal-install
