### ISSUE TITLE
Need for recompilation not detected in some situations

### ISSUE THREAD

**Issue by sol** [haskell/cabal#5009] opened 2018-01-08 18:20 UTC
**Steps to reproduce:**

Given the following source files:

```haskell
-- driver/Foo.hs 
module Main where

main :: IO ()
main = putStrLn "foo"
```
```haskell
-- driver/Bar.hs 
module Main where

main :: IO ()
main = putStrLn "bar"
```

And a cabal file:
```cabal
name:           hello
version:        0.0.0
build-type:     Simple
cabal-version:  >= 1.10

flag foo
  default: True

executable hello
  build-depends: base
  if flag(foo)
    main-is: driver/Foo.hs
  else
    main-is: driver/Bar.hs
    other-extensions: Foo
  default-language: Haskell2010
```

We perform the following steps:

```
$ cabal build > /dev/null && ./dist/build/hello/hello
foo
```

Now we change the cabal file to:

```
name:           hello
version:        0.0.0
build-type:     Simple
cabal-version:  >= 1.10

flag foo
  default: True

executable hello
  build-depends: base
  if flag(foo)
    main-is: driver/Foo.hs
    other-extensions: Foo
  else
    main-is: driver/Bar.hs
  default-language: Haskell2010
```

And compile and run again:

```
$ cabal build > /dev/null && ./dist/build/hello/hello
```

Expected output: `bar`
Actual output: `foo`

Not sure who is to blame, GHC or Cabal.

**Why is this a problem?**

In general, GHCs recompilation detection works very well, this is why I rely on it.  The more it hurts when you rely on it and it does not work.

I haven't looked into it, but I assume the bug is due to both source files producing files with the same names when compiled (`Main.o`, `Main.hi`), GHC does simple timestamp checking, determines that the existing files are newer than the source file and does not recompile.

**Comment by gbaz** [comment] 2018-01-08 18:22
should the second cabal file have a different default for the flag? (also, it would be good to check this with new-build, which should be more principled about recording things like flags...)

**Comment by sol** [comment] 2018-01-08 18:27
> should the second cabal file have a different default for the flag?

No.

**Comment by gbaz** [comment] 2018-01-08 18:34
Ok, color me confused. Why should just changing the other-extensions field change the build outcome?

**Comment by gbaz** [comment] 2018-01-08 21:36
ah, ok, this was explained to me. The other-extension field is not satisfiable, causing the solver to backtrack and toggle the flag. So this is an instance of the chosen flags not being recorded in a rebuild, just at one step remove...

(the name-clash between the two "Foo" things confused me as to what the intended effect was)

**Comment by gbaz** [comment] 2018-01-09 03:29
I've confirmed this happens with new-build too, and it happens without the other-extension field as well but just toggling the default for the `foo` flag directly, and furthermore it happens with HEAD. Good bug!

**Comment by gbaz** [comment] 2018-01-09 03:42
So here's the wild bit. I ran this with -v3 and saw that the key line is the following:

> /usr/local/bin/ghc --make -fbuilding-cabal-package -O -static -outputdir /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -odir /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -hidir /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -stubdir /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -i -i/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -i. -i/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/autogen -i/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/global-autogen -I/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/autogen -I/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/global-autogen -I/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello-tmp -optP-include -optP/Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/autogen/cabal_macros.h -hide-all-packages -Wmissing-home-modules -no-user-package-db -package-db /Users/gershom/.cabal/store/ghc-8.2.1/package.db -package-db /Users/gershom/devel/scr/cabalbug/dist-newstyle/packagedb/ghc-8.2.1 -package-db /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/package.conf.inplace -package-id base-4.10.0.0 -XHaskell2010 ./Foo.hs -o /Users/gershom/devel/scr/cabalbug/dist-newstyle/build/x86_64-osx/ghc-8.2.1/hello-0.0.0/x/hello/build/hello/hello -hide-all-packages

Now, if I change the "Foo.hs" to "Bar.hs" but otherwise leave everything unchanged, then it still leaves the executable as the one that outputs "foo"! So this seems on first inspection to be something that's a problem with GHC itself. I.e. when the flags change, cabal is smart enough to recompile with the new settings, but somehow what looks like passing a different command to GHC nonetheless leaves the same executable!

**Comment by gbaz** [comment] 2018-01-09 03:51
Minimal case:

> ghc --make Foo.hs -o hello
> ghc --make Bar.hs -o hello

This suffices to reproduce this behavior.

**Comment by gbaz** [comment] 2018-01-09 04:01
Ticket filed upstream: https://ghc.haskell.org/trac/ghc/ticket/14651

In the meantime, I would suggest that whenever cabal recompiles an executable, it first removes the existing target, as a workaround.

**Comment by sol** [comment] 2018-01-09 06:02
> Once the {Foo,Bar}.{hi,o} files are created by the first run of each command, subsequent commands don't cause rebuilds.

I don't think `{Foo,Bar}.{hi,o}` files are created.  The module name is `Main` so as I stated above, the corresponding build products should be `Main.{hi,o}` which I assume is the source of the "bug".

**Comment by gbaz** [comment] 2018-01-09 06:04
I don't think this is correct if you look at the -v3 trace. Also look at my minimal repro above with just `ghc --make` -- that shows the Foo.hi and Foo.o files lying around.

**Comment by sol** [comment] 2018-01-09 06:34
Ah, thats actually interesting.  You are right for your minimal example.  I still see that on my box cabal will create `Main.{hi,o}`.  This seems to happen as soon as you pass `-outputdir` to GHC.

```
$ ghc --make Foo.hs -o hello -outputdir .
[1 of 1] Compiling Main             ( Foo.hs, Main.o )
Linking hello ...
```

**Comment by sol** [comment] 2018-01-09 06:38
I haven't tried yet, but I imagine that it may be possible to trigger a similar bug by changing the `hs-source-dir`.

**Comment by sol** [comment] 2018-01-09 06:52
> I haven't tried yet, but I imagine that it may be possible to trigger a similar bug by changing the hs-source-dirs.

This actually works as expected, as a flag change is detected (I guess the `-i`):

```
[2 of 2] Compiling Foo              ( bar/Foo.hs, dist/build/Foo.o ) [flags changed]
```

**Comment by gbaz** [comment] 2018-01-09 06:54
Cabal detects the flag change in the failing case too! (you can see this with -v3). The problem is the behavior of GHC means that it ends up running something like my minimal example above (but with way more flags passed in).

**Comment by 23Skidoo** [comment] 2018-01-31 10:29
Closing as a GHC bug, feel free to reopen if you disagree.

**Closed by 23Skidoo** 2018-01-31 10:29 UTC
Labels: Cabal: cmd/build, blocked: upstream, type: bug
