### ISSUE TITLE
Change the default behavior of `cabal upload`

### ISSUE THREAD

**Issue by jfischoff** [haskell/cabal#2158] opened 2014-10-11 07:15 UTC
Currently cabal upload just uploads a premade sdist. 

I think the default behavior should change to make it easier to upload to Hackage, and to distribute the work of documentation building to clients.

I think generating and uploading a sdist with doc should be the default. If I want to upload an older version, that should be possible with an additional flag, e.g.

```bash
$ cabal upload 
```
would be equivalent to 
```bash
$ cabal sdist && cabal upload dist/some-version.tar.gz && cabal haddock && upload-docs-by-glguy
```
The old behavior can be regained with.
```bash
$ cabal upload --no-docs --with-sdist=dist/some.tar.gz
```
Less to type for the typical case, and I think offloading work from Hackage to clients gives Hackage more resources to scale.

Originally proposed here: https://github.com/haskell/cabal/issues/2156#issuecomment-58726528

**Comment by ttuegel** [comment] 2015-04-24 13:47
Duplicate of #2080.

**Closed by ttuegel** 2015-04-24 13:47 UTC
Labels: cabal-install, enhancement, high-priority, library
