### ISSUE TITLE
'configure' having no effect

### ISSUE THREAD

**Issue by georgefst** [haskell/cabal#6411] opened 2019-12-09 17:19 UTC
I have the following `cabal.project`:

```
packages:
    a
```

Running `cabal build a --builddir=build` creates build products in `build`. But `cabal configure --builddir=build`, followed by `cabal build a`, uses the default (`dist-newstyle`).

Cabal 3.0.0.0 on Ubuntu 16.04

**Comment by jneira** [comment] 2019-12-12 07:16
I think the cause of this is: https://github.com/haskell/cabal/issues/5271
`cabal configure` writes correctly `builddir: build` in `cabal.project.local` but that option is ignored afterwards (also if you put it directly in the main `cabal.project`)

**Comment by phadej** [comment] 2019-12-12 12:00
Duplicate of https://github.com/haskell/cabal/issues/5271, *Supporting builddir in cabal.project*

**Closed by phadej** 2019-12-12 12:00 UTC
