### ISSUE TITLE
Cabal uses hardcoded not relative path in package descriptors.

### ISSUE THREAD

**Issue by wdanilo** [haskell/cabal#1542] opened 2013-10-14 13:03 UTC
Hi!
When invoking 'cabal install <pkgname>' cabal executes ghc-pkg several times, in particular executes 'ghc-pkg update - <some other options>' passing package descriptors by stdin.

The problem is, that some fields, like 'import-dirs' use hardcoded paths, like:
/home/myuser/local-ghc-installation/lib/x86_64-linux-ghc-7.6.3/testlib-0.1

instead of:
${pkgroot}/testlib-0.1

the same problem occurs with fields haddock-interfaces and haddock-tml, where we could replace the beggining of the path with "${pkgroot}/../../share/doc/ <...>"

This would make the installation of GHC (with packages installed by cabal) movable on Linux boxes.

**Comment by mietek** [comment] 2015-03-14 23:41
@christiaanb: Is this a duplicate of #462?  Does [PR#2255](https://github.com/haskell/cabal/pull/2255) implement all or any of the above?

**Comment by christiaanb** [comment] 2015-03-15 10:24
@mietek: I wouldn't say this is a duplicate of #462, but the solution to #462(which #2255 partially implements) does solve the problem described in this issue. However, some of the use-cases described here, such as creating the HP installer are just out of reach because because GHC installer doesn't use/know the `--enable-relocatable` flag, but more importantly, because of what I said in https://github.com/haskell/cabal/pull/2255#issuecomment-66086160:

One (major) flaw in the current implementation (#2255) is that in handles libraries with `data-files` poorly. One such example would be `pandoc`. The reason is that data-files are found relative to the `bin-dir`. This poses two problems:

1. `data-files` cannot be located from within `ghc` binary (`ghci`, `runhaskell`, etc.) when the library is installed in:
  * The global database: The `ghc` binary (which `System.Environment.getExecutablePath` will resolve to) is located in `lib/ghc-<version>/bin`, not `bin`.
  * Any other  database: The ghc binary is definitely not prefix relative to any package database other than the global database.
2. `data-files` cannot be located by a binary installed in a location that is not prefix-relative to the library.

Problem 2. could be solved by _wrapper_ schell scripts, such as the `ghc` script in ghc's `bin` directory. But I wouldn't know how to solve problem 1 other than embedding the data files in the library (http://hackage.haskell.org/package/file-embed)

**Comment by ttuegel** [comment] 2015-04-23 23:22
See #462.

**Closed by ttuegel** 2015-04-23 23:22 UTC
Labels: enhancement
