### ISSUE TITLE
worldfile written with incorrect case

### ISSUE THREAD

**Issue by bos** [haskell/cabal#854] opened 2012-05-24 05:52 UTC
(Imported from [Trac #864](http://hackage.haskell.org/trac/hackage/ticket/864), reported by @benmachine on 2011-07-17)

If I issue a command like <tt>cabal install bindings-dsl</tt>, cabal will happily install <tt>bindings-DSL</tt> and write <tt>bindings-dsl</tt> to the world file. Then when I <tt>cabal install --dry-run world</tt>, I get

<pre class="wiki">Warning: The following 'world' packages will be ignored because they refer to
packages that cannot be found: bindings-dsl
</pre>This seems to be because of the discrepancies in capitalisation -- the world file is case-sensitive, the install command isn't.

**Comment by BardurArantsson** [comment] 2015-06-25 17:57
I can confirm that this is actually still an issue. However, is it important enough to fix or should it be dropped?

**Comment by bmillwood** [comment] 2015-07-12 16:31
Can we just change `PackageTargetNamed` to `PackageTargetNamedFuzzy` in [`expandUserTarget`](https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Targets.hs#L419)?

**Comment by phadej** [comment] 2015-07-12 22:03
@bmillwood it would be better to write right cased package name in the first place. Someone could introduce differently cased package later in the future, and fuzzy match won't work anymore.

**Comment by bmillwood** [comment] 2015-07-26 14:57
That would be better indeed, but also much more work. My suggested change is pretty much a strict improvement over the status quo, I think, since the status quo doesn't prevent you installing the wrong package in the way you suggest.

**Comment by phadej** [comment] 2015-07-30 16:09
I could try to implement my idea tomorrow.

**Comment by BardurArantsson** [comment] 2015-08-21 20:06
I think the problem here is that cabal is actually happy to install MixedCasething where the package is actually called mixedcaseThing? In effect I'm saying: let's drop any kind of "fuzzy" (i.e. wrong) matching for target packages.

That's at least *simple* and  *understandable* and doesn't lead to bizarre follow-on errors. I mean the explanation can be summarized in very few words: "Package names are case sensitive".

Actual real-life conflicts on non-case-sensitive file systems are already *very* rare given the current Hackage database. Rarer still if Hackage mandates a no-duplicates policy (ignoring case). I think it makes this problem mostly academic...?!?

@phadej  Do you agree with this sentiment and would you want to implement it? (I'm not in a position to merge anything to master, but I think this is really the most sensible approach. I'll happily go to bat, arguing for the whole ignore-case-up-front approach.)

**Comment by phadej** [comment] 2015-08-22 22:04
@BardurArantsson it would result in unfriendly UX:
```
$ cabal install quickcheck
ERR: did you mean QuickCheck
$ cabal install QuickCheck
```

It's the same as requiring user to do manual `configure`, that is recently fixed too.

The code how cabal-install creates an "what to do" (which should be written to worldfile) from "what user said on the command line" (which is written now) is a bit messy. I unfortunately didn't had enough time (and though) to do that.

**Comment by BardurArantsson** [comment] 2015-08-27 14:57
Let's remember that cabal-install users are *programmers*. The concept of case sensitivity should not be foreign to them.

At least my suggestion gives users an *obvious* solution and doesn't lead to bizarre follow-up errors which may be extremely hard to diagnose for people who are not intimately familiar with cabal-install internals.

Remember: The current situation is *clearly* a bug, but nobody has come up with a satisfactory solution since 2011. That signals to me that we should declare that Cabal doesn't not attempt "case folding" and just remove the nonsense that leads to this bug. I'd be absolutely fine with having an "enhancement" level issue left in the issue tracker about implementing case insensitivity *properly* (obviously pointing to this issue and perhaps others around case insensitivity) -- though I venture to guess nobody will actually come around to implementing that either.

**Comment by gbaz** [comment] 2021-08-28 04:38
closing as obsolete

**Closed by gbaz** 2021-08-28 04:38 UTC
Labels: type: bug, cabal-install: other
