### ISSUE TITLE
new-haddock after new-build does not work

### ISSUE THREAD

**Issue by yav** [haskell/cabal#4992] opened 2018-01-02 18:48 UTC
Hello,
this is what I did:

1. `cabal new-build my-package`: builds the package successfully.
2. Now I want the docs:  `cabal new-haddock my-package`.   Cabal says `Up to date`, but there is no documentation generated anywhere (or at least, `find --name '*.html'` does not return anything :-)

It looks like there is a confusion between the package being built, and the documentation for the package being built.

**Comment by dalaing** [comment] 2018-01-02 22:44
This looks like a duplicate of #4506.

**Comment by 23Skidoo** [comment] 2018-01-03 12:49
Closing in favour of #4506.

**Closed by 23Skidoo** 2018-01-03 12:49 UTC
