### ISSUE TITLE
new-build busted on macOS Sierra

### ISSUE THREAD

**Issue by angerman** [haskell/cabal#4653] opened 2017-08-01 09:04 UTC
As mentioned in #4651, new-build's dynamic library paths end up being quite long,
this then easily exhausts the load command size of the shared library with messages
like:

```
malformed mach-o: load commands size (33576) > 32768
```

I don't really know how to fix this properly. We'd need to drastically reduce the length
of library names :-/

**Comment by 23Skidoo** [comment] 2017-08-01 09:46
This is duplicate of #4263.

**Closed by 23Skidoo** 2017-08-01 09:46 UTC
Labels: resolution: duplicate
