### ISSUE TITLE
"Permission denied" error: cabal v2-clean + windows + source-repository-package

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#6933] opened 2020-06-29 22:19 UTC
**Describe the bug**

* In a project with a `source-repository-package`,  after whatever command that triggers the checkout of the remote package, a `cabal v2-clean` fails with:
```
D:\dev\ws\haskell\hls\dist-newstyle\src\cabal-plan-42253b883cc08e6b\.git\objects\pack\pack-c3bf961b7416d8452ca36187ab82474e84f77980.pack: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:DeleteFile "\\\\?\\D:\\dev\\ws\\haskell\\hls\\dist-newstyle\\src\\cabal-plan-42253b883cc08e6b\\.git\\objects\\pack\\pack-c3bf961b7416d8452ca36187ab82474e84f77980.pack": permission denied (Acceso denegado.)
```
* `rmdir .\dist-newstyle -for -rec` deletes the directory succesfully

**To Reproduce**

```
> cabal v2-build any-pkg-with-source-repo-package
> cabal v2-clean
```

**Expected behavior**

`cabal clean` should delete the directory `dist-newstyle`

**System information**
 - Operating system: windows 10
 - `cabal-3.2.0.0`, `ghc-8.8.3` 
 - git version: 2.27.0.windows.1

**Comment by fendor** [comment] 2023-03-15 15:30
**To Reproduce**
Steps to reproduce the behavior:

```bash
$ mkdir some-dir
$ cd some-dir
$ cabal init -n
$ cat cabal.project
packages: ./

source-repository-package
  type:git
  location: https://github.com/pepeiborra/ekg-json
  tag: 7a0af7a8fd38045fd15fb13445bdcc7085325460
```

Now run the commands:
```
$ cabal v2-build
$ cabal v2-clean
D:\Privat\Documents\programming\haskell\cabal-bug-extra-sources\dist-newstyle\src\ekg-json-22461580dac5d569\.git\objects\pack\pack-e4512fa369e17e4072b6931011453082eace5e88.pack: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:DeleteFile "\\\\?\\D:\\Privat\\Documents\\programming\\haskell\\cabal-bug-extra-sources\\dist-newstyle\\src\\ekg-json-22461580dac5d569\\.git\\objects\\pack\\pack-e4512fa369e17e4072b6931011453082eace5e88.pack": permission denied (Access is denied.)
```

**Comment by avently** [comment] 2023-09-15 11:24
Any news about this issue? Actually, it stops from building on Windows (happens with cabal build). 
dist-newstyle/src/somePackage/.git/modules/someModule/objects/pack/packFileName.pack has permissions r-r-r, which means it can not be deleted by "directory" package, see for more info: 
https://github.com/commercialhaskell/stack/issues/2426
If you want to build, you have to delete such pack file yourself or at least make it writable. All builds in Github actions fails and need workaround to be applied.

**Comment by jasagredo** [comment] 2024-07-18 21:33
Closing as a duplicate of #10182 (which IMO has more concrete information)

**Closed by jasagredo** 2024-07-18 21:33 UTC
Labels: type: bug, platform: windows, attention: pr-welcome, cabal-install: cmd/clean, cabal-install: source-repository-package
