### ISSUE TITLE
cabal v2-install does not work with conditionally buildable executable

### ISSUE THREAD

**Issue by andrewthad** [haskell/cabal#6014] opened 2019-04-25 15:25 UTC
Here's an example of how to observe this problem:

```
$ git clone https://github.com/andrewthad/ping
$ cd ping
$ cabal v2-install -f+application
Resolving dependencies...
Up to date
Warning: You asked to install executables, but there are no executables in
targets: . Perhaps you want to use --lib to install libraries instead.
```

But there is an executable. It happens to be hidden behind a flag like this:

```
executable multiping
  if flag(application)
    buildable: True
  else
    buildable: False
  main-is: Multiping.hs
```

I don't want users to incur all the extra dependencies of the executable, since it's just a CLI application exposing the library's functions. With `cabal v2-build -f+application`, the application does successfully get built. So I suspect that `cabal v2-install` may be forgetting to apply flags.

**Comment by phadej** [comment] 2019-04-25 17:10
Try

```
cabal v2-install -f+application .
```

(Note the dot).

If that helps, than this is a duplicate of https://github.com/haskell/cabal/issues/5978

**Closed** 2019-06-20 20:00 UTC
Labels: cabal-install: cmd/install, cabal-install: nix-local-build, type: bug
