### ISSUE TITLE
Print out full version of installed packages in the "could not resolve" explanation

### ISSUE THREAD

**Issue by hansroland** [haskell/cabal#6465] opened 2019-12-25 09:42 UTC
**The issue**
In error messages explaining why cabal could not install/build a package, like: 

```
cabal: Could not resolve dependencies:
[__0] trying: base-4.13.0.0/installed-4.1... (user goal)
...
```

hiding the installed version as  `installed-4.1...` is very annoying! 

**To Reproduce**

```
$ cabal v2-install ghc-vis-0.9
```

**Expected behavior**

Print **always** the full version number eg `4.10.1.0`

**System information**
 - Operating system: Linux Debian 9 (64 bit)
 - The Glorious Glasgow Haskell Compilation System, version 8.8.1
 - cabal-install version 3.0.0.0
 - compiled using version 3.0.0.0 of the Cabal library 

**Additional context**
In the above example it's very easy to spot the problem! However there are cases (which need more files and steps to reproduce), where the missing version info is really important!

The essence of cabal are the versions of the dependencies. Therefore the version numbers should not be hidden from the user.

**Comment by grayjay** [comment] 2019-12-29 02:32
This is a duplicate of #5892.

**Closed by grayjay** 2019-12-29 02:32 UTC
