### ISSUE TITLE
cabal new-build --project-file=otherfile.project is broken

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5121] opened 2018-02-06 20:40 UTC
```
% ls cabal-8.4.1.project 
cabal-8.4.1.project

% cabal --project-file=cabal-8.4.1.project new-build all --dry
cabal: There is no <pkgname>.cabal package file or cabal.project file. To
build packages locally you need at minimum a <pkgname>.cabal file. You can use
'cabal init' to create one.
```

ping @fgaz 

This happens with

```
ii  cabal-install-head                              2.1+git20180202.0.2773999-5~16.04             amd64        Command-line interface for Cabal and Hackage
```

**Comment by phadej** [comment] 2018-02-06 22:41
Ah, the ordering. Confusing.

Is it?

**Comment by fgaz** [comment] 2018-02-15 09:43
@phadej the ordering of what?

On 94a7374d7b1a9b554542 it's even worse, it just gives me
```
The given project file cabal-8.4.1.project' does not exist.
```
(it _does_ exist)

**Comment by hvr** [comment] 2018-02-18 09:33
I've briefly looked at the code emitting the error message, and it appears we don't have convenient access to which `cabal.project` were used; so the short-term solution for this is imho to change the


> cabal: There is no <pkgname>.cabal package file or cabal.project file. To build packages locally you need at minimum a <pkgname>.cabal file. You can use 'cabal init' to create one.

text into something like

> There is no <pkgname>.cabal package file or the currently active cabal.project file (if one exists) doesn't specify any packages. To build packages locally you need at minimum a <pkgname>.cabal file. You can use 'cabal init' to create one.
```

**Comment by jneira** [comment] 2022-06-19 19:49
I cant reproduce with an actual cabal.project files and i cant find any `cabal-8.4.1.project` in https://github.com/haskell/cabal/tree/94a7374d7b1a9b55454209e92d5057ba81be7d6a
From the last comment i badly infers there was no `packages` field in that project file. And it the only way i get to reproduce the error.
So closing this issue in favor of https://github.com/haskell/cabal/issues/7401

**Closed by jneira** 2022-06-19 19:49 UTC
Labels: type: bug
