### ISSUE TITLE
Upload documentation by default

### ISSUE THREAD

**Issue by cocreature** [haskell/cabal#3934] opened 2016-10-03 18:56 UTC
Since `cabal` 1.24 it is possible to upload documentation which is great!

However packages on Hackage that don’t have docs for some versions have still not disappeared. This is partly the fault of the Hackage build being unreliable or slow but it is also simply impossible to have a single configuration that can build all packages (just to name two reasons: a package could require a different ghc version or an external library).

I propose to make `cabal upload` build and upload documentation by default and add a `--no-docs` argument to suppress this behavior.

Edit: there is some discussion on this subject in #2080

**Comment by 23Skidoo** [comment] 2016-10-04 16:28
We briefly talked with @hvr about this, and we both agree that it's a good idea.

**Comment by hvr** [comment] 2016-10-04 16:39
The discussion @23Skidoo refers to is most likely #3837 of which this ticket could be considered a duplicate

**Comment by 23Skidoo** [comment] 2016-10-04 16:43
Closing as a duplicate of #3837.

**Closed by 23Skidoo** 2016-10-04 16:43 UTC
Labels: type: enhancement
