### ISSUE TITLE
Failed when execute ghcjs-boot

### ISSUE THREAD

**Issue by Rizary** [haskell/cabal#4440] opened 2017-04-07 04:54 UTC
I got the following error when try to execute ghcjs-boot with the option mentioned in here https://github.com/ghcjs/ghcjs/issues/487

I'm using cabal HEAD version and ghc 8.0.2 downloaded from haskell web. I tried to build ghc using guide in here https://github.com/leksah/leksah.

thing that i noted is that the ghc-pkg still notice my Cabal-1.24.2.0 as mentioned in the third line on the below code.

```
ghcjs-intree
includes
/Users/Rizitecs$ [ghc-pkg]: /usr/local/bin/ghc-pkg "list" "--simple-output"
/Users/Rizitecs$ [ghc-pkg]: /usr/local/bin/ghc-pkg "dump"
/Users/Rizitecs$ [ghc-pkg]: /usr/local/bin/ghc-pkg "field" "Cabal-1.24.2.0" "abi"
/Users/Rizitecs$ writing /Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/package.conf.d/Cabal-1.24.2.0.conf
/Users/Rizitecs$ [ghcjs-pkg]: /Users/Rizitecs/.cabal/bin/ghcjs-pkg "recache" "--global" "--no-user-package-db"
installing stage 0
/Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/ghcjs-boot/boot/ghc-prim$ rm_rf dist
/Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/ghcjs-boot$ [cabal]: /usr/local/bin/cabal "--config-file" "/Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/cabalBootConfig" "--ignore-sandbox" "install" "./boot/ghc-prim" "--solver=topdown" "--global" "--ghcjs" "--one-shot" "--avoid-reinstalls" "--builddir" "dist" "--with-compiler" "/Users/Rizitecs/.cabal/bin/ghcjs" "--with-hc-pkg" "/Users/Rizitecs/.cabal/bin/ghcjs-pkg" "--prefix" "/Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs" "--enable-documentation" "--haddock-html" "--haddock-hyperlink-source" "--enable-shared" "--enable-library-profiling" "-v2" "--dry-run"
/usr/local/bin/cabal --config-file /Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /Users/Rizitecs/.cabal/bin/ghcjs --with-hc-pkg /Users/Rizitecs/.cabal/bin/ghcjs-pkg --prefix /Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling -v2 --dry-run
solver must be one of: modular
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:46:24 in Cabal-2.1.0.0-inplace:Distribution.ReadE
ghcjs-boot: error running: /usr/local/bin/cabal --config-file /Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /Users/Rizitecs/.cabal/bin/ghcjs --with-hc-pkg /Users/Rizitecs/.cabal/bin/ghcjs-pkg --prefix /Users/Rizitecs/.ghcjs/x86_64-darwin-0.2.1-8.0.2/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling -v2 --dry-run
exit status: 1
stderr: solver must be one of: modular
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:46:24 in Cabal-2.1.0.0-inplace:Distribution.ReadE
```

**Comment by ezyang** [comment] 2017-04-07 05:27
Dupe of #3987, which was fixed Cabal side, but the ghcjs build system has to be adjusted to take advantage of the new flag.

**Closed by ezyang** 2017-04-07 05:27 UTC

**Comment by b-mehta** [comment] 2018-07-25 22:23
I'm still getting this issue, has this been fixed?

**Comment by grayjay** [comment] 2018-07-29 06:30
It looks like there is a PR to update GHCJS, but it hasn't been merged: https://github.com/ghcjs/ghcjs/pull/624

**Comment by Rizary** [comment] 2018-07-29 08:21
@b-mehta @grayjay did you use Cabal in master branch?

**Comment by grayjay** [comment] 2018-07-30 06:50
@Rizary I'm not sure I understand.  The cabal master branch has a flag (added in #4227) that ghcjs-boot could use to reinstall boot libraries without passing `--solver=topdown` to cabal.  `--solver=topdown` causes an error in newer versions of cabal.
