### ISSUE TITLE
Wildcards in data-files don't work with filenames containing multiple dots

### ISSUE THREAD

**Issue by bos** [haskell/cabal#784] opened 2012-05-24 05:46 UTC
(Imported from [Trac #794](http://hackage.haskell.org/trac/hackage/ticket/794), reported by guest on 2011-01-22)

The Hoogle cabal file reads:

<pre class="wiki">data-files:
    resources/_.js
    -- surely a Cabal bug that this isn't picked up by *.js
    -- but that hoogle.js is matched
    resources/jquery-1.4.2.js
    resources/jquery.cookie.js
</pre>It seems that the filename <tt>a.b.ext</tt> doesn't get picked by the wildcard <tt>_.ext</tt>.

-- Neil Mitchell

**Comment by BardurArantsson** [comment] 2015-06-25 17:47
It seems that this is essentially a duplicate of #2522 (given the discussion therein). Close?

**Closed as completed** 2018-06-16 08:21 UTC
Labels: type: bug, Cabal: other
