### ISSUE TITLE
Let packages opt-in to the Package Versioning Policy

### ISSUE THREAD

**Issue by bos** [haskell/cabal#427] opened 2012-05-24 05:22 UTC
(Imported from [Trac #434](http://hackage.haskell.org/trac/hackage/ticket/434), reported by @dcoutts on 2008-12-18)

Package version numbers and version constraints on dependencies are proxies for API compatibility. It is hard for people to specify the dependencies correctly and we would like to improve their quality.

We have the [Package versioning policy](http://haskell.org/haskellwiki/Package_versioning_policy) which says how the package version number relates to API changes.

What we want is a mechanism by which package authors can opt-in to the versioning policy. We should then get hackage to check that the package really is following the policy. Just as important we can use the fact that a package does follow the policy to give suggestions to package authors. For one thing we can discourage or ban upwardly open version ranges and provide a suggestion on what upper version bound to use.

**Comment by adamgundry** [comment] 2015-10-11 19:00
Closing as duplicate of #465.

**Closed by adamgundry** 2015-10-11 19:00 UTC
Labels: enhancement, library
