### ISSUE TITLE
`cabal v2-build` doesn't respect `builddir` option in `~/.cabal/config`

### ISSUE THREAD

**Issue by konsumlamm** [haskell/cabal#7818] opened 2021-11-14 13:30 UTC
**To Reproduce**

Add `builddir: dist` to `~/.cabal/config`.
```
$ cabal init
$ cabal v2-build
```
The build artifacts still go to `dist-newstyle`.

**Expected behavior**
The build artifacts go to `dist` (this is the case with `cabal v1-build`).

**System information**
cabal-install version 3.6.2.0

**Comment by jneira** [comment] 2021-11-14 14:46
Reproduced in windows with cabal-3.4.0.0 and 3.6.2.0 as well. Confirmed that `cabal v1-build` honours the global config value.

Thanks for reporting the issue. It is a duplicate of #5271

**Closed** 2021-11-14 14:59 UTC
Labels: type: bug
