### ISSUE TITLE
Cabal does not always rebuild when TH dependency changes

### ISSUE THREAD

**Issue by zliu41** [haskell/cabal#7862] opened 2021-12-09 08:17 UTC
HLint's [EmbedData.hs](https://github.com/ndmitchell/hlint/blob/master/src/EmbedData.hs) uses `embedFile` to load `data/hlint.yaml` at compile time. `embedFile` registers the file as a dependency via `qAddDependentFile`.

When `hlint.yaml` is modified, and if at least one source hs file is also modified, then cabal correctly rebuilds EmbedData.

However, if we only modify `hlint.yaml` itself, then `cabal v2-build` simply prints `Up to date` and terminates, without building EmbedData.

Environment: GHC 8.10.7, Cabal 3.6.2.0

**Comment by Mikolaj** [comment] 2021-12-09 08:32
Duplicate of #4746

**Comment by Mikolaj** [comment] 2021-12-09 08:33
@zliu41: thank you for the report. Is that with `cabal build` or `cabal install` (#5786)? Does adding that file to `extra-source-files` help?

**Comment by Mikolaj** [comment] 2021-12-09 19:42
Oh, interesting. 

https://github.com/haskell/cabal/issues/4746#issuecomment-909499995 may be just about that, but @gbaz knows best.

**Comment by gbaz** [comment] 2021-12-10 18:27
This was resolved in https://github.com/haskell/cabal/pull/7608 but is not yet in a released cabal I believe.

**Closed by gbaz** 2021-12-10 18:27 UTC
