### ISSUE TITLE
Win pkg-config cflags

### ISSUE THREAD

**Issue by cchantep** [haskell/cabal#1861] opened 2014-05-12 16:42 UTC
For pkg-config lib whose .pc file is properly resolved and which defined CFLAGS (-I...), while building hackage depending on such native lib, required .h are not found on Win.

E.g. For `cabal install glib`, glib.h is not found whereas `-Ipath` for it are properly defined in its .pc descriptor, and `pkg-config --cflags glib` displays it properly.

Workaround: Appending paths from `pkg-config --cflags` as `--extra-include-dirs=` to `cabal configure`.

Env: Win7 msys2 ghc7.8.2 cabal1.18

**Comment by ezyang** [comment] 2016-08-11 03:37
I tried to reproduce this but I couldn't figure out how to install glib.h! Do you know what the package name in `pacman` for the library is? When I type `pkg-config --list` on my msys installation there do not appear to be any libraries available.

**Comment by erikd** [comment] 2016-08-11 04:21
On debian:
```
> apt-file search /glib.h 
libghc-glib-doc: /usr/lib/ghc-doc/haddock/glib-0.13.2.2/glib.haddock
libglib2.0-dev: /usr/include/glib-2.0/glib.h
libglib2.0-doc: /usr/share/doc/libglib2.0-doc/glib/glib.html
libhiredis-dev: /usr/include/hiredis/adapters/glib.h
syslog-ng-dev: /usr/include/syslog-ng/compat/glib.h
```
so you probably want the arch (?) equivalent of `libglib2.0-dev`.

**Comment by jasagredo** [comment] 2024-07-18 21:23
I am able to compile `glib` with cabal without any issues. Perhaps this was due to `pkg-config` on Windows doing funny stuff, ([see](https://github.com/input-output-hk/actions/blob/67d7fa31e3483ae98270d815d1482622e2a7c248/base/action.yml#L43-L51)). I'm closing this, re-open if you disagree.

**Closed by jasagredo** 2024-07-18 21:23 UTC
Labels: type: bug, platform: windows
