### ISSUE TITLE
inconsistency in solving/planning(?)

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#4148] opened 2016-12-01 15:35 UTC
I just ran into this weird situation:

```
$ cabal get hakyll-4.9.2.0
Unpacking to hakyll-4.9.2.0/

$ cd hakyll-4.9.2.0/
$ cabal new-build -w ghc-7.10.3
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - hakyll-4.9.2.0 {hakyll-4.9.2.0-inplace-hakyll-init} (exe:hakyll-init) (first run)
 - pandoc-citeproc-0.10.3 {pandoc-citeproc-0.10.3-5c3ba26facbb19ac48e6fbd28aa16da7852c52bbebbaba6e4e2590ec3cda9530} (lib:pandoc-citeproc) (requires build)
 - hakyll-4.9.2.0 {hakyll-4.9.2.0-inplace} (lib) (first run)
Configuring component exe:hakyll-init from hakyll-4.9.2.0
Configuring  pandoc-citeproc-0.10.3-5c3ba26facbb19ac48e6fbd28aa16da7852c52bbebbaba6e4e2590ec3cda9530 (all, due to Custom setup)
Preprocessing executable 'hakyll-init' for hakyll-4.9.2.0...
[1 of 3] Compiling Paths_hakyll     ( /tmp/hakyll-4.9.2.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/hakyll-4.9.2.0/c/hakyll-init/build/hakyll-init/autogen/Paths_hakyll.hs, /tmp/hakyll-4.9.2.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/hakyll-4.9.2.0/c/hakyll-init/build/hakyll-init/hakyll-init-tmp/Paths_hakyll.o )
[2 of 3] Compiling Hakyll.Core.Util.File ( src/Hakyll/Core/Util/File.hs, /tmp/hakyll-4.9.2.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/hakyll-4.9.2.0/c/hakyll-init/build/hakyll-init/hakyll-init-tmp/Hakyll/Core/Util/File.o )
[3 of 3] Compiling Main             ( src/Hakyll/Init.hs, /tmp/hakyll-4.9.2.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/hakyll-4.9.2.0/c/hakyll-init/build/hakyll-init/hakyll-init-tmp/Main.o )
Linking /tmp/hakyll-4.9.2.0/dist-newstyle/build/x86_64-linux/ghc-7.10.3/hakyll-4.9.2.0/c/hakyll-init/build/hakyll-init/hakyll-init ...

Failed to build pandoc-citeproc-0.10.3. The failure occurred during the
configure step.
Build log (
/home/hvr/.cabal/logs/ghc-7.10.3/pandoc-citeproc-0.10.3-5c3ba26facbb19ac48e6fbd28aa16da7852c52bbebbaba6e4e2590ec3cda9530.log
):
[1 of 1] Compiling Main             ( /tmp/hakyll-4.9.2.0/dist-newstyle/tmp/src-3565/pandoc-citeproc-0.10.3/dist/setup/setup.hs, /tmp/hakyll-4.9.2.0/dist-newstyle/tmp/src-3565/pandoc-citeproc-0.10.3/dist/setup/Main.o )
Linking /tmp/hakyll-4.9.2.0/dist-newstyle/tmp/src-3565/pandoc-citeproc-0.10.3/dist/setup/setup ...
Configuring pandoc-citeproc-0.10.3...
setup: At least the following dependencies are missing:
process -any, temporary >=1.1
cabal: Failed to build pandoc-citeproc-0.10.3 (which is required by
hakyll-4.9.2.0). See the build log above for details.

```

However, the only components in `pandoc-citeproc` which seem to require those two packages seem to be

```
executable test-citeproc
  Main-Is:        test-citeproc.hs
  Other-Modules:  JSON
                  Prelude
  Hs-Source-Dirs: tests, prelude
  if flag(test_citeproc)
    Buildable:    True
  else
    Buildable:    False
  build-depends:  base >= 4, aeson, directory, text,
                  pandoc-types >= 1.16 && < 1.18,
                  pandoc >= 1.16 && < 1.20,
                  filepath,
                  bytestring, pandoc-citeproc, process, temporary >= 1.1,
                  yaml >= 0.8.8.7, containers >= 0.4, vector >= 0.10
  default-language: Haskell2010

test-suite test-pandoc-citeproc
  Type:           exitcode-stdio-1.0
  Main-Is:        test-pandoc-citeproc.hs
  Other-Modules:  JSON
                  Prelude
  Hs-Source-Dirs: tests, prelude
  build-depends:  base >= 4, aeson, directory, text,
                  pandoc-types >= 1.16 && < 1.18,
                  pandoc >= 1.16 && < 1.20, filepath,
                  bytestring, pandoc-citeproc, process, temporary >= 1.1,
                  yaml >= 0.8.8.7
  default-language: Haskell2010

```

And the flag settings according to `plan.json` were

```js
    {
      "type": "configured",
      "id": "pandoc-citeproc-0.10.3-5c3ba26facbb19ac48e6fbd28aa16da7852c52bbebbaba6e4e2590ec3cda9530",
      "pkg-name": "pandoc-citeproc",
      "pkg-version": "0.10.3",
      "flags": {
        "unicode_collation": false,
        "test_citeproc": false,
        "embed_data_files": false,
        "debug": false,
        "bibutils": true
      },
```

Nor where any of those components mentioned in the `components` list in `plan.json`...

/cc @ezyang @dcoutts

**Comment by hvr** [comment] 2016-12-01 18:39
After more experimentation it looks like it's the `executable test-citeproc`'s build-depends fault; it looks like Cabal-1.22.5 doesn't honour `buildable: False` ... is this a known issue?

**Comment by ezyang** [comment] 2016-12-01 23:24
Yes, this is https://github.com/haskell/cabal/issues/1725

**Comment by hvr** [comment] 2016-12-01 23:34
@ezyang wow... I even forgot I commented there... :-)

IOW, 53d85bb0621a9153de49923bd26312a6e52a8691 would need to be backported to Cabal-1.22.x ?

**Comment by grayjay** [comment] 2016-12-02 01:48
There is also a new-build issue: #3881

**Comment by hvr** [comment] 2016-12-02 10:40
Hrm... looking at #3337, what about a refined heuristic forcing >=1.24 only if we detect problematic uses of `buildable`? like e.g. `buildable: False` being active, while there's still `build-depends`-lines active as well?

**Comment by ezyang** [comment] 2016-12-05 23:59
I guess it's OK, and there's prior art for it, although the heuristic would be annoying to compute.

**Comment by grayjay** [comment] 2017-03-12 04:09
Closing as a duplicate of #3881.  I was able to build `hakyll` by adding `--constraint='pandoc-citeproc:setup.Cabal >= 1.24'`.

**Closed by grayjay** 2017-03-12 04:09 UTC
Labels: cabal-install: nix-local-build
