### ISSUE TITLE
A nice way to run an executable as part of a test suite?

### ISSUE THREAD

**Issue by kindaro** [haskell/cabal#5418] opened 2018-07-08 08:01 UTC
There is [a hack][1] that allows one to make an executable available to the test suite of the same package. I wonder if I may ask for a more direct way to achieve the same. For instance, allow a test suite to depend on an executable (as in #5415) and then, if such dependency is present, build the executable and make it available for the test suite by updating `$PATH`.

[1]: https://stackoverflow.com/a/51226090/2108477

**Comment by hvr** [comment] 2018-07-08 09:14
@kindaro What you call "a hack" is the designated way to do this. It's fully documented in the cabal user's guide too. I'm not sure why you call it "a hack" when it's a fully intentional semantics of `build-tools`.

**Comment by gbaz** [comment] 2018-07-08 21:14
Updating the docs to clarify that `build-tool-depends` is intended to make executables available during test-runtime as running tests is considered part of the build is probably a good idea.

**Comment by hvr** [comment] 2018-07-08 21:14
Duplicate of #5411

**Comment by hvr** [comment] 2018-07-08 21:15
@kindaro I think what you're suggesting sounds a lot like what #5411 is trying to address

**Comment by kindaro** [comment] 2018-09-02 10:50
@hvr If what @gbaz is saying about testing being counted as part of the build process, then I am happy, except for the note that the "tool" part of the name is unfortunate. I think the issue you are referring to is more general and overall about a different problem, that may well happen to never be solved.

**Comment by domenkozar** [comment] 2018-09-03 18:42
Clarified in https://github.com/haskell/cabal/pull/5561

**Comment by domenkozar** [comment] 2018-09-29 10:55
This was clarified in #5561 and https://github.com/haskell/cabal/issues/5411 covers the run use-case.

**Closed by domenkozar** 2018-09-29 10:55 UTC
