### ISSUE TITLE
Backpack and --dependencies-only

### ISSUE THREAD

**Issue by AlexeyRaga** [haskell/cabal#6081] opened 2019-06-17 02:24 UTC
I am having an issue when building a multi-project with `--depencencies-only` flag.
My repository is structured like:

```
.
|- cabal.project
|- strategy-a
|- strategy-b
|- my-lib
   |- library
      |- Signature.hsig
   |- tests
|- my-app-1
   |- executable
   |- library
   |- tests
```

the `tests` suite in `my-lib` uses one of the `strategy-*` in its `mixins` stanza to satisfy the dependency. So does `my-app-1`.

When I build this project with 
```
cabal v2-build my-lib --enable-tests --dependencies-only
```
I am getting an error, similar to:
```
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the packages my-lib-1.0.0 and
strategy-a-1.0.0 are required by a dependency of one of the other
targets.
``` 

It feels like `cabal` doesn't like `tests` to reference `strategy-a` or/and `my-lib`.

`cabal v2-build all` seems to experience similar problems, but now at the `my-app-1` level.

**Comment by jfischoff** [comment] 2020-01-05 19:13
I'm experiencing a similar problem.

**Comment by phadej** [comment] 2020-01-05 19:28
I think this is moral duplicate of https://github.com/haskell/cabal/issues/6106

**Closed** 2020-01-05 19:28 UTC
