### ISSUE TITLE
`cabal v2-install --ignore-project` crashes when project file is present

### ISSUE THREAD

**Issue by andreasabel** [haskell/cabal#8094] opened 2022-04-09 20:23 UTC
Reproducer:
```sh
DIR=$(mktemp -d)
cd $DIR
${CABAL:-cabal} init -n --exe --application-dir=app
echo "optimization: False" > cabal.project.local
${CABAL:-cabal} install --ignore-project
```
This crashes with (current `master`):
```
...
Error: cabal: Invalid package ID: .
"<eitherParsec>" (line 1, column 2):
unexpected all digits or a dot in a portion of package name
expecting "-"
```
Same problem with `cabal.project` instead of `cabal.project.local`.

Behavior of previous versions of `cabal-install`:
```
cabal-3.0: unrecognized 'install' option `--ignore-project'
cabal-3.2: Invalid package ID: .
```
From 3.4 it is the same error as today.

### What is my interest in `cabal v2-install --ignore-project`?
I'd like to develop with `-O0` (via `optimization: False` in a project file), but deploy to my system with default optimization (`-O1`).
Originally, I would have expected that `cabal v2-install` ignores the project files by default, because it behaves as if it installs from the `sdist`ed tarball, which does (in my case) not contain any `cabal.project*` files.
But this does not seem to be the case.  There is a long discussion of the complex at:
- #7297

In https://github.com/haskell/cabal/issues/7297#issuecomment-1048797853 it is suggested to use `--ignore-project` to this end, but it does not work as expected...

**Comment by jneira** [comment] 2022-04-10 18:38
> In https://github.com/haskell/cabal/issues/7297#issuecomment-1048797853 it is suggested to use --ignore-project to this end, but it does not work as expected...

sorry i did not make it clear in the comment but that was in the context of a hypothetical fix for the bug and that would be a feature to be added and allow opt out the behaviour that fix would set

**Comment by andreasabel** [comment] 2022-04-11 10:06
Maybe then the concrete fix would be to remove `--ignore-project` from the options of `cabal install`?  Or does it have some use for remote installation?

**Comment by jneira** [comment] 2022-04-11 12:15
Related issues:
* https://github.com/haskell/cabal/issues/7057 asking to add `--ignore-project` to v2-build. I think some v2 commands honour `--ignore-project`, like v2-run, v2-repl, v2-exec?. Not sure what is the status of that but `v2-sdist` does not have suppor for (https://github.com/haskell/cabal/issues/7965)
* https://github.com/haskell/cabal/issues/6942 afaics duplicate of this one
*

**Comment by gbaz** [comment] 2022-04-12 03:24
the globalConfig is not a project file in parent directories -- that's still a "project" config, just one found in another directory. The global config referred to in that function is, as I understand it, the `~/.cabal/config` file.

**Comment by Colton-Clemmer** [comment] 2022-04-12 15:38
@gbaz ok, the reason I said that is that it looks like if you run `cabal sdist --ignore-project` on a subdirectory of your project (such as the `cabal-install` directory of the cabal project) it will load the global config from `~/.cabal` but if you do it on the same directory as the `cabal.project` file it will use that project file. That seems like a bug to me, and I assume the intended functionality is that it `--ignore-project` would always ignore the local `cabal.project` file and always use the global one, right?

**Comment by gbaz** [comment] 2022-04-12 16:25
That sounds correct to me.

**Closed** 2023-01-04 13:57 UTC
Labels: type: bug, cabal-install: cmd/install, re: project-file, re: --ignore-project
