### ISSUE TITLE
cabal install fails to build executable if license-file does not exist

### ISSUE THREAD

**Issue by stphndemos** [haskell/cabal#2421] opened 2015-02-16 18:37 UTC
`cabal init` will set the license-file as LICENSE when you choose no license, but it doesn't create the LICENSE file. It seems to fail when trying to create the executable, because commands like `cabal repl` will work fine. 
```
$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library
$ cabal install
Resolving dependencies...
Configuring servant-test-0.1.0.0...
Warning: The 'license-file' field refers to the file 'LICENSE' which does not
exist.
Building servant-test-0.1.0.0...
Preprocessing executable 'servant-test' for servant-test-0.1.0.0...
cabal: LICENSE: does not exist
Failed to install servant-test-0.1.0.0
cabal: Error: some packages failed to install:
servant-test-0.1.0.0 failed during the final install step. The exception was:
ExitFailure 1
$ ls
cabal.sandbox.config  dist/  servant-test.cabal  Setup.hs  src/
$ touch LICENSE
$ cabal install
Resolving dependencies...
Configuring servant-test-0.1.0.0...
Building servant-test-0.1.0.0...
Preprocessing executable 'servant-test' for servant-test-0.1.0.0...
Installing executable(s) in
/home/demos/projects/servant-test/.cabal-sandbox/bin
Installed servant-test-0.1.0.0
```
This is Fedora 21 with the cabal packaged in yum - 
```
$ cabal install
Resolving dependencies...
Configuring cabal-test-0.1.0.0...
Warning: The 'license-file' field refers to the file 'LICENSE' which does not
exist.
Building cabal-test-0.1.0.0...
Preprocessing executable 'cabal-test' for cabal-test-0.1.0.0...
[1 of 1] Compiling Main             ( src/Main.hs, dist/build/cabal-test/cabal-test-tmp/Main.o )
Linking dist/build/cabal-test/cabal-test ...
cabal: LICENSE: does not exist
Failed to install cabal-test-0.1.0.0
cabal: Error: some packages failed to install:
cabal-test-0.1.0.0 failed during the final install step. The exception was:
ExitFailure 1
$ ls    
cabal-test.cabal  dist/  Setup.hs  src/
$ touch LICENSE
$ ls
cabal-test.cabal  dist/  LICENSE  Setup.hs  src/
$ cabal install
Resolving dependencies...
Configuring cabal-test-0.1.0.0...
Building cabal-test-0.1.0.0...
Preprocessing executable 'cabal-test' for cabal-test-0.1.0.0...
Installing executable(s) in /home/demos/.cabal/bin
Installed cabal-test-0.1.0.0
$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library
```

**Comment by lspitzner** [comment] 2015-02-16 19:48
seems to be duplicate of #2217

**Comment by 23Skidoo** [comment] 2015-02-16 19:56
> seems to be duplicate of #2217

Which is already fixed.

**Closed by 23Skidoo** 2015-02-16 19:56 UTC
Labels: duplicate

**Comment by stphndemos** [comment] 2015-02-16 21:09
#2217 is talking about the same thing, but my issue is more focused on the fact that the `cabal install` command fails when the file specified in license-file doesn't exist in the project root. I don't know why a license file is required to build the project, especially if #2217 is marked as won't fix.

**Comment by lspitzner** [comment] 2015-02-16 21:59
it was only temporarily marked as wontfix, but is fixed in HEAD (i just tested to make sure); see the commit from Jan 12.

**Comment by stphndemos** [comment] 2015-02-16 22:17
Ah, I didn't see the tail end of that issue. Cool, thanks.
