### ISSUE TITLE
cabal update creates dist-newstyle folder in $PWD

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal#8589] opened 2022-11-13 21:54 UTC
**Describe the bug**
When `cabal update` is run this creates a new folder `dist-newstyle` in PWD.
This seems wrong as the command shouldn't pollute my PWD and will also
fail if ran in a read-only directory 

**To Reproduce**
```
PS C:\Users\WDAGUtilityAccount\Desktop> mkdir temp

    Directory: C:\Users\WDAGUtilityAccount\Desktop

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        11/13/2022   9:51 PM                temp


PS C:\Users\WDAGUtilityAccount\Desktop> cd .\temp\
PS C:\Users\WDAGUtilityAccount\Desktop\temp> cabal v2-update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date.
The index-state is set to 2022-11-13T17:52:14Z.
PS C:\Users\WDAGUtilityAccount\Desktop\temp> ls


    Directory: C:\Users\WDAGUtilityAccount\Desktop\temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        11/13/2022   9:51 PM                dist-newstyle

```

**Expected behavior**
I don't expect this folder to be created. `cabal update` updates global state, so I don't understand the need for local storage.

**System information**
 - Operating system: Windows 11
 - `cabal` 3.8.1.0

**Comment by ulysses4ever** [comment] 2022-11-13 23:45
`cabal repl -b` suffers similarly: #8550

**Comment by gbaz** [comment] 2022-11-14 00:22
expect this may be fixed by https://github.com/haskell/cabal/pull/8358 ?

**Comment by ulysses4ever** [comment] 2022-11-14 17:32
> expect this may be fixed by #8358?

No. See #8550 for discussion.

**Closed** 2023-01-04 21:40 UTC
Labels: type: bug, cabal-install: cmd/update, regression in 3.8

**Comment by arrowd** [comment] 2023-01-04 21:41
I hope this will end up in the next 3.8 release.

**Comment by Mikolaj** [comment] 2023-01-05 09:46
@arrowd: 3.10 branch is about to be cut and this is intended to make it there. Unlikely to make it into a future 3.8 release, if any. (cc @andreasabel)

**Comment by juhp** [comment] 2024-01-06 04:56
Worthy of a backport I would say - it's a pretty bad 3.8 regression

**Comment by juhp** [comment] 2024-01-06 06:03
Nvm, ugh I see now that #9588 doesn't prevent dist-newstyle being created...

**Comment by juhp** [comment] 2024-01-06 06:29
I tried #8358 too, that also doesn't stop cabal update from generating `dist-newstyle/` for me...

**Comment by gbaz** [comment] 2024-01-06 07:06
the combination of #8358 and #8627 should prevent the creation of dist-newstyle _in a directory with no package or project_. In the case you run `cabal update` and there is a package, then dist-newstyle is still created, but I think this is fine.

That said, I do not think we have further plans for a new 3.8 release, so I'm not sure of what the purpose of a backport would be...

**Comment by juhp** [comment] 2024-01-06 07:06
Okay I created a [backport](https://src.fedoraproject.org/rpms/cabal-install/blob/rawhide/f/cabal-install-3.8-dist-newstyle-8627.patch) intended for Fedora 39, which seems to work

**Comment by juhp** [comment] 2024-01-06 07:10
> That said, I do not think we have further plans for a new 3.8 release,

As I expected ;-(

> so I'm not sure of what the purpose of a backport would be...

It is easier to pick commits from a stable branch than hunting around the project and then backporting...

There are quite a few distros shipping 3.8 currently...

**Comment by gbaz** [comment] 2024-01-06 07:16
In that case, I think a backport to the 3.8 branch would be welcome.

**Comment by juhp** [comment] 2024-01-06 07:21
Let me try then - anyway thanks #8358 and #8627 together indeed apply (my patch above basically just included the minimum from 8358)
