### ISSUE TITLE
cabal-install bootstrapping fails with a --user install of Cabal lib 2.0.0.2, Can't find Distribution.Package and Distribution.Text

### ISSUE THREAD

**Issue by MatthewRalston** [haskell/cabal#4783] opened 2017-09-21 17:24 UTC
Hi everyone. I'm getting a similar compilation issue to issue #4137 during cabal-install bootstrapping, complaining that `Distribution.Package` and `Distribution.Text` are not found.

The error is shown in this [gist](https://gist.github.com/MatthewRalston/702d27ff338600e9a939977656405a04). Also, ghc is installed system-wide, but the Cabal library was installed from source, configured with the `--user` flag. Operating system is Centos6.

**Comment by 23Skidoo** [comment] 2017-10-14 11:24
Looks like a duplicate of #4365.

**Comment by 23Skidoo** [comment] 2017-10-14 14:26
Actually seems to be unrelated to #4365. The error message says:

> Perhaps you haven't installed the profiling libraries for package ‘Cabal-2.0.0.2’?

So maybe you installed the Cabal library manually without profiling and then tried to run the bootstrap script, which defaults to building dependencies with profiling. Try running the bootstrap script with `EXTRA_CONFIGURE_OPTS="" ./bootstrap.sh --no-doc`.

**Comment by 23Skidoo** [comment] 2017-10-14 14:27
Optimistically closing, please reopen if the issue persists.

**Closed by 23Skidoo** 2017-10-14 14:27 UTC
Labels: cabal-install: bootstrap, type: user-question
