### ISSUE TITLE
'cabal new-clean' should also delete the environment file

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/cabal#5689] opened 2018-11-16 13:13 UTC
How to reproduce:

```
# In some project's directory
$ cabal new-build
$ cabal new-clean
$ ls .ghc.environment.*
.ghc.environment.x86_64-linux-8.4.4 # Expected: zero hits
```

I'd prefer `cabal new-clean` to imply `rm -rf .ghc.environment.*` in the project's root directory, though it might be argued that it only should delete the environment file for the currently configured compiler.

/cc @hvr @typedrat

**Comment by fommil** [comment] 2018-11-20 18:34
dupe of ##5587 ?

**Comment by 23Skidoo** [comment] 2018-11-20 18:51
Closing in favour of #5587.

**Closed** 2018-11-20 18:52 UTC
Labels: cabal-install: cmd/clean, cabal-install: nix-local-build, resolution: duplicate, type: enhancement
