### ISSUE TITLE
Concatenation of mains from conditional branches

### ISSUE THREAD

**Issue by georgefst** [haskell/cabal#6973] opened 2020-07-19 19:39 UTC
I have an executable which requires slightly different top-level code on different platforms. I have:
```
    if os(windows)
        main-is: Windows.hs
    if os(linux)
        main-is: Linux.hs
```

which I thought was a relatively nice solution, but unfortunately I get the rather nonsensical error:

```
cabal: Windows.hsLinux.hs doesn't exist
```

Obviously there are various ways to work around this, but it would be great if it just worked.

**Comment by georgefst** [comment] 2020-07-20 15:28
Investigating slightly further:

- This actually works fine with `repl`, `build`, `run`, but *not* `install`.
- The lack of an 'else' branch isn't the problem - changing `if os(linux)` to else makes no difference.
- Neither is the mismatch of file and module name - changing everything to `Main.hs` just gives `cabal: Main.hsMain.hs doesn't exist`.

**Comment by phadej** [comment] 2020-07-20 18:02
Duplicate of https://github.com/haskell/cabal/issues/3313

A workaround is to have dummy  `Main.is`

```haskell
module Main (main) where
import RealMain (main)
```

and put `RealMain`s into different source-directories:

```cabal
main-is: Main.hs

-- most sources are here
hs-source-dirs: src/

-- but RealMain has multiple implementations:
if os(windows)
  hs-source-dirs: windows/
If os(linux)
  hs-source-dirs: linux/

other-modules: RealMain

...
```

**Closed by phadej** 2020-07-20 18:02 UTC

**Comment by georgefst** [comment] 2020-07-20 19:41
Ah thanks, I did do a quick search but missed that one somehow.
