### ISSUE TITLE
Multi line `subdir` containing `.` fails in `source-repository-package`

### ISSUE THREAD

**Issue by hamishmack** [haskell/cabal#7006] opened 2020-08-05 06:49 UTC
When `.` is included in `subdir` and the `subdir`s are split over multiple lines the
cabal does not seem to find the package in the root of the source repo.

**To Reproduce**

```
$ cat cabal.project 
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-prelude
  tag: 71ea865408f2e03e6d6832359423546699730849
  subdir:
    .
    test
$ cabal v2-build cardano-prelude
Warning: There are no packages or optional-packages in the project
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: cardano-prelude-test-0.1.0.0 (user goal)
[__1] unknown package: cardano-prelude (dependency of cardano-prelude-test)
[__1] fail (backjumping, conflict set: cardano-prelude, cardano-prelude-test)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-prelude-test, cardano-prelude
```

Please use version-prefixed commands (e.g. `v2-build` or `v1-build`) to avoid ambiguity.

**Expected behavior**

Expected it to work the same as it does when all the subdirs are listed on the same line:

```
$ cat cabal.project 
source-repository-package
  type: git
  location: https://github.com/input-output-hk/cardano-prelude
  tag: 71ea865408f2e03e6d6832359423546699730849
  subdir: . test
$ cabal v2-build cardano-prelude
HEAD is now at 71ea865 Merge #114
Warning: There are no packages or optional-packages in the project
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - base-compat-0.11.1 (lib) (requires build)
...
```

**System information**
 - macOS with nix
 - Tested with`cabal` 3.2 3.4 and master, `ghc` 8.8.4

**Additional context**

**Comment by phadej** [comment] 2020-11-03 13:16
This is fixed in `master`. Duplicate of https://github.com/haskell/cabal/issues/7131

**Closed by phadej** 2020-11-03 13:16 UTC
