### ISSUE TITLE
cabal new-repl target1 target2 shouldn't bring up GHCi prompt twice

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3659] opened 2016-08-02 03:49 UTC
When I run `cabal new-repl` with two targets, what it does is first bring up GHCi for the first target, and then the second target, UNLESS they are both targets from the same package, in which case only one target is brought up.

There are some relevant TODOs in the code in `elaboratePackageTargets`:

```
        --TODO: instead of listToMaybe we should be reporting an error here
        replTargets   = listToMaybe
                      . nubComponentTargets
                      . map compatSubComponentTargets
                      . concatMap elaborateReplTarget
                      $ targets
```

**Comment by ezyang** [comment] 2016-08-24 06:32
See also https://github.com/commercialhaskell/stack/issues/130

**Comment by dcoutts** [comment] 2016-09-04 00:17
Should simply fail if two targets are given if they span different components.

FYI, I'd prefer not to go down the route of trying to pretend that ghci supports multiple packages by unioning everything together and preying (as stack does). Of course, if we can get ghci to support multiple "home" packages then that'd be nice.

**Comment by dcoutts** [comment] 2016-09-04 09:31
@hesselink any chance you could explain in more detail the problems you have had with cabal repl?

**Comment by hesselink** [comment] 2016-09-05 09:23
It's been a while... One that I remember was very annoying was that `cabal repl` would fail to launch if there were type errors (!). I think this was https://github.com/haskell/cabal/issues/1715 and it's marked as fixed. I just tried a few packages and most things seem to work. One thing I did notice is that `repl` doesn't do an install, which means you can't just call `repl`, you have to remember to do `install --only-dep` first. It would be nice if common use cases just did what was needed.

Regarding the discussion above: I often load two components of the same package, e.g. a library and the test suite. Additionally, I often have a development flow where I load two packages together, including their intermediate dependencies that are also part of the project. This is a very convenient flow while developing: first make a library change (in the repl), then fix all the integration issues up to the final executable (again in the repl). I can see that there are difficult details involved, but I've used it for quite a while (in stack) with a large number of packages, and never had issues :-)

**Comment by Ericson2314** [comment] 2018-04-04 02:15
There is a class of package which are simple enough such that multi-package repl is trivial (just pass more deps and `-i` flags to ghci). [This ignores detecting improperly used dependencies and unexported modules but I think that's OK for now.] Can we teach Cabal to recognize those case and support them?

Stack has had some form of multi-package repl for a while now, so it would be good to get started on that.

**Comment by jkachmar** [comment] 2020-04-02 23:20
Is there anything that an individual contributor might be able to do to support this issue?

I've grown accustomed to `stack`'s ability to load multiple targets at once and I'd very much like to see `cabal v2-repl` gain similar functionality if possible.

It's helpful most notably when working on a project with one or more test suites, so that companion tools like `ghcid` can reload across the whole project and run tests once compilation is green.

**Comment by Ericson2314** [comment] 2020-04-02 23:33
Yes there is! Help me https://gitlab.haskell.org/ghc/ghc/merge_requests/935, which I sadly haven't attended to lately. 

Everything stack does, and anything Cabal could do is a workaround. To really fix the problem is to fix GHC, and that PR goes after the bulk of the work (changing CLI etc is the victory lap).

**Comment by jkachmar** [comment] 2020-04-03 00:10
Thank!

I’m reading up on this GHC PR, the proposal, and some of the related issues, are you on the Haskell IRC or is there a better place to follow-up with you if I have the time or capacity to help with this?

**Comment by Ericson2314** [comment] 2020-04-03 02:19
Sorry I was cooking and eating dinner then. Back now. Find me in #ghc.

**Comment by fendor** [comment] 2020-04-03 08:38
@jkachmar, @Ericson2314 Just want to say that I submitted a GSOC 2020 proposal to implement https://gitlab.haskell.org/ghc/ghc/merge_requests/935 this summer

**Comment by L-as** [comment] 2021-06-19 18:14
What is the current status of this feature?

**Comment by fendor** [comment] 2021-06-21 09:29
The linked work is being split into smaller units of work and semi-actively being worked on. There is currently no ETA, or any concrete plan to integrate the feature into cabal itself.

**Comment by ulysses4ever** [comment] 2022-09-15 03:17
Duncan seems to have gotten around to implement a graceful error message in def073a75f. I think this can be closed, and other tickets with actual feature requests in this spaces should be used going forward (e.g. #8238)

**Comment by Mikolaj** [comment] 2022-09-19 09:30
Well spotted. Closing.

**Closed by Mikolaj** 2022-09-19 09:30 UTC
Labels: type: bug, cabal-install: nix-local-build
