### ISSUE TITLE
Make cabal install --lib create the global environments in %APPDATA% for Windows

### ISSUE THREAD

**Issue by danidiaz** [haskell/cabal#7269] opened 2021-02-02 17:55 UTC
Currently, cabal-install creates the "global" environments in the `$HOME/.ghc/arch-os-version/environments` folder, both in Linux and Windows. This matches what the [GHC User Guide itself](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/packages.html#package-environments) says about the environment lookup path.

Currently there's a [bug](https://gitlab.haskell.org/ghc/ghc/-/issues/19286) in GHC, which makes the lookups fail because the %APPDATA% folder is searched instead of $HOME. 

However, perhaps it would make sense if the global package environments were created in %APPDATA% instead of $HOME. After all, cabal itself stores its configuration file in %APPDATA%:

    cabal --help
    ...
    You can edit the cabal configuration file to set defaults:
        C:\Users\myuser\AppData\Roaming\cabal\config

**Comment by jneira** [comment] 2021-02-07 22:37
As i commented in the ghc issue linked above i think the bug in ghc is in the documentation, as the right place to put application data is precisely %APPDATA%.
So i would change cabal to match actual ghc behaviour. do you agree @fgaz?

**Comment by phadej** [comment] 2021-02-07 23:40
This is fixed in 3.4, duplicate of https://github.com/haskell/cabal/issues/6565

**Closed by phadej** 2021-02-07 23:40 UTC
Labels: cabal-install: cmd/install, platform: windows
