### ISSUE TITLE
cabal: git: does not exist

### ISSUE THREAD

**Issue by mtomassoli** [haskell/cabal#2655] opened 2015-06-12 18:13 UTC
I'm on Windows 7 64-bit SP1. When I run `cabal init` I get this:

    Package name? [default: chapter02]
    Package version? [default: 0.1.0.0]
    Please choose a license:
     * 1) (none)
       2) GPL-2
       3) GPL-3
       4) LGPL-2.1
       5) LGPL-3
       6) AGPL-3
       7) BSD3
       8) MIT
       9) Apache-2.0
      10) PublicDomain
      11) AllRightsReserved
      12) Other (specify)
    Your choice? [default: (none)]
    cabal: git: does not exist

I don't have git installed but why should I install it just to create a local project?

**Comment by 23Skidoo** [comment] 2015-06-12 21:55
Duplicate of #1613.

**Closed by 23Skidoo** 2015-06-12 21:55 UTC
Labels: duplicate
