### ISSUE TITLE
Incorrect paths at the end of v2-install

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/cabal#6275] opened 2019-10-01 20:00 UTC
I ran `cabal -j1 v2-install termonad`.  Everything worked fine except at the end I received the message below.  All the paths have `/home/tom/.cabal/store/ghc-8.4.4/incoming/new-9102` prefixed to them.  For example

```
/home/tom/.cabal/store/ghc-8.4.4/incoming/new-9102/home/tom/.cabal/store/ghc-8.4.4/termonad-2.0.0.0-da5c660a11f3b66765dde3268515e4525bb2051590b0bce0fd9c1397dfe8e002/lib
```

should be just

```
/home/tom/.cabal/store/ghc-8.4.4/termonad-2.0.0.0-da5c660a11f3b66765dde3268515e4525bb2051590b0bce0fd9c1397dfe8e002/lib
```

I am using Debian's default GHC and `cabal-install` that I bootstrapped with Debian's default `cabal-install`

```
cabal --version && ghc --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
The Glorious Glasgow Haskell Compilation System, version 8.4.4
```

```
Linking dist/build/termonad/termonad ...
Installing library in /home/tom/.cabal/store/ghc-8.4.4/incoming/new-9102/home/tom/.cabal/store/ghc-8.4.4/termonad-2.0.0.0-da5c660a11f3b66765dde3268515e4525bb2051590b0bce0fd9c1397dfe8e002/lib
Installing executable termonad in /home/tom/.cabal/store/ghc-8.4.4/incoming/new-9102/home/tom/.cabal/store/ghc-8.4.4/termonad-2.0.0.0-da5c660a11f3b66765dde3268515e4525bb2051590b0bce0fd9c1397dfe8e002/bin
Warning: The directory
/home/tom/.cabal/store/ghc-8.4.4/incoming/new-9102/home/tom/.cabal/store/ghc-8.4.4/termonad-2.0.0.0-da5c660a11f3b66765dde3268515e4525bb2051590b0bce0fd9c1397dfe8e002/bin
is not in the system search path.
cabal: symlink-bindir is not defined. Set it in your cabal config file or use
--symlink-bindir=<path>
```

**Comment by ulysses4ever** [comment] 2022-06-24 19:38
I can't reproduce it for other executables (`termonad` fails because of missing system dependencies for me). Should this be closed? @tomjaguarpaw can you reproduce it on your end?

**Comment by tomjaguarpaw** [comment] 2022-06-24 20:54
Looks like this was for a super old version of `cabal-install`, and I can't be bothered to try to reproduce, so I don't mind if this is closed.

**Comment by Mikolaj** [comment] 2022-06-25 05:27
Thank you all. Closing.

**Closed by Mikolaj** 2022-06-25 05:27 UTC
Labels: type: bug, cabal-install: cmd/install
