### ISSUE TITLE
Cabal new-build sometimes requires Internet access?

### ISSUE THREAD

**Issue by jwiegley** [haskell/cabal#5783] opened 2018-12-08 22:19 UTC
I built a certain work project several times while at home today. Then I went to a café where I didn't have Internet access, and wanted to continue working on the project. I was greeted with this:

```
$ cabal new-build
dieVerbatim: user error (cabal: '/usr/bin/curl' exited with an error:
curl: (6) Could not resolve host: objects-us-west-1.dream.io
)
```

Given that every necessary dependency was on my machine, it seems most unfortunate that I couldn't use `new-build` because the Internet was temporarily unavailable.

**Comment by gbaz** [comment] 2018-12-09 04:09
cf https://github.com/haskell/cabal/issues/5363 and https://github.com/haskell/cabal/issues/4821

**Comment by hvr** [comment] 2018-12-09 08:10
@jwiegley here's a workaround I believe should work that you could try:

edit your `~/.cabal/config` temporarily to comment out the two lines

```
repository hackage.haskell.org
  url: http://hackage.haskell.org/
  -- ...
```

into

```
-- repository hackage.haskell.org
--    url: http://hackage.haskell.org/
  -- ...
```

this will effectively disable the package index and might help if all your library dependencies are pre-provisioned by Nix in your package-db -- it might however cause problems for build-tools, as we don't have a build-tool registry *yet* (i.e.  the equivalent of the global pkg-db for libraries for build-tools).

**Comment by 23Skidoo** [comment] 2019-01-16 14:14
`v1-install` had an `--offline` flag IIRC, should be possible to implement it for `v2-build` too.

**Comment by m-renaud** [comment] 2019-01-24 04:48
Do you have steps to reproduce? When using `cabal` from head and trying to build various projects after disabling network it succeeded without error. Is there a specific configuration you need to get yourself into to trigger this? If I can reproduce locally I'd be happy to take a stab at adding the `--offline` flag.

**Comment by arrowd** [comment] 2019-02-15 17:42
I get this problem too when trying to use `cabal-install` as a packaging tool for FreeBSD ports, however I managed to workaround it.

When issuing `cabal new-build --offline` for the package, Cabal's home dir was empty. This caused `cabal-install` to create it and also create default `config` file with Hackage repo. So, now I just run `touch $HOME/.cabal/config` before running `cabal new-build` and it works perfectly.

**Comment by schmittlauch** [comment] 2020-07-14 17:34
cabal-install 3.4 includes a documented fix/ workaround: https://github.com/haskell/cabal/issues/4821#issuecomment-658072368

**Comment by AleXoundOS** [comment] 2021-01-16 21:04
Also, it would be useful to configure cabal for offline usage on a permanent basis for a user. Without a need to pass `--offline` or edit cabal.project for every project (am I right?). Maybe the undocumented `offline` option in ~/.cabal/config is initially suited for this?

**Comment by gbaz** [comment] 2021-08-28 22:49
Can we close this as resolved?

**Comment by schmittlauch** [comment] 2021-08-28 23:17
As long as nothing has changed since my previous comment, I'm not entirely sure about closing:

Being able to configure the project itself via a `cabal.project` is already a good start. But maybe adding an `--offline` flag to cabal-build or defaulting to the repo fetching only being a warning as long as all required packages are already present on the machine might still be a good change.

I still deem `cabal run` always triggering a hard-failing network request to be a bad default behaviour.

**Comment by gbaz** [comment] 2021-08-29 00:17
Oh I agree we should add the --offline flag, but that's tracked by https://github.com/haskell/cabal/issues/5346 . If that covers the request, we'll resolve in favor of that.

**Closed by gbaz** 2021-08-29 00:17 UTC
Labels: type: bug

**Comment by schmittlauch** [comment] 2021-08-29 00:27
If we think closing this is fine (instead of discussing default choices), then #5363 & #5858 can probably also be closed.

**Comment by gbaz** [comment] 2021-08-29 01:07
Let's leave that open as it has a bit more detail about what invokes certain downloads and how we might avoid that. I do think you're right that there's more to be done. But I'd like to reduce the proliferation of tickets. Its still not clear to me what _specific_ interactions in cabal we need to fix so that it doesn't fail without network access in certain cases.
