### ISSUE TITLE
The "benchmark" target dependencies conflict with "executable" targets

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/cabal#1768] opened 2014-04-11 10:32 UTC
I have a package with the following structure:

```cabal
library
  ...
executable measure-memory
  ...
  build-depends:
    ghc-datasize,
    ...
benchmark benchmarks
  ...
  build-depends:
    criterion == 0.8.*,
    ...
```

The `criterion == 0.8.*` dependency conflicts with `ghc-datasize` and its impossible to compile having those two together. The issue with Cabal however is that neither the `benchmark` or `library` target has `ghc-datasize` in dependencies, yet Cabal still considers it and does not allow me to compile the `benchmark` target. When I remove the `executable` target, the compilation goes fine.

I'm on 
```
$ cabal --version
cabal-install version 1.19.2
using version 1.19.2 of the Cabal library 
```

**Comment by 23Skidoo** [comment] 2016-02-18 14:16
Closing as a duplicate of #1575.

**Closed by 23Skidoo** 2016-02-18 14:16 UTC
Labels: duplicate, enhancement
