### ISSUE TITLE
cabal build -v=2 fails with stack trace

### ISSUE THREAD

**Issue by robx** [haskell/cabal#7573] opened 2021-08-24 14:49 UTC
**Describe the bug**

Passing `-v=2` results in a stack trace:

```
$ cabal build -v=2
=2
CallStack (from HasCallStack):
  error, called at ./Distribution/ReadE.hs:42:24 in Cbl-3.4.0.0-ee8b7702:Distribution.ReadE
```

(I think the concrete command (`build`) doesn't matter.)

**Expected behavior**

A clear error stating that the parse failed. (Or alternatively, accepting the argument -- it's not particularly obvious from the help message that the correct syntax appears to be `-v2`; `-v 2` doesn't work either.)

**System information**

OS: macos

 ```
$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.4
```

**Additional context**

Related to #5967?

**Comment by emilypi** [comment] 2021-08-24 21:03
It looks like this is a duplicate of #5967 as you noted. Afaict, this is a problem with the `=` sign for shorthand `-v` verbosities: 

```shell
λ athena cabal → λ git master* → cabal run cabal-install:cabal -- build cabal-install -v=3
Up to date
=3
CallStack (from HasCallStack):
  error, called at src/Distribution/ReadE.hs:42:24 in Cabal-3.6.0.0-inplace:Distribution.ReadE
λ athena cabal → λ git master* → cabal run cabal-install:cabal -- build cabal-install -v 3
Up to date
Project settings changed, reconfiguring...
creating /home/tapas/haskell/cabal/dist-newstyle
creating /home/tapas/haskell/cabal/dist-newstyle/cache
this build was affected by the following (project) config files:
- /home/tapas/haskell/cabal/cabal.project
- /home/tapas/haskell/cabal/cabal.project.local

cabal: Unknown target '3'.
There is no component '3'.
The project has no package '3'.
```

**Closed** 2021-09-06 20:36 UTC
Labels: type: bug, cabal-install: other
