### ISSUE TITLE
`}`  character in a file-path - windows

### ISSUE THREAD

**Issue by IvanRenison** [haskell/cabal#7458] opened 2021-06-26 13:00 UTC
Hello, I have a `}` character in my users' path in windows: `C:\Users\usuario}\` and when I try to install something with cabal, like these: `cabal install ansi-terminal` I get an error like these:
```pwershell
cabal.exe: Error parsing config file
C:\Users\usuario}\AppData\Roaming\cabal\config:28:
mismatched brackets, unexpected }  
```
And the line 28 of that file is:
```
remote-repo-cache: C:\Users\usuario}\AppData\Roaming\cabal\packages
```
The first line of that file to have a path. I tried putting the path in that file with `" "`. `' '` and `< >` but it didn't work.

**Comment by Mikolaj** [comment] 2021-06-26 13:19
Hi @IvanRenison,

I've put such a line into my config file and I experience no problem. What is the output of `cabal --version` on your system?

**Comment by IvanRenison** [comment] 2021-06-26 13:34
`cabal --version` returns:
```
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```
I downloaded it yesterday form: https://www.haskell.org/cabal/download.html

**Comment by IvanRenison** [comment] 2021-06-26 13:36
It is strange, because I am seeing that there are version up tu `3.4.0.0`

**Comment by Mikolaj** [comment] 2021-06-26 13:38
Indeed, 2.4 is very old. You probably need to find and unistall the old cabal (renaming the cabal executable to cabal.old should be enough).

**Comment by jneira** [comment] 2021-06-26 13:39
> `cabal --version` returns:
> ```
> cabal-install version 2.4.1.0
> compiled using version 2.4.1.0 of the Cabal library
> ```
> I downloaded it yesterday form: https://www.haskell.org/cabal/download.html

hi, some reason to not download the last version, 3.4.0.0?

**Comment by Mikolaj** [comment] 2021-06-26 13:40
Yeah, I assumed the new version is somehow obscured by the old one, but I'm just guessing.

**Comment by IvanRenison** [comment] 2021-06-26 13:40
Yes, It seems that that is hapening

**Comment by IvanRenison** [comment] 2021-06-26 13:42
Manual using the new `.exe` I get the same error:
```powershel
PS C:\Users\usuario}\Desktop> ./cabal.exe --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
PS C:\Users\usuario}\Desktop> ./cabal.exe install ansi-terminal
cabal.exe: Error parsing config file
C:\Users\usuario}\AppData\Roaming\cabal\config:28:
mismatched brackets, unexpected } 
```

**Comment by Mikolaj** [comment] 2021-06-26 13:51
I was trying with development version, but perhaps there is something in the other parts of your config file (or with Windows). If the config file is not secret (no passwords in there), could you paste it, e.g., at https://gist.github.com?

It's also possible something else in our computer setups differs, though it's doubtful.

**Comment by IvanRenison** [comment] 2021-06-26 13:53
Here it is: https://gist.github.com/IvanRenison/1b3dea05c9b192bd7132cbd8a2d14311

**Comment by IvanRenison** [comment] 2021-06-26 13:55
I never touched that file, it was generated like that

**Comment by IvanRenison** [comment] 2021-06-26 13:59
I tried deleting the file, and `3.4.0.0` generated a new one, but with the same problem

**Comment by Mikolaj** [comment] 2021-06-26 14:08
Thank you for the full file. Still can't reproduce with cabal 3.5. @jneira: can you? Does anybody have 3.4 handy to try on Linux and on Windows?

**Comment by jneira** [comment] 2021-06-26 14:17
will try to reproduce in windows

**Comment by jneira** [comment] 2021-06-26 19:18
I've reproduced in windows simple adding a `}` in the `store-dir` field

**Comment by Mikolaj** [comment] 2021-06-26 19:26
Wild. So it looks like it happens only in Windows and in all versions of cabal?

**Comment by phadej** [comment] 2021-06-26 19:53
Try with `master`. The code generating `mismatched brackets` errors have been removed in https://github.com/haskell/cabal/commit/fe82a920598367debc7553da016e85574f8a3fe8, so the parsing shouldn't fail anymore.

**Comment by Mikolaj** [comment] 2021-06-26 20:02
Thank you @phadej. I do try with master and it doesn't fail for me. The commit you point to is probably the reason.

**Comment by jneira** [comment] 2021-06-28 08:02
I can confirm master works in windows too:

```
D:\ws\haskell\cabal-test>cabal build
cabal: Error parsing config file
D:\user\AppData\Roaming\cabal\config:30:
mismatched brackets, unexpected }

D:\ws\haskell\cabal-test>D:\user\AppData\Roaming\cabal\bin\cabal.exe build
Resolving dependencies...

D:\ws\haskell\cabal-test>cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library

D:\ws\haskell\cabal-test>D:\user\AppData\Roaming\cabal\bin\cabal.exe --version
cabal-install version 3.5
compiled using version 3.5.0.0 of the Cabal library
```

**Comment by Mikolaj** [comment] 2021-06-28 08:12
Splendid. @IvanRenison: will you wait for 3.6 release or try to use a pre-release? I think some windows artefacts are being built by CI, but I don't know how to get to them --- do we have any nightly builds available to users?

**Comment by phadej** [comment] 2021-06-28 08:43
@Mikolaj
- Actions tab
- Search for branch master (or one you are interested in) and Artifacts, e.g. https://github.com/haskell/cabal/actions?query=branch%3Amaster+Artifacts
- Click one, currently the latest is https://github.com/haskell/cabal/actions/runs/901692538
- Download an artifact

**Comment by Mikolaj** [comment] 2021-06-28 10:11
Amazing! @IvanRenison: would you kindly try and become an early adopter of the development snapshot artefacts feature and try to install the latest development version of cabal (as linked above) and become an early adopter of cabal 3.6-rc1 as well, which solves your bug (please do report whether it does)? Any feedback along the way would be much appreciated, e.g., which step was particularly confusing. Thank you!

**Comment by IvanRenison** [comment] 2021-06-28 12:58
Yes, I will try it.
Any way, don't worry about me. I use linux for all the coding. I only wanted to try my project in windows. But I have no harry for doing it

**Comment by IvanRenison** [comment] 2021-06-28 13:43
It didn't work:
```powershell
PS C:\Users\usuario}\Desktop> ./cabal.exe --version
cabal-install version 3.5
compiled using version 3.5.0.0 of the Cabal library
PS C:\Users\usuario}\Desktop> cabal install ansi-terminal
cabal.exe: Error parsing config file
C:\Users\usuario}\AppData\Roaming\cabal\config:27:
mismatched brackets, unexpected }
```
And when I manually deleted that config file:
```powershell
PS C:\Users\usuario}\Desktop> cabal install ansi-terminal
Config file path source is default config file.
Config file C:\Users\usuario}\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\usuario}\AppData\Roaming\cabal\config
cabal.exe: Error parsing config file
C:\Users\usuario}\AppData\Roaming\cabal\config:27:
mismatched brackets, unexpected }
```

**Comment by IvanRenison** [comment] 2021-06-28 14:01
Yes, it worked, but I had to manually delete the old `config` file

**Comment by Mikolaj** [comment] 2021-06-28 14:07
So, apparently, the dev binary artefacts are usable and the issue is indeed fixed. Success. Thank you all!

**Comment by Mikolaj** [comment] 2021-06-28 14:10
BTW, any idea where we could advertise what @phadej pictured above? How to get the dev build? Even just to point users to, after their bugs are fixed on master.

**Comment by fgaz** [comment] 2021-06-28 15:36
Maybe on the cabal website, next to the other downloads

**Comment by Mikolaj** [comment] 2021-06-28 15:58
Indeed, this looks a good location to me: https://www.haskell.org/cabal/download.html, somewhere closer to the bottom.

**Comment by Mikolaj** [comment] 2021-06-28 16:27
Anybody up to making a PR at https://github.com/haskell/cabal-website? I take it upon myself to badger @emilypi to rebuild the docs after it's merged (just as I annoyingly badger weekly right now:).

**Comment by emilypi** [comment] 2021-06-28 20:37
> Anybody up to making a PR at https://github.com/haskell/cabal-website

I feel badgered, and therefore will make a PR 😄

**Closed** 2021-09-02 21:59 UTC
Labels: type: bug, Cabal: parser, status: fixed in master
