### ISSUE TITLE
Diagnosing linking problems

### ISSUE THREAD

**Issue by Rufflewind** [haskell/cabal#1987] opened 2014-07-08 22:16 UTC
Currently, Cabal configure checks for dependencies by running a sample program through the C compiler.  This can fail for many reasons, but Cabal just lumps them into a single error message:

    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.

This can be very confusing, because there are times where this message is completely wrong.  Cabal's mechanism for detecting the missing libraries is very simplistic: it just compiles each of them separately.  So what's the problem with this?

Here's what I ran into: I wanted to link library A and B (and library A depends on library B), but it reports both A and B are "missing".  It turns out that library B also depends on library C.  But since Cabal checks missing libraries by going through each one separately, the dependency is broken and thus the error message becomes meaningless.

It's not easy to automatically figure out what caused the problem, so I think it would be really helpful if the stderr from the test compilation was recorded into a log file (similar to how Autoconf logs everything into `config.log`) for debugging purposes.  Furthermore, it's probably a bad idea to try to compile each library separately in an attempt to narrow down the cause.  In fact, it's probably easiest to just dump `ld`'s error message to the user similar to how `gcc` does.

**Comment by ttuegel** [comment] 2015-04-23 23:55
Duplicate of #1152.

**Closed by ttuegel** 2015-04-23 23:55 UTC
Labels: enhancement
