### ISSUE TITLE
Package installation error

### ISSUE THREAD

**Issue by MagisDing** [haskell/cabal#2793] opened 2015-08-25 16:35 UTC
Maybe this issue is not really about "cabal", but I was trying to install package "network", and met the error like this:
>○ cabal install network
Resolving dependencies...
Configuring network-2.6.2.1...
Failed to install network-2.6.2.1
Build log ( /Users/Yuzhe_Ding/.cabal/logs/network-2.6.2.1.log ):
Configuring network-2.6.2.1...
configure: WARNING: unrecognized options: --with-compiler, --with-gcc
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/var/folders/pp/76z_j1x56xn2t3g08k0jrvm80000gn/T/cabal-tmp-48042/network-2.6.2.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
cabal: Error: some packages failed to install:
network-2.6.2.1 failed during the configure step. The exception was:
>ExitFailure 1

Where and how can I get the "config.log"? I tried 
>Yuzhe_Ding at Yuzhe-Ding-MacBook-Pro in ~/.cabal
○ ./configure
zsh: no such file or directory: ./configure

and here is my $PATH:
>○ echo $PATH
usr/local/bin
:/Users/Yuzhe_Ding/.pyenv/shims
:/usr/local/Cellar
:/Users/Yuzhe_Ding/.local/bin
:/Users/Yuzhe_Ding/.cabal/bin
:/Applications/ghc-.10.2.app/Contents/bin
:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin

**Comment by 23Skidoo** [comment] 2015-08-25 17:04
> Where and how can I get the "config.log"?

It's in the temporary build directory that gets deleted after `install` finishes. Try the following:

```
$ cabal get network
$ cd network
$ cabal build
```
The `config.log` file will be in the `network` directory.

**Comment by 23Skidoo** [comment] 2015-08-25 17:05
And yes, it's likely a `network` issue.

**Comment by MagisDing** [comment] 2015-08-26 04:08
@23Skidoo Really appreciated for your replies, finally I've got the config.log, show as follows:
>## ----------- ##
## Core tests. ##
## ----------- ##

configure:2270: checking build system type
configure:2284: result: x86_64-apple-darwin14.5.0
configure:2304: checking host system type
configure:2317: result: x86_64-apple-darwin14.5.0
configure:2392: checking for gcc
configure:2408: found /usr/bin/gcc
configure:2419: result: gcc
configure:2648: checking for C compiler version
configure:2657: gcc --version >&5
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
configure:2668: $? = 0
configure:2657: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
configure:2668: $? = 0
configure:2657: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:2668: $? = 1
configure:2657: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:2668: $? = 1
configure:2688: checking whether the C compiler works
configure:2710: gcc    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2714: $? = 0
configure:2762: result: yes
configure:2765: checking for C compiler default output file name
configure:2767: result: a.out
configure:2773: checking for suffix of executables
configure:2780: gcc -o conftest    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2784: $? = 0
configure:2806: result: 
configure:2828: checking whether we are cross compiling
configure:2836: gcc -o conftest    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2840: $? = 0
configure:2847: ./conftest
./configure: line 2849: ./conftest: cannot execute binary file
configure:2851: $? = 126
configure:2858: error: in `/Users/Yuzhe_Ding/network-2.6.2.1':
configure:2860: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

And by the way, I met the same problem when I was trying to install the package “old-time",config.log shows 
>## ----------- ##
## Core tests. ##
## ----------- ##

configure:2256: checking for gcc
configure:2272: found /usr/bin/gcc
configure:2283: result: gcc
configure:2512: checking for C compiler version
configure:2521: gcc --version >&5
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
configure:2532: $? = 0
configure:2521: gcc -v >&5
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
configure:2532: $? = 0
configure:2521: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:2532: $? = 1
configure:2521: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:2532: $? = 1
configure:2552: checking whether the C compiler works
configure:2574: gcc    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2578: $? = 0
configure:2626: result: yes
configure:2629: checking for C compiler default output file name
configure:2631: result: a.out
configure:2637: checking for suffix of executables
configure:2644: gcc -o conftest    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2648: $? = 0
configure:2670: result: 
configure:2692: checking whether we are cross compiling
configure:2700: gcc -o conftest    -Wall -undefined dynamic_lookup -bundle  conftest.c  >&5
configure:2704: $? = 0
configure:2711: ./conftest
./configure: line 2713: ./conftest: cannot execute binary file
configure:2715: $? = 126
configure:2722: error: in `/Users/Yuzhe_Ding/network-2.6.2.1/old-time-1.1.0.3':
configure:2724: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

Actually, I was stuck by the two packages when I made a fresh installation for Haskell. Should I take these two as considerable dependency errors? And BTW: what is the recommendable ways to upgrade cabal,ghc and stack  if I follow the steps on http://ghcformacosx.github.io/?

**Comment by 23Skidoo** [comment] 2015-08-26 12:18
So it looks like your problems are caused by `clang` not perfectly mimicking `gcc`. I don't know that much about GHC on OS X, maybe @cartazio can help?

**Comment by cartazio** [comment] 2015-08-26 13:38
What ghc version are you on?
What does ghc --info emit? 
Do you have auto tools / auto conf installed?

**Comment by cartazio** [comment] 2015-08-26 13:39
What version of Cabal are you using

**Comment by cartazio** [comment] 2015-08-26 13:39
And which ghc installer did you use

**Comment by cartazio** [comment] 2015-08-26 13:40
Please provide this info and I'll try to get back to you this afternoon.

**Comment by 23Skidoo** [comment] 2015-08-27 00:20
Since this seems to be not a Cabal bug, I'm closing the ticket, but you guys are welcome to continue the conversation here.

**Closed by 23Skidoo** 2015-08-27 00:20 UTC
Labels: invalid, question

**Comment by cartazio** [comment] 2015-08-27 14:30
Theory: did you install the Xcode command line tools?

**Comment by MagisDing** [comment] 2015-08-27 14:42
@cartazio Yeah, I've installed that.
> xcode-select -p
> /Applications/Xcode.app/Contents/Developer
