### ISSUE TITLE
`cabal init` fails if folder name exists on hackage

### ISSUE THREAD

**Issue by menelaos** [haskell/cabal#6236] opened 2019-09-12 13:33 UTC
**Describe the bug**

If `cabal init` is run inside a folder that has the same name as a package on hackage, cabal throws an error: `Error: no package name provided.`

**To Reproduce**

```
mkdir lens
cd lens
cabal init
```

This also happens for a hidden folder (`.lens`).

It does not happen if the folder name does not exist on hackage:

```
mkdir doesnotexistonhackage
cd doesnotexistonhackage
cabal init
```

**Expected behavior**
I would except `cabal` to at least give a more precise error message or better proceed with only a warning.

**System information**
 - cabal-install version 3.0.0.0

**Comment by naglalakk** [comment] 2019-09-14 13:56
I second this. I just got this error as well and it's very confusing and gives no indication of what is actually going on

**Comment by codygman** [comment] 2019-11-10 06:38
I was just bit by this one and if I hadn't found the issue googling it could have wasted a bit of time.

**Comment by hvr** [comment] 2019-11-10 08:29
This appears to be a regression; previously `cabal init` would complain to you about this during the interactive questionnaire:

```
This package name is already used by another package on hackage. Do you want to choose a different name? [default: y] 
```

**Comment by fgaz** [comment] 2021-05-27 09:05
@emilypi #7344 fixes this, right?

**Comment by jneira** [comment] 2021-07-13 17:43
i would close it when the mentioned pr is merged

**Comment by gbaz** [comment] 2021-07-13 21:52
As a general practice I would recommend closing tickets when the prs resolving them are merged, _not_ when a cabal with the pr merged is actually released. It makes ticket management much saner.

**Comment by jneira** [comment] 2021-07-14 05:37
> 
> 
> As a general practice I would recommend closing tickets when the prs resolving them are merged, _not_ when a cabal with the pr merged is actually released. It makes ticket management much saner.

Yeah, i forgot we have milestones here to signal the issue is fixed for some release

**Closed by jneira** 2021-07-14 05:37 UTC
Labels: cabal-install: cmd/init, status: fixed in master, type: bug

**Comment by emilypi** [comment] 2021-07-14 17:54
This was fixed in #7344 yes

**Comment by weihsiu** [comment] 2022-03-10 06:40
this error is back.  using cabal-install version 3.6.2.0

**Comment by Mikolaj** [comment] 2022-03-10 06:48
Hi @weihsiu,

I think we had a wrong milestone set, suggesting the fix has been merged to 3.6.2, while it's slated for 3.8.

Could you perhaps try with the master branch?

**Comment by weihsiu** [comment] 2022-03-10 06:51
np, i just wanted to report the issue.  as long as it will be fixed, i am cool.

**Comment by rkuprov** [comment] 2023-03-11 06:54
The issue is alive as of 2023.03.10

**Comment by ulysses4ever** [comment] 2023-03-11 11:00
@rkuprov what version of cabal are you using?

**Comment by rkuprov** [comment] 2023-03-11 16:32
`cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library`

**Comment by rkuprov** [comment] 2023-03-11 16:33
Had to do the `init --interactive` and force ignore the warning about the package already present on Hackage.

**Comment by emilypi** [comment] 2023-03-11 16:41
@rkuprov use a version of cabal that was released in the last 2 years and you'll be set.

**Comment by rkuprov** [comment] 2023-03-11 16:46
My bad. I wrongly assumed that GHCup would use everything latest.

**Comment by ulysses4ever** [comment] 2023-03-11 17:21
@rkuprov unfortunately, ghcup has its own notion of `recommended` release, which it uses to pick default versions, and the lead maintainer @hasufell explicitly refused to bump recommended cabal to 3.8 citing several regressions on 3.8. In my opinion, there were much more bug fixes in that release that justify a handful of regression, but of well...

**Comment by hasufell** [comment] 2023-03-12 03:54
Correct. GHCup is a distribution channel just like nixpkgs, brew or some ubuntu ppa. As such it has absolute autonomy regarding which versions are recommended. 

To always and only get upstream bindists, you can use a different channel: https://github.com/haskell/ghcup-metadata/blob/develop/ghcup-vanilla-0.0.7.yaml

In this channel I can make `latest` and `recommended` equivalent, but we will close bug reports as WONTFIX if you use that channel. 

Check out the configuration: https://github.com/haskell/ghcup-hs/blob/c20deceaa8189a1f3034335759b84132f9a9ef82/data/config.yaml#L59
