### ISSUE TITLE
`new-install` no documentation in ~/Library/Haskell/doc/

### ISSUE THREAD

**Issue by xsebek** [haskell/cabal#6044] opened 2019-05-10 22:24 UTC
Hi,

I would like to have a master index of documentation for new style Cabal packages.
This may be under documented or just plain fail in my setting.

I am quite new to Cabal and I did not find any mention about this in the documentation.
There is however the `where_is_my_stuff.txt` that says master index should be in `~/Library/Haskell/doc/` (no such folder) after first `cabal install`.
However I do not want to use the old style commands _again_.

Thanks for any hints 😄

**Comment by 23Skidoo** [comment] 2019-05-14 11:34
Looks like a duplicate of #5268.

**Closed** 2021-10-14 01:38 UTC
Labels: type: enhancement, cabal-install: nix-local-build, cabal-install: cmd/install, cabal-install: cmd/haddock
