### ISSUE TITLE
cabal new-build fails with "Invalid package conduit-extra-1.2.3.2"

### ISSUE THREAD

**Issue by laura-dietz** [haskell/cabal#5447] opened 2018-07-19 04:17 UTC
I have a [project](https://github.com/bgamari/simplir) which inexplicably fails to build with `cabal new-build`. Specifically,
```
simplir$ cabal new-build -v3
File monitor 'config' unchanged.
this build was affected by the following (project) config files:
- /home/dietz/trec-car/code/mediawiki-annotate/simplir/cabal.project
File monitor 'improved-plan' changed: first run
File monitor 'elaborated-plan' changed: first run
File monitor 'compiler' unchanged.
File monitor 'solver-plan' unchanged.
Elaborating the install plan...
File monitor 'source-hashes' changed: first run
Invalid package conduit-extra-1.2.3.2
```
Strangely, I see no error similar to this in the `cabal` repository. Any idea what this might be due to?

**Comment by hvr** [comment] 2018-07-19 07:34
@laura-dietz which commit of `simplir` did you try to build? which version of GHC and which version of `cabal --version`?

I tried to reproduce, but it worked (with GHC 8.2.2; but I had to use `--max-backjumps=1`)

have you tried removing `dist-newstyle/` in case `new-build`'s cache got corrupted somehow?

**Comment by laura-dietz** [comment] 2018-07-19 12:13
I tried 2.2 and latest `master`.

This is `simplir` commit 2c0eaccdd854604699f52958d05e189ed13dfe1a.

We've tried removing `dist-newstyle` as well as `~/.cabal/store`.

**Comment by hvr** [comment] 2018-07-19 12:19
@laura-dietz https://github.com/bgamari/simplir/commit/2c0eaccdd854604699f52958d05e189ed13dfe1a doesn't appear to exist

**Comment by laura-dietz** [comment] 2018-07-19 13:36
Indeed removing `~/.cabal/packages` resolved the issue. Would it be possible to include this hint in the error message?

Thank you!

**Comment by fgaz** [comment] 2021-02-02 15:36
> "Strangely, I see no error similar to this in the cabal repository. Any idea what this might be due to?"

Same, both in the cabal and ghc one. I'll close this since it's an old ticked but if someone finds where that error comes from please leave a comment.

**Closed by fgaz** 2021-02-02 15:36 UTC
