### ISSUE TITLE
cabal new-build doesn't handle / understand how to handle missing profiled library lib 

### ISSUE THREAD

**Issue by cartazio** [haskell/cabal#3865] opened 2016-09-19 01:34 UTC
not sure if it should, but definitely seems like a hump in the usability

do we have a ticket tracking these sorts of little warts?

**Comment by ezyang** [comment] 2016-09-19 14:25
Barring a more detailed report, I'm going to close this as a dupe of #3790.

**Closed by ezyang** 2016-09-19 14:25 UTC
