### ISSUE TITLE
cabal upload -c should be removed?

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal#2583] opened 2015-05-07 22:06 UTC
Cabal check appears to do a fully local check now.

Meanwhile upload -c seems to hit a url that was never enabled on new-hackage? Is this correct? If so we should either remove it or make it an alias for cabal check?

**Comment by 23Skidoo** [comment] 2015-05-08 09:18
Duplicate of #1823. 

tl;dr: yes, it probably should be removed.

**Closed by 23Skidoo** 2015-05-08 09:18 UTC
Labels: duplicate
