### ISSUE TITLE
Failed to parse libcmark-gfm's pkgconfig modversion

### ISSUE THREAD

**Issue by felixonmars** [haskell/cabal#4860] opened 2017-11-03 09:35 UTC
```
$ pkg-config --modversion libcmark-gfm
0.28.0.gfm.11
```

```
Configuring cmark-gfm-0.1.3...
Setup: parsing output of pkg-config --modversion failed
```

**Comment by hvr** [comment] 2017-11-03 11:34
I'm sure we have issues about this; didn't we already fix the problem with non-numeric pkg-config versions?

@felixonmars which cabal version did you use?

**Comment by 23Skidoo** [comment] 2017-11-03 11:48
Looks like a duplicate of #163.

**Comment by felixonmars** [comment] 2017-11-03 11:56
@hvr Cabal-2.0.0.2.

@23Skidoo Indeed, thanks.

**Comment by 23Skidoo** [comment] 2017-11-03 14:17
Closing in favour of #163.

**Closed by 23Skidoo** 2017-11-03 14:17 UTC
Labels: resolution: duplicate, type: bug

**Comment by idontgetoutmuch** [comment] 2018-03-01 15:51
Has this become unfixed?

```
[nix-shell:~/hmatrix/packages/gsl]$ cabal build
Resolving dependencies...
Configuring hmatrix-gsl-0.18.2.0...
cabal: parsing output of pkg-config --modversion failed

[nix-shell:~/hmatrix/packages/gsl]$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.1 of the Cabal library 

[nix-shell:~/hmatrix/packages/gsl]$ pkg-config --version
0.29.2
```

**Comment by 23Skidoo** [comment] 2018-03-01 16:08
@idontgetoutmuch #163 is still open, so I think this wasn't fixed in the first place.
