### ISSUE TITLE
Does not support ~ in paths in .cabal/config

### ISSUE THREAD

**Issue by bos** [haskell/cabal#645] opened 2012-05-24 05:40 UTC
(Imported from [Trac #652](http://hackage.haskell.org/trac/hackage/ticket/652), reported by @nomeata on 2010-04-03)

This feature request was submitted via the Debian Bugtracker at [http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=576303](http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=576303):

Paths in ~/.cabal/config don't seem to support ~ or any other means of
specifying $HOME.  This makes it difficult to specify paths like prefix, build-summary, and remote-repo-cache in a non-system-specific way.

Greetings,
Joachim

**Comment by ntc2** [comment] 2016-01-26 23:47
This seems to effectively stop me from versioning my ~/.cabal/config and sharing it across all systems I use, without creating a duplicate for every system on which I have a different user name. Of course, I only have three user names, so duplication is not very difficult, just ugly.

**Comment by lspitzner** [comment] 2016-01-27 23:45
have not touched the code yet, but modifying `initialPathTemplateEnv` in `Cabal:Distribution.Simple.InstallDirs` might be the approach. (semi note-to-self)

**Comment by Mikolaj** [comment] 2021-06-25 19:22
Duplicate of #1857

**Comment by Mikolaj** [comment] 2021-06-25 19:24
Also, this is related to #680 that is now being worked on, so I'm taking the liberty to close it to focus the discussion in two places instead of ten.

**Closed by Mikolaj** 2021-06-25 19:24 UTC
Labels: cabal-install: other, type: enhancement
