### ISSUE TITLE
Test failure in Cabal unit-tests

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#3037] opened 2016-01-12 14:02 UTC
Reliably reproducible with

```
unit-tests --quickcheck-replay '5 TFGenR 00000005BDE3310B000000000007A120000000000000E03700000000431D6580 0 283726776524341248 58 0'
```

I don't know if this is a bug in the test suite or in `Distribution.Version`.

**Comment by ezyang** [comment] 2016-01-12 16:56
What's the error?

**Comment by edsko** [comment] 2016-01-13 08:29
```
  Distribution.Version
    Parse Property 1:                              FAIL
      *** Failed! Falsifiable (after 1 test): 
      IntersectVersionRanges (ThisVersion (Version {versionBranch = [2], versionTags = []})) (VersionRangeParens (UnionVersionRanges (UnionVersionRanges (VersionRangeParens (LaterVersion (Version {versionBranch = [2], versionTags = []}))) (EarlierVersion (Version {versionBranch = [0], versionTags = []}))) (ThisVersion (Version {versionBranch = [0], versionTags = []}))))
      Use --quickcheck-replay '5 TFGenR 00000005BDE3310B000000000007A120000000000000E03700000000431D6580 0 283726776524341248 58 0' to reproduce.
    Parse Property 2:                              FAIL
      *** Failed! Falsifiable (after 1 test): 
      IntersectVersionRanges (ThisVersion (Version {versionBranch = [2], versionTags = []})) (VersionRangeParens (UnionVersionRanges (UnionVersionRanges (VersionRangeParens (LaterVersion (Version {versionBranch = [2], versionTags = []}))) (EarlierVersion (Version {versionBranch = [0], versionTags = []}))) (ThisVersion (Version {versionBranch = [0], versionTags = []}))))
      Use --quickcheck-replay '5 TFGenR 00000005BDE3310B000000000007A120000000000000E03700000000431D6580 0 283726776524341248 58 0' to reproduce.

2 out of 60 tests failed (0.53s)
```

**Comment by dcoutts** [comment] 2016-01-13 13:39
Oh, that's my code & tests :-)

**Comment by edsko** [comment] 2016-01-13 13:40
I should have known :grin:

**Comment by 23Skidoo** [comment] 2016-01-31 23:12
So we have the following situation here:

```
display (vr)                       = "==2 && ((>2) || <0 || ==0)"
display $ simpleParse (display vr) = "==2 && ((>2) || <=0)"
```

And the property says that these two must be equal, so it seems to be wrong.

**Comment by 23Skidoo** [comment] 2016-02-01 00:25
The property is definitely wrong. The problem is that there's no way to tell whether the source string used `<0 || ==0` or `<= 0` since the latter is a syntax sugar for the former and both look like `UnionVersionRanges (EarlierVersion [...]) (ThisVersion [...])` on the `VersionRange` level.

Also there seems to be ambiguity in how `(a) || b || c` can be expressed: can be either `UnionVersionRanges (VersionRangeParens [...]) (UnionVersionRanges [...] [...])` or `UnionVersionRanges (UnionVersionRanges (VersionRangeParens [...]) [...]) [...]`.

So I think I'll just disable these tests and close this issue.

**Comment by 23Skidoo** [comment] 2016-02-01 00:25
The property is definitely wrong. The problem is that there's no way to tell whether the source string used `<0 || ==0` or `<= 0` since the latter is a syntax sugar for the former and both look like `UnionVersionRanges (EarlierVersion [...]) (ThisVersion [...])` on the `VersionRange` level.

Also there seems to be ambiguity in how `(a) || b || c` can be expressed: can be either `UnionVersionRanges (VersionRangeParens [...]) (UnionVersionRanges [...] [...])` or `UnionVersionRanges (UnionVersionRanges (VersionRangeParens [...]) [...]) [...]`.

So I think I'll just disable these tests and close this issue.

**Closed** 2016-02-01 00:28 UTC
Labels: bug

**Comment by 23Skidoo** [comment] 2016-02-13 11:04
If someone wants to look into this, I think the proper solution would be to add a `normalise` function. So instead of `parse . display === id` (which does not hold in general for the `VersionInterval` type), something like `parse . display . normalise === normalise` would hold.
