### ISSUE TITLE
`new-build` does not like `gtk3`-dependency

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#3320] opened 2016-04-11 22:30 UTC
It seems to be independent of local cabal package.

(`foo` is local, has a direct dependency on `gtk3`, compiles fine when removing the dependency.)

~~~~
cabal new-build -j1
In order, the following will be built (use -v for more details):
gtk3-0.14.2
foo-0.1.0.0
[1 of 2] Compiling SetupWrapper     ( CWD/dist-newstyle/tmp/gtk3-12054/gtk3-0.14.2/SetupWrapper.hs, CWD/dist-newstyle/tmp/gtk3-12054/gtk3-0.14.2/dist/setup/SetupWrapper.o )
[2 of 2] Compiling Main             ( CWD/dist-newstyle/tmp/gtk3-12054/gtk3-0.14.2/dist/setup/setup.hs, CWD/dist-newstyle/tmp/gtk3-12054/gtk3-0.14.2/dist/setup/Main.o )
Linking CWD/dist-newstyle/tmp/gtk3-12054/gtk3-0.14.2/dist/setup/setup ...
[1 of 2] Compiling Gtk2HsSetup      ( Gtk2HsSetup.hs, dist/setup-wrapper/Gtk2HsSetup.o )
[2 of 2] Compiling Main             ( SetupMain.hs, dist/setup-wrapper/Main.o )
Linking dist/setup-wrapper/setup ...
Configuring gtk3-0.14.2...
setup: At least the following dependencies are missing:
time -any, transformers -any
~~~~

**Comment by ezyang** [comment] 2016-04-11 22:35
I think this is #3199. As a workaround, try passing `--constraint=gtk3 +build-demos`

**Comment by lspitzner** [comment] 2016-04-11 22:45
(ah, sorry for dup; i had filtered for nix-local-build.)

**Comment by ezyang** [comment] 2016-04-11 22:49
I am not sure it is a duplicate. Did the workaround work?

**Comment by ezyang** [comment] 2016-04-11 23:31
Workaround confirmed to work, closing as dupe.

**Closed by ezyang** 2016-04-11 23:31 UTC
Labels: bug, nix-local-build, urgent
