### ISSUE TITLE
cabal: Could not resolve dependencies

### ISSUE THREAD

**Issue by wereHamster** [haskell/cabal#2399] opened 2015-01-30 13:07 UTC
Instead of telling me that a package doesn't exist, I get an error telling me that cabal cold not resolve dependencies. Here is the cabal file: https://gist.github.com/wereHamster/5d2c1f52ef635998a875. Also, if I move the build-depends line around I get different error messages. Here are a few:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: test-0.1.0.0 (user goal)
next goal: this-package-doesnt-exist-but-cabal-doesnt-tell-me-that (dependency
of test-0.1.0.0)
Dependency tree exhaustively searched.
```

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: test-0.1.0.0 (user goal)
next goal: this-package-doesnt-exist-but-cabal-doesnt-tell-me-that (dependency
of test-0.1.0.0)
fail (unknown package:
this-package-doesnt-exist-but-cabal-doesnt-tell-me-that)
Dependency tree exhaustively searched.
```

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: test-0.1.0.0 (user goal)
trying: transformers-0.3.0.0/installed-645... (dependency of test-0.1.0.0)
trying: snap-0.13.3.2 (dependency of test-0.1.0.0)
trying: errors-1.4.7 (dependency of snap-0.13.3.2)
trying: either-4.3.3 (dependency of errors-1.4.7)
trying: semigroupoids-4.2 (dependency of either-4.3.3)
trying: semigroupoids-4.2:+comonad
trying: semigroupoids-4.2:+distributive
trying: distributive-0.4.4 (dependency of semigroupoids-4.2:+distributive)
trying: transformers-compat-0.3.3.4 (dependency of distributive-0.4.4)
trying: transformers-compat-0.3.3.4:-two
rejecting: transformers-compat-0.3.3.4:-three (conflict:
transformers==0.3.0.0/installed-645..., transformers-compat-0.3.3.4:three =>
transformers>=0.4.1 && <0.5)
rejecting: transformers-compat-0.3.3.4:+three (manual flag can only be changed
explicitly)
Dependency tree exhaustively searched.
```

cabal-install version 1.22.0.0, using version 1.22.0.0 of the Cabal library

**Comment by wereHamster** [comment] 2015-01-30 14:06
cabal 1.20 gives yet another error message. It's like lottery.

**Comment by wereHamster** [comment] 2015-01-30 16:11
Also noteworthy: removing the build-depends line which references that non-existing package allows cabal to come up with a valid install plan.

**Comment by grayjay** [comment] 2016-02-07 23:42
The missing error message in the first log is a duplicate of #2179, and the message in the third log that is unrelated to the missing dependency is a duplicate of #941.  I assume that the second log is the expected result.

**Closed by grayjay** 2016-02-07 23:42 UTC
Labels: bug, cabal-install, solver
