### ISSUE TITLE
cabal update says to use cabal new-update, but latter is broken.

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5398] opened 2018-06-26 18:05 UTC
I cannot find my old ticket, but not it's super annoying:

```
% cabal update
Warning: The update command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style or the legacy v1-update
alias as new-style projects will become the default in the next version of
cabal-install. Please file a bug if you cannot replicate a working v1- use
case with the new-style commands.

Downloading the latest package list from hackage.haskell.org
```

```
% cabal new-update
No cabal.project file or cabal file matching the default glob './*.cabal' was found.
Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.
```

I consider this is a release blocker.

**Comment by typedrat** [comment] 2018-06-26 18:08
Are you within a new-build project? There are two possible bugs here, either new-update only works in a project which is decidedly non-ideal but a missing functionality issue or it's very broken internally, and I hope it's the former.

**Comment by phadej** [comment] 2018-06-26 19:12
Found previous issue: https://github.com/haskell/cabal/issues/5096

**Comment by typedrat** [comment] 2018-06-26 19:19
That’s an easy fix. Should have it in today.

Alexis Williams

**Comment by typedrat** [comment] 2018-06-26 20:13
Duplicate of #5096.

**Closed by typedrat** 2018-06-26 20:13 UTC
Labels: cabal-install: cmd/update, cabal-install: nix-local-build, priority: high :fire:, type: bug
