### ISSUE TITLE
Symlinks always fail

### ISSUE THREAD

**Issue by Fresheyeball** [haskell/cabal#1802] opened 2014-04-21 22:15 UTC
No matter what I try and install with cabal, the linking step fails. I've tried:

    cabal install hoogle

and 

    cabal install hoogle --global

And I always get back something like this: 

    Warning: could not create symlinks in /Users/me/Library/Haskell/bin for
    cpphs, hoogle, shake because the files exist there already and are not managed
    by cabal. You can create symlinks for these executables manually if you wish.
    The executable files have been installed at
    /Library/Haskell/ghc-7.6.3/lib/cpphs-1.18.4/bin/cpphs,
    /Library/Haskell/ghc-7.6.3/lib/hoogle-4.2.32/bin/hoogle,
    /Library/Haskell/ghc-7.6.3/lib/shake-0.11.4/bin/shake

I've tried deleting the files located in `/Users/me/Library/Haskell/bin` and reinstalling, but still no luck.

Why is this happening? I can make the links by hand, but would really prefer that cabal work as intended.

**Comment by ttuegel** [comment] 2015-04-24 00:05
Duplicate of #1452.

**Closed by ttuegel** 2015-04-24 00:05 UTC
