### ISSUE TITLE
MIN_VERSION macro semantics/sharing between components

### ISSUE THREAD

**Issue by lspitzner** [haskell/cabal#3188] opened 2016-02-24 16:36 UTC
`MIN_VERSION_foo` is defined for the executable component of a package when the executable itself does not depend on `foo`, but the library component of the same package does. It is not even necessary that the executable depends on the library.

See https://github.com/lspitzner/MIN_VERSION-testcase

**Comment by lspitzner** [comment] 2016-02-24 16:39
Expected behaviour is that MIN_VERSION definitions always correspond to package visibility.

**Comment by ezyang** [comment] 2016-02-24 19:31
This is fixed in https://github.com/haskell/cabal/pull/3022 (but the commit seems to have disappeared from GitHub PR, I'll see what happened)

**Comment by ezyang** [comment] 2016-02-24 21:45
I fixed the PR; the specific commit is https://github.com/ezyang/cabal/commit/c96c423768a79497c85fca8df39cb9ed6cc653b0

**Comment by ezyang** [comment] 2016-02-24 21:46
Closing as dupe of #1893.

**Closed by ezyang** 2016-02-24 21:46 UTC
Labels: enhancement

**Comment by lspitzner** [comment] 2016-02-25 09:59
great, thanks!
