### ISSUE TITLE
GHC 8: * Couldn't match expected type `PackageDescription' with actual type `PackageIdentifier'

### ISSUE THREAD

**Issue by Heather** [haskell/cabal#3054] opened 2016-01-15 14:32 UTC
during building `cabal-install`

```
[78 of 83] Compiling Distribution.Client.Install ( Distribution\Client\Install.hs, dist\build\cabal\cabal-tmp\Distribution\Client\Install.o )

Distribution\Client\Install.hs:1396:44: error:
    * Couldn't match expected type `PackageDescription'
                  with actual type `PackageIdentifier'
    * In the first argument of `Configure.computeComponentId', namely
        `(PackageDescription.package pkg)'
      In the expression:
        Configure.computeComponentId
          (PackageDescription.package pkg)
          CLibName
          (CD.libraryDeps (depends rpkg))
          (flags rpkg)
      In an equation for `ipid':
          ipid
            = Configure.computeComponentId
                (PackageDescription.package pkg)
                CLibName
                (CD.libraryDeps (depends rpkg))
                (flags rpkg)
```

**Comment by 23Skidoo** [comment] 2016-01-15 14:44
Guess we need to bump the Cabal library version in `master`.

**Comment by Heather** [comment] 2016-01-15 14:47
@23Skidoo do you mean caba-install and Cabal in this repository are currently have no compatibility?

**Comment by 23Skidoo** [comment] 2016-01-15 14:57
I think that the problem here is that cabal-install `master` is not compatible with the Cabal 1.23 snapshot released with GHC 8 RC1.

**Comment by Heather** [comment] 2016-01-15 15:22
@23Skidoo I build Cabal from this repository too

**Comment by 23Skidoo** [comment] 2016-01-15 15:31
Looks like `master` is actually broken. Wonder why Travis didn't catch this.

**Comment by 23Skidoo** [comment] 2016-01-15 15:43
Just built cabal-install/Cabal from source, everything worked fine. I guess that in your case the wrong Cabal snapshot was picked up for some obscure reason.

**Comment by Heather** [comment] 2016-01-15 15:44
@23Skidoo thanks

**Comment by ezyang** [comment] 2016-01-15 16:40
This is not good, I have seen Cabal pick up the wrong version of the library from time-to-time and it drives me nuts. Can we diagnose the root cause here?

**Comment by Heather** [comment] 2016-01-15 17:11
@ezyang I can try to dig more on monday

**Comment by ezyang** [comment] 2016-01-15 18:05
Actually, this might be very explainable. When you installed cabal-install, did you previously "cabal install Cabal"?

**Comment by Heather** [comment] 2016-01-15 18:28
@ezyang yes

**Comment by ezyang** [comment] 2016-01-15 18:42
OK. I wonder if this is a case of there being two Cabal-1.23.0.0s on the system, and cabal-install preferring the one in the global store as opposed to the local store.

**Comment by 23Skidoo** [comment] 2016-01-15 18:43
Yes, that's what I think is happening.

**Comment by ezyang** [comment] 2016-01-15 18:45
Is that intentional behavior? I think all things being equal, packages later in the package stack should be preferred.

**Comment by Heather** [comment] 2016-01-15 18:51
Also I really wonder if there was some another Cabal in my system

**Comment by ezyang** [comment] 2016-01-15 18:56
There must be, GHC always ships with a version of Cabal.

**Comment by 23Skidoo** [comment] 2016-01-15 19:17
> I think all things being equal, packages later in the package stack should be preferred.

I'm not sure why this is happening and whether it is a Cabal or GHC issue, but I agree that the current behaviour is surprising.

**Comment by Heather** [comment] 2016-01-15 19:34
@23Skidoo @ezyang that means we always should bump version to be safe?

**Comment by jwaldmann** [comment] 2016-01-15 19:52
Is this related to the version bump?

```
sh bootstrap.sh
...
Downloading Cabal-1.23.1.0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by 23Skidoo** [comment] 2016-01-15 19:54
> Downloading Cabal-1.23.1.0...

Looks like you don't have Cabal-1.23.1.0 installed, so the bootstrap script is trying to download an unreleased version.

**Comment by jwaldmann** [comment] 2016-01-15 20:06
OK, thanks.

I was just assuming that since Cabal is wired in (is is? at least it's pre-installed when building ghc from source) it should not be touched or shadowed. 

Well, I am getting a different error now, I'll investigate and perhaps open another issue.

**Comment by 23Skidoo** [comment] 2016-01-15 20:10
Yes, GHC comes with Cabal, but your GHC had an earlier version than 1.23.1.0.

**Comment by jwaldmann** [comment] 2016-01-15 20:13
Yes. it is 8.0-rc1 built from source. It has Cabal-1.23.0.0

**Comment by ezyang** [comment] 2016-01-18 00:58
Cabal is not wired in. You can tell if a package is wired in by checking to see if it has `-this-unit-id PACKAGENAME` (or `-this-package-key` or `-package-name`, if you're going back in time) in its Cabal file. However, it does come with GHC.

If we can't build cabal-install GHC 8 that's a different error, but also one that needs to be fixed. (Also surprising: I am regularly building cabal-install from HEAD with GHC 8.0.)

**Comment by Heather** [comment] 2016-01-18 06:27
Currently issue is gone for me, I can't reproduce, @ezyang since that I think this issue could be closed

**Comment by ezyang** [comment] 2016-01-27 04:22
OK, fair enough.

**Closed by ezyang** 2016-01-27 04:22 UTC
Labels: bug
