### ISSUE TITLE
Cabal docdist

### ISSUE THREAD

**Issue by bitemyapp** [haskell/cabal#2156] opened 2014-10-10 22:11 UTC
I've lost multiple hours just to fixing the Haddocks for Hackage. The defaults aren't great. What percent of users are generating haddocks for something other Hackage? Generating the tarball is fiddly and requires slightly different flags on Mac vs. Linux. This has given rise to [scripts like the one in the lens project by glguy](https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh).

Ideally this would then lend itself to a `cabal upload --with-docs` so it can push the tarball generated by docdist to Hackage.

Follow-ups to this:

1. `cabal upload --with-docs`

2. smart `cabal upload --with-docs` which handles `cabal sdist` and `cabal docdist`.

**Comment by ttuegel** [comment] 2015-02-28 04:31
Duplicate of #1702.

**Closed by ttuegel** 2015-02-28 04:31 UTC
Labels: duplicate
