### ISSUE TITLE
Context needed for ParseFailed: >= 1.2.*

### ISSUE THREAD

**Issue by malthe** [haskell/cabal#989] opened 2012-08-06 09:19 UTC
I had a `build-depends` section with a trailing comma, a syntax error which is arguably hard to spot.

Cabal gave me this error:

```
cabal: <name>.cabal:<lineno>: Parse of field 'build-depends' failed.
```
1. The `<lineno>` was always the first line of the `build-depends` section, not the last (which had the syntax error).
2. There is no mention of the character that failed to parse.

Can we improve this? The logic is defined in `ParseUtils.hs`. I find the code there to be a little dense and wasn't sure how to get started.

**Comment by MKloczko** [comment] 2015-10-22 11:45
+1

A little thing that might waste people's time. I'll try to look into it later.

**Comment by phadej** [comment] 2015-10-22 13:05
After https://github.com/haskell/cabal/pull/2879 is merged, there will be more context to get better error.

**Comment by harendra-kumar** [comment] 2015-11-25 04:14
I am a Haskell newbie and this issue frustrated among many such small things. I did not know what's wrong, it just printed a message saying "NoParse "build-depends" 23". Line 23 did not have any problem. the problem was on a later line. I had to start with a bare minimum build-depends line and incrementally build it until I got to the problem. It was someone else's code so I had no idea where exactly the problem might be in the long list of dependencies.

Until it gets fixed it might frustrate more people like me. Basic tools like cabal working smoothly is important for Haskell adoption. I appreciate the efforts of those working on getting it fixed.

**Comment by harendra-kumar** [comment] 2015-11-25 04:25
BTW - the issue for me was exactly the same as neothemachine reported above i.e. a "<=" comparison with "x.y.*".

**Comment by msteffen** [comment] 2017-08-20 22:32
I encountered this issue as well:
```
build-depends:
    base >=4.10 && < 4.11,
    vector == 0.12.*
```

As a relative Haskell newbie, I think a clearer error message for this type of mistake might have helped me catch it faster

**Comment by hvr** [comment] 2017-08-21 06:58
@msteffen and in fact, the new parsers gives you the following work-in-progress error message:

```
Warning: z.cabal:8:12:
unexpected '>'
expecting ",", white space or end of input: "base >=4.10 && < 4.11,\nvector >=
0.12.*"
cabal: Failing parsing "z.cabal".
```

where the `*:8:12` points to the position marked with a caret `^` below

```
build-depends:
    base >=4.10 && < 4.11,
    vector >= 0.12.*
~~~~~~~~~~~^
```

it's not ideal yet, but it points you already closer to the cause than the old parser error messages did, even though it's still confusing...

**Comment by phadej** [comment] 2017-08-21 09:14
I'll investigate how to make this error message. Probably I'll parse `0.12.*` "version ranges" even after `>=`, but then `fail` with proper explanation.

And the second point: Printing the line and a caret below shouldn't be too hard. I'll do that when I'll verify that errors actually point to the right place. (IIRC if you have an empty line in `build-depends`, positions will be off).

**Closed** 2017-12-26 15:03 UTC
Labels: Cabal: other, Cabal: parser, type: enhancement
