### ISSUE TITLE
Cabal is not working on Windows when user name uses locale characters

### ISSUE THREAD

**Issue by wdanilo** [haskell/cabal#1583] opened 2013-11-16 17:56 UTC
Hi!
Cabal is not working on Windows if there are locale characters in your user name.
For example, if I'm testing cabal with user name "userążółć" (some polish locales), I get very strange errors:

```
C:\Users\userazólc>cabal update -v3
Config file path source is default config file.
Config file C:\Users\usercabal: <stdout>: invalid argument
```
etc. 

I've tested it on 1.18.2 and 1.19.1 (current HEAD).

**Comment by ttuegel** [comment] 2015-04-25 13:05
Duplicate of #650.

**Closed by ttuegel** 2015-04-25 13:05 UTC
Labels: bug, windows
