### ISSUE TITLE
cabal new-build doesn't rebuild when qAddDependentFile'd file changes

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#5686] opened 2018-11-13 13:05 UTC
*EDIT:* I'm pretty sure I saw this issue, but cannot find in on tracker.

**Comment by hvr** [comment] 2018-11-13 14:48
Duplicate of #4746

**Comment by jneira** [comment] 2021-04-06 14:28
so this could be closed as duplicate?

**Closed** 2021-04-06 14:45 UTC
