### ISSUE TITLE
build-depends of buildable:False stanzas are still required

### ISSUE THREAD

**Issue by snoyberg** [haskell/cabal#2602] opened 2015-05-21 10:43 UTC
Here's a sample session. Note how, even though the `bench` flag is disabled by default and therefore the vector-algorithms-bench stanza won't be built, Cabal (the library) is still requiring that its dependencies (in this case, mtl and mwc-random) be installed.

```
vagrant@vagrant-ubuntu-trusty-64:~/Desktop$ cabal unpack vector-algorithms
cUnpacking to vector-algorithms-0.7/
vagrant@vagrant-ubuntu-trusty-64:~/Desktop$ cd vector-algorithms-0.7/
vagrant@vagrant-ubuntu-trusty-64:~/Desktop/vector-algorithms-0.7$ cabal sandbox init
Writing a default package environment file to
/home/vagrant/Desktop/vector-algorithms-0.7/cabal.sandbox.config
Creating a new sandbox at
/home/vagrant/Desktop/vector-algorithms-0.7/.cabal-sandbox
vagrant@vagrant-ubuntu-trusty-64:~/Desktop/vector-algorithms-0.7$ cabal install vector
Resolving dependencies...
Notice: installing into a sandbox located at
/home/vagrant/Desktop/vector-algorithms-0.7/.cabal-sandbox
Configuring primitive-0.6...
Building primitive-0.6...
Installed primitive-0.6
Configuring vector-0.10.12.3...
Building vector-0.10.12.3...
cabal configure
Installed vector-0.10.12.3
vagrant@vagrant-ubuntu-trusty-64:~/Desktop/vector-algorithms-0.7$ cabal configure
Resolving dependencies...
Configuring vector-algorithms-0.7...
cabal: At least the following dependencies are missing:
mtl -any, mwc-random -any
```

**Comment by 23Skidoo** [comment] 2015-05-21 10:55
Duplicate of #1725.

**Closed by 23Skidoo** 2015-05-21 10:55 UTC
Labels: duplicate
