### ISSUE TITLE
Build failure with GHC-8.2

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#9952] opened 2024-04-29 10:04 UTC
Failed to build Cabal-syntax-3.12.0.0.

```
src/Distribution/Types/ForeignLib.hs:168:13: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Distribution.Compat.Prelude.<>’,
                             imported from ‘Distribution.Compat.Prelude’ at src/Distribution/Types/ForeignLib.hs:18:1-34
                             (and originally defined in ‘Data.Semigroup’)
                          or ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/Distribution/Types/ForeignLib.hs:31:1-18
```

Have someone forgot adjusting lowerbounds? Has Cabal-syntax dropped support for GHC-8.0 and GHC-8.2 (I dont' see a mention in the changelog).

**Comment by phadej** [comment] 2024-04-29 10:22
The bad commit is 54183f2353dfa730d86e1503abc792f49f85c586, old GHC support breakage seems unintentional.

**Comment by ffaf1** [comment] 2024-04-29 10:43
It passed [old GHCs](https://github.com/haskell/cabal/actions/runs/7514538870/job/20458480509) `validate` workflow, so I am puzzled.

**Comment by Mikolaj** [comment] 2024-04-29 10:47
But the problem is when *building* with GHC-8.2? It's out of the support window. Oldest tested for compilation is GHC 8.6.5. 

I don't think we announce when GHCs drop out of our support window. Should we? It happens without any action. We could announce when we spot it and adjust CI. If so, that should be added to the criteria stating when a changelog is necessary.

**Comment by Mikolaj** [comment] 2024-04-29 10:49
> Have someone forgot adjusting lowerbounds?

That is a problem, though. Whenever we drop a GHC from CI we should bump the bounds and I think usually we do, so it's not unclear, I think.

**Comment by ffaf1** [comment] 2024-04-29 13:34
Which revision would fix this?

**Comment by Mikolaj** [comment] 2024-04-29 13:36
I think Cabal-syntax bound on `base`. I think @phadej is right, especially that revisions can always be reverted once we do the same bump in a PR and reviewers point out how the revision could be improved.

**Comment by Mikolaj** [comment] 2024-04-29 13:38
@ffaf1: you have full authority to do just that revision, if you'd like to. I'd announce it on the channel, though, for transparency and in case we missed something.

**Comment by ffaf1** [comment] 2024-04-29 13:53
I am going to download GHC 8.4.2 locally, make sure it compiles, make an announcemente on Matrix and then do a revision setting `base` lower bound to `>= 4.11.1.0`.

**Comment by ffaf1** [comment] 2024-04-29 14:28
Revision has been published.

**Comment by phadej** [comment] 2024-04-29 16:05
@ffaf1 Thanks

---

@Mikolaj 

> I don't think we announce when GHCs drop out of our support window. Should we? 

You definitely should. Dropping support for old GHCs, `base` or any other dependency (and/or supporting newer versions) is something downstream users care about (recall, `cabal-install` is not the only user of `Cabal-syntax`). It also may affect `build-type: Custom` people.

Virtually all maintainers do so, e.g. https://hackage.haskell.org/package/containers-0.6.6/changelog; it's the *first line* in the changelog. Also previously such changes were announced in Cabal's changelog, though not very prominently https://github.com/haskell/cabal/blob/c80ee7583ef98a1448309ea4d7dd05b15c91b082/release-notes/Cabal-3.10.1.0.md#L131

**Comment by ffaf1** [comment] 2024-04-29 16:44
Release notes are being updated in #9953.

**Comment by Mikolaj** [comment] 2024-05-01 10:55
I think the only major remaining task in this issue is a PR that fixes the base bound on master and a backport to 3.12. Am I right? Volunteers?

**Comment by Mikolaj** [comment] 2024-05-13 07:30
It's been merged and backported. Is there anything else we could do? If not, shall we close this ticket?

**Closed** 2024-11-17 02:30 UTC
Labels: type: bug, status: consider closing
