### ISSUE TITLE
Parser problem for cabal.project

### ISSUE THREAD

**Issue by edsko** [haskell/cabal#2980] opened 2015-12-22 15:20 UTC
If I leave out a comma, as in

```
packages: Cabal/Cabal.cabal cabal-install/cabal-install.cabal
```

then `new-build` simply doesn't build anything at all.

**Comment by ezyang** [comment] 2015-12-22 15:25
Duplicate of #2973 haha.

**Comment by edsko** [comment] 2015-12-22 15:25
Whoops, sorry @dcoutts :)

**Comment by edsko** [comment] 2015-12-22 15:25
(Though I consider this as evidence that syntax without commas is more natural :)

**Closed by ezyang** 2015-12-22 15:25 UTC
Labels: nix-local-build
