### ISSUE TITLE
Cabal-3 likes to yell about version ranges that users didn't write.

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#6085] opened 2019-06-17 13:42 UTC
There are no explicit self-related version ranges in my packages yet my screen fills with dozens if not hundreds of messages like:

```
Warning: The package has an extraneous version range for a dependency on an
internal library: harfbuzz -any && ==0 && ==0. This version range includes the
current package but isn't needed as the current package's library will always
```

**Comment by 23Skidoo** [comment] 2019-06-17 13:46
Yeah, that's a known issue, we should apply the same workaround we made for 2.4.

**Comment by 23Skidoo** [comment] 2019-06-17 13:47
See #5119, #5524.

**Comment by fgaz** [comment] 2020-05-22 11:45
Closing as duplicate of #5119

**Closed by fgaz** 2020-05-22 11:45 UTC
