### ISSUE TITLE
custom-setup solving problem, is `Cabal` version shared across all `Setup.hs`?

### ISSUE THREAD

**Issue by phadej** [haskell/cabal#4295] opened 2017-02-05 17:21 UTC
Happens only with GHC 7.8.4 and older.

With the code in https://github.com/phadej/cabal-doctest/commit/742c2d009d33d2f00fd9cb010382c5a397b7f590
Only if I add a `cabal-doctests >=1.0.1` bound to `example.cabal`'s setup-depends, I'll get a solver error https://travis-ci.org/phadej/cabal-doctest/jobs/198593113

This is very unfortunate, as I don't see why there can't be valid plan (`Cabal` for `ComponentSetup` should interfere with `ghc` / `doctest` etc part of the `--enable-tests` plan)

```
example:setup.Cabal-1.2.1, example:setup.Cabal-1.1.6 (constraint from minimum
version of Cabal used by Setup.hs requires >=1.20)
rejecting: example:setup.Cabal-1.24.1.0 (dependencies not linked: cannot make
example:setup.Cabal canonical member of
{*Cabal-1.18.1.5/installed-647...,example:setup.Cabal-1.18.1.5/installed-647...};
conflict set: Cabal, example:setup.Cabal, example:setup.cabal-doctest)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: example:setup.Cabal (6609),
example:setup.cabal-doctest (6567), Cabal (3617), doctest (3451),
example-1:test (3447), example (2798), example:setup.base (1432),

**Comment by phadej** [comment] 2017-02-05 17:27
cc @grayjay

**Comment by phadej** [comment] 2017-02-05 17:27
I have no idea where from the `Cabal >= 1.20` bound comes from. Feel free to ask me on IRC for more details.

**Comment by ezyang** [comment] 2017-02-05 20:55
new-build requires 1.20 or later because 1.18 setup does not support `--dependency`, so it's not possible for us to request specific packages. 80de7ff4fa5cc5c1a5b1e620787750e08f91325b and #4051

**Comment by grayjay** [comment] 2017-02-05 21:58
The problem is that new-build adds all packages from cabal.project to the list of targets for the dependency solver, so they all are required to have consistent dependencies.  In this example, the solver would ideally choose the installed `Cabal` for `example`'s `doctests` test suite and a newer `Cabal` for `example`'s setup script.  The test suite needs the installed `Cabal`, because it depends on `doctest`, which depends on the installed `ghc` package, and `ghc` depends on `Cabal`.  However, the two `Cabal` dependencies are forced to be the same instance because the setup script also depends on `cabal-doctest` and `cabal-doctest` is a top-level build target.

One solution is to enable --independent-goals for new-build.  Then some packages in a project can be setup dependencies for others and be allowed to have different versions for their dependencies.

/cc @dcoutts

**Comment by phadej** [comment] 2017-02-06 06:27
@grayjay thanks for the explanation!

**Comment by ezyang** [comment] 2017-02-07 20:50
Note that the `--independent-goals` flag is currently disabled.

**Comment by grayjay** [comment] 2019-12-23 01:47
I think the issue with building cabal-doctest was resolved with the --independent-goals flag.  I opened a separate issue for enabling the flag by default: #6460

**Closed by grayjay** 2019-12-23 01:47 UTC
Labels: Cabal: custom, attention: needs-test, cabal-install: nix-local-build, cabal-install: solver, cabal-install: stanza/custom-setup
