### ISSUE TITLE
new-build does not rebuild when project-file is changed

### ISSUE THREAD

**Issue by andrewthad** [haskell/cabal#5225] opened 2018-03-21 14:46 UTC
When I use `cabal new-build --project-file=...` to manually select a project file and then run the same command with a different project file, `cabal` finishes immidiately the second time, claiming that the project is up to date. Cabal should take the project file into account when deciding whether or not to rebuild things. I can work around this by just changing an arbitrary module in the project.

**Comment by andrewthad** [comment] 2018-03-21 15:08
That makes sense. I'll start doing that. It would be nice if `builddir` could be specified in the `cabal.project` file.

**Comment by lspitzner** [comment] 2018-03-29 13:32
Mildly certain that this is a duplicate of #4206.

**Comment by 23Skidoo** [comment] 2018-06-08 17:13
@andrewthad Can you please confirm that #5239 fixed this?

**Comment by quasicomputational** [comment] 2018-08-08 14:42
I'm happy to confirm that this is fixed in HEAD and, considering when the commit landed, it should also be fixed in 2.4.

**Closed by quasicomputational** 2018-08-08 14:42 UTC
Labels: cabal-install: nix-local-build, type: enhancement
