### ISSUE TITLE
Support automatic population of `exposed-modules:`

### ISSUE THREAD

**Issue by finlaydotb** [haskell/cabal#7016] opened 2020-08-22 05:30 UTC
I am new to Haskell, and the very first thing I wondered about when I started using `cabal-install` was the need to manually add modules to the `exposed-modules:` fields in `.cabal` files.

I think it would be a good idea if this is done by the tool. 

I recently looked into hpack and I asked over [here](https://www.reddit.com/r/haskell/comments/idzm2j/is_hpack_worth_it/) on reddit if it was worth it. and one of the reasons people give is that with `hpack` the `exposed-modules:` is populated for you.

I think it will be nice if this is a native feature instead of something an external tool like `hpack` helps with

**Comment by phadej** [comment] 2020-08-24 04:56
Duplicate of https://github.com/haskell/cabal/issues/5343

**Closed by phadej** 2020-08-24 04:56 UTC

**Comment by codygman** [comment] 2020-08-30 17:19
It was [brought to my attention on reddit](https://github.com/haskell/cabal/issues/5343#issuecomment-521590517) that even though this was closed, at least @phadej thinks the [globbing solution](https://github.com/haskell/cabal/issues/5343#issue-325970372] is [worth putting into Cabal](https://github.com/haskell/cabal/issues/5343#issuecomment-521590517) if someone implements it.

My takeaway from this being closed was there wasn't interest in fixing this issue, so I post this so others don't make my same mistake and see there is a way forward 🙂

**Comment by phadej** [comment] 2020-08-30 17:30
@codygman you understood me wrong. I expect the patch being quite big and invasive. Yet if someone actually makes it and still thinks it's a good idea, I'd be curious to know.

I do not recommend to pursuing that path to the end, the patch will probably be still rejected.

Case-in-point, just now I used @hvr's tool to find out which package exports `Data.RFC5051`. It saved me a lot of time while I fix Hackage metadata (going through pandoc dependencies by hand is not a human job).

There are nice things which would be nice to have, but we cannot.

Wouldn't  it be nice if `cabal` figured out dependencies without explicit `build-depends`. In theory possible, in practice not. This is issue is the same. Reddit polls won't change my mind.

**Comment by codygman** [comment] 2020-08-30 22:40
I said or elsewhere, but I want to preface this comment with:

You guys do a huge amount of work as volunteers and I appreciate it. I appreciate it so much I want others to be able to come back to Cabal from stack so even more can appreciate that work.

Technically I suspect cabal is better in many ways, but UX wise in a lot of ways it's just not and I can provide many examples if there is interest.

> Reddit polls won't change my mind.

They should carry some weight if you care about users opinions. If the problem is the poll is on reddit, what sort of poll would convince your? If you simply don't care about users opinions with regards to UX issues, that's pretty alarming. Please confirm that isn't the case?

> There are nice things which would be nice to have, but we cannot.

I mean, we can have it. I and others would just like to not resort to "switch to stack" or "use some external tool".

> In theory possible, in practice not.

From a user perspective, that's hard to buy since `stack build` ends up doing it just fine. There are differences there and technical arguments below the surface, but at the end of the day people will judge cabal against stack.

**Comment by phadej** [comment] 2020-08-31 07:32
`stack build` is not *just fine*. It preprocesses the `package.yaml` file (into `pkgname.cabal`), it doesn't interpret it directly. That is very important to understand. Package tarballs uploaded to Hackage with `stack` still have "old-style, explicit module listing `pkgname.cabal`" in them.

I'm not against preprocessing, `cabal-fmt` does this. But how to make the UX so users are not confused if that functionality was part of `cabal` and implicitly done on builds? I don't know. (I don't think it will be non-confusing if it's implicit).

Also Herbert is rightfully concerned about performance. Note, it's not only that `cabal-install` would need to do file system watching (which it already does, so it's not an issue). But also `Cabal` the library would need to traverse a filesystem every time `./Setup` is invoked, if `./Setup.hs` is also preprocessing as well. (E.g. in Nix, or GHCs build systems). I think it shouldn't, `Setup` is already complicated interface.

---

>  If you simply don't care about users opinions with regards to UX issues, that's pretty alarming

Not true. I do listen. And we do implement features to improve users experiences. Judging by response to a single request is just not fair.

**Comment by jhrcek** [comment] 2020-08-31 08:32
Just as a datapoint in a discussion: even Michael Snoyman stated recently, that supporting automatic generation of cabal files from package.yaml in stack projects (using hpack) led to all sorts of build reproducibility issues. See https://www.fpcomplete.com/blog/storing-generated-cabal-files/
