### ISSUE TITLE
cabal-install's bootstrap script is broken on Windows

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4895] opened 2017-11-16 18:20 UTC
It currently fails with,
```
$ bash -x bootstrap.sh
...
+ CC=gcc
+ echo 'Using gcc for C compiler. If this is not what you want, set CC.'
Using gcc for C compiler. If this is not what you want, set CC.
+ break
+ '[' -gcc- = -- ']'
++ for link in collect2 ld
+++ gcc -print-prog-name=collect2
++ '[' C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/collect2.exe = collect2 ']'
++ gcc -print-prog-name=collect2
++ break
+ LINK=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/collect2.exe
+ '[' -C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/collect2.exe- = -- ']'
+ echo 'int main(){}'
+ gcc -xc - -o /dev/null
nul.exe: final close failed: File truncated
collect2.exe: error: ld returned 1 exit status
+ die 'C compiler and linker could not compile a simple test program.
    Please check your toolchain.'
+ printf '\nError during cabal-install bootstrap:\n%s\n' 'C compiler and linker could not compile a simple test program.
    Please check your toolchain.'

Error during cabal-install bootstrap:
C compiler and linker could not compile a simple test program.
    Please check your toolchain.
+ exit 2
```
The problem is that `/dev/null` doesn't exist on Windows; rather, msys2 translates the name to the reserved `nul` name. This is a reserved name and attempting to create a file by this name consequently fails.

Really, `bootstrap.sh` should probably just leave the toolchain alone. GHC takes great pains to ensure that it uses the correct mingw toolchain on Windows. `cabal-install` will very likely get this wrong, finding an msys toolchain instead.

**Comment by Mistuke** [comment] 2017-11-16 18:28
To clarify, `nul` is the NULL device on Windows, so `msys2` is doing the right thing. The issue is that because gcc was also asked to link, it appends `.exe` to the file name, since you can't easily execute executables on Windows without this suffix. This makes the name `nul.exe` which violates the reserved name `nul`.

**Comment by 23Skidoo** [comment] 2017-11-17 09:08
Thanks! We should probably add it to AppVeyor. TBH, can't remember when I last used `bootstrap.sh` on Windows - I usually use Haskell Platform.

**Comment by jneira** [comment] 2022-05-05 20:35
bootstrap.sh does not exist anymore, so i am gonna close it optimistically, betting the newbootstrap.py does not suffer the issue 😄
feel free to reopen the issue ifthat is not the case

**Closed by jneira** 2022-05-05 20:35 UTC
Labels: type: bug, platform: windows, cabal-install: bootstrap
