### ISSUE TITLE
Cabal init should create main file for executables.

### ISSUE THREAD

**Issue by cgag** [haskell/cabal#2465] opened 2015-03-13 05:01 UTC
Currently it prompts and tells you that it doesn't exist, it seems like it should just create it for you in that case.  I'd love it if after running cabal init for an executable, `cabal run` would print out "hello world" or something.

**Comment by 23Skidoo** [comment] 2015-03-13 05:05
/cc @byorgey 

Duplicate of #2304.

**Closed by 23Skidoo** 2015-03-13 05:05 UTC
Labels: duplicate, init
