### ISSUE TITLE
--only-dependencies should work if not using --only-dependencies would work

### ISSUE THREAD

**Issue by newhoggy** [haskell/cabal#7226] opened 2021-01-05 08:57 UTC
**Describe the bug**
If a project P depends on A depends on B depends on C and a git reference is supplied in `cabal.project` for project `B` (for example to test a patch), then using `--dependencies-only` will fail.

**To Reproduce**

See this build failure:

https://github.com/input-output-hk/cardano-ledger-specs/runs/1648708803?check_suite_focus=true

The error reported is:

```
cabal: Cannot select only the dependencies (as requested by the
'--only-dependencies' flag), the package ListLike-4.7.3 is required by a
dependency of one of the other targets.
```

**Expected behavior**
Expected behaviour.  If the project should build without `--dependencies-only` then it should also build with `--dependencies-only`.

The reason this is useful is because it is common in CI to build with `--dependencies-only` and then cache the cabal store.  This helps ensure that *something* is cached in the project even if the project itself fails to build.

**System information**
All operating systems, versions of `cabal` and `ghc`.

**Additional context**
To make this work, `cabal` can choose to build the minimal number of additional components outside of the the "dependencies only" set.

**Comment by fgaz** [comment] 2021-01-05 09:26
I think there are other tickets about treating source-repository packages as remote, but I can't find them right now

**Comment by phadej** [comment] 2021-01-05 12:34
Duplicate of https://github.com/haskell/cabal/issues/6106

**Closed by phadej** 2021-01-05 12:34 UTC

**Comment by newhoggy** [comment] 2021-01-05 13:30
Thanks!
