### ISSUE TITLE
Trying to build happy in a sandbox with cabal-install from git fails.

### ISSUE THREAD

**Issue by Ongy** [haskell/cabal#4574] opened 2017-06-25 11:30 UTC
I first reported that to happy, I got redirected here. https://github.com/simonmar/happy/issues/89#issuecomment-310892996

Trying to build happy I encountered a problem during the `cabal install` step.

This is on archlinux with ghc 8.0.2 and cabal from recent git HEAD.

Full log, so you can see what I'm doing. The interesting line is probably:

> happy: /tmp/happy-1.19.5/.cabal-sandbox/share/x86_64-linux-ghc-8.0.2/happy-1.19.5/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)

> + cabal get happy
> Unpacking to happy-1.19.5/
> + cd happy-1.19.5
> + cabal sandbox init
> Writing a default package environment file to
> /tmp/happy-1.19.5/cabal.sandbox.config
> Creating a new sandbox at /tmp/happy-1.19.5/.cabal-sandbox
> + cabal install --dependencies-only
> Resolving dependencies...
> Notice: installing into a sandbox located at /tmp/happy-1.19.5/.cabal-sandbox
> Configuring mtl-2.2.1...
> Building mtl-2.2.1...
> Installed mtl-2.2.1
> + cabal configure
> Resolving dependencies...
> [1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
> 
> dist/setup/setup.hs:21:1: warning: [-Wtabs]
>     Tab character found here, and in 39 further locations.
>     Please use spaces instead.
> Linking ./dist/setup/setup ...
> Configuring happy-1.19.5...
> + cabal build
> Building happy-1.19.5...
> Preprocessing executable 'happy' for happy-1.19.5...
> [ 1 of 18] Compiling Target           ( src/Target.lhs, dist/build/happy/happy-tmp/Target.o )
> [ 2 of 18] Compiling Paths_happy      ( dist/build/autogen/Paths_happy.hs, dist/build/happy/happy-tmp/Paths_happy.o )
> [ 3 of 18] Compiling ParseMonad       ( src/ParseMonad.hs, dist/build/happy/happy-tmp/ParseMonad.o )
> [ 4 of 18] Compiling NameSet          ( src/NameSet.hs, dist/build/happy/happy-tmp/NameSet.o )
> [ 5 of 18] Compiling Lexer            ( src/Lexer.lhs, dist/build/happy/happy-tmp/Lexer.o )
> [ 6 of 18] Compiling GenUtils         ( src/GenUtils.lhs, dist/build/happy/happy-tmp/GenUtils.o )
> [ 7 of 18] Compiling AttrGrammar      ( src/AttrGrammar.lhs, dist/build/happy/happy-tmp/AttrGrammar.o )
> [ 8 of 18] Compiling AttrGrammarParser ( dist/build/happy/happy-tmp/AttrGrammarParser.hs, dist/build/happy/happy-tmp/AttrGrammarParser.o )
> [ 9 of 18] Compiling AbsSyn           ( src/AbsSyn.lhs, dist/build/happy/happy-tmp/AbsSyn.o )
> [10 of 18] Compiling ParamRules       ( src/ParamRules.hs, dist/build/happy/happy-tmp/ParamRules.o )
> 
> src/ParamRules.hs:5:1: warning: [-Wdeprecations]
>     Module ‘Control.Monad.Error’ is deprecated:
>       Use Control.Monad.Except instead
> 
> src/ParamRules.hs:6:1: warning: [-Wdeprecations]
>     Module ‘Control.Monad.Instances’ is deprecated:
>       This module now contains no instances and will be removed in the future
> 
> src/ParamRules.hs:31:17: warning: [-Wdeprecations]
>     In the use of type constructor or class ‘ErrorT’
>     (imported from Control.Monad.Error, but defined in transformers-0.5.2.0:Control.Monad.Trans.Error):
>     Deprecated: "Use Control.Monad.Trans.Except instead"
> 
> src/ParamRules.hs:71:10: warning: [-Wdeprecations]
>     In the use of type constructor or class ‘ErrorT’
>     (imported from Control.Monad.Error, but defined in transformers-0.5.2.0:Control.Monad.Trans.Error):
>     Deprecated: "Use Control.Monad.Trans.Except instead"
> 
> src/ParamRules.hs:72:27: warning: [-Wdeprecations]
>     In the use of ‘runErrorT’
>     (imported from Control.Monad.Error, but defined in transformers-0.5.2.0:Control.Monad.Trans.Error):
>     Deprecated: "Use Control.Monad.Trans.Except instead"
> [11 of 18] Compiling Grammar          ( src/Grammar.lhs, dist/build/happy/happy-tmp/Grammar.o )
> [12 of 18] Compiling First            ( src/First.lhs, dist/build/happy/happy-tmp/First.o )
> [13 of 18] Compiling LALR             ( src/LALR.lhs, dist/build/happy/happy-tmp/LALR.o )
> [14 of 18] Compiling Info             ( src/Info.lhs, dist/build/happy/happy-tmp/Info.o )
> [15 of 18] Compiling ProduceCode      ( src/ProduceCode.lhs, dist/build/happy/happy-tmp/ProduceCode.o )
> [16 of 18] Compiling ProduceGLRCode   ( src/ProduceGLRCode.lhs, dist/build/happy/happy-tmp/ProduceGLRCode.o )
> [17 of 18] Compiling Parser           ( dist/build/happy/happy-tmp/Parser.hs, dist/build/happy/happy-tmp/Parser.o )
> [18 of 18] Compiling Main             ( src/Main.lhs, dist/build/happy/happy-tmp/Main.o )
> Linking dist/build/happy/happy ...
> ++ realpath dist/build/happy
> + export PATH=/tmp/happy-1.19.5/dist/build/happy:/home/ongy/.bin/:/home/ongy/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> + PATH=/tmp/happy-1.19.5/dist/build/happy:/home/ongy/.bin/:/home/ongy/.cabal/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> + cabal install
> Resolving dependencies...
> Notice: installing into a sandbox located at /tmp/happy-1.19.5/.cabal-sandbox
> Configuring happy-1.19.5...
> Building happy-1.19.5...
> Failed to install happy-1.19.5
> Build log ( /tmp/happy-1.19.5/.cabal-sandbox/logs/ghc-8.0.2/happy-1.19.5-GUPzpM8oSlA9ybE7TUr7pj.log ):
> cabal: Entering directory '.'
> [1 of 1] Compiling Main             ( dist/dist-sandbox-661b7d0a/setup/setup.hs, dist/dist-sandbox-661b7d0a/setup/Main.o )
> Linking ./dist/dist-sandbox-661b7d0a/setup/setup ...
> Configuring happy-1.19.5...
> Building happy-1.19.5...
> Preprocessing executable 'happy' for happy-1.19.5...
> happy: /tmp/happy-1.19.5/.cabal-sandbox/share/x86_64-linux-ghc-8.0.2/happy-1.19.5/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
> cabal: Leaving directory '.'
> cabal: Error: some packages failed to install:
> happy-1.19.5-GUPzpM8oSlA9ybE7TUr7pj failed during the building phase. The
> exception was:
> ExitFailure 1

**Comment by 23Skidoo** [comment] 2017-10-15 15:38
Duplicate of #4593.

**Closed by 23Skidoo** 2017-10-15 15:38 UTC
Labels: cabal-install: nix-local-build, type: bug
