### ISSUE TITLE
support test library

### ISSUE THREAD

**Issue by PierreVDL** [haskell/cabal#4297] opened 2017-02-07 09:24 UTC
Only one library can be defined in a single Cabal file.
According to https://github.com/haskell/cabal/issues/2716 it is a fundamental design decision.

As a developer, I want to expose additional functionality for test purposes only.
For example, I want to expose generators of test data defined in a package
such that it can be used by packages that use that test data (e.g. for QuickCheck).

One way to deal with this cabal limitation, is the usage of flags: See e.g.
[PackageStructure.zip](https://github.com/haskell/cabal/files/757066/PackageStructure.zip)
This has however some unwanted side effects.
Among others, understanding the packages' builds becomes more complicated, 
one gets discussions whether the program that is shipped is the program that is tested,
and the generators are also included in the coverage reports.

Could support for an additional test library be added?

**Comment by ezyang** [comment] 2017-02-07 09:28
Does #4206 encompass this? If so, please pipe in on that thread supporting the feature!

**Comment by 23Skidoo** [comment] 2017-02-07 09:30
Don't internal libraries available in current `master` (1.25+) solve your problems? See http://cabal.readthedocs.io/en/latest/developing-packages.html#library

**Comment by PierreVDL** [comment] 2017-02-07 09:57
#4206 does encompass this.
Yet #4206 encompasses more than strictly need by me.

**Comment by PierreVDL** [comment] 2017-02-07 09:59
internal libraries don't solve my problem: I want to use the test-library in the test code of other packages.

**Comment by ezyang** [comment] 2017-02-07 21:16
@PierreVDL Is there a substantially simpler version of #4206 that solves your problem? #4206 is unlikely to get solved in the near future.

**Comment by PierreVDL** [comment] 2017-02-08 08:15
A simpler solution could be: introduce a keyword like `test-library` or `library test`.
For me, the constraint that this keyword might only be used when a library is present is acceptable.

When a test library is not declared, exactly the same behaviour as currently is implemented will be obtained. In particular, when I include the package / *.cabal file in another package to build a test
the normal library will be used.

However, when a package / *.cabal file declares such a test library besides the normal library, then 
when I include the package / *.cabal file in another package to build a library, benchmark, or executable I get the normal library.
Yet, when I include the package / *.cabal file in another package to build a test, I get the test library.
In this way additional test functionality related to a package can be shared with packages that use that package.

This proposal makes building and testing explicitly two different activities for which different libraries might be needed.

**Comment by PierreVDL** [comment] 2017-02-08 08:39
I realized that another choice is possible:
so we have the normal functionality and the test functionality we would like to expose.

We can make two libraries:
one that contains the normal functionality and
another that contains both the normal and the test functionality.

However, we can also make two libraries as follows:
one that contains the normal functionality and
another that contains only the test functionality (and depends on the other library).

In the latter case, we can make the inclusion of the test library in other packages explicit, instead implicitly based on the test / library / benchmark / executable context.

**Comment by ezyang** [comment] 2017-02-23 07:57
Based on your previous comments, possibly the most expedient thing to do from an implementation perspective is to add a condition (maybe a special flag?) which is true when the top level goal is a test. But there have been philosophical objections to letting the APIs of packages change this way (which is why, for example, you can't demand a dependency have a flag set a certain way).

**Comment by 23Skidoo** [comment] 2017-10-15 12:54
Closing as a duplicate of #4206. For now, a workaround is to use a separate package.

**Closed by 23Skidoo** 2017-10-15 12:54 UTC
Labels: Cabal: file format, type: enhancement
