### ISSUE TITLE
Undecipherable error message when an exposed module is omitted

### ISSUE THREAD

**Issue by ygale** [haskell/cabal#2591] opened 2015-05-14 18:29 UTC
When a module is omitted from the lists of exposed/other modules, the resulting error message is extremely cryptic. You get a linker error that is difficult to read, and then an anonymous "error status" cabal error at the end.

There should be some way for cabal somehow to collaborate with GHC to figure out what actually went wrong, and then just tell the poor user the truth.

http://www.reddit.com/r/haskell/comments/35xu29/bizarre_ld_error_when_trying_to_compile_my_program/

**Comment by rwbarton** [comment] 2015-05-14 19:47
Yuras's suggestion of -no-additional-modules sounds promising. Would it make sense to have that behavior controlled by -fbuilding-cabal-package? Then no change to cabal is needed.

**Comment by 23Skidoo** [comment] 2015-05-15 19:23
Duplicate of #1746.

**Closed by 23Skidoo** 2015-05-15 19:23 UTC
Labels: duplicate
