### ISSUE TITLE
Cabal init first example with git readCreateProcessWithExitCode

### ISSUE THREAD

**Issue by phobo3s** [haskell/cabal#10169] opened 2024-07-03 08:59 UTC
i am on windows and i have git installed systemwide.
tried to run cabal. i downloaded ghcup and starting to use cabal but there was an error when i try to use cabal init.

![image](https://github.com/haskell/cabal/assets/47847184/9b1b04e5-2aa5-42c4-9600-84f4a519436d)

MSYS2 has no git installed but my system has git so when i try to "cabal init" it gives git error. 
I am not a professional so... 

this workaround has worked by the way:
![image](https://github.com/haskell/cabal/assets/47847184/4bfffe11-38f6-4ba3-927a-81442c23bb3e)

thank you jasagredo

**Comment by Mikolaj** [comment] 2024-07-03 09:08
We discussed in the channel briefly and IMHO it would be fine to just continue if git is not present. The way it's used in `cabal init` is not crucial, after all, just a convenience, so probably not even a warning is needed.

**Comment by jasagredo** [comment] 2024-07-03 09:13
I assume git is used to get the default user name and email. If git is not present then we could just suggest no default, but do not crash.

**Comment by ulysses4ever** [comment] 2024-11-29 19:32
This looks like a duplicate of https://github.com/haskell/cabal/pull/10486, which was recently fixed. Please, try cabal 3.14.1.0 (or cabal-head, as described in the README).

**Closed** 2024-11-29 19:32 UTC
Labels: type: bug, cabal-install: cmd/init, hacktoberfest
