### ISSUE TITLE
"--reinstall" has no effect

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/cabal#1829] opened 2014-04-30 14:08 UTC
Running
```
cabal install --dependencies-only --reinstall
```
results in the following absurd message:
```
Resolving dependencies...
All the requested packages are already installed:
Use --reinstall if you want to reinstall anyway.
```

_Cabal 1.20_

**Comment by lspitzner** [comment] 2015-04-24 13:23
duplicate of #1175

**Closed** 2015-04-24 13:32 UTC
Labels: bug, cabal-install
