### ISSUE TITLE
Attempting to de-reference a non-existing flag gives a really bad error.

### ISSUE THREAD

**Issue by ekmett** [haskell/cabal#5283] opened 2018-04-25 15:58 UTC
If you add something like

```
   if flag(that-does-not-exist)
```

to any stanza then you get the rather unhelpful

```
Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:610:17 in containers-0.5.11.0:Data.Map.Internal
```

with no indicator as to even which cabal file it was in, that this was an issue about a flag at all, or where the error happened. 

I found this while trying to refactor several cabal projects, and it took me the better part of a day to track down the erroneous line of configuration.

**Comment by Mikolaj** [comment] 2019-02-09 01:02
This is a duplicate of #4476.

**Closed** 2019-03-02 15:33 UTC
Labels: type: bug
