### ISSUE TITLE
improve dist/setup-config format mismatch detection

### ISSUE THREAD

**Issue by hvr** [haskell/cabal#2251] opened 2014-12-02 20:15 UTC
@dcoutts asked me to file this:

I was having this weird issues with the devel version of `cabal` where some `cabal` invocations would fail with the following rather non-obvious error message

```
cabal: Prelude.chr: bad argument: 2041223
```

Even with `-v3` this is the very first output you get from `cabal`. Only `strace` provided the hint that `setup-config` was the last file read before that error message was emitted.

(the underlying problem  was most likely that `cabal` had been compiled against an older snapshot of the `Cabal` lib than the `Cabal` lib snapshot registered in the pkg db. And those two snapshots probably disagreed on the `setup-config` schema)

**Comment by svenpanne** [comment] 2015-02-02 08:49
I don't think this is really fixed, the same problem showed up again recently: https://travis-ci.org/haskell-opengl/OpenGLRaw/builds/49116074

This time not only for cabal-HEAD/ghc-HEAD, but for cabal-1.22/ghc-7.10.1, too, which is a bit scary given the fact that 7.10 should be released soon.

**Comment by nikita-volkov** [comment] 2015-02-06 00:17
Same issue here: https://travis-ci.org/nikita-volkov/record/jobs/48711367.

Also I experience it locally while executing `cabal sdist` on [this commit](https://github.com/nikita-volkov/list-t/tree/d9fd2ca035c481807efe52c2800f6325f0a13fd1). I'm running a freshly installed OS X 10.10.2 with the following setup:
```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.0.20150123
$ cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 
```

**Comment by svenpanne** [comment] 2015-02-06 07:53
Can we please re-open this bug?

**Comment by 23Skidoo** [comment] 2015-02-06 12:09
Reopened.

**Comment by dcoutts** [comment] 2015-02-19 17:07
The fundamental problem is that cabal-install tries to read the `dist/setup-config` file, but when the build-type is Custom then it really has no right whatsoever to do so because it cannot expect it to exist or if it does to understand the format.

I see that we try and read the file with some degree of error handling, but that will fail for older binary lib versions that just throw exceptions.

We should look again in `cabal-install/Main.hs` at the uses of `tryGetPersistBuildConfig` and `getPersistBuildConfig` and for each one ask "but what about build-type: Custom?", remembering that for custom we cannot expect the file to be meaningful (a custom Setup.hs doesn't even have to use the Cabal lib).

One of my colleagues is actually getting this bug with building Cabal head itself (using cabal-install version 1.22.0.0 using version 1.22.0.0 of the Cabal library). I cannot reproduce it but I suspect we're using different versions of the binary package.

**Comment by dcoutts** [comment] 2015-02-19 17:12
One option of course is to go back to the text format and use the old code that I wrote carefully to avoid these problems :-) until we can sort things out to use a binary format properly.

**Comment by edsko** [comment] 2015-02-19 17:14
To be precise, as Duncan said, trying to build Cabal HEAD (5c3a514bc2662aa47caa870b9f02bd6d897e146b) with 

```
# cabal --version
cabal-install version 1.22.0.0
using version 1.22.0.0 of the Cabal library 
```

and 

```
# ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

# ghc-pkg list | grep binary
    binary-0.7.1.0
```

calling `cabal configure` works but then `cabal build` fails immediately with

```
# cabal build -v3
cabal: Prelude.chr: bad argument: 2898156
```

Calling the generated `setup` directory

```
dist/build/setup configure --user
dist/build/setup build
dist/build/setup install --only
```

is a workaround for now.

**Comment by ttuegel** [comment] 2015-02-19 17:23
@dcoutts It's unclear to me why we cannot catch exceptions thrown by older versions of `binary`. Could you elaborate more?

@edsko Would it be possible for you to reproduce that failure with a profiled build of `cabal-install`? I'd like to know what is calling `Prelude.chr`, because it's not clear to me where the failure is even happening. I suspect it's something in `Data.ByteString.Char8`. If you could run `cabal build -v3 +RTS -xc`, that should give a definitive answer.

**Comment by dcoutts** [comment] 2015-02-19 18:05
@ttuegel the old binary did not return errors in a structured way, it just called `error`. Those `error` calls are not the ones we're catching.

But more generally, in principle it's not legitimate for use to even try and look at a `dist/setup-config` if we're using `build-type: Custom`. Currently reconfigure does it with the try variant, but a couple other commands do it unconditionally, which cannot possibly work in general with custom build type.

Although edsko had a recent version of binary installed, that's not conclusive evidence that his cabal-install binary was built with that version. I've certainly seen that chr error from old versions of the binary package when reading binary formats that do not match was was expected.

The other reason I suspect it's coming from binary is that there's no log output before the error, and the first thing that `cabal build` does is the reconfigure check, which tries to reads the `dist/setup-config` file.

**Comment by ttuegel** [comment] 2015-02-19 18:20
@dcoutts We never call `decode` directly. With old `binary` we only call it through [this](https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Compat/Binary.hs#L52) wrapper, which catches calls to `error`. Either that exception is coming from somewhere else, or the wrapper is not correct.

I understand it's not legitimate to look at `dist/setup-config` for `build-type: Custom` packages, but this exception should be caught and dealt with.

**Comment by dcoutts** [comment] 2015-02-19 18:26
Mm, strange indeed. Yes, we should track down where exactly the `chr` exception is coming from.

**Comment by cocreature** [comment] 2015-02-20 06:01
I can reproduce this by running 'cabal clean && cabal configure' followed by 'cabal repl' in the Cabal directory of this repository. The exact error message is `cabal: Prelude.chr: bad argument: 2898156`.

**Comment by svenpanne** [comment] 2015-02-20 08:07
I don't understand the details you're discussing in this thread, but I just wanted to point out that I had trouble in various projects with ``build-type: Simple``. I don't use ``Custom``, so this can't be the root cause. Some examples:

  https://travis-ci.org/haskell-opengl/OpenGLRaw/jobs/51387029
  https://travis-ci.org/svenpanne/ObjectName/jobs/48734376
  https://travis-ci.org/haskell-opengl/GLUT/jobs/49324948

As it is, it looks like a show-stopper, because it happens most of the time with the soon-to-be-released GHC 7.10.

**Comment by edsko** [comment] 2015-02-20 10:21
@ttuegel I tried to do as you suggested. Strangely, I tried this first with ghc 7.4.2, binary 0.7.3.0, Cabal 1.22 and `cabal-install` 1.22, no I could not reproduce. Then I tried with ghc 7.4.2, binary 0.7.1.0, and again, could not reproduce. Then I tried with ghc 7.8.3, binary 0.7.1.0, and now I can reproduce. No idea why. Anyway, here's the trace you requested; compiled cabal-install with

```
# cabal configure --enable-profiling --ghc-option=-fprof-auto-calls
```

then ran `cabal configure` (with the newly compiled `cabal`) in `Cabal` HEAD, and then build crashes:

```
# ~/local/src/cabal-install-1.22.0.0/dist/build/cabal/cabal build +RTS -xc 
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Main.mainWorker,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Main.mainWorker,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Main.mainWorker,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Main.mainWorker,
  called from Main.mainWorker
cabal: Prelude.chr: bad argument: 2898156
```

**Comment by edsko** [comment] 2015-02-20 10:49
Ok, more complete trace, compiling `Cabal-1.22` also with `-fprof-auto-calls`:

```
# ~/local/src/cabal-install-1.22.0.0/dist/build/cabal/cabal build +RTS -xc
*** Exception (reporting due to +RTS -xc): (THUNK_1_0), stack trace: 
  Distribution.Utils.NubList.get,
  called from Distribution.Simple.Program.Db.get,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.deferErrorIfBadVersion,
  called from Distribution.Simple.Configure.getConfigStateFile,
  called from Distribution.Simple.Configure.getPersistBuildConfig,
  called from Distribution.Simple.Configure.tryGetPersistBuildConfig,
  called from Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Distribution.Simple.Utils.topHandlerWith,
  called from Distribution.Simple.Utils.topHandler,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Distribution.Utils.NubList.get,
  called from Distribution.Simple.Program.Db.get,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.deferErrorIfBadVersion,
  called from Distribution.Simple.Configure.getConfigStateFile,
  called from Distribution.Simple.Configure.getPersistBuildConfig,
  called from Distribution.Simple.Configure.tryGetPersistBuildConfig,
  called from Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Distribution.Simple.Utils.topHandlerWith,
  called from Distribution.Simple.Utils.topHandler,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Distribution.Utils.NubList.get,
  called from Distribution.Simple.Program.Db.get,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.deferErrorIfBadVersion,
  called from Distribution.Simple.Configure.getConfigStateFile,
  called from Distribution.Simple.Configure.getPersistBuildConfig,
  called from Distribution.Simple.Configure.tryGetPersistBuildConfig,
  called from Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Distribution.Simple.Utils.topHandlerWith,
  called from Distribution.Simple.Utils.topHandler,
  called from Main.mainWorker
*** Exception (reporting due to +RTS -xc): (base:GHC.Exception.SomeException), stack trace: 
  Distribution.Utils.NubList.get,
  called from Distribution.Simple.Program.Db.get,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.getStoredValue,
  called from Distribution.Simple.Configure.getConfigStateFile.deferErrorIfBadVersion,
  called from Distribution.Simple.Configure.getConfigStateFile,
  called from Distribution.Simple.Configure.getPersistBuildConfig,
  called from Distribution.Simple.Configure.tryGetPersistBuildConfig,
  called from Main.reconfigure,
  called from Main.buildAction,
  called from Main.mainWorker,
  called from Distribution.Simple.Utils.topHandlerWith,
  called from Distribution.Simple.Utils.topHandler,
  called from Main.mainWorker
cabal: Prelude.chr: bad argument: 2898156
```

Hope that helps.

**Comment by ttuegel** [comment] 2015-02-20 13:08
@cocreature What version of `cabal-install` are you running that with?

**Comment by ttuegel** [comment] 2015-02-20 13:09
@edsko Well, GHC stack traces are never as helpful as you hope, but that gives me an idea where to look. Thanks!

**Comment by cocreature** [comment] 2015-02-20 13:17
@ttuegel 1.22.0.0 from the nix haskellngPackages.

**Comment by ttuegel** [comment] 2015-02-20 13:43
@cocreature Thank you! I can finally reproduce this.

**Comment by ttuegel** [comment] 2015-02-20 15:55
This seems to be unrelated to the version of `binary`. This issue is present in the 1.22 branch, but not on master.

**Comment by ttuegel** [comment] 2015-02-20 18:04
Actually, I think it does depend on the version of `binary`. I think it only happens with *new* `binary`. We use `decodeOrFail` when it's available, but it turns out `decodeOrFail` can throw exceptions from `get` and friends. The `Binary` instance for `Char` calls `chr`, which is partial.

I will switch over to using our wrapper around `decode` to catch exceptions. I'll also upstream a patch to `binary` that makes that instance total.

**Comment by ttuegel** [comment] 2015-02-20 20:17
Fixed in #2428.

**Closed by ttuegel** 2015-02-20 20:17 UTC
Labels: bug

**Comment by svenpanne** [comment] 2015-02-20 20:24
Cool, thanks. @hvr: Could you build an updated Ubuntu package and put that into your ppa? This would unbreak lots of Travis CI projects...

**Comment by 23Skidoo** [comment] 2015-02-20 20:32
@ttuegel 
> it turns out `decodeOrFail` can throw exceptions from `get` and friends.

Is this a bug in `binary` or expected behaviour? Perhaps we should report it.

**Comment by ttuegel** [comment] 2015-02-20 21:33
It is unexpected and avoidable, but technically correct (impossible to catch exceptions in pure code). I have submitted a [patch](https://github.com/kolmodin/binary/pull/70).

**Comment by 23Skidoo** [comment] 2015-03-16 13:20
> One of my colleagues is actually getting this bug with building Cabal head itself

Interestingly enough, the [problem reported by](https://github.com/haskell/cabal/issues/2251#issuecomment-75093834) @edsko recently [started happening on Travis with 7.10](https://travis-ci.org/haskell/cabal/jobs/54560604). What I don't get is why `build` fails to read back the `setup-config` file - both `build` and `configure` (which generated it) use the internal setup method, so the versions of `binary` should match. @ttuegel, any ideas?

**Comment by svenpanne** [comment] 2015-03-16 14:22
I know that I'm probably repeating myself, but I have problems with GHC 7.10 and Cabal 1.22 for months now, too, see e.g.

   https://travis-ci.org/haskell-opengl/GLURaw/jobs/53960254
   https://travis-ci.org/haskell-opengl/StateVar/jobs/53657899
   https://travis-ci.org/haskell-opengl/OpenGL/jobs/53853598

to name just a few. https://launchpad.net/~hvr/+archive/ubuntu/ghc contains only relatively old cabal-install 1.22 versions, so could somebody please clarify what the current state of affairs is? To be honest, I don't understand things anymore. :confused: Which versions are expected to work together? How can I test this on Travis CI?

The current situation is quite frustrating: I can either ignore failures with 7.10 and 1.22 via ``allow_failures`` (bad, because I might not catch problems, and both versions should be out soon) or I have relatively random failures in my build matrix (bad, too, for the obvious reasons).

**Comment by ttuegel** [comment] 2015-03-16 14:34
Cabal and cabal-install must always have the same major version, in this case `1.22.y.z`. Releases with the same major version must be compatible, i.e. `Cabal-1.22.u.v` is compatible with `cabal-install-1.22.y.z` for all u, v, y, z. It is always best to use the latest minor release, as that will have the most recent bug fixes. Right now that is `Cabal-1.22.1.1` and `cabal-install-1.22.0.1`. That means you should be updating cabal-install every time Cabal is updated. Travis does not do this, and so it is broken right now.

**Comment by ttuegel** [comment] 2015-03-16 14:40
@23Skidoo The proximate cause of that error is Travis not using cabal-install built with the latest Cabal. Not sure yet why it insists on reconfiguring, but we would get a more meaningful explanation if Travis used the latest Cabal.

**Comment by 23Skidoo** [comment] 2015-03-16 17:26
What's interesting is that the same version of `cabal-install` is used in all cases (7.4.2, 7.6.3, 7.8.3, ...), but the exception only happens with HEAD and 7.10. I wonder whether this has something to do with the 7.10 snapshot reporting its version as `7.10.0.20150314`. Maybe this triggers some bug in the `Data.Version` Binary instance?

**Comment by 23Skidoo** [comment] 2015-03-16 18:05
@ttuegel 
> The proximate cause of that error is Travis not using cabal-install built with the latest Cabal. 

I understand that it doesn't include your fix (#2428) for the uncaught exception problem, which is why we get `Prelude.chr: bad argument:` instead of `Reconfiguring with default arguments...`. But I don't understand why we get an exception in the first place: `setup-config` was generated by the same `cabal-install` executable that tries to read it back, versions of `Cabal` and `binary` should match.

**Comment by svenpanne** [comment] 2015-03-16 21:52
Hmmm, even after all those explanations my question remains: What shall I (and lots of other people) do to get their Travis builds green again? I don't fully understand the details yet, but having to do seemingly unrelated things in lockstep is a horrible user experience, and this should mitigated somehow. In the C/C++ world: Imagine if gcc/make/rpm/... would have to be kept tightly in sync somehow... :scream:

**Comment by ttuegel** [comment] 2015-03-16 22:06
@svenpanne I'm not sure what you mean by keeping things in lockstep here. The bug is fixed in Cabal-1.22.1.1. Travis does not use this version, so you do not get the bug fix. That's the extent of the problem blocking builds.

There is an unrelated issue that cabal-install sometimes reconfigures when it doesn't need to. In Cabal < 1.22.1.1, this also triggers the `Prelude.chr` bug, but if Travis updated their Cabal, your builds would still succeed. (Albeit after reconfiguring unnecessarily.) The bug fix will also be available in GHC 7.10.1-rc3, so if/when Travis updates to that, you'll be good to go.

**Comment by 23Skidoo** [comment] 2015-03-16 22:27
> There is an unrelated issue that cabal-install sometimes reconfigures when it doesn't need to. In Cabal < 1.22.1.1, this also triggers the `Prelude.chr` bug

I don't think that the reconfigure logic is at fault. The `Main.reconfigure` function reconfigures only if necessary. `buildAction` unconditionally calls `reconfigure`, which tries to load `setup-config` with `tryGetPersistBuildConfig`, which raises the `Prelude.chr` exception.

**Comment by svenpanne** [comment] 2015-03-17 08:03
Just to clarify: The only missing thing to get Travis CI builds with 7.10 green again is a new version (1.22.1.1) of cabal-install in https://launchpad.net/~hvr/+archive/ubuntu/ghc, correct? GHC seems to be updated quite regularly there, but not cabal-install. Can we somehow arrange to get that soon? 7.10 is already at release candidate 3, and I haven't been able to get consistently green builds for that.

Given the heavy reliance of lots of packages on Travis CI (not only mine), we should probably have some *automated* PPA where there relevant packages (GHC, cabal-install, etc.) live.

**Comment by 23Skidoo** [comment] 2015-03-17 12:09
@svenpanne 
> The only missing thing to get Travis CI builds with 7.10 green again is a new version (1.22.1.1) of cabal-install in https://launchpad.net/~hvr/+archive/ubuntu/ghc, correct? GHC seems to be updated quite regularly there, but not cabal-install. Can we somehow arrange to get that soon?

That's up to @hvr, who maintains that PPA.

**Comment by svenpanne** [comment] 2015-03-17 12:44
@23Skidoo Well, I know that, and I think Herbert is really doing a great job, but he's probably overloaded with work, so he couldn't update the PPA. My proposal was to replace that "single point of failure" for all those Haskell projects using Travis CI with something automatic, i.e. have a PPA somewhere with GHC, cabal-install etc. on it.

**Comment by ttuegel** [comment] 2015-03-18 03:31
@23Skidoo

<blockquote>I don't think that the reconfigure logic is at fault. The Main.reconfigure function reconfigures only if necessary. buildAction unconditionally calls reconfigure, which tries to load setup-config with tryGetPersistBuildConfig, which raises the Prelude.chr exception.</blockquote>

I think you're right. I just checked, and the `setup-config` files created during the configure and build runs are byte-for-byte identical. I suspect a bug in binary or one of our instances.

**Comment by 23Skidoo** [comment] 2015-03-18 18:41
Looks like @hvr has updated his PPA or something; this problem no longer happens for `cabal-install` on Travis.
