### ISSUE TITLE
Show new server index state in cabal v2-update

### ISSUE THREAD

**Issue by jneira** [haskell/cabal#6934] opened 2020-06-30 07:06 UTC
* Hi, it is a minor ui improvement but i hope it will not be very difficult to implemement
* The actual `cabal v2-update` default output is:
```
PS D:\dev\ws\haskell\hls> cabal v2-update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2020-06-29T21:09:43Z'
```
* I often need to know the actual timestamp, not the previous one, to fill the `index-state` cabal.project field or simply compare with release or revisions dates on hackage.
  * So i have to run a second `cabal update` to make it tell me the last state, just downloaded
* So the output could be changed to something like:
```
 PS D:\dev\ws\haskell\hls> cabal v2-update
Downloading the latest package list from hackage.haskell.org
hackage.haskell.org index state updated to '2020-06-29T22:09:43Z'
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2020-06-29T21:09:43Z'
```
* for each server updated

**Comment by phadej** [comment] 2020-06-30 08:14
```
 cabal --version
cabal-install version 3.3.0.0
compiled using version 3.3.0.0 of the Cabal library 
```

```
% cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2020-06-30T06:46:07Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2020-06-25T09:14:58Z'
```

Resolved in #6810, Duplicate of #6804

**Closed by phadej** 2020-06-30 08:14 UTC
