### ISSUE TITLE
Please provided binary download for cabal command with linux x86_64

### ISSUE THREAD

**Issue by netroby** [haskell/cabal#2408] opened 2015-02-09 03:12 UTC
Please provided binary download for cabal command with linux x86_64

We only have https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-linux.tar.gz

but we need x86_64

**Comment by ttuegel** [comment] 2015-04-23 23:34
Duplicate of #1653.

**Closed by ttuegel** 2015-04-23 23:34 UTC
