### ISSUE TITLE
How do I escape my password in the config file?

### ISSUE THREAD

**Issue by poscat0x04** [haskell/cabal#7211] opened 2020-12-24 11:28 UTC
My hackage password contains closing brackets (`}`), which caused cabal's config parser to fail with this error message

```
cabal: Error parsing config file /home/poscat/.cabal/config:14:
mismatched brackets, unexpected }
```
I tried to quote my password, but it did not work. I then tried to escape the bracket with a backslash, it did not work either.
How do I escape my password in the config file?

**Comment by IvanRenison** [comment] 2021-06-25 21:11
I have a similar problem, I am in windows, and path's contain a `}` character, like these: `C:\Users\usuario\}\AppData\Roaming\cabal\packages`. When trying to use cabal install, I get this error:
```
cabal.exe: Error parsing config file
C:\Users\usuario}\AppData\Roaming\cabal\config:28:
mismatched brackets, unexpected }
```

**Comment by Mikolaj** [comment] 2021-06-25 22:43
Hi @poscat0x04 and @IvanRenison,

There possibly is a bug, but I can't reproduce the issue. Could you kindly prepare a minimal version of a configuration file that causes the problem (but without your real password!), state the path at which the files resides and give the exact commandline invocation that produces the error? Thank you.

**Comment by Mikolaj** [comment] 2021-06-25 22:44
Oh, and please append the output of `cabal --version`.

**Comment by Mikolaj** [comment] 2021-06-26 20:06
@poscat0x04: in another issue, a colleague pointed out this was probably fixed in https://github.com/haskell/cabal/commit/fe82a920598367debc7553da016e85574f8a3fe8 and so when cabal 3.6 is released, the problem should be gone. Please kindly verify at that time and for now, I'm afraid, your password can't work due to the error in parsing.

**Closed** 2021-10-17 08:14 UTC
Labels: type: bug, Cabal: parser
