### ISSUE TITLE
cabal-install has to install something before it realizes it's in a sandbox

### ISSUE THREAD

**Issue by MasterMastic** [haskell/cabal#2181] opened 2014-10-25 17:04 UTC
Say there is a package and installing it on user/global would require re-installations of dependencies.
If I install it in a sandbox, cabal-install doesn't realize I'm in a sandbox, and it will warn me about the re-installs.
To install the package in the sandbox, I have to find a dependency package I don't have on user/global, install it in the sandbox, and only then cabal-install gets that this is a sandbox and I can install the package I want without warnings.

I don't know what happens when you force the re-installs (as I don't wanna mess my user/global).
I also don't know if the package I have to install first has to be a dependency.
If finding out either would be necessary & helpful, let me know and I'll try to see.

In my scenario it happens on cabal-install version 1.20.0.3, cabal library 1.20.0.2, GHC 7.8.3 x64 on Windows 7. The package this happens to me with is criterion.

**Comment by ttuegel** [comment] 2015-04-24 14:29
@23Skidoo Were you able to reproduce this? Is it just a duplicate of #2101?

**Comment by 23Skidoo** [comment] 2015-04-24 15:01
Yes, looks like a duplicate of #2501.

**Closed by 23Skidoo** 2015-04-24 15:01 UTC
Labels: duplicate, sandbox
