### ISSUE TITLE
Cannot use ghc-pkg's ${pkgroot} with include-dirs or extra-lib-dirs

### ISSUE THREAD

**Issue by avaranovich** [haskell/cabal#1317] opened 2013-05-07 13:05 UTC
I want to distribute native binaries together with the package. Both binaries and C-headers are organized as subfolders.

here is the relevant part of Cabal config:

```
library
  hs-source-dirs:  src
  include-dirs:    ${pkgroot}/native/include
  extra-lib-dirs:  ${pkgroot}/native/lib
```

Then

```
cabal install
cabal: libhdfs.cabal:10: unexpected span: "/native/include"
make: *** [build-local] Error 1
```

My cabal version:  
cabal-install version 0.14.0
using version 1.14.0 of the Cabal library

**Comment by gbaz** [comment] 2016-03-21 18:28
From irc discussion with @dcoutts : 

"An obvious feature request is to be able to specify target dirs as extra-lib-dirs. E.g. extra-lib-dirs: $libdir, i.e. whatever libdir the user configures with, but unspecified who is responsible for installing the lib."

We could then have the equivalent of install-includes for libs.

**Comment by winterland1989** [comment] 2018-04-25 20:17
What is the state this ticket? It's almost five years since it has been open? Is there a standard practice to bundle binary dep(for example, a DLL) with cabal now?

**Comment by gbaz** [comment] 2018-04-27 02:00
I think it is stalled, waiting for a volunteer to implement it.

**Comment by flip111** [comment] 2019-04-01 13:34
The current error changed, i now get:
```
Warning: 'extra-lib-dirs: ${pkgroot}/myLib' directory does not exist.
```

In which situation is `extra-lib-dirs` actually useful? It seems to be that when you hardcore it to a path on your OS it's not portable to other OS/distro's. When you build or bundle the static library (archive file) with your haskell library or program it doesn't work because `${pkgroot}` doesn't work.

I looked to see if the configuration could be modified. At first glance this didn't seem to difficult. Searching from:

https://github.com/haskell/cabal/blob/c9f02b27d4916f2317e7506e075ef94fb77ad405/Cabal/Distribution/Simple/Setup.hs#L630-L633

https://github.com/haskell/cabal/blob/c9f02b27d4916f2317e7506e075ef94fb77ad405/Cabal/Distribution/Simple/Configure.hs#L993

Then using `postConf` hook [could](https://www.haskell.org/cabal/release/latest/doc/users-guide/developing-packages.html#more-complex-packages) do some work. Until i read this blog ...

https://rufflewind.com/2014-07-16/custom-cabal-build-type

Note to @vlasenkov and @winterland1989 if you want to load dynamic libraries on runtime you can use https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-DynamicLinker.html and https://hackage.haskell.org/package/Win32-2.8.3.0/docs/System-Win32-DLL.html

I think this configuration flag is mainly useful for static libraries (`.a` on linux/macos and `.lib` on windows)

**Comment by flip111** [comment] 2019-04-01 13:49
Maybe there is more hope now to get this into the cabal configuration file. Because:

>  Now that this info is plumbed through, it will be straightforward to add support for relative paths elsewhere in configuration.

https://github.com/commercialhaskell/stack/issues/2830#issuecomment-287593038

**Comment by phadej** [comment] 2019-04-01 13:56
Distributing binary blobs just won't work. There are system package managers to do that. And `pkg-config`.

**Comment by flip111** [comment] 2019-04-01 14:08
@phadej ok it's a difference between the person who opened the issue wanting to distribute binary blobs. I want to compile on the target system with other build tools before linking it into the haskell program.

**Comment by Mistuke** [comment] 2019-04-01 14:11
Except not all operating system have a library level package manager. So this assumption is invalid. Also you don't have to distribute the binary blob. You could have build it locally as a side-effect of the package build.

Both of these issues are solved by having `extra-lib-dirs` do something useful I stead of requiring a Unix like toolchain to do something so basic as `pkg-config` requires.

**Comment by phadej** [comment] 2019-04-01 14:24
@Mistuke. @flip111  So `"a side effect of the package build" is something for which `c-sources` like functionality isn't enough (e.g. you want to build the part of an application with rust and fortran), but that requires custom-setup.

If the extra *shared* object is built by a custom `Setup.hs`, how it's `copy`d and made available for the user? So this would work if Cabal also manages the final link step.

I have a clear opinion: if you have multiple-source language programs, or otherwise complicated build setup: then don't use `Cabal` to orchestrate the top-level build. It's not designed for that.

Yet, if the application is build externally, then additional `extra-lib-dirs` can be provided via `cabal.project{.local}`, which i'd use. The `${projectroot}` variable would make sense there (but not in `pkg.cabal`).

**Comment by flip111** [comment] 2019-04-01 14:37
@phadej how does that work with `cabal.project{.local}` i couldn't find documentation on that with a quick google. Do you have an example?

Don't know what you mean with shared object. I intend to just compile into a static library and then let cabal link it into the final program. That's not shared afaik.

The use case is just writing a haskell library that provides a C lib and it's bindings. It's the same use case as for which `c-sources` is used. Only that i don't like cabal to compile the c files directly. Cabal has the `build-type: custom` and building works, so that part is covered.  Only finding the libraryt is the last piece of the puzzle to make it all work now as it looks like. If not using cabal to do the top-level build has serious drawbacks that it the library can not be pulled from hackage just like that for a dependency of another program.

I don't think it's too much to ask to just make relative path working. Especially after the work already put in by mgsloan.

**Comment by phadej** [comment] 2019-04-01 14:58
> Cabal has the build-type: custom and building works

`build-type: custom` should be treated as a code smell. You do something which in perfect world `Cabal` would be able to do.

> Only that i don't like cabal to compile the c files directly. 

What's wrong, shouldn't we rather fix that?

> Don't know what you mean with shared object

It's not relevant whether the end result is `.exe`, `.a`, `.dll`, `.so` or `.dylib`. If it's not pure Haskell than very soon `Cabal` is the wrong tool to orchestrate the whole thing. (an extreme example: `hadrian` for GHC).

> If not using cabal to do the top-level build has serious drawbacks that it the library can not be pulled from hackage/stackage just like that for a dependency of another program.

So you are building a Haskell library, which some extra non-Haskell code which you want to compile *manually* so to speak, and link into the final object file. I have to re-ask, what's wrong with `c-sources` and `cc-options`?

So say, you compile the C-files manually, putting them in `temporary` directory. Then you should able to tweak the needed bits in `buildHook` to include that additional directory in `-L` and library on `extra-libraries` before you pass control to default [`buildHook`](http://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Simple-UserHooks.html#v:buildHook) implementation.
And you can even add additional `cpp-options`, that the custom setup was actually run and everything external is setup.

---

If you go for `build-type: Custom`, then cleaner if you do all extra bits there. `${pkgroot}` doesn't have good use without custom setup, does it?

**Comment by Mistuke** [comment] 2019-04-01 15:05
`c-sources` and `cc-sources` defer to ghc for compilation do they not? In which case there's quite a lot wrong with using them.

When building shared libraries ghc will always provide extra c libraries such as the rts, and even worse it tells the compiler to export all symbols. The assumption here is that you're compiling c code that wants to use things from the compiler. For static libraries this is not a problem. For dynamic way by default variants of ghc this is not a problem, as the extra symbols will be in their own so. For non dynamic way versions of ghc this is a big problem, as you will now have multiple copies of the rts inside your c shared library, where you need and expect 0. If you load this the dynamic linker may get confused if you use a symbol we didn't export from the linker. 

Also shared libraries on windows produce two files, not one. I haven't checked but cabal would then need to be able to know it has multiple side effects from one compilation. Regardless of it's `-o` setting.

**Comment by phadej** [comment] 2019-04-01 15:11
@Mistuke but @flip111 is building a **Haskell** library, not a foreign library, as they talk about distribution via Hackage/Stackage?

If the end result is non-Haskell specific DLL, then IMHO you should use external build tooling, and only use Cabal to build the Haskell bits.

**Comment by flip111** [comment] 2019-04-01 15:48
> When building shared libraries ghc will always provide extra c libraries such as the rts

This would still be good to avoid. But phadej was right that i was not asking about this scenario.

>  I have to re-ask, what's wrong with `c-sources` and `cc-options`?

Nothing onto itself. It's just that C library comes with it's own tooling that goes along with the documentation for that C library. You get to set flags for features you want and stuff like that. I don't know all that the build tool is doing but recreating that through cabal doesn't seem like the best idea. It's double effort, which you need to keep in sync with changes to the original build recipe. And when you go back to the authors of the C library to ask for help you get "we don't support that build tool (cabal)" (not that i actually tried this, but i would expect so).

> If you go for `build-type: Custom`, then cleaner if you do all extra bits there. `${pkgroot}` doesn't have good use without custom setup, does it?

This is a bit debatable because `build-type: Custom` is not really regarded as "clean" in the first place, so keeping more stuff out of it would make things "cleaner"?! 

> `${pkgroot}` doesn't have good use without custom setup, does it?

Let's call it "relative path" because `${pkgroot}` was some artifact from `ghc-pkg`. I'm just saying that this to clear confusion. Both the topic started and me goal is to back it work with a relative path from the package root. `${pkgroot}` is not really relevant here further than it pops up as a suggestion in an error message. Having said that ... some people do think there is a usecase for relative paths, i point again to https://github.com/commercialhaskell/stack/issues/2830 I just leave it at that than to go further think of use cases in which one want to use relative path.

Please i ask again. How does the solution with `cabal.project{.local}` work? If i know that i continue on my project immediately without having to spend time writing build hooks.

**Comment by phadej** [comment] 2019-04-01 16:06
> so keeping more stuff out of it would make things "cleaner"?

You just move part of your custom setup script into `Cabal` proper, but only a part, without any way to move the rest. For me it's not "cleaner".

---

> Nothing onto itself. It's just that C library comes with it's own tooling that goes along with the documentation for that C library.

So is the goal to bundle C-library with a non-trivial (and non-autoconf) build setup? I'd like (better) system package managers for that.

> How does the solution with cabal.project{.local} work?

It doesn't work, but in `cabal.project` setting the relative-to-absolute `${projectroot}` makes some sense than in a single package context (yet one can argue that `cabal.project` could be generated itself). Anyway, that doesn't help you, as you' want to distribute the package through Hackage, if I understand right.

**Comment by phadej** [comment] 2019-04-11 10:38
https://github.com/haskell/cabal/issues/694 is related

**Comment by aherrmann** [comment] 2021-12-02 17:45
I encountered this issue in the context of trying to make builds of Cabal packages in Bazel with rules_haskell deterministic, see https://github.com/tweag/rules_haskell/issues/1600#issuecomment-967285858 and https://github.com/tweag/rules_haskell/pull/1648.

Bazel runs build actions in a sandbox in a Bazel controlled working directory with an non-deterministic path. If a Cabal package has C library dependencies that were built by Bazel, then the sandbox working directory will leak into the Cabal build through the absolute paths in `--extra-include-dirs` and `--extra-lib-dirs`. These paths enter the package configuration and cached package-db, but also the generated interface files in the `flag hash` field. rules_haskell [patches](https://github.com/tweag/rules_haskell/blob/a7241fa64c7cd36462a1f6ac4c660d1247d5e07b/haskell/private/cabal_wrapper.py#L292-L294) the package configuration, replacing the absolute path by `${pkgroot}`, after the Cabal build completed and re-caches the package-db. This way the final package-db is relocatable and deterministic. However, the flag hash field in the interface file remains indeterministic.

I.e. Bazel builds of Cabal packages that have C library dependencies produce indeterministic GHC interface files. We would like to achieve reproducible builds, because Bazel's caching is content hash based, and reproducible builds enable early cut-off due to cache hits.

I've created https://github.com/aherrmann/demo-cabal-reproducibility-issue to illustrate the issue on a minimal example.

If `--extra-include-dirs` and `--extra-lib-dirs` could accept paths relative to `${pkgroot}` then we could avoid this issue and achieve reproducible builds of Cabal packages in Bazel.

**Comment by Mikolaj** [comment] 2021-12-02 19:50
@aherrmann: thank you for the illustration. So the bigger problem are the leaking hashes, not any problems with `${pkgroot}` as in the title of this ticket? Where are the hashes coming from? Is it from the random paths? Do you have any ideas how to make the hashes deterministic? Anything in the long discussion of this ticket that could be a valid workaround for you?

**Comment by gbaz** [comment] 2021-12-02 21:46
Ok, I'm confused. As described above, cabal now does accept `${pkgroot}/etc/etc` while warning that this does not of course exist (since it knows nothing of this template variable).

If I install a lib with such a thing, it properly installs it and the ghc-pkg package manifest correctly has the package root metavariable set in the manifest.

So the original ticket is "resolved" in the sense that we can "use" this metavariable. The question is _what should cabal do if it is set_? Cabal will neither know to put anything in this special location, nor will it know how to expand this location "differently" or whatever at compile time.

That's what I think really blocked this ticket -- not allowing the syntax, but anyone specifying precisely what it should mean.

That said, I think that baezel may be able to "work around" the issue sufficiently -- just place the built C dependencies in a uniform location (even if they originally were generated in a special sandbox dir), then proceed as above?

**Comment by cocreature** [comment] 2021-12-03 07:29
> That said, I think that baezel may be able to "work around" the issue sufficiently -- just place the built C dependencies in a uniform location (even if they originally were generated in a special sandbox dir), then proceed as above?

That’s very tricky to achieve in a way that works across different setups so you can benefit from remote caching. Specifically, Bazel wants to place things somewhere in your user directory for very sensible reasons (it doesn’t run as root). But if your username is `gbaz` while mine is `cocreature` all absolute paths to our user directories are different (`/home/cocreature` vs `/home/gbaz`). For system libraries that come from nix or something else that it less of an issue but for libraries built by Bazel itself, I don’t see a reasonable way to hack around this.

**Comment by aherrmann** [comment] 2021-12-03 11:49
@Mikolaj 

> So the bigger problem are the leaking hashes, not any problems with `${pkgroot}` as in the title of this ticket?

Yes, the hashes are the bigger problem, the package configuration requires a workaround on our part, but at least we have that workaround available. For the flag hash I'm not sure how to work around it, yet.

> Where are the hashes coming from? Is it from the random paths?

They are computed by GHC based on the `DynFlags` [here](https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-8.10.7-release/compiler/iface/MkIface.hs#L654). I think the `extra-include-dirs` enter through `includePaths` [here](https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-8.10.7-release/compiler/iface/FlagChecker.hs#L48).

> Do you have any ideas how to make the hashes deterministic? Anything in the long discussion of this ticket that could be a valid workaround for you?

If we could pass relative paths to GHC during the compilation, then the paths would be deterministic in our case. The absolute paths are indeterministic because they contain the Bazel controlled sandbox working directory. That working directory takes the following shape:
```
  /home/user/.cache/bazel/_bazel_user/685f50f995fafec37ae0502294766983/sandbox/linux-sandbox/28/execroot/myproject
# $HOME     /.cache/bazel/_bazel_$USER/$WORKDIR_HASH                  /sandbox/$OS-sandbox/$COUNTER/execroot/$PROJECT_NAME
```
It's out of our control and a certain amount of indeterminism in the absolute seems inevitable because we don't have root access and multiple build actions may run in parallel and cannot share working directories.

@gbaz

> So the original ticket is "resolved" in the sense that we can "use" this metavariable. The question is _what should cabal do if it is set_? Cabal will neither know to put anything in this special location, nor will it know how to expand this location "differently" or whatever at compile time.

Right, that needs to be specified carefully to solve our issue in the Bazel use-case.
For Cabal itself, when it comes to checking for the existence of headers and C libraries, we'd want it to interpret `${pkgroot}` as the path implied by the [`--package-db`](https://github.com/aherrmann/demo-cabal-reproducibility-issue/blob/a0d6e39dd7b0f47d526593fdc6bbefaff9702bff/build.sh#L27) flag; and we'd want it to use the literal string `${pkgroot}` when writing the package configuration and caching the package-db.
But, to resolve the issue of indeterministic interface files due to the flag hash we need to avoid absolute paths passed to GHC. In that case we'd want Cabal to pass a relative include path to GHC instead of an absolute one. I'm not sure if a general policy of converting any `${pkgroot}` based path to a relative path for GHC would be feasible.

> That said, I think that baezel may be able to "work around" the issue sufficiently -- just place the built C dependencies in a uniform location (even if they originally were generated in a special sandbox dir), then proceed as above?

Unfortunately, as @cocreature described above, we can't really do that. Build actions are not supposed to persist anything outside the sandbox directory. Actions may not be run at all in case their output was cached previously, so downstream actions cannot depend on side effects of previous actions. And multiple actions may be scheduled to run in parallel, so we cannot write to the same fixed absolute path without risking collisions, and we don't have root access and shouldn't assume that things like `$TMP` are identical across machines.

**Comment by Mikolaj** [comment] 2021-12-03 13:01
I don't remember, does GHC accept relative paths there? If so, are there any cabal tickets about making cabal *not* change relative paths to absolute ones for its own use or for calling GHC? I seem to remember tictets in the opposite direction, but I don't remember what bugs that was fixing.

**Comment by aherrmann** [comment] 2021-12-03 13:52
> I don't remember, does GHC accept relative paths there?

Yes, GHC accepts relative paths. We use relative paths in the regular (non-Cabal) Haskell rules for Bazel `haskell_library`, `haskell_binary`, `haskell_test`.

> If so, are there any cabal tickets about making cabal _not_ change relative paths to absolute ones for its own use or for calling GHC?

Well, it's not that Cabal is changing a relative path to an absolute path, it's that it doesn't allow us to set relative paths in the first place. At least, if I adjust the demo [to use relative paths](https://github.com/aherrmann/demo-cabal-reproducibility-issue/commit/0b64c89b6404ff4517ab45bc11bf6537aee781d4), then the configure step raises a warning:
```
Warning: 'include-dirs: ../install1/myclib' is a relative path outside of the source tree. This will not work when generating a tarball with 'sdist'.
Warning: 'extra-lib-dirs: ../install1/myclib' is a relative path outside of the source tree. This will not work when generating a tarball with 'sdist'.
Warning: 'include-dirs: ../install1/myclib' is a relative path outside of the source tree. This will not work when generating a tarball with 'sdist'.
Warning: 'extra-lib-dirs: ../install1/myclib' is a relative path outside of the source tree. This will not work when generating a tarball with 'sdist'.
```
The build step succeeds. But, the install step fails:
```
mypackage-0.1.0.0: library-dirs: ../install1/myclib is a relative path which makes no sense (as there is nothing for it to be relative to). You can make paths relative to the package database itself by using ${pkgroot}. (use --force to override)
mypackage-0.1.0.0: dynamic-library-dirs: ../install1/myclib is a relative path which makes no sense (as there is nothing for it to be relative to). You can make paths relative to the package database itself by using ${pkgroot}. (use --force to override)
```
Which is the same issue as reported [above](https://github.com/haskell/cabal/issues/1317#issuecomment-67573011).

**Comment by gbaz** [comment] 2021-12-03 14:56
Ok, in that case, does building with relative paths work, and then performing the rewriting step to use pkg-root before installing/registering?

**Comment by gbaz** [comment] 2021-12-10 18:40
related ghc issue: https://gitlab.haskell.org/ghc/ghc/-/issues/10424

**Comment by aherrmann** [comment] 2021-12-13 16:13
@gbaz Thanks for the relevant GHC issue!

> Ok, in that case, does building with relative paths work, and then performing the rewriting step to use pkg-root before installing/registering?

I'm not sure how to do this. I tried patching the package configuration and recaching the db in `dist/package.conf.inplace` between `build` and `install`, but it didn't seem to have any effect. The `install` still failed due to the relative paths. IIUC this information is read from `dist/setup-config`.

I tried patching `setup-config` directly, but that failed with Cabal telling me that the file is corrupted and I need to run `configure` again.

I also tried running `Setup.sh configure` with different settings between `build` and `install`, but this of course caused `install` to rebuild the code and interface files.

Did you have something else in mind?

**Comment by gbaz** [comment] 2021-12-13 22:46
Well, above you wrote: "rules_haskell patches the package configuration, replacing the absolute path by ${pkgroot}, after the Cabal build completed and re-caches the package-db. This way the final package-db is relocatable and deterministic. However, the flag hash field in the interface file remains indeterministic."

So what I'm suggesting is to try building using relative paths instead of absolute paths, and then as above patch to replace the in this case relative path by pkgroot. Perhaps you already described in the above how that fails? Note that you do not need to use `cabal` to do the final `install` of a package -- you can use `ghc-pkg register` to do this step manually.

**Comment by Mikolaj** [comment] 2022-01-29 11:38
@aherrmann: ping?

**Comment by aherrmann** [comment] 2022-01-31 15:20
Thanks for the ping and sorry for the late reply.

---

@gbaz 
> So what I'm suggesting is to try building using relative paths instead of absolute paths, and then as above patch to replace the in this case relative path by pkgroot. Perhaps you already described in the above how that fails?

Right, yes, that fails in the `Setup.hs install` step as described above:

> I tried patching the package configuration and recaching the db in `dist/package.conf.inplace` between `build` and `install`, but it didn't seem to have any effect. The `install` still failed due to the relative paths. IIUC this information is read from `dist/setup-config`.

---

> Note that you do not need to use `cabal` to do the final `install` of a package -- you can use `ghc-pkg register` to do this step manually.

IIUC I'd have to reimplement `Setup.hs install` in that case. I.e. copy all the required artifacts (`.so`,`.hi`,`.a`,docs,etc.) into the right locations and then manually run the registration step, correct?

Maybe this is a pointer as to how the use-case could be supported by Cabal. If I could configure the C search paths separately for build and install, then I could configure them the way I need in both cases. I.e. for build I could configure relative search paths (`--extra-include-dirs ../install1/myclib` etc.) and for install I could configure one using `${pkgroot}` (`--extra-include-dirs ${pkgroot}/myclib` etc.)

**Comment by aherrmann** [comment] 2022-01-31 16:06
> IIUC I'd have to reimplement `Setup.hs install` in that case. I.e. copy all the required artifacts (`.so`,`.hi`,`.a`,docs,etc.) into the right locations and then manually run the registration step, correct?

Answering my own question. I found that `Setup.hs` offers the `copy` command, which seems to be doing the file copying part of `install` but without the registering part, and a `register` command which can generate the package config file without registering it. So, it looks like I can achieve the "build & patch & install" model by using `Setup.hs copy` and `Setup.hs register --gen-pkg-config` followed by `ghc-pkg register`. A working example looks [like this](https://github.com/aherrmann/demo-cabal-reproducibility-issue/compare/relative-paths...manual-install?expand=1#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823L29-R50).

At least with that example I get bit reproducible builds:
```
$ ./build.sh
$ diff -ru work1/install work2/install
```

Thanks for the suggestion @gbaz. I haven't tried to integrate this into rules_haskell, yet, but it's looking promising. I'll report back when I've tried it in rules_haskell.

**Comment by aherrmann** [comment] 2022-02-07 17:10
I have implemented the approach described above in rules_haskell in https://github.com/tweag/rules_haskell/pull/1689.

**Comment by jneira** [comment] 2022-05-01 20:42
* Hi, we have a interesting discussion here but i think is hard to conclude what concrete action is needed in cabal. I think add support in cabal for `${pkgroot}` was not considered
* We have #2641, which imo summarizes the problems with relative paths and the interaction with ghc-pkg and list the possible actions to fix or improve the situation
* So i am gonna close this one, feel free to reopen (or ask to do it) if you think there is some value in keeping it opened

**Closed by jneira** 2022-05-01 20:42 UTC
Labels: type: bug, Cabal: file format, Cabal: other, type: discussion
