### ISSUE TITLE
`--reinstall` and `--force-reinstalls` have not effect on resolution of conflicted dependencies even in a sandbox

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/cabal#2166] opened 2014-10-17 21:25 UTC
```
huge-black-box-mac:hasql-postgres mojojojo$ cabal install --only-dependencies --enable-tests -j --reinstall --force-reinstalls
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: random-1.1/installed-2a5... (user goal)
next goal: hasql-postgres (user goal)
rejecting: hasql-postgres-0.1.0 (conflict: random =>
time==1.5/installed-0e1..., hasql-postgres => time==1.4.*)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

The previously installed `random` package has no restriction on [the `time` dependency](https://github.com/haskell/random/blob/master/random.cabal#L39), so the conflict could be easily resolved by simply reinstalling the package. However I've tried all the flags out there and nothing helps. 

Cabal version:
```
huge-black-box-mac:hasql-postgres mojojojo$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
```

**Comment by ttuegel** [comment] 2015-04-24 14:28
This looks to be a duplicate of #2179.

**Closed by ttuegel** 2015-04-24 14:28 UTC
Labels: bug, cabal-install, solver
