### ISSUE TITLE
running 'cabal build' in an empty directory creates directories before erroring.

### ISSUE THREAD

**Issue by julialongtin** [haskell/cabal#9390] opened 2023-11-03 00:22 UTC
**To Reproduce**
```
$ cabal build
```

**Expected behavior**
The production of the normal error output, and no dist-newstyle folder created.

**Undesired behavior**
```
$ find dist-newstyle/
dist-newstyle/
dist-newstyle/cache
dist-newstyle/cache/compiler
```

**System information**
 - debian unstable
 - cabal 3.8.1.0, ghc 9.4.6

**Comment by geekosaur** [comment] 2023-11-03 00:30
I can't reproduce with 3.10.1.0:
```
skkukuk Z$ ls
skkukuk Z$ cabal build 
Error: cabal: There is no <pkgname>.cabal package file or cabal.project file.
To build packages locally you need at minimum a <pkgname>.cabal file. You can
use 'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root
directory of your project. This file lists the packages in your project and
all other build configuration. See the Cabal user guide for full details.

zsh: exit 1     cabal build
skkukuk Z$ find .
.
```

**Comment by geekosaur** [comment] 2023-11-03 00:37
I can't easily test 3.8.1.0 because I use XDG paths and I have a dummy file `~/.cabal` in place for those rare times when I have to reinstall ghcup (I run a prerelease) and it switches me back to the "recommended" version.

**Comment by ulysses4ever** [comment] 2023-11-03 01:20
I have a feeling that’s due of an issue that was subsequently fixed. Let’s close until there’s a reproducer with the latest release?

**Comment by gbaz** [comment] 2023-11-03 02:30
indeed should be fixed by https://github.com/haskell/cabal/pull/8627

**Comment by ffaf1** [comment] 2023-11-03 03:02
```
f@x270:/tmp/prova$ cabal build
Warning: this is a debug build of cabal-install with assertions enabled.
Error: [Cabal-7136]
There is no <pkgname>.cabal package file or cabal.project file. To build packages locally you need at minimum a <pkgname>.cabal file. You can use 'cabal init' to create one.

For non-trivial projects you will also want a cabal.project file in the root directory of your project. This file lists the packages in your project and all other build configuration. See the Cabal user guide for full details.

f@x270:/tmp/prova$ cabal --version
cabal-install version 3.11
compiled using version 3.11.0.0 of the Cabal library
f@x270:/tmp/prova$
```

So it should be ok in master. I am closing this, reopen if needed.

**Closed by ffaf1** 2023-11-03 03:02 UTC
Labels: type: bug, status: consider closing
