### ISSUE TITLE
<command line>: cannot satisfy -package-id Cabal-1.24.2.0-inplace

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#4212] opened 2017-01-06 16:35 UTC
`cabal new-build` fails to install `distributive` with
```
```
This is strange because `Cabal-1.24.2.0` is included in the install plan,
```
$ cabal new-build --allow-newer=base,primitive,bifunctors,directory,hashable,constraints,vector -j1
In order, the following will be built (use -v for more details):
 - Cabal-1.24.2.0 (lib) (first run)
 - asn1-parse-0.9.4 (lib) --enable-library-profiling (requires build)
 - binary-serialise-cbor-0.1.1.0 (lib) --enable-library-profiling (first run)
 - contravariant-1.4 (lib) --enable-library-profiling (first run)
 - mwc-random-0.13.5.0 (lib) --enable-library-profiling (requires build)
 - safecopy-0.9.2 (lib) --enable-library-profiling (configuration changed)
 - scientific-0.3.4.10 (lib) --enable-library-profiling (requires build)
 - vector-binary-instances-0.2.3.3 (lib) --enable-library-profiling (configuration changed)
 - vector-th-unbox-0.2.1.6 (lib) --enable-library-profiling (requires build)
 - unbounded-delays-0.1.0.9 (lib:unbounded-delays) --enable-library-profiling (first run)
 - distributive-0.5.1 (lib:distributive) --enable-library-profiling (first run)
...
```
Despite the fact that `Cabal` is present in the install plan it seems that `cabal new-build` skip it entirely: the first package that `new-build` builds is in fact `asn1-parse`.

`plan.json` says this,
```json
    {
      "type": "configured",
      "id": "Cabal-1.24.2.0-inplace",
      "pkg-name": "Cabal",
      "pkg-version": "1.24.2.0",
      "flags": {
        "bundled-binary-generic": false
      },
      "style": "inplace",
      "pkg-src-sha256": "b7d0eb8e3503fbca460c0a6ca5c88352cecfe1b69e0bbc79827872134ed86340",
      "dist-dir": "/home/ben/code/laura/dist-newstyle/build/x86_64-linux/ghc-8.1.20161223/Cabal-1.24.2.0",
      "depends": [
        "array-0.5.1.2",
        "base-4.10.0.0",
        "binary-0.8.4.0-inplace",
        "bytestring-0.10.8.1",
        "containers-0.5.7.1",
        "deepseq-1.4.3.0",
        "directory-1.3.0.0",
        "filepath-1.4.1.1",
        "pretty-1.1.3.3",
        "process-1.4.3.0",
        "time-1.7.0.1",
        "unix-2.7.2.1"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
```

Currently I'm observing this while trying to build http://git.smart-cactus.org/ben/simpl-ir with a `ghc` `master` build but I'll try to come up with an easier way to reproduce.

**Comment by bgamari** [comment] 2017-01-06 16:37
The `dist-dir` for `Cabal-1.24.2.0` is largely empty,
```
$ ls /home/ben/code/laura/dist-newstyle/build/x86_64-linux/ghc-8.1.20161223/Cabal-1.24.2.0/ -R
/home/ben/code/laura/dist-newstyle/build/x86_64-linux/ghc-8.1.20161223/Cabal-1.24.2.0/:
build  cache  setup-config

/home/ben/code/laura/dist-newstyle/build/x86_64-linux/ghc-8.1.20161223/Cabal-1.24.2.0/build:

/home/ben/code/laura/dist-newstyle/build/x86_64-linux/ghc-8.1.20161223/Cabal-1.24.2.0/cache:
config
```

**Comment by bgamari** [comment] 2017-01-06 16:48
[Here](https://gist.github.com/bgamari/13a7c4d7174a75a7cd7cc7eb371f33a6) is a gist with a full log from `cabal new-build -v3`.

**Comment by ezyang** [comment] 2017-01-06 17:12
What version of cabal-install are you using? Can you try HEAD?

**Comment by bgamari** [comment] 2017-01-06 18:18
The logs above were with a snapshot from 13 Nov 2016 however I'm sorry to report that this is still reproducible with HEAD (89e7c5065eec32db67d83c3150ecef9ad7d409ce).

**Comment by bgamari** [comment] 2017-01-06 18:55
@ezyang the `cabal.project` can be found [here](https://git.smart-cactus.org/ben/simpl-ir/blob/master/cabal.project).

**Comment by bgamari** [comment] 2017-01-06 19:04
@ezyang diagnosed the problem to be that I vendor'd `binary`, which `Cabal` depends upon.

**Comment by ezyang** [comment] 2017-01-06 19:12
Steps to reproduce:
1. Create a new project
2. Create a new library which depends on `distributive`
3. `cabal unpack binary`
4. Add a project file that contains `packages: binary* .`
5. `cabal new-build`

**Comment by ezyang** [comment] 2017-01-06 20:49
Simplified repro: get rid of distributive, just make the local package have a custom project.

This bug will be a good impetus for us to improve our logging in ProjectBuilding, which is woefully underlogged. For some reason, Cabal-1.24.0.2 has no components to build, so the building process is skipped. I don't know why yet.

**Comment by Ericson2314** [comment] 2017-01-11 15:39
I'm hitting this when trying to build cabal itself now

**Comment by ezyang** [comment] 2017-01-20 07:21
With the latest Hackage index, this now puts the solver into some sort of bad, infinite backtracking situatoin.

**Comment by grayjay** [comment] 2018-02-11 05:40
I think this is fixed on master.  I was able to reproduce it with 89e7c5065eec32db67d83c3150ecef9ad7d409ce with these steps:

- Run `cabal unpack binary-0.8.4.0`.
- Create `cabal.project` containing `packages: binary-0.8.4.0 .`.
- Create `issue4212.cabal` containing

```
name: issue4212
version: 1.0
build-type: Simple
cabal-version: 1.24

library
  build-depends: distributive <= 0.5.1
  default-language: Haskell2010
```

- Run `cabal  new-build --index-state=2018-02-11T04:42:27Z` with GHC 8.2.1:

```
$ cabal new-build --index-state=2018-02-11T04:42:27Z                                       
Resolving dependencies...
In order, the following will be built (use -v for more details):
 - base-orphans-0.6 (lib) (requires build)
 - binary-0.8.4.0 (lib) (first run)
 - old-locale-1.0.0.7 (lib) (requires build)
 - process-1.4.3.0 (lib) (requires build)
 - transformers-compat-0.5.1.4 (lib) (requires build)
 - old-time-1.1.0.3 (lib) (requires build)
 - Cabal-1.24.2.0 (lib) (requires build)
 - tagged-0.8.5 (lib) (requires build)
 - distributive-0.5.1 (lib:distributive) (requires build)
 - issue4212-1.0 (lib) (first run)
Configuring old-locale-1.0.0.7 (lib)...
Configuring component lib from binary-0.8.4.0...
Configuring process-1.4.3.0 (lib)...
Configuring transformers-compat-0.5.1.4 (lib)...
Configuring base-orphans-0.6 (lib)...
Building old-locale-1.0.0.7 (lib)...
Building transformers-compat-0.5.1.4 (lib)...
Building base-orphans-0.6 (lib)...
Preprocessing library binary-0.8.4.0...
[1 of 9] Compiling Data.Binary.Builder ( src/Data/Binary/Builder.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Builder.o )
[2 of 9] Compiling Data.Binary.FloatCast ( src/Data/Binary/FloatCast.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/FloatCast.o )
[3 of 9] Compiling Data.Binary.Internal ( src/Data/Binary/Internal.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Internal.o )
[4 of 9] Compiling Data.Binary.Get.Internal ( src/Data/Binary/Get/Internal.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Get/Internal.o )
Configuring tagged-0.8.5 (lib)...
Configuring old-time-1.1.0.3 (lib)...
Building process-1.4.3.0 (lib)...
[5 of 9] Compiling Data.Binary.Get  ( src/Data/Binary/Get.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Get.o )
Building tagged-0.8.5 (lib)...
[6 of 9] Compiling Data.Binary.Put  ( src/Data/Binary/Put.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Put.o )
Building old-time-1.1.0.3 (lib)...
[7 of 9] Compiling Data.Binary.Class ( src/Data/Binary/Class.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Class.o )
[8 of 9] Compiling Data.Binary.Generic ( src/Data/Binary/Generic.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary/Generic.o )
[9 of 9] Compiling Data.Binary      ( src/Data/Binary.hs, /home/kristen/projects/issue-4212/dist-newstyle/build/x86_64-linux/ghc-8.2.1/binary-0.8.4.0/build/Data/Binary.o )
Configuring component lib from Cabal-1.24.2.0...
<command line>: cannot satisfy -package-id Cabal-1.24.2.0-inplace
    (use -v for more information)
cabal: Failed to build distributive-0.5.1 (which is required by
issue4212-1.0). The failure occurred during the configure step.
```

The same command succeeded with master.  I also tried running the command with several index states from around the time of this issue, but cabal didn't find a solution.  I couldn't reproduce the backtracking issue.

**Comment by grayjay** [comment] 2018-11-18 06:39
Closing, since this was fixed on master.

**Closed by grayjay** 2018-11-18 06:39 UTC
Labels: cabal-install: nix-local-build, type: bug
