### ISSUE TITLE
`cabal install' fails for current package when `--store-dir' is used

### ISSUE THREAD

**Issue by pjones** [haskell/cabal#7130] opened 2020-10-22 19:32 UTC
**Describe the bug**
 
When using a `source-repository-package` statement in a `cabal.project` file and using `--store-dir`: `cabal build` works but `cabal install` fails.

cabal 3.2 and 3.4rc4 fail for different reasons.

**To Reproduce**

The following repository contains a minimal example of a failure:

https://github.com/pjones/cabal-install-local-bug

**Expected behavior**

If the build succeeds then the install should too.

**System information**
 - Linux
 - cabal 3.2 and 3.4rc4
 - GHC 8.4.4

**Additional context**
 
The repo mentioned above has two failing CI jobs, one for 3.2 and one for 3.4. 

  - [3.2](https://github.com/pjones/cabal-install-local-bug/runs/1294427558?check_suite_focus=true)
  - [3.4rc4](https://github.com/pjones/cabal-install-local-bug/runs/1294427556?check_suite_focus=true)

**Comment by phadej** [comment] 2020-10-23 00:01
When I rename

```
mv cabal-install-local.cabal cabal-install-local-bug.cabal
```

the install succeeds with `3.4`.

```
% cabal --storedir=/codetmp/store install -w ghc-8.8.4                                                 
Wrote tarball sdist to
/codetmp/cabal-install-local-bug/dist-newstyle/sdist/cabal-install-local-bug-0.1.0.0.tar.gz
Wrote tarball sdist to
/codetmp/cabal-install-local-bug/dist-newstyle/sdist/byline-1.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - cabal-install-local-bug-0.1.0.0 (exe:cabal-install-local) (requires build)
Starting     cabal-install-local-bug-0.1.0.0 (exe:cabal-install-local)
Building     cabal-install-local-bug-0.1.0.0 (exe:cabal-install-local)
Installing   cabal-install-local-bug-0.1.0.0 (exe:cabal-install-local)
Completed    cabal-install-local-bug-0.1.0.0 (exe:cabal-install-local)
Symlinking 'cabal-install-local' to '/cabal/bin/cabal-install-local'
```

---

The `sdist` should check that `.cabal` file is properly named, but it doesn't.

**Comment by pjones** [comment] 2020-10-23 00:28
@phadej Okay, I'll have to go back to the drawing board then because I have a production app that fails to install with 3.4.  I must be missing something with my minimal example.

**Comment by pjones** [comment] 2020-10-23 21:13
@phadej I updated the example repo so that the package name matches the cabal file and it still fails with the following error:

```
+ cabal --store-dir=.cabal install
Wrote tarball sdist to
/home/runner/work/cabal-install-local-bug/cabal-install-local-bug/dist-newstyle/sdist/cabal-install-local-0.1.0.0.tar.gz
Wrote tarball sdist to
/home/runner/work/cabal-install-local-bug/cabal-install-local-bug/dist-newstyle/sdist/byline-1.1.0.0.tar.gz
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - cabal-install-local-0.1.0.0 (exe:cabal-install-local) (requires build)
Starting     cabal-install-local-0.1.0.0 (exe:cabal-install-local)

Failed to build exe:cabal-install-local from cabal-install-local-0.1.0.0. The
failure occurred during the configure step.
Build log (
/home/runner/.cabal/logs/ghc-8.8.4/cabal-install-local-0.1.0.0-e-cabal-install-local-30ac814c315a7cf9b8afff947187b0273c761ab3d383c19f5802ca6e697d4636.log
):
Configuring executable 'cabal-install-local' for cabal-install-local-0.1.0.0..
cabal: The following package dependencies were requested
--dependency='byline=byline-1.1.0.0-d0dc2effa3ece7269068e979e71f5ce2ccd7ae025b218ba1fa82066b5fd69006'
cabal: Failed to build exe:cabal-install-local from
however the given installed package instance does not exist.
cabal-install-local-0.1.0.0. See the build log above for details.
```

Is there something I'm missing that is allowing this to work for you but not for me?  I get the same failure on my local machine that I"m getting in Github CI.

**Comment by phadej** [comment] 2020-10-23 22:09
Ok, that's better.

I think that `--store-dir` you point to is invalid, e.g. this might be duplicate of https://github.com/haskell/cabal/issues/6060

Specifically, `--store-dir=.cabal` is invalid, we should only accept absolute paths there, relative ones are doomed to not work.

Can you try with `--store-dir=$(pwd)/.cabal` (empty one?)

**Comment by pjones** [comment] 2020-10-23 23:53
Using an absolute path does indeed fix the issue.  If fact, it fixes it for both 3.2 and 3.4.

Requiring an absolute path seems a bit silly.  If `cabal` changes its working directory and expects any paths to continue to work it should resolve them itself.

Also, it appears that using `install` forces a new build and doesn't use the previously built objects.  That's a bit annoying for a CI/CD system.  I was hoping to use `install` to replace the `--copy-bins` option from `stack`.

Does that mean that the `install` command is truly a "global" command and can't use the current package context?  Should we have another command that would install all available binaries?  (Using `list-bins` isn't desirable since it requires that you provide a target.  To write a generic CI/CD recipe I'd like a command that finds all executable targets and installs the binaries into a specific directory.  I'm sure this would be useful for downstream OS package maintainers as well.)

**Comment by phadej** [comment] 2020-10-24 11:43
> Requiring an absolute path seems a bit silly. If cabal changes its working directory and expects any paths to continue to work it should resolve them itself.

It should, but it doesn't. PRs are welcome. This kind of problem is not new, and is why I work on #6667.

---

Re `install` question. `install` doesn't reuse `build` artifacts. It is by design.

> Should we have another command that would install all available binaries?

No, that wouldn't work in general. (what to do with `data-files`?). If you want plural `list-bins` (`cabal-install-3.4` has only `list-bin`) listing all the binaries, check https://hackage.haskell.org/package/cabal-plan

**Closed by phadej** 2020-10-24 11:43 UTC

**Comment by pjones** [comment] 2020-10-26 15:09
@phadej Thank you for the clarifications.
