### ISSUE TITLE
cabal init fails if git is not installed

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/cabal#10065] opened 2024-06-01 23:17 UTC
**Describe the bug**
If running `cabal init` without git installed, an error occurs
```
git: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
```

**To Reproduce**
```console
$ docker run --rm -it ubuntu:latest

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ apt-get update && apt-get install -y curl build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev pkg-config
$ curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
$ source ~/.ghcup/env

$ ghcup install ghc 9.10.1 --set
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.10.1
$ cabal --version
cabal-install version 3.10.3.0
compiled using version 3.10.3.0 of the Cabal library

$ cabal init -n app
git: readCreateProcessWithExitCode: posix_spawnp: does not exist (No such file or directory)
```

**Expected behavior**
Should either:
1. Ask for author name/email without a default
2. Default name with `$USER`

**System information**
 - Operating system
 - `cabal`, `ghc` versions

**Additional context**

**Comment by ulysses4ever** [comment] 2024-06-01 23:51
> System information
>
>   Operating system
>    cabal, ghc versions

?

**Comment by ulysses4ever** [comment] 2024-06-01 23:52
Most likely, duplicate of

- #8478

**Comment by brandonchinn178** [comment] 2024-06-02 00:32
Interesting, it seems like a regression. I've updated the ticket with a repro with Docker. I'm definitely using cabal 3.10

**Comment by brandonchinn178** [comment] 2024-06-02 00:34
ah looks like it's not released yet?

**Closed** 2024-06-02 00:35 UTC
Labels: type: bug, cabal-install: cmd/init, resolution: duplicate

**Comment by ulysses4ever** [comment] 2024-06-02 01:59
I'm surprised that it's not released but thank you for double-checking. One more reason to release cabal-install-3.12 soon!
