### ISSUE TITLE
Segmentation fault when configuring network-uri-2.6.1.0 while building with bootstrap.sh script

### ISSUE THREAD

**Issue by kozross** [haskell/cabal#6302] opened 2019-10-18 21:40 UTC
**Describe the bug**

I am using the ``bootstrap.sh`` script to build ``cabal-install`` on an ARMv7 machine. However, after getting to the configuration step of ``network-uri``, I get a segmentation fault. An example of the behaviour below:

```
[alarm@Liyana cabal-install]$ GHC=/home/alarm/mnt/ghc-82/bin/ghc GHC_PKG=/home/alarm/mnt/ghc-82/bin/ghc-pkg PREFIX=/home/alarm/mnt ./bootstrap.sh --no-doc
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../haskeline-0.7.4.0/libHShaskeline-0.7.4.0-ghc8.2.2.so)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../ghc-8.2.2/libHSghc-8.2.2-ghc8.2.2.so)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../terminfo-0.4.1.0/libHSterminfo-0.4.1.0-ghc8.2.2.so)
Using gcc for C compiler. If this is not what you want, set CC.
Using /usr/lib/gcc/armv7l-unknown-linux-gnueabihf/8.3.0/collect2 instead.
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../terminfo-0.4.1.0/libHSterminfo-0.4.1.0-ghc8.2.2.so)
Checking installed packages for ghc-8.2.2...
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc-pkg: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../terminfo-0.4.1.0/libHSterminfo-0.4.1.0-ghc8.2.2.so)
deepseq is already installed and the version is ok.
binary is already installed and the version is ok.
time is already installed and the version is ok.
transformers is already installed and the version is ok.
mtl is already installed and the version is ok.
text is already installed and the version is ok.
parsec is already installed and the version is ok.
network-uri-2.6.1.0 will be installed from local directory.
network-2.7.0.0 will be downloaded and installed.
HTTP-4000.3.12 will be downloaded and installed.
zlib-0.6.2 will be downloaded and installed.
random-1.1 will be downloaded and installed.
stm-2.4.5.0 will be downloaded and installed.
hashable-1.2.7.0 will be downloaded and installed.
async-2.2.1 will be downloaded and installed.
base16-bytestring-0.1.1.6 will be downloaded and installed.
base64-bytestring-1.0.0.1 will be downloaded and installed.
cryptohash-sha256-0.11.101.0 will be downloaded and installed.
resolv-0.1.1.1 will be downloaded and installed.
mintty-0.1.2 will be downloaded and installed.
echo-0.1.3 will be downloaded and installed.
edit-distance-0.2.2.1 will be downloaded and installed.
ed25519-0.0.5.0 will be downloaded and installed.
tar-0.5.1.0 will be downloaded and installed.
digest-0.0.1.2 will be downloaded and installed.
zip-archive-0.3.3 will be downloaded and installed.
hackage-security-0.5.3.0 will be downloaded and installed.
Cabal is already installed and the version is ok.

Using local directory for network-uri-2.6.1.0.
cleaning...
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../haskeline-0.7.4.0/libHShaskeline-0.7.4.0-ghc8.2.2.so)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../ghc-8.2.2/libHSghc-8.2.2-ghc8.2.2.so)
/home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/ghc: /usr/lib/libtinfo.so.5: no version information available (required by /home/alarm/mnt/ghc-82/lib/ghc-8.2.2/bin/../terminfo-0.4.1.0/libHSterminfo-0.4.1.0-ghc8.2.2.so)
Linking Setup ...
Configuring network-uri-2.6.1.0...
./bootstrap.sh: line 357: 16238 Segmentation fault      (core dumped) ./Setup configure $args

Error during cabal-install bootstrap:
Configuring the network-uri package failed.
```

**To Reproduce**

```
$ GHC=/path/to/ghc-82/bin/ghc GHC_PKG=/path/to/bin/ghc-pkg PREFIX=/home/me ./bootstrap.sh --no-doc
# then await the segfault as described above
```

**Expected behavior**

``network-uri`` configures and builts properly as part of the process of running ``bootstrap.sh``.

**System information**
 - Arch Linux
 - GHC 8.2.2

**Comment by gbaz** [comment] 2019-10-18 22:23
I assume the ghc is not the standard one in the arch distro? You will need to use arch's tools to install a compatible libtinfo. Installing https://aur.archlinux.org/packages/ncurses5-compat-libs/ should help...

Closing this as not a cabal issue.

**Closed by gbaz** 2019-10-18 22:23 UTC

**Comment by kozross** [comment] 2019-10-18 22:26
@gbaz Arch doesn't package an ARM GHC, and I have ``ncurses5-compat-libs`` installed. I'm using the ARMv7 binary build of GHC, from [here][1].

[1]: https://www.haskell.org/ghc/download_ghc_8_2_2.html#linux_armv7

**Comment by gbaz** [comment] 2019-10-18 22:30
well, whatever the issue is, it certainly isn't a cabal issue. Sorry I don't have any advice to help you debug this configuration further, but its going to be something affecting the ghc build process in general as far as I can tell...
