### ISSUE TITLE
Add "cabal nuke" command

### ISSUE THREAD

**Issue by DylanLukes** [haskell/cabal#2308] opened 2014-12-29 03:23 UTC
Given how regularly people find themselves needing to empty `ghc-pkg`, delete and uninstall cabal, and otherwise just nuke all of their packages, it would be nice to have a "safe" way to do so.

So let there be `cabal nuke`. After asking if you're sure (twice!) it should return the package list to a known stable state (e.g. the base set of packages and nothing more).

**Comment by rtpg** [comment] 2015-01-04 13:25
Are there possible issues with e.g. people installing the Haskell Platform through their own package manager?

**Comment by DylanLukes** [comment] 2015-01-06 17:14
@rtpg That's why it would be important to have a solid base set of packages. As I understand it GHC (relevant since ghc-pkg is part of GHC) already ships with a default set of packages in global.

`cabal nuke` should just reset to the package state as of the last GHC upgrade.

**Comment by 23Skidoo** [comment] 2015-01-09 08:28
Note that for sandboxes there's `cabal sandbox delete`.

**Comment by ttuegel** [comment] 2015-04-24 14:24
Duplicate of #2151, which also has a list of the steps which are actually helpful.

**Closed by ttuegel** 2015-04-24 14:24 UTC
Labels: enhancement
