### ISSUE TITLE
cabal new-install attempts to dump non-existent package db

### ISSUE THREAD

**Issue by bgamari** [haskell/cabal#5597] opened 2018-09-29 15:39 UTC
@AndreasPK has noticed that `cabal new-install cabal-install` attempts to run `ghc-pkg dump` on a non-existent `~/.cabal/store/ghc-8.4.3/package.db`.

Running `cabal new-build` on a random package and then trying again creates the missing package database, allowing `new-install` to proceed.

**Comment by phadej** [comment] 2018-09-29 17:49
Duplicate of https://github.com/haskell/cabal/issues/5516

**Comment by typedrat** [comment] 2018-09-30 06:50
Yup, @phadej. Closing.

**Closed by typedrat** 2018-09-30 06:50 UTC
