### ISSUE TITLE
exec command doesn't work with `install --with-ghc ...`

### ISSUE THREAD

**Issue by osa1** [haskell/cabal#2459] opened 2015-03-09 03:50 UTC
I'm trying to use `cabal exec` to install using a specific GHC binary. The problem is that it's always failing with:

```
    Could not find module ‘<the module it just installed>’
    Use -v to see a list of the files searched for.
```

I'm running it like this:

```
$ cabal sandbox init
$ cabal install --with-ghc <ghc-path>
$ cabal exec <ghc-path> -- <Haskell source path>
```

I also tried using `cabal configure --with-ghc` but got same error.

**Comment by lspitzner** [comment] 2015-03-09 08:52
duplicate of #2177.

**Closed** 2015-03-09 20:19 UTC
Labels: duplicate
